### ISSUE TITLE
Updating applicationGateways property of waf policy throws "Unable to deserialize to object"

### ISSUE THREAD

**Issue by ryciakd** [Azure/azure-cli#10011]
## Describe the bug

**Command Name**
`az network application-gateway waf-policy update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
pip-install-ygnynjtx\msrest\msrest\serialization.py, ln 1288, in _deserialize
pip-install-ygnynjtx\msrest\msrest\serialization.py, ln 1078, in rest_key_case_insensitive_extractor
pip-install-ygnynjtx\msrest\msrest\serialization.py, ln 1101, in attribute_key_case_insensitive_extractor
...
pip-install-ygnynjtx\msrest\msrest\serialization.py, ln 1101, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information. Both commands gives the same error:

- `az network application-gateway waf-policy update --name {} --resource-group {} --add applicationGateways '{"id":"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXXXX/providers/Microsoft.Network/applicationGateways/XXXXXXX","resourceGroup":"XXXXXX"}'`
- `az network application-gateway waf-policy update --name {} --resource-group {} --add applicationGateways '{"id":{"value":"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXXXX/providers/Microsoft.Network/applicationGateways/XXXXXXX"},"resourceGroup":{"value":"XXXXXX"}}'`

## Expected Behavior

Command completes successfully and updates the applicationGateways property of waf policy resource (or at least not throwing errors about serializing).

## Environment Summary
```
Windows-8.1-6.3.9600-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66 *

```

**Comment by MyronFanQiu** [comment]
@ryciakd Hello. Thanks for opening this issue. I dig a little bit deeper. Actually, I think there are two issues.
One is the errors about serializing, I think it's python sdk or msrest runtime error. @zikalino Could you please take a look? 
This function ```WebApplicationFirewallPoliciesOperations.create_or_update``` will raise error during deserializing the response. The `parameters` below is passed to the function. Maybe it's not a correct format, but the return value should be some useful information instead of throwing out the errors.
![image](https://user-images.githubusercontent.com/49134743/61780783-b84c0400-ae35-11e9-9725-b484b38a9675.png)
The other one is to generate correct `parameters`. Currently, I'm not sure whether this `parameters` is acceptable by the service server or not. I will check it once the runtime error fixed. If it doesn't work, I will fix the command to generate correct `parameters`.

**Comment by MyronFanQiu** [comment]
@ryciakd Hello. Sorry for the delay due to low bandwidth. Just an update. I'm still working on it.
I could use this command to update it. However, I think we should improve the usage experience.
```
az network application-gateway waf-policy update --name waf-policy-test --resource-group fanqiu-test --add applicationGateways {\"id\":{\"value\":\"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXXXX/providers/Microsoft.Network/applicationGateways/XXXXXXX\"},\"resourceGroup\":{\"value\":\"XXXXXX\"}} --debug
```

**Comment by MyronFanQiu** [comment]
@ryciakd Hello. Currenlty. the command `az network application-gateway create` supports a new argument `--waf-policy`. You can create a application-gateway with a waf-policy. It should solve this issue. Feel free to reopen this issue if you have any more question.
