### ISSUE TITLE
I got an error when trying to run az webapp up

### ISSUE THREAD

**Issue by beautifullife** [Azure/azure-cli#10086]
I got this error when I follow this tutorial:
https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service?pivots=csharp

![azure-webapp-1](https://user-images.githubusercontent.com/28057/62086482-10af4700-b224-11e9-89bf-0eda883cb9a8.PNG)

Any help?

**Comment by zikalino** [comment]
@beautifullife from the URL I can see that the issue is not related to the Webapp itself.
Could you call the same command with **--resource-group** parameter?

az webapp up --name "$APPNAME" --resource-group ….

I just wonder if you get the same error.

Could you also verify that the subscription **955..42** is correct and also resource group **dung1582002_rg_Windows_centralus**?

Could you try to display resource group as well?

**az group show -g dung1582002_rg_Windows_centralus**

**Comment by yugangw-msft** [comment]
@beautifullife, can you also run with `--debug` and share with us the trace? Might be another bad error from appservice

**Comment by beautifullife** [comment]
Thanks for your help! I missed 1 step that needs to get information about my Azure:

APPNAME=$(az webapp list --query [0].name --output tsv)
APPRG=$(az webapp list --query [0].resourceGroup --output tsv)
APPPLAN=$(az appservice plan list --query [0].name --output tsv)
APPSKU=$(az appservice plan list --query [0].sku.name --output tsv)
APPLOCATION=$(az appservice plan list --query [0].location --output tsv)

After this step, I run:

az webapp up --name $APPNAME --resource-group $APPRG --plan $APPPLAN --sku $APPSKU --location "$APPLOCATION"

It works perfectly now!

![azure-webapp-2](https://user-images.githubusercontent.com/28057/62144516-97613400-b2b7-11e9-8c46-db739fd74485.png)
