### ISSUE TITLE
az self-test doesn't report loading failure from extension

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#10137]
This causes https://github.com/Azure/azure-cli/issues/10088

**Comment by Juliehzl** [comment]
@yugangw-msft  It looks you have fix this bug through deleting prompt-toolkit in requirements.txt.

**Comment by yugangw-msft** [comment]
Not yet. My fix was for `az interactive`. This one is on `self-test` used by CI to ensure cli core change won't break extensions. W/o fixing this, extensions like `az interactive` might  break again.

**Comment by yonzhan** [comment]
add to S164.

**Comment by haroldrandom** [comment]
When I install both `IPython` and `interactive` extension, this error appear again for the dependency `prompt_toolkit` conflict.

However, importing the module [azure-cli-extensions/src/interactive/azext_interactive/\_\_init\_\_.py](https://github.com/Azure/azure-cli-extensions/blob/master/src/interactive/azext_interactive/__init__.py#L9-L11) isn't enough to detect the import error because the error comes from a function and that function won't get called while importing.

``` Python
def start_shell(cmd, style=None):
    from .azclishell.app import AzInteractiveShell  # The problem hide here
    AzInteractiveShell(cmd.cli_ctx, style)()


class InteractiveCommandsLoader(AzCommandsLoader):

    def __init__(self, cli_ctx=None):
        super(InteractiveCommandsLoader, self).__init__(cli_ctx=cli_ctx)

    def load_command_table(self, _):
        return self.command_table

    def load_arguments(self, _):
        pass


COMMAND_LOADER_CLS = InteractiveCommandsLoader
```

the `start_shell` will be evaluated only when it's executed instead of at import time.

So, the `self-test` won't be able to find it as all it does is to import the corresponding CommandLoader class and execute `load_command_table` and `load_parameter_table` instead of execute any actual custom function.

 So, the error can only be detected when it's called such as in intergation test. `az self-test` can do nothing to help this I think.
