### ISSUE TITLE
'az eventgrid event-subscription delete' not working 

### ISSUE THREAD

**Issue by NicolasConstant** [Azure/azure-cli#10225]
**Describe the bug**
Using Azure CLI to delete a eventgrid event-subscription is not working

**To Reproduce**
1. List evengrid event-subscription 
2. Get the name and id 
3. Run 'az eventgrid event-subscription delete --name [my name] --source-resource-id /subscriptions/[subscription id]/resourceGroups/[ressource group]/providers/Microsoft.Storage/storageAccounts/[storageaccount]/providers/Microsoft.EventGrid/eventSubscriptions/[my name]'
4. Getting following error: 

> No registered resource provider found for location 'eastus2' and API version '2019-06-01' for type 'storageAccounts'. The supported api-versions are '2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth'.

**Expected behavior**
Not getting an error and deleting the subscription

**Environment summary**
Installation via .msi
CLI 2.0.70
Win10 Pro 1809 64bit
cmd.exe

**Comment by ahamad-MS** [comment]
Thanks for reporting the issue. I had tried the same scenario using the provided steps in eastus2 regions and the command works fine as expected. By looking closer to the provided command, the --source-resource-id is for the event subscription itself rather than the topic to which the event subscription is associated with.

In this context, the command in step 3

[Run 'az eventgrid event-subscription delete --name [my name] --source-resource-id /subscriptions/[subscription id]/resourceGroups/[ressource group]/providers/Microsoft.Storage/storageAccounts/[storageaccount]/providers/Microsoft.EventGrid/eventSubscriptions/[my name]'

should be replaced with

. Run 'az eventgrid event-subscription delete --name [my name] --source-resource-id /subscriptions/[subscription id]/resourceGroups/[ressource group]/providers/Microsoft.Storage/storageAccounts/[storageaccount]'

where event subscriptions parts are removed.

Please try this out and let us know if you still have any issue.

Thanks

**Comment by NicolasConstant** [comment]
Oh right, the error message mislead me: I thought there where an issue with the API versioning. 

I tried it with your pattern and it's working, thanks a lot!
