### ISSUE TITLE
Unable to create SQL MI via az cli

### ISSUE THREAD

**Issue by ernani** [Azure/azure-cli#10295]
## Describe the bug

**Command Name**
`az sql mi create`

**Errors:**
```
Deployment failed. Correlation ID: 63abf0b2-9aaf-4bc5-858b-6c87318d1fea. Route Table. (https://go.microsoft.com/fwlink/?linkid=871071)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql mi create --resource-group {} --location {} --name {} --admin-user {} --admin-password {} --capacity {} --family {} --collation {} --edition {} --license-type {} --proxy-override {} --storage {} --public-data-endpoint-enabled {} --subnet {}`

## Expected Behavior
That it would create it

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.71

Extensions:
azure-firewall 0.1.2
interactive 0.4.3

```
## Additional Context
I am adding all the required params and for some reason the error in the deployment section in the resource group is the following:

"properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VnetSubnetConflictWithIntendedPolicy\",\"message\":\"Route Table. (https://go.microsoft.com/fwlink/?linkid=871071)\"}]}}"
    },
    "relatedEvents": []

**Comment by ernani** [comment]
It seems that it must create a route table first, but that's not documented anywhere in the az cli sql mi create doc AFAIK.

**Comment by urosmil** [comment]
Hi, deploying managed instance has specific network requirements that can be found here. https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-connectivity-architecture#network-requirements

In order to prepare your vnet and subnet for managed instance deployment, you can follow instructions from this article
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-configure-vnet-subnet
