### ISSUE TITLE
add start-task-user-id option to the az batch pool create list of supported options

### ISSUE THREAD

**Issue by JonShelley** [Azure/azure-cli#10296]
**Is your feature request related to a problem? Please describe.**
When creating a pool in batch I am able to add a start_task but it fails since the user_id is not set to pool autouser admin

**Describe the solution you'd like**
I would like an option added like --start-task-user-id that could be set to one of the 4 supported options (i.e. task autouser, non-admin/admin and pool autouser, non-admin/admin) 

**Describe alternatives you've considered**
I can do it if I use the --json-file but it is more straight forward to the users to have --start-task-* options instead of having to create a json file and then call the az batch pool create command.

**Additional context**

**Comment by bgklein** [comment]
Hi @JonShelley . Thanks for the feedback. 

I am slightly confused by 'I am able to add a start_task but it fails since the user_id is not set'. Is this that your task needs to run as admin or are you reporting a bug that this property is not set? There should a service side default so I am unsure exactly what you are requesting/reporting.

For a little bit of background, historically we have not aimed for 'feature parity' in the Az CLI in Batch due to Batch resources being a larger hierarchy than most other Azure services (you have probably seen this in how pool has the nested object of StartTask with its own set of properties/sub-objects). Exposing every single property of pool create would create excessive amounts of args for pretty much every operation, so instead we have favored exposing new/deep properties through --json-file for advanced users. 

That being said we have gotten a little more lenient over time about what we are willing to expose on the command-line so I will discuss this with @xingwu1 on whether this should be implemented.
