### ISSUE TITLE
parameters dont have comment about valid values in several properties or have link that has valid values

### ISSUE THREAD

**Issue by vairamsvsjdo** [Azure/azure-cli#10305]
parameters dont have comment about valid values in several properties or have link that has valid values
don't provide syntax for all values
az vm create does not have valid values for:
size, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qwordy** [comment]
You can use `az vm list-sizes`  to list all available sizes in your location.

Run `az vm create -h`

or visit

https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

You can see help

```
--size

The VM size to be created. See https://azure.microsoft.com/en-us/pricing/details/virtual-machines/ for size info.
default value: Standard_DS1_v2
```

It is hard to provide valid size values because they depend on location.

We will revise the help message to include how to get valid value list.
