### ISSUE TITLE
Error conditions do not honor output type

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#10350]
C:\Users\gsaral>az acr delete -n gsaralms -o json
The resource with name 'gsaralms' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'CodeLens_Test (6bd70c51-ff44-4c89-9212-8d3f10e2a90a)'

The error is correct but the format should be json, in the current model it is tough to progamitically consume output in case of errors.

**Comment by djyou** [comment]
I think `-o json` only applies to stdout, not stderr, while this is an error case with a user-friendly message.

**Comment by adewaleo** [comment]
Agreed, errors, warnings, etc are written to stderr while command output it written to stdout. The CLI does not apply output formatting to errors and other messages (debug, info, warning) logged to stderr. 

```
C:\Users\oladewal\source>az acr delete -n foobarwillfail 2> err.txt > output.txt

C:\Users\oladewal\source>more err.txt
ERROR: The resource with name 'foobarwillfail' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'ACR - Dev (dfb63c8c-7c89-4ef8-af13-75c1d873c895)'.

C:\Users\oladewal\source>more output.txt

C:\Users\oladewal\source>
```

Is there a reason you would like the error message to be formatted in json?

If the reason is to programmatically detect errors, so we can better understand?

If you are trying to determine if a command failed, I will recommend checking the exit code of the previous command instead of looking at the error message to determine if a command failed. 

### Linux(-like) 
`echo $?
`
### Windows
`echo %ERRORLEVEL%
`

**Comment by adewaleo** [comment]
I will be closing this issue, given the previous comment. Please let us know if you have any more questions.
