### ISSUE TITLE
get-instance-view should accept quoted string for ids

### ISSUE THREAD

**Issue by ashokez** [Azure/azure-cli#1036]
this works: az vm get-instance-view --ids id1 id2 
but not this: az vm get-instance-view --ids "id1 id2"

It would be helpful if it accepts quoted string. For example, this fails:

az vm list --query "join(' ',[*].id)" | xargs -I {} -P 8 az vm get-instance-view --ids {}

or is there a way for me to make jmespath give me unquoted string ? The jp has Unquoted Output : https://github.com/jmespath/jp , but azure-cli jmespath query cant do unquoted output.

**Comment by johanste** [comment]
The quoted/unquoted output depends on the output formatter. If you are using json as the output, then it will be quoted (in order to be well formed json). You can use --out tsv to get unquoted "raw" tab separated output. 

Does that address your immediate problem? 

That said, arguments have been made that we should support space separated values for the --ids parameter specifically since that would allow the use of piping similar to:

   az vm list --query "[].id" --out tsv | az vm get-instance-view --ids @-

**Comment by ashokez** [comment]
using the -o tsv does resolve the quote issue. But for some reason the pipe-lining does not seem to work.

even with your example : az vm list --query "[].id" --out tsv | az vm get-instance-view --ids @-

or with my originial one with -o tsv : az vm list --query "join(' ',[*].id)" -o tsv | xargs -I {} -P 8 az vm get-instance-view --ids {}

**Comment by tjprescott** [comment]
Hi @ashokez the reason @- is not working in this instance is because the @ syntax takes the supplied file (stdout for -) and reads its contents into a string. Thus you are getting the space separated list of IDs, but they are then being interpreted as a single string argument. The best example for the use of @ currently is with commands that accept JSON encoded strings. Typing these on the command line is painful, but using @ you can just point to a JSON file and everything will work.

We have an open issue #944 to have an alternate syntax for treating a file as a list. This would enable your scenario.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
