### ISSUE TITLE
delete all blobs excluding two directories in one container

### ISSUE THREAD

**Issue by test123114** [Azure/azure-cli#10374]
[Enter feedback here]
I want to use `az storage blob delete-batch` to delete blobs in one container, but I want to  exclude two directories from being deleted. How to implement it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-delete-batch)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tomfaltesek** [comment]
This appears to have been prompted by my recent [SO question: "delete-batch to delete all blobs excluding two directories".](https://stackoverflow.com/questions/57713726/azure-cli-storage-blob-delete-batch-to-delete-all-blobs-excluding-two-directori)

I've opened a separate issue (#10382) that addresses enhancing the documentation around the `--pattern` parameter, in general. It would make more sense to address #10382 instead of this issue, as it's more comprehensive.

**Comment by Juliehzl** [comment]
@test123114 Maybe you can try `az storage remove` with `--exclude`  in the latest azure cli version.

**Comment by dangrima90** [comment]
@Juliehzl using the `az storage remove` with `--exclude` how can one ignore a directory?

I'm running the following command, but everything is being deleted:

`az storage remove -c $web --acount-name storageaccountname` -n folder --recursive --exclude "folder-to-ignore/*"

I had a look at the [documentation](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#az-storage-remove), but I cannot see an example of how to exclude a folder from deletion. I'm guessing it's similar to excluding files, but from my tests I haven't managed.

**Comment by dangrima90** [comment]
I think I found what the issue is from my end. I'm trying to ignore a sub-folder of the folder being deleted, example:

`az storage remove -c $web --account-name storageaccountname -n folder --recursive --exclude "folder-to-ignore/*" `

Where the path is `"$web/folder/folder-to-ignore/"`

Since the function is recursive I guess you cannot exclude a sub-folder in that case.

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
HI @dangrima90, in latest azure cli, you can use `az storage remove` with `--exclude-path`. You can ignore two paths using `az storage remove -c container --exclude-path "folder1/subfolder;folder2" --recursive --account-name account`.
