### ISSUE TITLE
HTTP post request wrong Json output

### ISSUE THREAD

**Issue by chfa** [Azure/azure-cli#10479]
Hi,

When calling for my API from CLI, the Post request returns a Json string with all the escape character inside. it feels like the string has been json marshalled twice.
Example:  {\n  \"properties\": {\n   \"disabled\": true\n  }\n }
Expected output: 
{
  "properties": {
"disabled": true
   }
 }

in comparison I also have the default command which returns the correct value.
The code I used for those 2 API are identical. same methods So I don't understand the disparity in the returns.

This only happens when I call it through CLI, If I set up a local service, I can directly use CURL commands to call those APIS and I will get the expected returns.

Rrunning in cloudshell: 
az resource invoke-action --action enableConsole --ids "/subscriptions/$Subscription/providers/Microsoft.SerialConsole/consoleServices/default"
"{\n  \"properties\": {\n   \"disabled\": false\n  }\n }"

az resource show --ids "/subscriptions/$Subscription/providers/Microsoft.SerialConsole/consoleServices/default" | jq .properties
{
  "disabled": false
}

Both the Above API uses same method to create the json string and add the string to Header.

**Comment by Juliehzl** [comment]
@chfa Thanks for reaching out. I will have a look at this issue later.

**Comment by chfa** [comment]
Some update. I ran the Cli commands with --debug on , and this is what I see

![Cli](https://user-images.githubusercontent.com/55109447/64642329-f9d34700-d3c2-11e9-8819-4dcec617b064.PNG)

So in the header it seems to be the correct format and once displayed, it got Json marshalled again it seems.

**Comment by Juliehzl** [comment]
@chfa I think the different format is because you have different response content format. When you run `az resource show --ids "/subscriptions/$Subscription/providers/Microsoft.SerialConsole/consoleServices/default" | jq .properties --debug`, you can see the response content is in string format without line breaks. However, in the debug information you show, response content includes line breaks, which will be displayed as `\n` in CLI. It can be fixed when your response content in the following format:
```
msrest.http_logger : Response content:
msrest.http_logger : {"properties": { "disabled": false} }
```
In addition, if it is hard for you to change the returned content, we can add transformer function like [this](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_format.py#L107).

**Comment by chfa** [comment]
can you please add a transformer function?

thanks


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
