### ISSUE TITLE
Need a proper examples for the az ad sp update 

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#10568]
Hi,
Is there a proper example on how to use the az ad sp update --id &lt;&gt; --add &lt;&gt; command.
Looks like there  is none on the page even for some of the other sections.
Can you please add a proper example, so people can easily understand it.
something like : az ad sp update --id &lt;http://test-sp-account&gt; --add &lt;appDisplayName=newname&gt; 
Not sure if the above one is correct.

also tried az ad sp update --id http://test-sp-nametest​​​​​​​ --set "appDisplayName=test-sp-nametest-other" -- which does not work
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by akramwaseem** [comment]
Update on the issue : 
if I do : az ad sp create-for-rbac -n test-sp-testother --skip-assignment -o json
it works fine.
and the name shows "appDisplayName": "test-sp-testother",

adding http://test-sp-testother  throws it of.

**Comment by jiasli** [comment]
`-add` is a generic update operation: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#using-the-generic-update-arguments

The actual value is defined by Azure AD Graph API: https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/api-catalog

'Display name' is for Application instead of Service Principal. The proper way is to use `az ad app update
` to update `--display-name` https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update (Currently not working. Will fix soon.)
