### ISSUE TITLE
az appservice plan create resets plan SKU to B1

### ISSUE THREAD

**Issue by CapitalistHippie** [Azure/azure-cli#10577]
## Describe the bug
The az appservice plan create command without the SKU parameter specified resets the app service plan SKU when run on an existing plan. It resets it back to the default: B1. This goes against the idempotent nature of Azure CLI and makes it difficult for us to manually scale services while also deploying new versions of our software.

**Command Name**
`az appservice plan create`

**Errors:**
None

## To Reproduce:
```bash
az appservice plan create --name test-sku --is-linux --resource-group test-sku
# Manually set SKU to something other than B1. B2 for example.
az appservice plan create --name test-sku --is-linux --resource-group test-sku
```

## Expected Behavior
The SKU stays at B2

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67 *

```

**Comment by panchagnula** [comment]
@CapitalistHippie - B1 is the default SKU value of appservice plan create it calls it out in the documentation https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create

accepted values: B1, B2, B3, D1, F1, FREE, P1V2, P2V2, P3V2, PC2, PC3, PC4, S1, S2, S3, SHARED
default value: B1

What i am trying to understand here is this command is meant to creating a ASP, we have other commands to show the properties of an ASP https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-show
is there a reason you are using this command for show instead of create that this is meant for???

**Comment by CapitalistHippie** [comment]
We are using the command to create the ASP. The problem we're having with it is that the command resets the SKU back to B1 when the ASP already exists.

**Comment by panchagnula** [comment]
Are you saying that you are using the command with a name that already exists? Ideally we would not let you use this command with an existing ASP name but due to  these command guidelines 
https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md 

> "CREATE - standard command to create a new resource. Usually backed server-side by a PUT request. 'create' commands should be idempotent and should return the resource that was created"

so for now i recommend you can pass a SKU parameter  this command, so that at the end you get ASP of your choice doesn't matter it exists or not!

**Comment by panchagnula** [comment]
I am closing this out - with the recommendation to pass SKU if using this to set a SKU to an existing ASP or use the show command to view the properties of an existing command. Thanks!

**Comment by CapitalistHippie** [comment]
The recommended solution does not work in our situation. We want to be able to manually scale our app service plans up or down without our CD pipelines setting it to a constant value.

We have also considered a solution where we check if the app service plan already exists or not. If it already exists we could then just not create the app service plan again. This solution however would introduce a lot of boilerplate if checks in our CD scripts which we would like to prevent.

The behaviour we would really like to see would be of the safe non-destructive create commands as described in #7613.
