### ISSUE TITLE
Question: What tool to use to test azure cli

### ISSUE THREAD

**Issue by midacts** [Azure/azure-cli#10576]
What testing framework do most people use to unit/acceptance/integration test their azure cli code?

Python uses pytest.
PowerShell uses Pester.
Ansible uses Molecule.
etc

**Comment by qwordy** [comment]
We use unittest library. And we write our own testing module based on it. It includes features like recording, replay, etc.
https://docs.python.org/3/library/unittest.html
https://github.com/Azure/azure-cli/tree/dev/src/azure-cli-testsdk

**Comment by midacts** [comment]
Moreso as a consumer of the module, what do you see end users using to test their azure-cli code?

**Comment by qwordy** [comment]
@zikalino Do you have any idea?

**Comment by haroldrandom** [comment]
@midacts Do you mean you want to test your code that are using azure-cli ?

**Comment by midacts** [comment]
Yes.   : )

**Comment by haroldrandom** [comment]
@midacts Since you are a end user, I would assume that the results of azure-cli deliver matter. If that's the case, then the test framework is not important. 

You can test the result that azure-cli returns or check whether the modification on Azure Cloud through azure-cli satisifies your design. 
Both cases can be done by code automatically or watch the monitor to see the reaction.

If you test by code, you can use the test framework azure-cli is using (as mentioned above) if you don't want to import other libraries. 

Hope can help you.
