### ISSUE TITLE
'az storage copy' fails between Standard and Premium blob storage

### ISSUE THREAD

**Issue by jessebenson** [Azure/azure-cli#10630]
`az storage copy` fails when copying between Standard storage (StorageV2) and Premium storage (BlockBlobStorage).
```
az storage copy -s https://standard.blob.core.windows.net/container/file.json -d https://premium.blob.core.windows.net/container/file.json
```

Error logs show the following:

2019/09/25 00:46:37 ERR: [P#0-T#0] COPYFAILED: https://standard.blob.core.windows.net/container/file.json?se=2019-09-26t00%3A46%3A32z&sig=REDACTED&sp=rwdlacup&srt=sco&ss=b&sv=2018-03-28 : 400 : 400 Value for one of the query parameters specified in
the request URI is invalid.. When Setting BlockBlob tier. X-Ms-Request-Id: e8aa9578-701e-0072-563a-73ba64000000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4e415-fc8d-26d5-3213-da937fd6932c
* Version Independent ID: dcb2f2d6-fd80-495d-8582-8be859d68792
* Content: [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#az-storage-copy)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Hi @jessebenson, thanks for your feedback. `az storage copy` command depends on Azcopy v10. And I can reproduce your issue with storageV2 and Premium storage accounts using both `az storage copy command` and Azcopy v10. Let's wait for the feedback from Azcopy team.

**Comment by Juliehzl** [comment]
After the discussion with Azcopy team, this is because AzCopy is trying to preserve the access tier.  ANd your premium storage account don't support access tiers. Details are here https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs#copy-blobs-between-storage-accounts. 
If it is blocking you now, you can use Azcopy with `--s2s-preserve-access-tier=false` and it will work.
In addition, I will try to fix it in this sprint.
