### ISSUE TITLE
Az cli requires --cert-file, --cert-password when using --key-vault-secret-id

### ISSUE THREAD

**Issue by vbrinza** [Azure/azure-cli#10651]
**Describe the bug**
az network application-gateway ssl-cert create --resource-group openitems_res_gr_acc_westeurope --gateway-name openitems-waf-acc-westeurope --name wildcard --key-vault-secret-id https://myvault-key-vault-dt.vault.azure.net/secrets/somelongid/somelongversionofthesecret

Results into:
az network application-gateway ssl-cert create
error: the following arguments are required: --cert-file, --cert-password
when I use
--key-vault-secret-id argument

**To Reproduce**
Use the argument.

**Expected behavior**
It will NOT trait "--cert-file, --cert-password" as required

**Environment summary**

azure-cli                         2.0.67 *
MacOS 10.14.4
Bash

**Comment by MyronFanQiu** [comment]
@vbrinza Hello. I'm looking at this issue. Thanks

**Comment by haroldrandom** [comment]
2.0.67 is too old. In the latest version 2.0.77, the problem should be gone. Can not repro.
Please update to the latest version.

But, even in 2.0.77, it's still imperfect, 
https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L433-L435

Which need service to take a futher fix on the service-side

**Comment by haroldrandom** [comment]
@vbrinza  May close this and open a new one with more specific target?

**Comment by haroldrandom** [comment]
It should be a feature enabled from https://github.com/Azure/azure-cli/pull/10119/files

But as I mentioned above, some bug existed.

cc: @akshaysngupta Any idea on this?

**Comment by haroldrandom** [comment]
The problem mentioned in original description should be fixed.

Thansk @akshaysngupta  I can create a ssl-cert under an application-gateway with only --key-vault-secret-id specified. No mandatory requirement to specify --cert-file, --cert-password.

As shown below. I tested against a secret which generated from a *.pfx cert without password protection
![image](https://user-images.githubusercontent.com/14357159/70122227-33a6a780-16ab-11ea-83e1-5c65952d005a.png)

But I can not find a PR about this, and the commit history proves the code hasn't changed since creation. So I guess it was fixed on service side. If I am wrong, please point me out :)

Please have a try on the latest version of azure-cli. feel free to reopn.

**Comment by haroldrandom** [comment]
> 2.0.67 is too old. In the latest version 2.0.77, the problem should be gone. Can not repro.
> Please update to the latest version.
> 
> But, even in 2.0.77, it's still imperfect,
> https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L433-L435
> 
> we still can not create a ssl-cert under an application-gateway. Which need service to take a further fix on the service-side

As for this, I will make it right.
