### ISSUE TITLE
Storage authentication parameters are cumbersome to use

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1065]
Storage commands such as az container list require the connection string, SaS, account name, etc.  These make sense as optional parameters but shouldn't be required, since you're already authenticated and can retrieve the connection string, SaS, etc via other commands.

Presently, you have to call two commands in the common case--one to get the SaS and one to query the container.  There should be one command.  

The support for environment variables and global config isn't helpful in situations where you're interacting with more than one storage account, which is also quite common.

**Comment by tjprescott** [comment]
You can specify just storage account name with --account-name (or use the environment variable) and it will automatically attempt to get the storage key for you. However, I don't suggest that because it doesn't cache the key which means you are making multiple REST calls per command You also have to include the storage account name parameter every time. You could set the storage account name environment variable, but then you'd still incur the double REST calls and if you're going to be doing a lot of storage commands, setting the connection string makes sense.

If you are using a SAS token to authenticate, it is likely because you don't have the permissions to retrieve the key and the token was given to you.

**Comment by tjprescott** [comment]
For commands which use multiple storage accounts (the copy commands are the only ones I know of), the parameters for the source account are provided in a separate argument group. They do not have backing environment variables though.

**Comment by johanste** [comment]
I believe that @binderjoe's "multiple storage account" comment is not about a single command using multiple storage accounts into affect, but rather that he has multiple storage accounts, and thus need to reset the environment variable constantly in order to work with 'em all. In other words, using environment variables don't really solve his problem.

**Comment by tjprescott** [comment]
@johanste I see what you mean. In that case, you might rely on the --account-name shortcut and accept the double REST call penalty. This is already supported.

**Comment by colemickens** [comment]
Why not something like this, for advanced users:

```
source $(azure storage export-keys --account-name=mycoolstrgacct)
```

that would automatically export the relevant variables into their current shell?

**Comment by tjprescott** [comment]
That's an option, but functionally not different from setting the connection string environment variable. You still incur that additional command call one way or another.

**Comment by colemickens** [comment]
IMO, it's a fair bit better than me running a command that dumps the key to standard out, then having to copy and paste it into the KEY variable, and then again exporting the NAME variable. (1 command, versus 3 with a copy/paste action).

Though, to be honest, I'll probably just use the `--account-name` shortcut that retrieves the key for me even if there's a slight overhead.

**Comment by tjprescott** [comment]
You can also use this single command instead of three:
`export AZURE_STORAGE_CONNECTION_STRING=$(az storage account show-connection-string -g myrg -n myaccount -o tsv)`

Also, for those scenarios where making multiple calls for the keys could be onerous (think copying/uploading/downloading files in bulk) we will likely have this loop occur within the command (vice looping the command itself) which means the key would only be requested once.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
