### ISSUE TITLE
"az ad app permission add" description not understandable

### ISSUE THREAD

**Issue by deaksa** [Azure/azure-cli#10698]
Under the Required Parameters, the --api-permissions property documentation states this:
Space seperated list of =.
The values next to the "=" are not visible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
Hi @deaksa, may I know which platform you are using? I tested on Windows CMD, PowerShell, WSL and Cloud Shell. All work as expected:

```
> az ad app permission add -h

Command
    az ad app permission add : Add an API permission.
        Invoking "az ad app permission grant" is needed to activate it.

Arguments
    --api             [Required] : The target API to access.
    --api-permissions [Required] : Space seperated list of <resource-access-id>=<type>.
    --id              [Required] : Identifier uri, application id, or object id.
```

**Comment by Falconne** [comment]
I expect this issue was raised from the Microsoft documentation page: https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest

If you look there you can see the issue; the generated website content doesn't escape the content for HTML, so the text inside angle brackets don't show up.

**Comment by yonzhan** [comment]
add to S165.

**Comment by dbradish-microsoft** [comment]
I am adding myself to this issue thread in order to notify interested parties upon resolution.

**Comment by jiasli** [comment]
I see. The reason is that the doc generator parses `<resource-access-id>` as a possible HTML entity, but it doesn’t match up with an entity with what’s on the [Docs HTML Whitelist](https://review.docs.microsoft.com/en-us/help/onboard/admin/html-whitelist?branch=master), and the content is discarded. 

I am thinking maybe we can quote the text with backtick `` ` `` like what `azure-cli-core` does: https://github.com/Azure/azure-cli/blob/c4e91c00b7266efb7fb05dcd75870ea2dde713cc/src/azure-cli-core/azure/cli/core/commands/parameters.py#L241
