### ISSUE TITLE
[Storage] Resource group should be optional or omitted for most storage management commands

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1073]
Since storage accounts have globally unique names, there is no reason you should have to specify a resource group name when performing storage account management operations (except create). In KeyVault, the vault is found using only the name provided it is contained within the subscription. If resource group IS specified, it is treated as a filter (i.e. perform this operation only if the vault with X name is in Y resource group).

**Comment by johanste** [comment]
I'm a bit concerned about this since the storage account name isn't *that* globally unique (it is only unique for a given endpoint for one - I'm pretty sure you can have a storage account with the same name on stack as you have on public azure). Also, there is nothing really contractual about the name being unique - it happens to form the basis of the URLs to access the storage account, but I don't think it would be a breaking change if (hypothetically), a new storage account type used a different suffix than the current one.

**Comment by tjprescott** [comment]
But it is like you said--you don't need the resource group name to identify the storage account--you need the endpoint URL (of which RG isn't a part). Since KeyVault and storage access their resources in the same way (URLs) then it would seem that they should behave consistently.

Right now, RG is optional for KeyVault (in our CLI but also Xplat) and specifying it only makes a request more likely to fail, whereas RG is required for storage. It seems they should behave the same, one way or the other.

**Comment by derekbekoe** [comment]
@williexu
