### ISSUE TITLE
Azure CLI get applications with the differential query option

### ISSUE THREAD

**Issue by tucane** [Azure/azure-cli#10755]
Does Az ad app list support [differential query ](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-differential-query)?

[Az ad app list api reference](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-list)

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
Per [differential query doc](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-differential-query#url-query-string-parameters), differential query is not applicable to applications:

>The supported entity types are: User, Group and Contact. 

Also differential query requires the caller to maintain `deltaLink`. CLI can't do this because it is a stateless tool (except for login credentials).

**Comment by yonzhan** [comment]
Solution provided.
