### ISSUE TITLE
Secondary service bus - allow updates

### ISSUE THREAD

**Issue by mmulhearn** [Azure/azure-cli#10762]
**Resource Provider**
Service Bus Namespace

**Description of Feature or Work Requested**
Ability to update tags on secondary service bus namespaces.  Currently, if you try to, for instance, add tags to a secondary namespace, you receive the error "Cannot update a namespace which is secondary"

**Swagger Link**
N/A, using CLI

**Comment by jfggdl** [comment]
@mmulhearn, thanks for creating this issue. We are investigating the level of support we have to add tags to secondary service bus namespaces.

**Comment by jfggdl** [comment]
@mmulhearn, we have created an internal backlog item to be able to update tags on secondary service bus namespaces. I am closing this issue, but feel free to request to open it again if you have any questions or concerns. At this time, we do not have an ETC, but rest assured that we will get to it.


https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/5529891

**Comment by mmulhearn** [comment]
Sounds good, @jfggdl . Thanks for the update

**Comment by jhueppauff** [comment]
Not sure why this issue was closed? I think this still needs attention. 
I am facing the same issue when deploying infrastructure as part of an ARM Template/Bicep. 

Even if there are no changes in the template, the peering prevents a successful completion of the deployment if you try to apply it a second time.
Shouldn't ARM deployments be declarative and iterative? This behavior seems to be against the core principles of ARM/IaC.

**Comment by SathishGP** [comment]
Yeah. I am still facing this issue still. I am generating this as a part of the ARM templates using EV2 and it fails when trying to update the secondary eventHub. I am configured the deployments to be incremental, and there are no changes to the code as well in the subsequent deployments. This fails all the downstream tasks as a result. Can you help reopen the issue and mitigate it?

**Comment by UmairSyed** [comment]
Any updates on this one? I am also getting the same error when redeploying the same configs through bicep? As a workaround I could break the pairing and then do the deployment but that also wont work if we have any queues or topics deployed in future.

**Comment by C0smin** [comment]
Hi, I'm getting the same problem, we need to deploy geo-paring via CI/CD, did anyone find a way to work around this limitation?

**Comment by EldertGrootenboer** [comment]
We are currently rolling out a new HA / DR feature, [Geo-Replication](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-geo-replication). This will reach GA state soon, at which point we recommend switching to this instead of the current [Geo-DR](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-geo-dr) feature. The new Geo-Replication feature uses a single namespace with multiple regions, instead of having to peer two different namespaces. This solves a variety of drawbacks of the Geo-DR feature, among which that not all configuration is replicated. As such, it will also resolve the issue discussed here.
