### ISSUE TITLE
Rule dependecy loop and warning

### ISSUE THREAD

**Issue by microkost** [Azure/azure-cli#10764]
I have az cli commands:
  az monitor autoscale rule create ... --scale in 2
  az monitor autoscale rule create ... --scale out 1
but executing sequentionally I get error independently on commands orders: 
az : WARNING: Profile 'default' has rules to scale out but none to scale in. Recommend creating at least 1 scale in rule.
How to avoid this warning except ignoring it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25999d81-221d-052e-03b8-601585f71e3a
* Version Independent ID: ee988a97-bcf4-0ea2-9ab7-cd6af5e98237
* Content: [az monitor autoscale rule](https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@microkost Hello. which command sends the warning message? Both or the second one?

**Comment by microkost** [comment]
It doesn't matter which one is first if first scale-out or first scale-in. It's always worried that there is no opposite command.

**Comment by microkost** [comment]
It's maybe also related: the previous command:
`az monitor autoscale create --name...`
produce error:
`az : WARNING: Follow up with `az monitor autoscale rule create` to add scaling rules.`
even the next commands is:
`az monitor autoscale rule create --autoscale-name  ... --scale in 2`
produce error:
`az : WARNING: Profile 'default' has rules to scale in but none to scale out. Recommend creating at least 1 scale out rule.`
even the next commands is:
`az monitor autoscale rule create --autoscale-name  ... --scale out 1`

There is a problem with sequencing or I am somehow undersranding it wrongly...

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by jsntcy** [comment]
@microkost, I have tried the commands and the warning is by design (scale in and scale out are expected to be created as a pair. The warning can notify users when they forget to create a paired rules which may cause unexpected behaviors for auto-scale, such as unlimited scale out, or scale in to zero.) I use azure cli 2.9.1. Could you try that version?

Below is the screenshot that I created scale in rule first, then scale out rule. (only show warning when I create scale in rule, after I create scale out rule, no warning shows.)
![image](https://user-images.githubusercontent.com/16348853/88759696-e88f5680-d19d-11ea-8628-6af19e8f2ffa.png)

@achandmsft, please help confirm the warning behavior.

**Comment by yonzhan** [comment]
@microkost, any update?

**Comment by jsntcy** [comment]
close as no response from customer for a long time. @microkost, if you still have this issue, you can reopen this issue.
