### ISSUE TITLE
RHEL8 packaging regression?

### ISSUE THREAD

**Issue by davemulford** [Azure/azure-cli#10779]
**Describe the bug**
The azure-cli-2.0.74-1.el7 package fails to install on RHEL8. The most recent version that installs successfully is azure-cli-2.0.69-1.el7.

**To Reproduce**
Install the azure-cli as described in the [azure-cli install docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest).

**Expected behavior**
The azure-cli should be installed.

**Environment summary**

    # cat /etc/redhat-release 
    Red Hat Enterprise Linux release 8.0 (Ootpa)

    # yum repolist -v
    Repo-id      : azure-cli
    Repo-name    : Azure CLI
    Repo-revision: 1569293360
    Repo-updated : Mon 23 Sep 2019 10:52:43 PM EDT
    Repo-pkgs    : 56
    Repo-size    : 1.3 G
    Repo-baseurl : https://packages.microsoft.com/yumrepos/azure-cli
    Repo-expire  : 172,800 second(s) (last: Tue 08 Oct 2019 05:37:47 PM EDT)
    Repo-filename: /etc/yum.repos.d/azure-cli.repo

**Additional context**
I'm aware of #7976 and #8780, but do not see a clear decision on whether support for various distros was dropped, or just not decided upon yet.

**Comment by fengzhou-msft** [comment]
@davemulford Thanks for reporting the issue. I am going to reproduce the issue and see what's broken.

**Comment by fengzhou-msft** [comment]
The package is for el7, and there are assumptions based on el7 that are no longer true for RHEL8. For now, instead of running `sudo yum install azure-cli`, please follow the workaround to install azure-cli:
```bash
$ sudo yum install python2
$ sudo yum install yum-utils
$ sudo yumdownloader azure-cli
$ sudo rpm -ivh --nodeps azure-cli-2.0.75-1.el7.x86_64.rpm
```
Then edit the second line of `/usr/bin/az` (result of `which az`) to specify using python2:
`PYTHONPATH=/usr/lib64/az/lib/python2.7/site-packages python2 -sm azure.cli "$@"`

Meanwhile, we will consider better ways to support  RHEL8 systems.

**Comment by davemulford** [comment]
@fengzhou-msft excellent! I had tried something similar to what you suggested, but was missing the need to modify /usr/bin/az.

Your instructions worked. Thank you!
