### ISSUE TITLE
az ad app create remove requirement for EOF

### ISSUE THREAD

**Issue by dotMikeH** [Azure/azure-cli#10820]
**Is your feature request related to a problem? Please describe.**
Reference: https://stackoverflow.com/questions/55500388/issue-creating-azure-app-registration-with-az-cli

There seems to be a dependency on certain parameters requiring a file as it's expecting an EOF.
**Command Example:** `az ad app create --display-name gizmo-auto-create --required-resource-accesses [{"resourceAppId": "00000002-0000-0000-c000-000000000000","resourceAccess": [ {"id": "a42657d6-7f20-40e3-b6f0-cee03008a62a","type": "Scope"}]}]`

Running this gives me the error: `SyntaxError: unexpected EOF while parsing`
However simply adding that same text to some file, say manifest.json and passing that file path as a the parameter value makes this work. Like why is that a dependency?

**Describe the solution you'd like**
We should be able to pass a string that is formatted in JSON in these parameters without relying on either having a file already created or creating the file in a script.
**Example Command That Should Work:** `az ad app create --display-name gizmo-auto-create --required-resource-accesses [{"resourceAppId": "00000002-0000-0000-c000-000000000000","resourceAccess": [ {"id": "a42657d6-7f20-40e3-b6f0-cee03008a62a","type": "Scope"}]}]`

**Describe alternatives you've considered**
The automation script that I'm building is built around python3 since the azure cli docker image supports it, I tried io.StringIO, but that doesn't have EOF so it still errors out with `SyntaxError: unexpected EOF while parsing`. Also tried converting to JSON using json.dumps(variable), but that also gives me the same error.

**Additional context**
We're converting our automation process to run on Linux Docker containers w/ the azure-cli image. It's adding unnecessary complexity to have to create a file that has for example app roles and then another file containing permissions, and then calling that file. Have not tested this, but even if you could add both parameters to a single file, the unnecessary complexity still stands.

Edit:
Same can be said about `az ad app update` as well since it also has the requirement of EOF

**Comment by jiasli** [comment]
Thank you for reaching us. We will investigate this issue.

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
`SyntaxError: unexpected EOF while parsing` doesn't mean it requires `EOF`, but instead it meets an unexpected `EOF` where it shouldn't.

This command:

```
az ad app create --display-name gizmo-auto-create --required-resource-accesses [{"resourceAppId": "00000002-0000-0000-c000-000000000000","resourceAccess": [ {"id": "a42657d6-7f20-40e3-b6f0-cee03008a62a","type": "Scope"}]}]
```

doesn't work is because it is not quoted correctly, so double quotes and whitespaces are interpretative by the shell. 

Since #3850, `SyntaxError: unexpected EOF while parsing` can be raised by `ast.literal_eval`, but in that case, it is caught and the original `ValueError` from `json.loads` will be thrown out.

https://github.com/Azure/azure-cli/blob/e6e437a80639616c9871d1d9248bbb1a65be268e/src/azure-cli-core/azure/cli/core/util.py#L398-L404

If you are still seeing `SyntaxError`, you may be using a very old version of Azure CLI.

Here is my test result in Cloud Shell:

```sh
# Fail if JSON is not quoted
$ az ad app create --display-name gizmo-auto-create --required-resource-accesses [{"resourceAppId": "00000002-0000-0000-c000-000000000000","resourceAccess": [ {"id": "a42657d6-7f20-40e3-b6f0-cee03008a62a","type": "Scope"}]}]
Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

# By quoting the JSON, the app is created successfully
$ az ad app create --display-name gizmo-auto-create --required-resource-accesses '[{"resourceAppId": "00000002-0000-0000-c000-000000000000","resourceAccess": [ {"id": "a42657d6-7f20-40e3-b6f0-cee03008a62a","type": "Scope"}]}]'
{
  "acceptMappedClaims": null,
  "addIns": [],
  "allowGuestsSignIn": null,
  "allowPassthroughUsers": null,
  "appId": "4c2c2fc5-0244-4a1b-a0fa-85ede9d69054",
  ...
```

You may check [Quoting issues](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) for more information.
