### ISSUE TITLE
vmss stop --instance-ids has trouble with multiple-digit IDs

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-cli#1087]
I'm currently running `az` off `pypi`(`azure-cli==0.1.0b7`), and when I do:

```
az vmss stop --instance-ids "10 14" --resource-group test --name agents
```

I get:

```
The provided instanceId 1 is not an active Virtual Machine Scale Set VM instanceId. 
```

Trying to stop instances 3 and 4 works, so I think there's something wrong with argument parsing here.

**Comment by johanste** [comment]
I haven't debugged (from the description, there is clearly an issue here), but my expectation for invoking the command would be that you do *not* put quotes around the list of instance ids.

**Comment by mayurid** [comment]
@rcarmo : Did removing quotes work for you?

**Comment by rcarmo** [comment]
No. If it had, I wouldn’t have opened the issue in the first place...

**Comment by tjprescott** [comment]
I just attempted to reproduce this issue and I believe that this is related to using quotes around the instance ids, because the help text would lead one to believe you should. The following works fine:

`az vmss stop --instance-ids 10 11 12 -g {rg} -n {name}`

I will issue a PR to update the help text.
