### ISSUE TITLE
Typo in group deployment command when defining parameters

### ISSUE THREAD

**Issue by sahan91** [Azure/azure-cli#10907]
In the following command 
`az group deployment create -g MyResourceGroup --template-uri https://myresource/azuredeploy.json --parameters @myparameters.json`

`--parameters @myparameters.json` part should be `--parameters '@myparameters.json'`

Tested on PowerShell Core
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de233487-a2e5-00ab-30e9-f68866735957
* Version Independent ID: 2cd3ed9f-113f-a6c2-6a36-2925a044edf8
* Content: [az group deployment](https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Hi @sahan91, thanks for your feedback. I can repro your issue in Powershell, user have to provide ''. We will find a way to deal with PS scenario.

**Comment by sahan91** [comment]
Yes, that's correct. Thanks for confirming it!

**Comment by yonzhan** [comment]
Can we close it?

**Comment by zhoxing-ms** [comment]
**This is a PowerShell special character `@` that causes parameter parsing exception.**
When running Azure CLI commands in PowerShell, parsing errors will occur when the arguments contain special characters of PowerShell, such as at `@`. 
You can solve this problem by adding `` ` `` before the special character to escape it, or by enclosing the argument with single or double quotes `'`/`"`. 
For example, `az group deployment create --parameters @parameters.json` dose't work in PowerShell 
because `@` is parsed as a [splatting symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting). 
To fix this, you may change the argument to `` `@parameters.json`` or `'@parameters.json'`.

**Comment by zhoxing-ms** [comment]
We have updated this issue to the relevant documentation.  [link](https://github.com/Azure/azure-cli/pull/11640/files)
If you have any other questions, please let us know.
