### ISSUE TITLE
Commands are missing `--subscription-id`

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1095]
This was a very important feature from `azure-xplat-cli` for me.

The fact that all commands took `--subscription-id` means that I can write scripts that have the user input their subscription ID and I can take action in that subscription without needing to change the global state.

Without this functionality, it's seems impossible to have concurrent running scripts that are running in different subscriptions.

**Comment by colemickens** [comment]
Worse, it seems to allow `--subscription` even though I gave it a bogus value (also ignored when I gave it a real subscription ID that was different from the default)... but it explicitly told me that `--subscription-id` was wrong when I tried it.

If I hadn't tested it thoroughly, then I might've thought that `--subscription` was actually honored, since it doesn't error but also doesn't work.

**Comment by colemickens** [comment]
cc: @ahmetalpbalkan for any thoughts?

**Comment by ahmetalpbalkan** [comment]
Agreed, this makes all the commands idempotent, rather than having a side effect of having a "default subscription" somewhere.

Also, for scripting purposes, having `--subscription-id` will serve as a better way of overriding the "default subscription" without actually modifying it (you don't want scripts to have side-effects like changing the default subscription on your machine).

**Comment by mayurid** [comment]
this is issue #807 
We have discussed this as something we need to pick from backlog soon and I have just moved it to one of the upcoming sprints.

**Comment by colemickens** [comment]
Apologies for the dupe, I've subscribed to #807. Thanks.
