### ISSUE TITLE
Service Principal Login should take subscription ID

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1096]
AAD Servie Principals are hard enough, we should make it easier on users and allow them to login to the CLI with SP Client ID/Secret and the Subscription ID as well as the Tenant ID.

The CLI can retrieve the tenant id in the same way the xplat-cli does it.

**Comment by yugangw-msft** [comment]
On this part new cli behaves the same with xplat-cli. No parity is missing. I am pretty sure xplat-cli will not be able to retrieve tenants for SP, because it won't be able to access the front door ''common" tenant which is the first thing before list the tenants.
But it is possible to get tenant if you can provide the subscription-id. There is published [trick](https://github.com/dushyantgill/VipSwapper/blob/master/CloudSense/CloudStackConsoleInstaller/Program.cs#L64) here we can leverage. 
So want to confirm here, it is more frequently you have subscription info at hand than the tenant? The `az login` has been heavily overloaded with loads of parameters, I just need more data voices to prioritize.

**Comment by colemickens** [comment]
>I am pretty sure xplat-cli will not be able to retrieve tenants for SP, because it won't be able to access the front door ''common" tenant which is the first thing before list the tenants.

Why not? Can't SPs auth to the common tenant just like a regular device login?

>So want to confirm here, it is more frequently you have subscription info at hand than the tenant? 

Very, very much so. That's been my observation with users. CC @ahmetalpbalkan who has more first-hand knowledge of users.

**Comment by yugangw-msft** [comment]
> Why not? Can't SPs auth to the common tenant just like a regular device login?

No. AFAIK, using device flow, in the browser you can only login by org-id or MSA (live-id). Please note, SP name can either be a guid or non-existing uri, there are no hints for the infrastructure to figure out what the tenant it is from.

**Comment by colemickens** [comment]
Sorry, I misspoke. I think SPs can still auth against the common tenant the same way the auth against the tenant-specific endpoint... And then can go through the normal tenant/subscription discovery flow.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
