### ISSUE TITLE
Using PowerShell...

### ISSUE THREAD

**Issue by miicahjardine** [Azure/azure-cli#11008]
Hi, 

I am having trouble using this from ps.  I am trying to update the approles and my code looks like this..

$manifest = get-content $manifestLocation | convertFrom-json
$appRoles = $manifest.appRoles | convertTo-json -depth 5 -compress
az ad app update --id $applicationInfo.appId --app-roles $appRoles

Recieve the following error : Expecting property name enclosed in double quotes: line 1 column 3 (char 2).

Have tried lots of different things, but I am hoping somebody here can help....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
First, PowerShell implicitly 'unboxes' a single-item array to a single object. If `appRoles` contains only one item, using `| ConvertTo-Json` will generate an object instead of an array for [`appRoles`](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps). See [ConvertTo-JSON an array with a single item](https://stackoverflow.com/questions/18662967/convertto-json-an-array-with-a-single-item), [Why does Powershell silently convert a string array with one item to a string](https://superuser.com/questions/414650/why-does-powershell-silently-convert-a-string-array-with-one-item-to-a-string). [`ConvertTo-Json`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6) in PowerShell 6 now has a new param `-AsArray` to support single-item array. So this command can be:

```powershell
$appRoles = $manifest.appRoles | convertTo-json -depth 5 -compress -AsArray
```

Second, `az` is a batch file. 

1. When invoking it with PowerShell, double quotes in the JSON will be parsed again by cmd, which breaks the command
2. PowerShell has problem passing string with commas to cmd. I have created issue https://github.com/PowerShell/PowerShell/issues/11295
3. When a JSON is passed in cmd, double quotes needs to be escaped by `\"`, while PowerShell escapes by `` ` ``

To avoid these complications, you may put `$appRoles` into a temporary file like `appRoles.json` and read it from Azure CLI.

```
$manifestLocation = "manifest.json"
$manifest = Get-Content $manifestLocation | ConvertFrom-Json
ConvertTo-Json $manifest.appRoles -depth 5 -compress > appRoles.json
az ad app update --id d62b494e-e38e-4a93-8394-d5f776d5988a --app-roles "@appRoles.json"
```

More info: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#argument-parsing-issue-in-powershell

**Comment by jiasli** [comment]
First, PowerShell implicitly 'unboxes' a single-item array to a single object. If `appRoles` contains only one item, using `| ConvertTo-Json` will generate an object instead of an array for [`appRoles`](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps). See [ConvertTo-JSON an array with a single item](https://stackoverflow.com/questions/18662967/convertto-json-an-array-with-a-single-item), [Why does Powershell silently convert a string array with one item to a string](https://superuser.com/questions/414650/why-does-powershell-silently-convert-a-string-array-with-one-item-to-a-string). [`ConvertTo-Json`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6) in PowerShell 6 now has a new param `-AsArray` to support single-item array. So this command can be:

```powershell
$appRoles = $manifest.appRoles | convertTo-json -depth 5 -compress -AsArray
```

Second, `az` is a batch file. 

1. When invoking it with PowerShell, double quotes in the JSON will be parsed again by cmd, which breaks the command
2. PowerShell has problem passing string with commas to cmd. I have created issue https://github.com/PowerShell/PowerShell/issues/11295
3. When a JSON is passed in cmd, double quotes need to be escaped by `\"`, while PowerShell escapes by `` ` ``

To avoid these complications, you may put `$appRoles` into a temporary file like `appRoles.json` and read it from Azure CLI.

```
$manifestLocation = "manifest.json"
$manifest = Get-Content $manifestLocation | ConvertFrom-Json
ConvertTo-Json $manifest.appRoles -depth 5 -compress > appRoles.json
az ad app update --id d62b494e-e38e-4a93-8394-d5f776d5988a --app-roles "@appRoles.json"
```

More info: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#argument-parsing-issue-in-powershell

**Comment by yonzhan** [comment]
Can we close this issue?

**Comment by jiasli** [comment]
Closing due to no response. If the issue happens again, please reply to this issue or create a new one.
