### ISSUE TITLE
`az ad sp list --show-mine` does not show all owned service-principals

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/azure-cli#11033]
When I run `az ad sp list --show-mine` I can not retrieve all service principals that I own.

What could be the reason that I do not see the same amount of service principals that I can see in Portal under: Azure Portal &gt; Azure Active Directory &gt; App registrations &gt; Owned applications.

I also tried adding (`--all`), just to be sure.

I am able to retrieve the service-principal by using: 
`az ad sp list --spn $AppID`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by N1ght3yes** [comment]
Still doesn't seem to work, in fact it does not return any of my "owned" App Registrations. Would be great if you'd get this to work soon. Also the result (when retrieving by appDisplayName or appId, which is also very unconvenient) doesn't seem to contain any information about the owner.

**Comment by jiasli** [comment]
In **Azure Portal > Azure Active Directory > App registrations > Owned applications**, it is retrieving your owned **apps**, instead of **service principals**. 

To get the same result as Azure Portal, please use `az ad app list --show-mine`

```
> az ad app list --show-mine --query "[].displayName"
[
  "myapp",
  "myapp2",
  "myapp3"
]
```

To add an owner to a service principal, please go to **Managed application in local directory**

![image](https://user-images.githubusercontent.com/4003950/80557522-c3a60e80-8a09-11ea-98cf-b77fa795b5af.png)

Add yourself as the owner

![image](https://user-images.githubusercontent.com/4003950/80557545-d882a200-8a09-11ea-9d7a-61b82725a46a.png)

The `az ad sp list --show-mine` will show the correct result:

```
> az ad sp list --show-mine --query "[].displayName"
[
  "myapp"
]
```
