### ISSUE TITLE
Consistent parameter naming for cosmosdb subcommands (and wider)

### ISSUE THREAD

**Issue by johnyesberg** [Azure/azure-cli#11154]
**Is your feature request related to a problem? Please describe.**
It is difficult to remember that different parts of the cli require different parameter names for the same information. For example, if we compare `az cosmosdb database show` and `az cosmosdb sql container list`, there are different parameter names for:

- a resource group: `--resource-group-name` vs `--resource-group` 
- a database name: `--db-name` vs `--database-name`
- an account: `--name` vs `--account-name`

**Describe the solution you'd like**
I'd like parameter names to be standard across the whole az cli as far as practical. Maybe non-standard names could be kept for backward compatibility reasons where there is no conflict.

**Describe alternatives you've considered**
I don't see any other reasonable alternatives.

**Additional context**
```
C:\>az cosmosdb database show
az cosmosdb database show: error: the following arguments are required: --db-name/-d
usage: az cosmosdb database show [-h] [--verbose] [--debug]
                                 [--output {json,jsonc,table,tsv,yaml,none}]
                                 [--query JMESPATH]
                                 [--resource-group-name DB_RESOURCE_GROUP_NAME]
                                 [--name DB_ACCOUNT_NAME]
                                 [--key DB_ACCOUNT_KEY]
                                 [--url-connection DB_URL_CONNECTION]
                                 [--subscription _SUBSCRIPTION] --db-name
                                 DATABASE_ID

C:\>az cosmosdb sql container list
az cosmosdb sql container list: error: the following arguments are required: --resource-group/-g, --account-name/-a, --database-name/-d
usage: az cosmosdb sql container list [-h] [--verbose] [--debug]
                                      [--output {json,jsonc,table,tsv,yaml,none}]
                                      [--query JMESPATH]
                                      [--subscription _SUBSCRIPTION]
                                      --resource-group RESOURCE_GROUP_NAME
                                      --account-name ACCOUNT_NAME
                                      --database-name DATABASE_NAME
```

**Comment by fengzhou-msft** [comment]
Thanks for the feedback. We will evaluate this request and see how to improve the command naming.

**Comment by shurd** [comment]
Hi @johnyesberg thank you for opening this issue. In version 2.0.71 of the CLI, we added API specific commands for dealing with databases and collections (az cosmosdb [sql|cassandra|gremlin|mongodb|table]). The parameter naming across these command groups is consistent, and we encourage the use of these commands instead of the older "database" and "collection" commands, which are much more limited. We will be deprecating these older commands in a future release.

The "--name" parameter does change at each command-group level, but that follows CLI guidelines that the "name" refers to the direct resource that command applies to. For example in `az cosmosdb sql database`, "--n" refers to the database name. In `az cosmosdb sql container`, "--n" refers to the container name.
