### ISSUE TITLE
Adding multiple network-rules at once

### ISSUE THREAD

**Issue by mkozioro** [Azure/azure-cli#11350]
Hi,

In each of my deployments I'm adding 8 subnets to my cosmosdb firewall. It takes lots of time, around 5 minutes per subnet. It would be nice to have feature allowing to add them all (maybe also with ip address rules) at once. 
I'm doing deployments couple times a day and setting firewall rules takes more time than everything else in deployment summed.

**Comment by MyronFanQiu** [comment]
@mkozioro Thanks for reporting this issue. Which command are you using?

**Comment by mkozioro** [comment]
Hi @MyronFanQiu 
I'm using
az cosmosdb network-rule add --resource-group "${RESOURCE_GROUP}" --name "${COSMOSDB_NAME}" --subnet ${SUBNET_ID}

**Comment by shurd** [comment]
Hi @mkozioro thank you for raising this issue. We do support adding multiple network rules at once as a part of the `az cosmosdb update`. With the `--virtual-network-rules` flag, you can specify a list of subnets to add to the account. 

We added the "network-rule" command group so that subnets could be added to an account before the virtual network has vnet service endpoint enabled. If you have the service endpoint enabled on all subnets you are adding to an account, you can use the `update` command. Specifying "subnet" and "ignoreMissingVnetServiceEndpoint" requires an object, so if you need both properties, then you have to add endpoints one at a time.
