### ISSUE TITLE
List of Graph API permission

### ISSUE THREAD

**Issue by gregdegruy** [Azure/azure-cli#11354]
In the "add a Graph API permission" example "Sign in and read user profile" are represented by guids. Is there a doc that has a complete list of all api permissions and their guids?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az-ad-app-permission-admin-consent)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by g-rad** [comment]
@gregdegruy https://blogs.msdn.microsoft.com/aaddevsup/2018/06/06/guid-table-for-windows-azure-active-directory-permissions/

311a71cc-e848-46a1-bdf8-97ff7156d8e6 - (Scope) Sign in and read user profile

**Comment by jiasli** [comment]
Thanks @g-rad, the link helps a lot! 😃

**Comment by Falconne** [comment]
@jiasli This issue is closed, but there is nothing in the documentation that would have let me find that GUID table blog post. I had Googled "az cli api permissions guids" but that didn't find it either. Luckily that search led me to this repo and I saw this issue. 

I think that table should really be in the official documentation and discoverable from the docs for " az ad app permission add".

**Comment by wsmelton** [comment]
Posting this here since Bing brought me here through searching.

SO answer includes `az` command to pull the Microsoft Graph API permissions listing: https://stackoverflow.com/questions/41946417/how-can-i-get-the-guids-of-graph-api-permissions-programmatically-for-an-azure-a/63405409#63405409

Command reference (in case you can't hit SO):

```
az ad sp show --id 00000003-0000-0000-c000-000000000000
```

Could not find this available data via `Microsoft.Graph` module.

**Comment by jiasli** [comment]
Hi @wsmelton, thank you for the link. 

Could you share more context about

> Could not find this available data via `Microsoft.Graph` module.

Do you mean the [`Microsoft.Graph`](https://www.powershellgallery.com/packages/Microsoft.Graph/1.1.0) PowerShell module?

**Comment by wsmelton** [comment]
Correct. I had assumed that would be the module to use but did find AzureAD has it as well, just have to pull the Service ID for `Microsoft Graph`.

```powershell
$msGraphService = Get-AzureADServicePrincipal -Filter "DisplayName eq 'Microsoft Graph'"
$permissions = $msGraphService.AppRoles.Where({$_.Value -in $appPerms})
```

**Comment by jiasli** [comment]
### `Get-AzureADServicePrincipal`

`Get-AzureADServicePrincipal` from [`AzureAD`](https://www.powershellgallery.com/packages/AzureAD/2.0.2.118) module calls **Active Directory Graph** internally.

In Windows PowerShell,

```powershell
Install-Module AzureAD
Connect-AzureAD -TenantId 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
$msGraphService = Get-AzureADServicePrincipal -Filter "DisplayName eq 'Microsoft Graph'"
ConvertTo-Json $msGraphService
```

We can see

- **Application permissions** appear under `AppRoles`
- **Delegated permissions** appear under `Oauth2Permissions`

### `Get-MgServicePrincipal`

`Get-MgServicePrincipal` from [`Microsoft.Graph`](https://www.powershellgallery.com/packages/Microsoft.Graph/1.1.0) module calls **Microsoft Graph** internally.

In PowerShell 7,

```powershell
Install-Module -Name Microsoft.Graph
Connect-MgGraph -Scopes "Application.Read.All" -TenantId 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
$msGraphService = Get-MgServicePrincipal -Filter "DisplayName eq 'Microsoft Graph'"
ConvertTo-Json $msGraphService
```

According to [servicePrincipal resource type](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0#properties),

- **Application permissions** appear under `AppRoles`
- **Delegated permissions** appear under `oauth2PermissionScopes`  << Note the name change


### Some findings (LT; DR)

I tried `AzureAD` in PowerShell 7, but hit a failure (https://github.com/PowerShell/PowerShell/issues/11564), so I used `-UseWindowsPowerShell`:

```powershell
Install-Module AzureAD
Import-Module AzureAD -UseWindowsPowerShell
Connect-AzureAD -TenantId 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
$msGraphService = Get-AzureADServicePrincipal -Filter "DisplayName eq 'Microsoft Graph'"
ConvertTo-Json $msGraphService
```

The result is corrupted, perhaps because

> WARNING: Module AzureAD is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax.

```powershell
> $msGraphService.AppRoles[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String
```

Not sure if there is any fix/workaround for this issue.

**Comment by jiasli** [comment]
Meanwhile, let me refine the help message for `az ad app permission add`.
