### ISSUE TITLE
az webapp up FileNotFoundError

### ISSUE THREAD

**Issue by suraj813** [Azure/azure-cli#11370]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\__init__.py, ln 485, in default_command_handler
cli\command_modules\appservice\custom.py, ln 2919, in webapp_up
cli\command_modules\appservice\_create_util.py, ln 59, in get_runtime_version_details
cli\command_modules\appservice\_create_util.py, ln 192, in parse_netcore_version
lib\xml\etree\ElementTree.py, ln 1196, in parse
    tree.parse(source, parser)
lib\xml\etree\ElementTree.py, ln 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} --dryrun`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76

```

**Comment by panchagnula** [comment]
2 things. 

1. Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76
2. Also when using az webapp up command make sure you run it from context of the local directory where the code to be deployed exists.


Please feel free to re-open if your issue is still not resolved by the instructions above. Thanks.
