### ISSUE TITLE
Please provide example for creating a correlation filter rule.

### ISSUE THREAD

**Issue by damiandiaz76** [Azure/azure-cli#11389]
Could you please provide an example for creating correlation filter rule.  We I try to specify a correlation filter argument (like --to), it errors out saying:
BadRequest - Value cannot be null.
Parameter name: sqlExpression

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd5960a-ea47-7542-6837-3e4e49e95d0a
* Version Independent ID: c8a9f5b6-2a2f-4820-3be4-c87e3896a6b7
* Content: [az servicebus topic subscription rule](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/servicebus/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/servicebus/_help.py)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jfggdl** [comment]
@damiandiaz76, thank you for your inquiry. This helps us understand any gaps in our documentation or samples. We are looking for a public document that provides an example of a correlation filter rule.

**Comment by jfggdl** [comment]
By the way, please provide the filter that you are using? It sounds like you are using a SQL filter expression.

**Comment by damiandiaz76** [comment]
I'm trying to not use an sql filter.  I want to create a correlation filter.  I want this correlation filter to use the "to" field.  I tried specifying the "--to" option: "--to requests" but received the sqlExpression error.

**Comment by LayZeeDK** [comment]
Related to https://github.com/Azure/azure-cli/issues/12369.

**Comment by Saglodha** [comment]
HI @damiandiaz76 , this has been fixed in our latest release. You should be able to create SQL filter rule now. 

Here is some sample cmdlet example : az servicebus topic subscription rule create --resource-group {rg} --namespace-name {namespacename} --topic-name {topicname} --subscription-name {subscriptionname} --name {rulename} --filter-type CorrelationFilter --correlation-id r00012d --label myvalue --message-id mid --reply-to reply --session-id ids --reply-to-session-id hi --content-type hi --to hi 

Please test it out and let us know in case you observe any discrepancies.

**Comment by damiandiaz76** [comment]
I tried out the command to add a correlation filter using the --to option and it worked.  Thanks for the update.

**Comment by Saglodha** [comment]
Thanks for confirming @damiandiaz76. With above confirmation, I would mark the issue as closed.
