### ISSUE TITLE
Ctrl-Y doesn't yank

### ISSUE THREAD

**Issue by exFalso** [Azure/azure-cli#11383]
## Describe the bug

**Command Name**
no command

**Errors:**
no errors

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Kill rest of line with Ctrl-K, or backwards-kill a word with Ctrl-W. Afterwards Ctrl-Y doesn't do anything.

## Expected Behavior

Ctrl-Y should yank the killed text

## Environment Summary
```
Linux-5.3.11-arch1-1-x86_64-with-arch
Python 3.6.8
Shell: bash

azure-cli 2.0.76

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
`az interactive` internally [uses](https://github.com/Azure/azure-cli-extensions/blob/a8523ab03708b16dd65c5be85cba4b4beca7cde6/src/interactive/setup.py#L35) [`prompt_toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit). We will investigate it. But since the interactive extension is in preview, we can't guarantee the ETA.

**Comment by jiasli** [comment]
`az interactive` internally [uses](https://github.com/Azure/azure-cli-extensions/blob/a8523ab03708b16dd65c5be85cba4b4beca7cde6/src/interactive/setup.py#L35) [`prompt_toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit). We will investigate whether this issue is related to interactive or prompt-toolkit. Since interactive is still in preview, we are actively working on it.

**Comment by RakeshMohanMSFT** [comment]
This must be fixed now https://github.com/Azure/azure-cli/issues/24213.
