### ISSUE TITLE
Missing `sku_name` parameter for `az postgres create`

### ISSUE THREAD

**Issue by SphinxKnight** [Azure/azure-cli#11464]
When reading [this guide about creating a Azure Database for PostgreSQL with AZ CLI](https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-database-azure-cli), one can find the following command, provided as an example:

`az postgres server create --resource-group myresourcegroup --name mydemoserver  --location westus --admin-user myadmin --admin-password &lt;server_admin_password&gt; --sku-name GP_Gen4_2 --version 9.6`

However, the current CLI doc does not mention the `sku-name` option nor does it link to some other page defining it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167cf208-d53e-0e14-7c3e-ba55e9933189
* Version Independent ID: 38dab769-ed7c-957d-b81c-6cbeba9670a8
* Content: [az postgres db](https://docs.microsoft.com/en-us/cli/azure/postgres/db?view=azure-cli-latest#commands)
* Content Source: [latest/docs-ref-autogen/postgres/db.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/postgres/db.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rachel-msft** [comment]
@SphinxKnight, thanks for getting in touch. The document you referenced in the issue is az postgres db, which is a way you can create databases in a server. I believe the document you are looking for is https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest#az-postgres-server-create
![image](https://user-images.githubusercontent.com/32173602/70182771-5c25a600-1699-11ea-846a-0a62be2fa6d8.png)

**Comment by SphinxKnight** [comment]
Thanks! Sorry for reading too quickly between `az postgres db create` and `az postgres server create` :s and wasting a bit of your time.

**Comment by rachel-msft** [comment]
No problem
