### ISSUE TITLE
The `file-snapshot` option is equivalent to _Restore_ command in Portal

### ISSUE THREAD

**Issue by giuliov** [Azure/azure-cli#11520]
The `file-snapshot` option is equivalent to _Restore_ command in Portal but this is not clear from documentation.

Looks like that running
```bash
az storage file copy start --account-name $STORAGEACCOUNT_NAME --account-key $STORAGEACCOUNT_KEY --destination-share database --destination-path pubs.mdf --source-share database --source-path pubs.mdf --file-snapshot $SNAPSHOT_TIMESTAMP -o json
```
has the same effect restoring a file of a share to an existing snapshot version.

Furthermore searching for "restore" does not return this page, which is what one is looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a635a197-a39e-7368-9d30-78c6e686272a
* Version Independent ID: 1a6dcecc-d86f-ea73-7452-ba8a9ba2137e
* Content: [az storage file copy](https://docs.microsoft.com/en-us/cli/azure/storage/file/copy?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@Juliehzl Please take a look

**Comment by Juliehzl** [comment]
Hi @giuliov, thanks a lot for your feedback. I think you're right. The file snapshot can be used to copy from existing snapshot even for the file which is already deleted, but no document for restore introduction.The information about the operation is in https://docs.microsoft.com/en-us/azure/storage/files/storage-snapshots-files#copying-data-back-to-a-share-from-share-snapshot. I think it is because the operation is a workaround for restore deleted files with snapshots, not actual "restore". In this way, you cannot the command/operaion is included the pages for "restore" 

In addition, we will have actual restore command for deleted files with soft-delete policy soon. This time we will have detailed documentation for "restore".

Anyway, thanks a lot for your feedback! If you still have any question, feel free to create an issue and let me know.
