### ISSUE TITLE
acs: create command with flag to create ssh keys looks like it is stuck in creating ssh keys step

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#1152]
<img width="1214" alt="screen shot 2016-10-24 at 11 14 28 pm" src="https://cloud.githubusercontent.com/assets/15387759/19674987/8cceb612-9a40-11e6-9857-dde1f276e27f.png">

@yugangw-msft - creating ssh key never changes state until the acs is created 15 mins after the cluster is created. The user might think that the command is stuck in creating ssh step..

**Comment by yugangw-msft** [comment]
@sauryadas  The root cause is the minimum output from the command (no progress by default).  It is not a unique behavior to ACS create. For `vm create` people was also confused that after input the user password on prompt, the command looks hang :-)
I am open to suggestion at this point. Maybe i can downgrade the warning to info; hence it will not show up?

**Comment by yugangw-msft** [comment]
Maybe i can reword the warning to `Ssh key ... created`? The reason I put in a warning was this is an important file

**Comment by sauryadas** [comment]
what if you put the warning Ssh key ... created and then the ssh key creation fails?

**Comment by yugangw-msft** [comment]
Sorry, i should have commented more clearly. 
It won't happen. I will move the warning to after the key is created. If there is failure on key-gen, you should see the failure detail and the command won't continue
