### ISSUE TITLE
Running az apim backup command provoque a traceback

### ISSUE THREAD

**Issue by mont5piques** [Azure/azure-cli#11608]
## Describe the bug

**Command Name**
`az apim backup`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


backup() takes at least 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/local/bin/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/bin/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: backup() takes at least 4 arguments (3 given)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim backup -n {} -g {}`

## Environment Summary
```
Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.04-disco
Python 2.7.16
Shell: bash

azure-cli 2.0.77 *

```

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14830

**Comment by navba-MSFT** [comment]
@mont5piques Apologies for the late reply. Refer #14127 #14830 . Please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the AzCLI and let us know if you still see the issue ? Also this issue is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.
