### ISSUE TITLE
why is there no `az webapp webjob [continuous|triggered] add` or `az webapp webjob [continuous|triggered] new` command?

### ISSUE THREAD

**Issue by BryanWilhite** [Azure/azure-cli#11636]
I would like to use an Azure CLI Task in Azure DevOps to Release WebJobs in a CD pipline.

In Azure PowerShell we have had the `New-AzureWebsiteJob` command [[docs](https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/new-azurewebsitejob?view=azuresmps-4.0.0) 📚 ] and i fail to see the Azure CLI equivalent.

This is what it looks like in PowerShell:

```ps1
$job =
@{
    Name = "job-feeds";
    SubscriptionName = "My Subscription";
    WebSiteName = "my-web-site-name";
    ZipFile = "$env:AGENT_RELEASEDIRECTORY\$env:BUILD_DEFINITIONNAME\drop\MyWebJobRelease.zip";
}

Get-AzureSubscription -SubscriptionName $job.SubscriptionName
Select-AzureSubscription -SubscriptionName $job.SubscriptionName

Get-AzureWebsite | ForEach-Object {Get-AzureWebsite -Name $_.Name}

New-AzureWebsiteJob `
    -Name $job.WebSiteName `
    -JobName $job.Name `
    -JobType Triggered `
    -JobFile $job.ZipFile
```

**Comment by panchagnula** [comment]
This is a by design decision taken by the feature crew. WebJobs SDK is older format of Azure functions - & moving forward the feature team support is for managing Webjobs only using CLI/Powershell commands & not for creating. At this point we have no plans for supporting this. 
Also CCing folks for Functions as FYI CC: @ahmedelnably
