### ISSUE TITLE
Issue with az rest updating appsettings for an azure function that contains a cron expression

### ISSUE THREAD

**Issue by chrisxpr** [Azure/azure-cli#11641]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If I try to update an azure function appsetting using the Azure API via the az rest command, I am experiencing an error when the setting value is a cron expression.

**To Reproduce**
For the following JSON body the put command results in an error.

$bodyJson = {\"properties\":{\"schedule\":\"0 10 0 * * TUE-SAT\"}}

az rest --method put --headers "Content-type=application/json" --uri "$resourceUri" --body $bodyJson --debug

Command arguments: ['rest', '--method', 'put', '--headers', 'Content-type=application/json', '--uri', 'https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.Web/sites/abc-func-yyy/config/appsettings?api-version=2019-08-01', '--body', '{"properties":{"schedule":"0', '10', '0', '*', '*', 'TUE-SAT"}}', '--debug']

**Yields**
cli.azure.cli.core.parser : az: error: unrecognized arguments: 10 0 * * TUE-SAT"}}
az: error: unrecognized arguments: 10 0 * * TUE-SAT"}}
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {rest} ...
az_command_data_logger : exit code: 2

**Expected behavior**
If the value is a regular string it works fine.

$bodyJson  = {\"properties\":{\"schedule\":\"fred\"}}

az rest --method put --headers "Content-type=application/json" --uri "$resourceUri" --body $bodyJson --debug

Command arguments: ['rest', '--method', 'put', '--headers', 'Content-type=application/json', '--uri', 'https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.Web/sites/abc-func-yyy/config/appsettings?api-version=2019-08-01', '--body', '{"properties":{"schedule":"fred"}}', '--debug']

**Yields**
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.Web/sites/abc-func-yyy/config/appsettings?api-version=2019-08-01 HTTP/1.1" 200 None

**Environment summary**
my az cli version details are:
az --version
azure-cli                         2.0.78

command-modules-nspkg              2.0.3
core                              2.0.78
nspkg                              3.0.4
telemetry                          1.0.4

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**
It looks like a transformation is being applied to the cron expression somehow
-->{"schedule":"0', '10', '0', '*', '*', 'TUE-SAT"}} 

not sure if this is a bug or if I am missing something.

Any help much appreciated.

**Comment by MyronFanQiu** [comment]
@chrisxpr Are you using powershell? You can try to use `--body @filepath` to load the body json from file.

**Comment by chrisxpr** [comment]
Hi, I am using Powershell to construct the list as I need to pull in values from external sources dynamically and don't want to persist sensitive data on the file system.

Version details are
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018

**Comment by MyronFanQiu** [comment]
@jiasli any idea?

**Comment by jiasli** [comment]
Same issue as https://github.com/Azure/azure-cli/issues/11008. 

This is because PowerShell strips the double quotes when passing the arguments to command prompt if there is no space in the argument: https://github.com/PowerShell/PowerShell/issues/1995

Also escaping double quotes with `\"` is required in command prompt, so to workaround these limitations, you will need to 

1. Add a space in the argument to force PowerShell to include double quotes when passing the argument to CMD
2. Replace `"` with `\"` so that `"` is not consumed by CMD

So the command becomes:
```
az vm '{\"name\":\"value\" }' --debug
Command arguments: ['vm', '{"name":"value" }', '--debug']
```

We highly recommend using command prompt directly or `@file` as an input to avoid the issues between PowerShell>CMD invocation. The file can then be removed using [Remove-Item](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-6).

**Comment by chrisxpr** [comment]
After a bit of experimenting I was able to get it working by performing an additional escape on the space character.

**Based on your example the following works fine:**

```
$bodyJson = ($settingsList | ConvertTo-Json -Compress)  -replace "`"", "\`""
echo $bodyJson --> {\"properties\":{\"name\":\"value\"}}
```

`Command arguments: ['rest', '--method', 'put', '--headers', 'Content-type=application/json', '--uri', 'https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Web/sites/<func>/config/appsettings?api-version=2019-08-01', '--body', '{"properties":{"name":"value"}}','--debug']`

**Introducing the space breaks the call** 

```
$bodyJson = ($settingsList | ConvertTo-Json -Compress)  -replace "`"", "\`""
echo $bodyJson --> {\"properties\":{\"name\":\"va lue\"}}
```
`
Command arguments: ['rest', '--method', 'put', '--headers', 'Content-type=application/json', '--uri', 'https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Web/sites/<func>/config/appsettings?api-version=2019-08-01', '--body', '{"properties":{"name":"va', 'lue"}}', '--debug']`

**But introducing an additional escape on the space character fixes the problem**
```

$bodyJson = ($settingsList | ConvertTo-Json -Compress) -replace "`"", "\`""
$bodyJson = ($bodyJson -replace " ", "\u0020")
echo $bodyJson --> {\"properties\":{\"name\":\"val\u0020ue\"}}
```
		
`Command arguments: ['rest', '--method', 'put', '--headers', 'Content-type=application/json', '--uri', 'https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Web/sites/<func>/config/appsettings?api-version=2019-08-01', '--body', '{"properties":{"name":"val\\u0020ue",}}', '--debug']`

Confirmed in the azure portal that the setting is displayed as "val ue" (with space!)

**Comment by jiasli** [comment]
You are right. The first one without space works because there is no special characters like `&` in the json. So even though double quotes are stripped, the json is still valid when passed to CMD. I have edited the reply to avoid confusing. Thanks a lot for the finding. 😄

**Comment by jiasli** [comment]
You are right. The first one without space works because there is no special characters like `&` in the json. So even though double quotes are stripped, the json is still valid when passed to CMD. I have edited the reply to avoid confusion. Thanks a lot for the finding. 😄

**Comment by jiasli** [comment]
You are right. The first one without space works because there is no special characters like `&` in the json. So even though double quotes are stripped, the json is still valid when passed to CMD. 

But for the "Introducing the space breaks the call", it still looks like a bug in PowerShell to me.

I have edited the reply to avoid confusion. Thanks a lot for the finding. 😄

**Comment by chrisxpr** [comment]
If they could add something like
$bodyJson = ($settingsList | ConvertTo-Json -_CompressAndEncode_)

to prevent having to do all the replacing that would be nice!  

Have a good night

**Comment by jiasli** [comment]
I don't think this should be a feature developed by PowerShell because `"` are parsed by cmd, not PowerShell itself. PowerShell expects to call exe directly. But given the current situation that PowerShell has issue calling native exe:

```powershell
python -c "import sys; print(sys.argv)" '"a"'
['-c', 'a']    # notice quotes are lost
```

We can keep using the cmd script for a while and pack Azure CLI as `az.exe` later when https://github.com/PowerShell/PowerShell/issues/1995 is fixed.

Thank you very much for the investigation.
