### ISSUE TITLE
Fail Create Boot Teams

### ISSUE THREAD

**Issue by Carolyreis** [Azure/azure-cli#11816]
## Describe the bug

**Command Name**
`az group deployment create`

**Errors:**
```
[Errno 13] Permission denied: 'C:\\Projects\\bots\\n-1-bottest\\deploymentTemplates'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group deployment create --name {} --resource-group {} --template-file {} --parameters {} {} {} {} {} {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.79

```

**Comment by yonzhan** [comment]
add to S165.

**Comment by zhoxing-ms** [comment]
@Carolyreis [Errno 13] Permission denied: this is because the file cannot be opened. 
The possible causes are no permission to access the file, or the file is occupied by other processes, or the path which opened is not a file but a directory, etc...

Maybe you can try these solutions:
1.  Check if you have permission to read the file. If you have insufficient permission, try to modify the file permission or modify the cmd permissions, run it as administrator.
2.  Check if this file is occupied by another processe and close it if there is one
3.  Check if this path is a file, not a directory

If you still have any other questions, please feel free to let us know~

**Comment by zhoxing-ms** [comment]
@Carolyreis Is there any new progress on this issue?

**Comment by zhoxing-ms** [comment]
Because it hasn't been replied for a long time, I'll close the issue first. If you have any other questions, please feel free to reopen it or create a new one.
