### ISSUE TITLE
Can create path mappings with az resource update --set on Windows but not on Linux.

### ISSUE THREAD

**Issue by sirwarshade** [Azure/azure-cli#11978]
I'm trying to add path mappings, i'm using the "az resource update" command to get to that goal. Only on windows do i get the expected result, which is the creation of additional path mappings.

Both Windows and Linux are on azure-cli 2.0.80. 

**Command Name**
`az resource update`

`az resource update --name I20200128R4-Test-Server/config/web --resource-group I20200128R4 --resource-type Microsoft.Web/sites/config --set 'properties.virtualApplications=[{\"physicalPath\":\"site\\wwwroot\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/\"},{\"physicalPath\":\"site\\wwwroot\\v2\\flow-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/flow\"},{\"physicalPath\":\"site\\wwwroot\\v2\\iris-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/iris\"}]'`

**Errors:**
No errors, but i does not create the path mappings i need when i use the command on Linux.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Have a web app;
- Use a ubuntu/debian Linux flavor;
- Try to create a path mapping with the "az resource update --set" command

## Expected Behavior

    "virtualApplications": [
      {
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null,
        "virtualPath": "/"
      },
      {
        "physicalPath": "site\\wwwroot\\v2\\flow-server",
        "preloadEnabled": false,
        "virtualDirectories": null,
        "virtualPath": "/flow"
      },
      {
        "physicalPath": "site\\wwwroot\\v2\\iris-server",
        "preloadEnabled": false,
        "virtualDirectories": null,
        "virtualPath": "/iris"
      }
    ]

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

```

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168

**Comment by zhoxing-ms** [comment]
@sirwarshade Hi, I have some questions to confirm with you, please take a look:
1. You mean that the WebApp deployed in a Windows environment can correctly set up path mappings for physicalPath and virtualPath, but the path mapping cannot take effect in WebApp deployed in Linux environment, right?
2. Do you have this problem when you perform the same operation on portal?

**Comment by sirwarshade** [comment]
@zhoxing-ms , i execute the azure cli command from a Linux device and it fails but if i execute the azure cli from a Windows device it succeeds.

The web app is allways a .NET 4.7 PaaS service. So Windows

**Comment by zhoxing-ms** [comment]
@sirwarshade Hi, `az resource update` is not designed to support updating the webapp config. (I can't actually update path mappings by executing this command on either Windows or Linux)
It only supports the following functions:
1. Resources - Update [(doc link)](https://docs.microsoft.com/en-us/rest/api/resources/resources/update)
2. Resources - Update By Id [(doc link)](https://docs.microsoft.com/en-us/rest/api/resources/resources/updatebyid)

If you want to update the configuration of webapp, the following command should be executed:
`az webapp config set --name {resource-name} -g {resource-group} --generic-configurations "{\"virtualApplications\":[{\"physicalPath\":\"site\\wwwroot\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/\"},{\"physicalPath\":\"site\\wwwroot\\v2\\flow-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/flow\"},{\"physicalPath\":\"site\\wwwroot\\v2\\iris-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/iris\"}]}"`
Because only this command implements the function of `Web Apps - Create Or Update Configuration` [(doc link)](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdateconfiguration)

**Comment by zhoxing-ms** [comment]
@sirwarshade You can have a try. If you have any other questions, please let us know.

**Comment by zhoxing-ms** [comment]
By the way, there is another unreasonable phenomenon: when the error message contains special characters, it will print a lot of less related error logs more than when there are no special characters in the error message.
The reason for this phenomenon is related to the bug of msrestazure-for-python: https://github.com/Azure/msrestazure-for-python/issues/143. When calling the logging library to print the log, we encountered an exception raised by the `__str__` method of msrestazure, which triggered the logic of printing all call stacks. This problem needs to wait for the msrestazure-for-python to be fixed.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by sirwarshade** [comment]
For me `az webapp config set --name {resource-name} -g {resource-group} --generic-configurations "{\"virtualApplications\":[{\"physicalPath\":\"site\\wwwroot\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/\"},{\"physicalPath\":\"site\\wwwroot\\v2\\flow-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/flow\"},{\"physicalPath\":\"site\\wwwroot\\v2\\iris-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/iris\"}]}"` this did not work. It gave a bunch of error's

`az webapp config set --name testestest1312312325435 -g TeamAzure --generic-configurations '"{\"virtualApplications\":[{\"physicalPath\":\"site\\wwwroot\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/\"},{\"physicalPath\":\"site\\wwwroot\\v2\\flow-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/flow\"},{\"physicalPath\":\"site\\wwwroot\\v2\\iris-server\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/iris\"}]}"'` This on the other-hand did work for me. So thank you for at-least giving me a good lead.

**Comment by eholman** [comment]
@sirwarshade Check out this doc regarding quoting issues you're having. I'm looking at the exact same thing. Doc is going into detail and might give you insights how to handle quotes based on the type of your environment:

https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues

**Comment by SteveHindmarsh** [comment]
There are various workarounds for this as seen, however these commands only allow you to update the complete list of virtual path mappings for the app service, I cannot just add a single (or multiple) new mapping to the existing list. Is there a command to achieve this?

**Comment by HaloX69** [comment]
I just want to comment that I find it very concerning that even Microsoft has put no effort into validating the very content that they publish publicly considering the number of consumers leveraging thier platform.  

I refered to Microsoft documentation regarding how to add App Service Path mappings, and why not its their baby, but I couldn't get it to work correctly.  I tried both the Azure cli commands **resource** and **webApp**, but Microsoft docuemntation was not correct or didn't have any real examples, so I took the time to delve into this because I too faced the same issues.

I started, as many probably did, with the [Configure an App Service app-Map a URL path to a directory](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=cli#code-try-27) that instructs how to add a virtual path, and I too had the very same problems.  Feedback from many regarding this open issue, **11978**, spoke of escaping the quotes and even referenced the Microsoft documenmt [Tips for using the Azure CLI successfully](https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest&tabs=bash%2Cbash2#quoting-issues) and yet this document, at least for this purpose, did not ring accuratly.

The document, Configure an App Service app-Map a URL path to a directory, had it wrong in two ways.  First the Json was improperly formated, and the quotes were wrong.  I break down each issue and show how to correct the issue.  Note, all of the commands and Json were tested in Azure Cloudshell 2.47.0.

Let start with the formatting issue since if you correct this issue you'll then be able to see the correct way to use quotes in the Json, at least for the following Azure cli commands:

- az resource update
- az webapp config

The example Json provided is as listed below.

**[
  {
    "physicalPath"':' "site\\wwwroot\\public",
    "preloadEnabled"':' false,
    "virtualDirectories"':' null,
    "virtualPath"':' "/"
  },
  {
    "physicalPath"':' "site\\wwwroot\\app2",
    "preloadEnabled"':' false,
    "virtualDirectories"':' null,
    "virtualPath"':' "/app2"
  }
]**

When you create an Azure App Service you already be default have a application "/" mapped to a directory "site\\wwwroot".  The above Json is instructing that ANOTHER directory "site\\wwwroot\\public" be mapped to the application "/" which throws an exception because the virtual path needs to be unique, because we already have a mapped application "/" to directory "site\\wwwroot".  This Json will never work unless we change the virtual path, lets make it "/Public".

**[
  {
    "physicalPath"':' "site\\wwwroot\\public",
    "preloadEnabled"':' false,
    "virtualDirectories"':' null,
    "virtualPath"':' "/Public"
  },
  {
    "physicalPath"':' "site\\wwwroot\\app2",
    "preloadEnabled"':' false,
    "virtualDirectories"':' null,
    "virtualPath"':' "/app2"
  }
]**

Now we attempt to use the above Json with the below Azure cli command.  

We now get a whole new exception:

InvalidArgumentValueError: Failed to parse string as JSON:
{\
Error detail: Expecting property name enclosed in double quotes

Well, this tells us everything.  I then noticed that within the Json are some random single quotes, ', which were breaking the Json format.

**[
  {
    "physicalPath": "site\\wwwroot\\public",
    "preloadEnabled": false,
    "virtualDirectories": null,
    "virtualPath": "/Public"
  },
  {
    "physicalPath": "site\\wwwroot\\app2",
    "preloadEnabled": false,
    "virtualDirectories": null,
    "virtualPath": "/app2"
  }
]**

I now execute the below Azure cli resource command and it successfully created the mapped directories.

_**az resource update --resource-group someResourceGroup --resource-type Microsoft.Web/sites/config --name someApp/config/web --set properties.virtualApplications="[{\"physicalPath\": \"site\\wwwroot\\public\",\"preloadEnabled\": false,\"virtualDirectories\": null,\"virtualPath\": \"/Public\"},{\"physicalPath\": \"site\\wwwroot\\app2\",\"preloadEnabled\": false,\"virtualDirectories\": null,\"virtualPath\": \"/app2\"}]"**_

So I wanted to apply the Json to the Azure cli webApp command:

**az webapp config set --name someApp -g someResourceGroup --generic-configurations "{\"virtualApplications\": [{\"virtualPath\": \"/\",\"physicalPath\": \"site\\wwwroot\",\"preloadEnabled\": true,\"virtualDirectories\": [{\"physicalPath\": \"site\\wwwroot\\public\",\"preloadEnabled\": false,\"virtualDirectories\": null,\"virtualPath\": \"/Public\"},{\"physicalPath\": \"site\\wwwroot\\app2\",\"preloadEnabled\": false,\"virtualDirectories\": null,\"virtualPath\": \"/app2\"}]}]}"**

I am back to the previous exception:

InvalidArgumentValueError: Failed to parse string as JSON:
{\
Error detail: Expecting property name enclosed in double quotes

I attempted using single quotes without success.  I then moved to double double quotes, **""**, and that did the trick.

**az webapp config set --name someApp -g someResourceGroup --generic-configurations "{""virtualApplications"": [{""virtualPath"": ""/"",""physicalPath"": ""site\\wwwroot"",""preloadEnabled"": true,""virtualDirectories"": [{""physicalPath"": ""site\\wwwroot\\public"",""preloadEnabled"": false,""virtualDirectories"": null,""virtualPath"": ""/Public""},{""physicalPath"": ""site\\wwwroot\\app2"",""preloadEnabled"": false,""virtualDirectories"": null,""virtualPath"": ""/app2""}]}]}"**

So, for some reason the Azure cli resource & webApp are not consistent how it handles the Json quotes.  The Microsoft Azure cli team should work together to figure out why there is a difference with how quotes are managed between the two command groups.  Please feel free to validate my findings.

I do want to mention that I changed the structure of the Json because I needed to map another mapped application as displayed below.

**{
    ""virtualApplications"": [
        {
            ""virtualPath"": ""/"",
            ""physicalPath"": ""site\\wwwroot"",
            ""preloadEnabled"": true,
            ""virtualDirectories"": [
                {
                    ""virtualPath"": ""/Public"",
                    ""physicalPath"": ""site\\wwwroot\\public""
                }
            ]
        },
        {
            ""virtualPath"": ""/app2"",
            ""physicalPath"": ""site\\wwwroot\\app2"",
            ""preloadEnabled"": true
        }
    ]
 }**

**Comment by jorferri** [comment]
My 2 cents here, I have been able to make it work in bash creating a json file and using it with azure client:

`echo "{\"virtualApplications\":[{\"physicalPath\":\"site\\\\wwwroot\",\"preloadEnabled\":false,\"virtualDirectories\":null,\"virtualPath\":\"/\"},{\"physicalPath\":\"site\\\\wwwroot\\\\someApp\",\"preloadEnabled\": false,\"virtualDirectories\": null,\"virtualPath\": \"/blueprints\"}]}" > json.txt`

`az webapp config set --resource-group someResourceGroup  --name someApp --generic-configurations "@json.txt"`
