### ISSUE TITLE
The az resource create example doesn't work

### ISSUE THREAD

**Issue by jacekmackiewicz** [Azure/azure-cli#11981]
Example: az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties '{
            "kind": "api",
            "location": "West US",
            "properties": {
                "serverFarmId": "/subscriptions/{SubID}/resourcegroups/{ResourceGroup}/providers/Microsoft.Web/serverfarms/{ServicePlan}"
            }
        }'
doesn't work, giving a "Error parsing JSON.
{
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest&source=docs#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S165.

**Comment by happyiphone** [comment]
Any news on this? I need to be able to use this command or an alternative for it. Any help on this will be highly appreciated. thanks!

**Comment by zhoxing-ms** [comment]
@happyiphone Thanks for your feedback, It seems that example is not friendly to users, I will submit a PR to improve it

**Comment by zhoxing-ms** [comment]
@happyiphone For the `az resource create` command, please use like this:
`az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties "{ \"kind\": \"api\", \"location\": \"West US\", \"properties\": { \"serverFarmId\": \"/subscriptions/{SubID}/resourcegroups/{ResourceGroup}/providers/Microsoft.Web/serverfarms/{ServicePlan}\" } }"`

**Comment by surexxx** [comment]
Examples above doesn't work for me in Azure Portal Cloud Shell.
This is a working example that will successfully run: 
`az resource create -g $resourceGroup -l $region -n $apiappName --resource-type Microsoft.web/sites --is-full-object --properties "{ \""kind\"": \""api\"", \""location\"": \""$region\"", \""properties\"": { \""serverFarmId\"": \""/subscriptions/$subscriptionId/resourcegroups/$resourceGroup/providers/Microsoft.Web/serverfarms/$appservicePlan1\"" } }"`

**Comment by zhoxing-ms** [comment]
@surexxx Hi, in fact, the parsing of these two ways of inputting parameters in CLI is the same.
Such as:
![Screenshot 2021-05-19 102536](https://user-images.githubusercontent.com/16612065/118747560-d1d10200-b88c-11eb-8f3e-ba0ba909413b.png)
![Screenshot 2021-05-19 102616](https://user-images.githubusercontent.com/16612065/118747564-d39ac580-b88c-11eb-937b-181a900ddd48.png)

May I ask what is the specific error message you encountered? Could you please add parameter `--debug` at the end of your command you executed (as the screenshot), and then send the printed information to me by email?
My email address is Zhou.Xing@microsoft.com, thanks

**Comment by surexxx** [comment]
@zhoxing-ms I've sent you the detailed debug information to you mail.
Here is a picture from my screen about the error:
![image](https://user-images.githubusercontent.com/18722513/118817882-00ae9e80-b8b4-11eb-9689-24cf909e2df5.png)

**Comment by zhoxing-ms** [comment]
@surexxx Hi, thank you for your information. I have found the root cause of this issue~ 
The reason I didn't reproduce this issue before is because I used `Bash` in `CloudShell`, however you used `PowerShell` in `CloudShell`.

Because the parameter of `--properties` passed in as a JSON object is the string type, which contains the special character `"`, so it needs to be escaped as `\"` before passing in into the CLI.
This issue is caused by that the escape characters are different in different environments: **In `Bash` environment, the escape character is `\`, but in `PowerShell` environment, the escape character is `.**
Therefore, in `PowerShell` environment, you should execute this command as follows:
```
az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties "{ \`"kind\`": \`"api\`", \`"location\`": \`"West US\`", \`"properties\`": { \`"serverFarmId\`": \`"/subscriptions/{subscription_id}/resourcegroups/{resource_group}/providers/Microsoft.Web/serverfarms/{plan_name}\`" } }"```
```
Or use the `--%` parameter ([stop-parsing symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.1)) prevent `PowerShell` from interpreting special characters, such as:
```
az --% resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties "{ \"kind\": \"api\", \"location\": \"West US\", \"properties\": { \"serverFarmId\": \"/subscriptions/{subscription_id}/resourcegroups/{resource_group}/providers/Microsoft.Web/serverfarms/{plan_name}\" } }"
```

For more details on how to use quotation marks, please refer to [doc link](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values)

**Comment by surexxx** [comment]
@zhoxing-ms yes that's could be the problem. But it's not documented nowhere in examples that you have to use Bash Shell instead of PowerShell.
![image](https://user-images.githubusercontent.com/18722513/118949531-a0723800-b959-11eb-9410-f51af2201090.png)

**Comment by zhoxing-ms** [comment]
@surexxx Yes, in fact, our sample is expected to be executed in the `Bash` environment.
Our doc team may need to consider optimizing this. For complex commands, we may need to support multiple environments with corresponding samples. @dbradish-microsoft, please aware it~

**Comment by dbradish-microsoft** [comment]
@surexxx, most of our articles are tested with `Bash` in Azure Cloud Shell, and the prerequisites in our conceptual docs point our readers to `Bash`.

![image](https://user-images.githubusercontent.com/58762114/119392721-1e0daf00-bc9e-11eb-9b61-98bd28eca2e7.png)

We also have [Quickstart for Bash in Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart) that encourages the use of `Bash`.  Because of the many [installation options](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) for the Azure CLI, we don't instruct to use `Bash` on all of our reference content.  However, I will talk to our engineering team to see what we can do to improve our error output.

Kindly,

Delora J Bradish
Senior Content Developer for the Azure CLI
C+AI Developer Relations

**Comment by surexxx** [comment]
@dbradish-microsoft I understand your answer, but... I don't find the page you attached from the Prerequisits. Where can I find it?
On page where the 'az resource create' command (and the other commands) is described there are no Prerequisits and thats why developers (like me) who just want to script some task in Azure don't know exactly what to use Bash or PowerShell. It would be really helpful if you could improve the documentation examples header like this: 
![image](https://user-images.githubusercontent.com/18722513/119453106-5dd4a500-bd37-11eb-9f41-2efa287257c3.png)

**Comment by dbradish-microsoft** [comment]
@surexxx , Prerequisites are given in conceptual articles like [this one](https://docs.microsoft.com/en-us/azure/app-service/scripts/cli-deploy-ftp?toc=/cli/azure/toc.json).  I like your suggestion for the code block header, and I'll add it to my suggestions for a redesign that is currently being reviewed.
