### ISSUE TITLE
--output none still prints text.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#12070]
**Describe the bug**

`az login --output none` produces this output

`You have logged in. Now let us find all the subscriptions to which you have access...`

It doesn't print the subs.

But it also shouldn't print the message above.

**To Reproduce**
Run the above command.

**Expected behavior**
Don't print anything, esp the message that it is trying to find subs.

If you need to leave You have logged in.  that's fine.

**Environment summary**
MSI

**Additional context**

**Comment by arrownj** [comment]
Hi @jiasli , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
Similar to #10856.

`--output none` only works for `stdout`, while the message are actually written to `stderr`. We are evaluating whether to add `--no-warning` or `--quite` switch. @achandmsft

**Comment by jongio** [comment]
@qianwens  - Why closed?

**Comment by qianwens** [comment]
Hi @jongio , I was trying to clean up some issues that are out-of-date. I closed this issue because I thought Jiashuo has answered the question and there is no response for several weeks. It seems this issue is used to track the bug to not show warnings in quite mode in CLI, let's keep it open. I will sync up with Jiashuo about the status.

**Comment by jiasli** [comment]
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.
