### ISSUE TITLE
Issue installing az cli extension

### ISSUE THREAD

**Issue by bigdatamoore** [Azure/azure-cli#12123]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.81

**Describe the bug**
Error when installing az extensions on Windows

**To Reproduce**
- Download and Install az cli using Windows MSI installer on Windows 10.
- Try installing an extension
- Get the error: "Could not install packages due to an EnvironmentError."

**Expected behavior**
- Extension should install successfully.

**Environment summary**
Windows 10 install with MSI

**Manual Workaround**
- Update pip on the system environment
- Install the extension manually by using pip outside of the az cli environment

**Additional context**
See details and workaround reported in this issue: https://github.com/MicrosoftDocs/azure-docs/issues/47465

**Comment by arrownj** [comment]
Hi @jsntcy , could you please help with this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jsntcy** [comment]
@bigdatamoore, what was the version of pip that caused the installation error?
I cannot reproduce the error on my machine with latest Azure CLI (2.5.1) and pip version on my machine is `pip 20.0.2 from c:\code\azure-cli-extensions-jsntcy\env\lib\site-packages\pip (python 3.7)` 

I can install storage-preview successfully on my machine,

> Executing pip with args: ['install', '--target', 'C:\\Users\\ychenu\\.azure\\cliextensions\\storage-preview', 'C:\\Users\\ychenu\\AppData\\Local\\Temp\\tmpl7xxuf6f\\storage_preview-0.2.10-py2.py3-none-any.whl']
> Running: ['C:\\Code\\azure-cli-extensions-jsntcy\\env\\Scripts\\python.exe', '-m', 'pip', 'install', '--target', 'C:\\Users\\ychenu\\.azure\\cliextensions\\storage-preview', 'C:\\Users\\ychenu\\AppData\\Local\\Temp\\tmpl7xxuf6f\\storage_preview-0.2.10-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
> Non-user install due to --prefix or --target option
> Created temporary directory: C:\Users\ychenu\AppData\Local\Temp\pip-target-xh3x99nz
> Created temporary directory: C:\Users\ychenu\AppData\Local\Temp\pip-ephem-wheel-cache-hz9s31_j
> Created temporary directory: C:\Users\ychenu\AppData\Local\Temp\pip-req-tracker-ohxc4yf7
> Initialized build tracking at C:\Users\ychenu\AppData\Local\Temp\pip-req-tracker-ohxc4yf7
> Created build tracker: C:\Users\ychenu\AppData\Local\Temp\pip-req-tracker-ohxc4yf7
> Entered build tracker: C:\Users\ychenu\AppData\Local\Temp\pip-req-tracker-ohxc4yf7
> Processing c:\users\ychenu\appdata\local\temp\tmpl7xxuf6f\storage_preview-0.2.10-py2.py3-none-any.whl
>   Added storage-preview==0.2.10 from file:///C:/Users/ychenu/AppData/Local/Temp/tmpl7xxuf6f/storage_preview-0.2.10-py2.py3-none-any.whl to build tracker 'C:\\Users\\ychenu\\AppData\\Local\\Temp\\pip-req-tracker-ohxc4yf7'
>   Removed storage-preview==0.2.10 from file:///C:/Users/ychenu/AppData/Local/Temp/tmpl7xxuf6f/storage_preview-0.2.10-py2.py3-none-any.whl from build tracker 'C:\\Users\\ychenu\\AppData\\Local\\Temp\\pip-req-tracker-ohxc4yf7'
> Installing collected packages: storage-preview
>   Created temporary directory: C:\Users\ychenu\AppData\Local\Temp\pip-unpacked-wheel-f8ogws_m
> 
> Successfully installed storage-preview-0.2.10
> Cleaning up...
> Removed build tracker: C:\\Users\\ychenu\\AppData\\Local\\Temp\\pip-req-tracker-ohxc4yf7

**Comment by bigdatamoore** [comment]
you can see it in the issue that I listed above that the problem was with the version of pip that was bundled with the AZ CLI.  When I tried installing the extension manually with my own local version of pip, it worked.  

The version of pip that came with AZ CLI is pip 10.0.1

```
PS> . "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip --version
pip 10.0.1 from C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip (python 3.6)
```

Note, I haven't upgraded my CLI in a while, so this may be out of date now.  I will try updating later and see if it is still the case.

**Comment by bigdatamoore** [comment]
See this issue for more details:  https://github.com/MicrosoftDocs/azure-docs/issues/47465

**Comment by bigdatamoore** [comment]
so the root cause was that the version of pip bundled with the AZ CLI was out of date.

**Comment by jsntcy** [comment]
@bigdatamoore, I saw there are many very old CLI packages (acr, acs, appservice and etc.) along with azure-cli 2.0.80 on your machine, and they may cause dependency conflict. (the version of pip bundled with the AZ CLI was out of date may not be the root cause and upgrading pip version may happen to fix the error.)

azure-cli                         2.0.80 *

acr                                2.2.1 *
acs                               2.3.18 *
appservice                        0.2.14 *
botservice                         0.1.7 *
command-modules-nspkg              2.0.3
container                         0.3.14 *
core                              2.0.80 *
eventhubs                          0.3.3 *
find                              0.2.13 *
hdinsight                          0.3.1 *
network                            2.3.3 *
nspkg                              3.0.4
rdbms                              0.3.7 *
role                               2.4.1 *
servicefabric                     0.1.13 *
telemetry                          1.0.4

- Before Mid of 2019, Az CLI is installed with many separated packages (acr, acs, appservice and ect.), but after that, Az CLI changed its installation mode and it is installed with only one pacakge (azure-cli).
- Could you uninstall Az CLI to see if those separated packages (acr, acs, appservice and etc.) still exist? If still exist, please delete them manually, then install latest Az CLI to check if this issue is resolved or not.

**Comment by bigdatamoore** [comment]
Ok, I removed and re-installed AZ CLI.  I then removed and re-installed the storage-preview extension.  It installed this time without error.    So I think we can close this issue now.  Thanks!
