### ISSUE TITLE
az ad app grants not working or usable as expected

### ISSUE THREAD

**Issue by dmprantz** [Azure/azure-cli#12137]
**Describe the bug**
"az ad app permission grant" only seems to grant a single scope.  If I call it successive times, the existing scope is overwritten.  This behaviour is not clearly documented, nor is the way to grant. multiple scopes.

"az ad app permission admin-consent" appears to be non-functional.  How can admin consent be granted without three key pieces of information, AppID, APIID, and Scope?  What is this doing?  How can a single scope be granted at the application level?

I would also consider it a bug that "az ad app permission grant" cannot be used to grant application type scopes.

**To Reproduce**
Try to execute the above commands.  "az ad app permission admin-consent" is not documented in any way that makes sense.  "az ad app permission grant" seems to work, but successive calls over-write your work.

**Expected behavior**
There should be a single command that allows you to grant individual (or comma separated lists) of scopes for an API to an app.  That same command should have a flag for Delegated vs Application Type.  It should not overwrite itself.  Worst case, if there have to be two commands, the one used to grant admin-consent to the application type should allow appropriate parameters.

Documentation of these calls should be clear and concise.

**Environment summary**
Windows 10.  Installed via downloaded MSI for x64.  cmd.exe shell.

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin>az --version
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dpomerantz\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

**Comment by arrownj** [comment]
Hi @jiasli , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by dmprantz** [comment]
This was pushed to a future release.  How many times is it going to get pushed before being addressed and resolved.  Is any one able to comment on a commitment that this will be resolved with a definitive timeline?

**Comment by jiasli** [comment]
`az ad app permission admin-consent` is the old way of granting all permissions to an app. It can only be called by a user, not a service principal. It calls an internal API: https://github.com/Azure/azure-cli/blob/1c0e9c3e18c34116d5a2e25cb7460d1af8a85969/src/azure-cli/azure/cli/command_modules/role/custom.py#L893

⚠ It fails in Cloud Shell, because `main.iam.ad.ext.azure.com` is an endpoint not supported by Cloud Shell.
⚠ We will deprecate it in the future. 

Before:

![](https://user-images.githubusercontent.com/4003950/76216029-d7739680-624a-11ea-87f7-7ce098bfd973.png)

After:

![](https://user-images.githubusercontent.com/4003950/76216059-e5291c00-624a-11ea-91bb-3328acc80755.png)


To grant **Delegated Permission**, we recommend using `az ad app permission grant`. If multiple scopes are needed, separate them with spaces and surround the scopes with quotes: `"a b"`. For example, to grant MS Graph (whose Application ID is `00000003-0000-0000-c000-000000000000`) Delegated Permission to my app (Application ID `46eb4122-bd2b-4f54-af7b-6d79b46ee31a`):

```sh
az ad app permission grant --id 46eb4122-bd2b-4f54-af7b-6d79b46ee31a --api 00000003-0000-0000-c000-000000000000 --scope "Directory.Read.All Directory.ReadWrite.All"
```

![](https://user-images.githubusercontent.com/4003950/76216296-510b8480-624b-11ea-93da-26001e0c90fa.png)

To grant **Application Permission**, we need to call [Update appRoleAssignments](https://docs.microsoft.com/en-us/graph/api/approleassignment-update?view=graph-rest-beta&tabs=http) API from MS Graph API which is still beta and not ready for production. (The doc is not very accurate, and is still under development.) We are working with AAD team to make it GA and adopt it in Azure CLI. For now, you may use `az rest` to play with it.

Both of these 2 approaches work but with different URLs:

```sh
# URL contains principalId
az rest --method POST --uri https://graph.microsoft.com/beta/servicePrincipals/8aaa6158-7450-4407-ba08-61377f23d05f/appRoleAssignedTo \
        --header Content-Type=application/json \
        --body '{
          "principalId": "8aaa6158-7450-4407-ba08-61377f23d05f",
          "resourceId": "a3efc889-f1b7-4532-9e01-91e32d1039f4",
          "appRoleId": "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        }' 
```

```sh
# URL contains resourceId
az rest --method POST --uri https://graph.microsoft.com/beta/servicePrincipals/a3efc889-f1b7-4532-9e01-91e32d1039f4/appRoleAssignments \
        --header Content-Type=application/json \
        --body '{
          "principalId": "8aaa6158-7450-4407-ba08-61377f23d05f",
          "resourceId": "a3efc889-f1b7-4532-9e01-91e32d1039f4",
          "appRoleId": "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        }' 
```

`principalId` (`8aaa6158-7450-4407-ba08-61377f23d05f`) is the corresponding service principal object ID of the app which I want to grant permissions to. Service principal is also called **Managed application in local directory** or **Enterprise Application**.

You may get it from Azure Portal:

![1](https://user-images.githubusercontent.com/4003950/76220078-d5610600-6251-11ea-848e-c313e2b2a97b.png)

![2](https://user-images.githubusercontent.com/4003950/76220165-fcb7d300-6251-11ea-8af1-450fb18b29d7.png)

Or query `principalId` with Application ID:

```sh
> az ad sp show --id 46eb4122-bd2b-4f54-af7b-6d79b46ee31a --query "objectId"
"8aaa6158-7450-4407-ba08-61377f23d05f"
```

`resourceId` (`a3efc889-f1b7-4532-9e01-91e32d1039f4`) is the resource app's corresponding service principal object ID. In this case it is for MS Graph. It varies in different tenants (directories). Retrieve it with MS Graph's Application ID:

```sh
$ az ad sp show --id 00000003-0000-0000-c000-000000000000 --query "objectId"
"a3efc889-f1b7-4532-9e01-91e32d1039f4"
```

`appRoleId` (`19dbc75e-c2e2-444c-a770-ec69d8559fc7`) is the ID of the permission. In this case, it is for `Directory.ReadWrite.All`. Retrieve it with MS Graph's Application ID:

```sh
> az ad sp show --id 00000003-0000-0000-c000-000000000000 --query "appRoles[?value=='Directory.ReadWrite.All']"
[
  {
    "allowedMemberTypes": [
      "Application"
    ],
    "description": "Allows the app to read and write data in your organization's directory, such as users, and groups, without a signed-in user.  Does not allow user or group deletion.",
    "displayName": "Read and write directory data",
    "id": "19dbc75e-c2e2-444c-a770-ec69d8559fc7",
    "isEnabled": true,
    "value": "Directory.ReadWrite.All"
  }
]
```

You may also use F12 Developer Tools of the browser to capture network trace to check related ID conversions. (Quite complicated I admit.)

More info can be found at this site which is written by MS Graph API: https://winsmarts.com/how-to-grant-admin-consent-to-an-api-programmatically-e32f4a100e9d

**Comment by dmprantz** [comment]
Thanks for all of the detailed information!  I'll take some time and digest this, and come back if I have any further questions on this.  I understand a bit more on the delays though.

**Comment by jiasli** [comment]
Hi @dmprantz , thanks a lot for your understanding. We have been working tightly with AAD team on this feature. Don't hesitate to let us know if there are any concerns.

**Comment by jiasli** [comment]
For the granting app (or service principal, which you use to log in and grant permissions to another service principal), 

- **Directory.ReadWrite.All** is needed for granting Delegated Permissions
- **AppRoleAssignment.ReadWrite.All** is needed for granting Application Permissions

⚠ Keep in mind that **AppRoleAssignment.ReadWrite.All** is extremely privileged, as it allows granting any app-only permission, including **RoleManagement.ReadWrite.Directory**, which can then be used to give anyone (or any app) even higher privileges up to and including Company Administrator (i.e. Global Admin).

If you use `az ad` command, make sure the permission is given under **Azure Active Directory Graph**, since `az ad` internally uses AD Graph API. If you use `az rest --uri https://graph.microsoft.com/`, the permission should be given under **Microsoft Graph**.

Reference: https://winsmarts.com/how-to-grant-admin-consent-to-an-api-programmatically-e32f4a100e9d

**Comment by fume** [comment]
Hi @jiasli ,using the `az ad app permission grant` command to grand Delegated Permission is giving us a 404 NotFound error (like #12797). In our case the Delegated Permission is from Microsoft Graph (Directory.ReadWrite.All). Can you please clarify HOW to grant Delegated Permissions programmatically?

**Comment by fume** [comment]
I found a solution.
BEFORE invoking the `az ad app permission grant`, the Service Principal for your App Registration MUST exists (that's why you get the 404 NotFound!). So, invoking the `az ad sp create --id <yourAppId>` before the `az ad app permission grant` will fix everything.

This is really confusing and undocumented.

**Comment by jiasli** [comment]
@fume, glad to know it is solved. You may use `--debug` to check which request failed and fix it accordingly. BTW, We will track MS Graph related issues at #12946

**Comment by jiasli** [comment]
Microsoft Graph API's Service Principal part is now GA https://developer.microsoft.com/en-us/identity/blogs/service-principal-api-in-microsoft-graph-is-now-generally-available/. However I still find the naming of the API confusing. Will track at issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/8412.

**Comment by felickz** [comment]
RE: https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479
> ⚠ We will deprecate it in the future.

@jiasli any indication when `az ad app permission admin-consent ` will be deprecated, and will there be another CLI function to wrap the API calls you are documenting above?

**Comment by jiasli** [comment]
These are good questions.

> Any indication when `az ad app permission admin-consent` will be deprecated?

Well, it is actually already not recommended to use it (from Azure CLI perspective), but we will keep it until we receive further notice from AAD service team about the shutting down schedule.

> and will there (please) be another CLI function to wrap the API calls you are documenting above?

Unfortunately not for now, as we (Azure CLI) simply don't have enough bandwidth developing another wrapper for the ever-growing Microsoft Graph API. 😢

As I pointed out in https://github.com/Azure/azure-cli/issues/12946#issuecomment-737196942, you may try Microsoft Graph CLI instead.

**Comment by felickz** [comment]
Is this now unofficially/officially deprecated?

> az ad app permission admin-consent --id <id>
```

Not Found(<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
)
```

**Comment by jiasli** [comment]
@felickz, this issue is now being tracked at #18603.

**Comment by estemendoza** [comment]
@jiasli Thanks for the provided info. I am having issues when running the `az rest` command to grant permissions.

I tried this command last year and it was working fine, i didn't have to use it these last few months but now I am getting the following error:

`"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.`

Any idea on what this could be?

My user is Owner and trying to run this on the PowerShell console

**Comment by jiasli** [comment]
Hi @estemendoza, Owner is a concept of [ARM RBAC](https://docs.microsoft.com/en-us/azure/role-based-access-control/). In order to call MS Graph, please make sure you have the permission shown in 

- https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto
- https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments

**Comment by estemendoza** [comment]
@jiasli Nevermind, I needed to run the script as an Administrator, thanks for the help.

**Comment by jiasli** [comment]
@estemendoza, passing JSON in PowerShell requires additional quoting rules. Please see https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md.

Azure CLI doesn't need Administrator permission to run.

**Comment by MartinHatchL365** [comment]
@jiasli 
Can I please have some clarification on this as I'm facing the exact issues but cannot get this working using the examples you provided

I'm logged into Azure CLI in a Windows Terminal (PowerShell) using a Service Principal.

I'm trying to grant admin consent for an Application Scoped API permission

Executing the following 
`az rest --method POST --uri https://graph.microsoft.com/v1.0/servicePrincipals/9fd6352e-9cba-4e76-9fff-74c41c0ec4fc/appRoleAssignments --body '{"principalId": "9fd6352e-9cba-4e76-9fff-74c41c0ec4fc", "resourceId": "00000003-0000-0ff1-ce00-000000000000", "appRoleId": "678536fe-1083-478a-9c59-b99265e6b0d3" }' --headers "content-type: application/json"`

I get an error message:

```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 575, in shell_safe_json_parse
  File "json\__init__.py", line 359, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 883, in send_raw_request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 601, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
content-type: application/json
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 24, in rest_call
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 886, in send_raw_request
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Yvand** [comment]
@MartinHatchL365 seems related to the value of `--headers`, and I think you can remove that parameter completely: I do not set it in [my working scenario](https://azurecp.yvand.net/docs/usage/register-application/#create-the-app-registration-using-az-cli).

**Comment by MartinHatchL365** [comment]
> servicePrincipals

If I don't use that then I get the following error message

`Bad Request({"error":{"code":"BadRequest","message":"Write requests (excluding DELETE) must contain the Content-Type header declaration.","innerError":{"date":"2023-03-29T11:41:10","request-id":"9207c760-0ffc-45f9-9663-f9a88adf9a7a","client-request-id":"9207c760-0ffc-45f9-9663-f9a88adf9a7a"}}})`

**Comment by MartinHatchL365** [comment]
@Yvand could it be that the URL is incorrect?

According to the official documentation on MS Graph, the correct endpoint is /appRoleAssignedTo and not /appRoleAssignments which is in the example above


Ref:
https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent?pivots=ms-graph#grant-admin-consent-for-application-permissions-1

**Comment by Yvand** [comment]
@MartinHatchL365 it looks good to me: In [my script](https://azurecp.yvand.net/docs/usage/register-application/#create-the-app-registration-using-az-cli) I am using endpoint /appRoleAssignments just fine...

**Comment by MartinHatchL365** [comment]
Does it make a difference that I'm logged in using a Service Principal?

**Comment by jiasli** [comment]
Another workaround is to use Microsoft Graph PowerShell SDK which is another client tool for AAD:

- `New-MgServicePrincipalAppRoleAssignment`: https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-app-only-api-permissions?view=graph-powershell-1.0
- `New-MgOauth2PermissionGrant`: https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-delegated-api-permissions?view=graph-powershell-1.0

**Comment by JeevaRP-SDE** [comment]
Hi Guys,
Hope you doing well, I have very big doubt and blocker in AURE AD(MICROSOFT ENTRA ID) API permission , trying to give admin Consent grant through API or Programmatically.
But still face issues on API not working i am not able find way.

**Comment by StefH** [comment]
Just a quick note (_I hope I'm not confusing anyone_), but on my Azure Tenant, the MS Graph (00000003-0000-0000-c000-000000000000) does **not** have an `objectId` but (only) a `id`.

So in my case, the code to get the correct resourceId for MS Graph is
```shell
az ad sp show --id 00000003-0000-0000-c000-000000000000 --query "i" --output tsv
```
