### ISSUE TITLE
different behaviour in web and cli az ad app credential

### ISSUE THREAD

**Issue by ArgTang** [Azure/azure-cli#12212]
**Describe the bug**
Creating a secret with long description has different constraints on the web and with cli.
```bash
az ad app credential reset --id "my-ad-app" --credential-description "long-description-for-secret"
# When present, application key identifier cannot be empty and can be at most 32 bytes.
# Parameter name: applicationKeyIdentifierValue
```
However in the portal interface it works good:
![image](https://user-images.githubusercontent.com/8416172/74540646-705f0c80-4f40-11ea-915f-af0e8745965a.png)

**Expected behavior**
I would expect that the length requirements on web and cli should be the same

**Environment summary**
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80 *
azure-cli-iot-ext 0.8.3

**Comment by yungezz** [comment]
HI @jiasli  could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
This is because Azure CLI uses [`customKeyIdentifier`](https://github.com/Azure/azure-rest-api-specs/blob/ad6d5f6467aaab8cda44ceaa2863f84359c1e022/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L2785) while Azure Portal use `displayName` which only belongs to the private 2.0 API. 

Since AD Graph has been deprecated, you may use `az rest` with Microsoft Graph. According to the  Microsoft Graph API doc for [`passwordCredential`](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0), `customKeyIdentifier` has been deprecated. Please use `displayName` instead. 

Property | Type | Description
-- | -- | --
customKeyIdentifier | Binary | Do not use.
displayName | String | Friendly name for the password. Optional.

Please see the detailed explanation and solution at https://github.com/Azure/azure-cli/issues/10234#issuecomment-577049720.

BTW, we will track MS Graph issues at https://github.com/Azure/azure-cli/issues/12946.
