### ISSUE TITLE
az storage core add does not support --auth-mode option

### ISSUE THREAD

**Issue by rodbutters** [Azure/azure-cli#12249]
**Command Name**
`az storage cors add`

**Errors:**
```
az: error: unrecognized arguments: --auth-mode login
```

## To Reproduce:
- `az storage cors add --auth-mode login ... 

## Expected Behavior
As with other storage-cli commands, `az storage core add` should support the option `--auth-mode login`. Without this it's impossible to script set up for my application. 

Previously, --auth-mode login was not required for other az storage ... commands. Other commands now require and support --auth-mode login. I consider this a bug to now require this option, but then not support it here. 

## Environment Summary
```
Linux-4.15.0-1069-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81 *

```

**Comment by Juliehzl** [comment]
Hi @rodbutters, thanks for your feedback. As what you have mentioned, not all storage commands have --auth-mode parameter. Whether the command has the parameter depends on service to some degree.

For `storage cors add`, it is because for file service they don't accept token credentials(--auth-mode-login). In this way, this command cannot have such support.

Please use account key, connection string or sas token for your operation. 
Sorry for inconvenience, but there is little CLI client can do for this. I will close the issue now and if you still have problem, feel free to reopen it and let me know.

**Comment by rodbutters** [comment]
This worked previously w/o any credentials other than being logged in to Cloud Shell or via az login. Latest upgrade broke this and now my installation and configuration scripts no longer function. This is impacting my ability to install new subscriptions for customers - I now need to require a manual step in the installation process. Is there a CLI command to extract the connection string from a storage account into a shell variable?
