### ISSUE TITLE
Issue when creating a vmss using an existing LB ID

### ISSUE THREAD

**Issue by Cr4zyJoe** [Azure/azure-cli#12461]
Hi,

When I create a VM scale set using "az vmss create" and passing an existing load balancer resource ID, I've got an error indicating that the command actually considers whatever is passed to -lb parameter as a name and not a resouce ID.

Error message:

`The template resource '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/loadBalancers/name-of-lb' for type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[System.String]' at line '1' and column '337' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.`

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
I tried this command and it succeeds.
```
az vmss create -g fytest5 -n vmss1 --image centos --lb /subscriptions/*/resourceGroups/fytest5/providers/Microsoft.Network/loadBalancers/lb1
```
Can you share the complete commands of how you create lb and vmss?

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
@Cr4zyJoe

**Comment by katalyse-crobin** [comment]
Hi, I moved on using an ARM template. I didn't retry the command, but I remember the load balancer was Standard tier and it was a private one (no public IP frontend, only a private one within a subnet). Can it makes a difference?

**Comment by Cr4zyJoe** [comment]
Oops, I was signed-in with another account while posting the comment above.

**Comment by vjagadish1989** [comment]
i have the exact same issue, this is one of the most confusing parts of Azure!!

**Comment by SeniorTigr** [comment]
I had similar error when trying to attach existing LB. It looked like this:
_{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/subscriptions/<subscription_id>/resourceGroups/net-rg/providers/Microsoft.Network/loadBalancers/**elk-lb**' for type 'Microsoft.Network/**loadBalancers**' at line '1' and column '243' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":243,"path":"properties.template.resources[0].type"}}]}}_

It is surely caused by the fact that the underlying code does not recognize that it is an resource id, because when I've tried to remove --public-ip-address "" option the error changed to:
_{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/subscriptions/<subscription_id>/resourceGroups/net-rg/providers/Microsoft.Network/loadBalancers/**elk-lbPublicIP**' for type 'Microsoft.Network/**publicIPAddresses**' at line '1' and column '275' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":275,"path":"properties.template.resources[0].type"}}]}}_

My command was:
**az vmss create -n elk-vmss -g elk-rg --computer-name-prefix elk-vm- --disable-overprovision --enable-agent true --enable-auto-update true --image canonical:0001-com-ubuntu-server-focal:20_04-lts:latest --instance-count 3 --license-type None --platform-fault-domain-count 1 --single-placement-group False --vm-sku Standard_F4s_v2 -z 1 2 3 --tags <some tags> --admin-username ubuntu --authentication-type ssh --ssh-key-values <@filename> --public-ip-address "" --subnet $(az network vnet subnet show -n int-vnet-snet-01 -g net-rg --vnet-name int-vnet  --query id -o tsv) --data-disk-sizes-gb 256 --os-disk-size-gb  48 --storage-sku StandardSSD_LRS --lb $(az network lb show -n elk-lb -g net-rg --query id -o tsv) --app-gateway "" --nsg ""**

What option may caused the difference with @qwordy example of proper work?
