### ISSUE TITLE
az rest does not honor --query / --output global parameters

### ISSUE THREAD

**Issue by hiteshmadan** [Azure/azure-cli#12472]
## Describe the bug
Adding --query or --output to an otherwise successful az rest command ends up suppressing stdout output. If these params are not present, a valid json response is seen.

**Command Name**
`az rest --method get --uri subscriptions/0d28f770-f3bc-4939-b759-82c2243deb4b/resourcegroups?api-version=2019-10-01 --query [].{N:name,L:location} --output table`

**Errors:**
empty output

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --uri {} --query {} --output {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
interactive 0.4.3

```
## Additional Context
this is in regular azure public cloud

**Comment by yungezz** [comment]
HI @zhoxing-ms could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S167

**Comment by zhoxing-ms** [comment]
@hiteshmadan This seems to be a problem with the jmespath syntax usage of `--query`. Because the outer layer of the resource group list is wrapped with the `value` key, so the parameter of `--query` should be `value[].{N:name, L:location}`. 
Please have a try~   If you still have any questions, please feel free to let us know.
