### ISSUE TITLE
az webapp create can't create a dotnet core app

### ISSUE THREAD

**Issue by gregorybleiker** [Azure/azure-cli#12508]
**Describe the bug**
It is not possible in azure cli to create a webapp with .net core runtime settings for a non-linux host. It can be set in the arm template with
```
          "metadata": [
            {
              "name": "CURRENT_STACK",
              "value": "dotnetcore"
            }
          ]
```
**To Reproduce**
Try running (or similar)
```
az webapp create -g test-rg -n test-app --runtime "dotnetcore"  -p test-plan
```

**Expected behavior**
runtime param should support the dotnetcore stuff

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@gregorybleiker have you tried creating an appserviceplan with the --is-linux and then do the az webapp create

'appservice plan create -g {} -n {} --is-linux'.format(resource_group, plan)' ?

**Comment by gregorybleiker** [comment]
so is the recommended way to create a dotnet core webapp to do it on a linux host???

**Comment by panchagnula** [comment]
CLI uses the API to verify the list of supported runtimes before an app is created currently the API has a known issue where dotnetcore is not listed as a supported runtime for windows you can verify this by running the command az webapp list-runtimes - once the API fix rolls out this will automatically work. Closing this since this is not a CLI issue.
