### ISSUE TITLE
webapp: dotnet core support for slots

### ISSUE THREAD

**Issue by gregorybleiker** [Azure/azure-cli#12507]
if you create a a webapp with the general stack set to ".NET core" and you create a deployment slot from this with
`az webapp deployment slot create`
then the created slot will have ".NET" as runtime.

## To Reproduce:
create app service with .net core stack, then issue the `az webapp deployment slot create`

## Expected Behavior
it should take the stack settings from the slot it is creating a slot from (usually 'production')

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.1.0
azure-cli-iot-ext 0.8.6

Extensions:
application-insights 0.1.1
azure-cli-iot-ext 0.8.6
log-analytics 0.1.4

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
az webapp deployment slot create - doesn't copy the Settings from the PROD application by default. Have you tried this command with the parameter  [--configuration-source]. Thanks!

**Comment by yonzhan** [comment]
move to S169

**Comment by panchagnula** [comment]
Closing due to lack of response. Please re-activate if the suggestion above doesn't help Thank you.

**Comment by YvonneArnoldus** [comment]
I'm using
az webapp deployment slot create -n $WebAppMgmt --slot staging --configuration-source $WebAppMgmt

And still my slot is in .Net and now why to get it to core because

az webapp config set -n $WebAppWeb --slot staging --windows-fx-version 'DOTNETCORE|3.1' is for containers

az webapp config set -n $WebAppWeb --slot staging --linux-fx-version 'DOTNETCORE|3.1' gives a 400 bad rewquest.

So how to get my slot to .Net Core???

**Comment by panchagnula** [comment]
> I'm using
> az webapp deployment slot create -n $WebAppMgmt --slot staging --configuration-source $WebAppMgmt
> 
> And still my slot is in .Net and now why to get it to core because
> 
> az webapp config set -n $WebAppWeb --slot staging --windows-fx-version 'DOTNETCORE|3.1' is for containers
> 
> az webapp config set -n $WebAppWeb --slot staging --linux-fx-version 'DOTNETCORE|3.1' gives a 400 bad rewquest.
> 
> So how to get my slot to .Net Core???

@YvonneArnoldus reading your comment this doesn't seem like slot not supporting Dotnet 3.1 but more like Linux slots not working with .NET. I.e  this works az webapp config set -n $WebAppWeb --slot staging --windows-fx-version 'DOTNETCORE|3.1' 
& this did not az webapp config set -n $WebAppWeb --slot staging --linux-fx-version 'DOTNETCORE|3.1'

Can you run the command as follows  az webapp config set -n $WebAppWeb --slot staging --linux-fx-version 'DOTNETCORE|3.1' --debug and share the detailed error message. Thanks!

**Comment by YvonneArnoldus** [comment]
az webapp config set -n 'web-app-ips-yat' --slot staging --linux-fx-version "DOTNETCORE|3.1" --debug

 {"Code":"BadRequest","Message":"The parameter LinuxFxVersion has an invalid value.","Target":null,"Details":[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01007","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"],"Code":"BadRequest","Message":"The parameter LinuxFxVersion has an invalid value."}}],"Innererror":null}
 
 
az webapp config set -n 'web-app-ips-yat' --slot staging --linux-fx-version DOTNETCORE|3.1 --debug
 
bash: 3.1: command not found


az webapp config set -n 'web-app-ips-yat' --slot staging --linux-fx-version '"DOTNETCORE|3.1"' --debug

{"Code":"BadRequest","Message":"The parameter LinuxFxVersion has an invalid value.","Target":null,"Details":[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01007","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"],"Code":"BadRequest","Message":"The parameter LinuxFxVersion has an invalid value."}}],"Innererror":null}

So also not a real helpful message. 

But after some more googling I found you get this error also when you have a windows app service plan. So that is my problem but --windows-fx-version 'DOTNETCORE|3.1' also isn't working and I read it was for containers.

So how to get a windows slot to DOTNETCORE|3.1???

**Comment by HaroldH76** [comment]
I'm running into this same issue.

How can I use az cli to set the stack of the slot to net6? I'm using a Windows app service plan.

I have tried:
```az webapp config set --slot staging --windows-fx-version 'dotnet:6' --ids "my id"```

It doesn't give an error but the stack isn't set either. And in the response json I get:
```
{
  "linuxFxVersion": "",
  ....
  "netFrameworkVersion": "v4.0",
  ....
  "windowsFxVersion": "dotnet:6"
}
```
