### ISSUE TITLE
Azure CLI command create permissions with incorrect case

### ISSUE THREAD

**Issue by Karishma-Tiwari-MSFT** [Azure/azure-cli#12531]
**Describe the bug**
After executing az keyvault set-policy -n $keyVaultName -g $rgName --object-id $desIdentity --key-permissions wrapkey unwrapkey get
the actual permission values are in camel case ("wrapKey","unwrapKey").

{
        "applicationId": null,
        "objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "permissions": {
          "certificates": null,
          "keys": [
            "wrapKey",
            "unwrapKey",
            "get"
          ],
          "secrets": null,
          "storage": null
        },
        "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
This behaviour results in "To associate a disk, image, or snapshot with this disk encryption set, you must grant permissions to the key vault <kyvault_name>." error in portal. Clicking on the error link will create the same set of permission but all lower case and the error message disappears.

{
        "applicationId": null,
        "objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "permissions": {
          "certificates": null,
          "keys": [
            "wrapKey",
            "unwrapKey",
            "get",
            "wrapkey",
            "unwrapkey"
          ],
          "secrets": null,
          "storage": null
        },
        "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}

**Environment summary**
I’m running it with Azure CLI installed locally on my machine. Using portal or Set-AzKeyVaultAccessPolicy cmdlet works as expected.

Reference doc: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption#cli
Related GitHub issue: https://github.com/MicrosoftDocs/azure-docs/issues/49499

Reported by : @gitmaximd

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
@Karishma-Tiwari-MSFT Hi, I did some investigations on this and finally found that this is not a CLI issue.
For KeyVault, I believe the permission options are case insensitive, both `wrapKey/unwrapKey` and `wrapkey/unwarpkey` are correct, so if you run `az keyvault set-policy --object-id xxx --key-permissions wrapKey/wrapkey/WRAPKEY`, the results are all same.
Although we can pass different cases into cmdlet or http rest call, the query result always shows us the camel case:
![image](https://user-images.githubusercontent.com/3250203/76388171-6abfdf80-63a3-11ea-97ac-8b3dc8090dce.png)

The real problem here is: I guess that this error message bar on portal uses lower case to match the permission strings, so if the lower case `wrapkey`, `unwrapkey` not found, it appears. Also, I've tried to set permissions via portal, the error message still shows up.
![image](https://user-images.githubusercontent.com/3250203/76388334-da35cf00-63a3-11ea-9c94-95b949f77102.png)

If we click the error link, actually the portal is trying to append these two permissions:
![image](https://user-images.githubusercontent.com/3250203/76388419-110be500-63a4-11ea-8925-ec1d841af9a8.png)

For some reasons, the service side doesn't do the `distinct` operation, so we finally have 5 permissions (`get`, `wrapKey`, `unwrapKey`, `wrapKey`, `unwrapKey`):
![image](https://user-images.githubusercontent.com/3250203/76388707-adce8280-63a4-11ea-9484-01f235872fdd.png)

So the root cause is the portal gives us a wrong error message bar even if we do have the wrap and unwrap permissions. Another thing, I think service side should do something to make sure no duplicates. Anyway, I will add this logic into CLI.

Anything confusing, we can have a further discussion here.

**Comment by bim-msft** [comment]
Closed the issue due to long time inactive.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks @bim-msft for detailed investigation and updating the CLI. Appreciate your help on this. I will share this feedback with the product team.

**Comment by hakanyildizhan** [comment]
Using Azure CLI version 2.249.8,
The command
`az keyvault set-policy -n <keyvault name> --key-permissions Get List Import --object-id <object id>`

results in 

```
{
    "tenantId": "<tenant id>",
    "objectId": "<object id>",
    "permissions": {
        "keys": [
            "get",
            "import",
            "list"
        ],
        "certificates": []
    }
}
```

when the response is inspected on the dev tools when loading the KV permissions on the Azure Portal UI.
However, permissions that are assigned via the UI show up as "Get", "Import", "List" with the first letter in uppercase.

This results in the following discrepancy:

![Image](https://github.com/user-attachments/assets/aabe7898-e138-45ca-87ab-c6defd65caf3)

I had a feeling this is caused by the uppercase/lowercase inconsistency. A similar inconsistency happens when no permissions are supplied i.e. for certificates - in this case, when permissions are fetched via Azure CLI, they show up as `"certificates": null` and when a user is given a set of permissions via the UI except for certificates, they show up as `"certificates": []` (null versus an empty array).

I think this inconsistency is confusing when viewing the KV access policies on Azure Portal and needs to be fixed.
