### ISSUE TITLE
Argument validation errors (custom validators) do not show the correct error message

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#1254]
Change #1037 broke the logic to show error message if a validator fails. 

Incorrect/incomplete error message:
$> az vm show
(--name --resource-group | --ids) are required

The problem is that CliError exceptions simply bypass the call to parser/error when validation is run in application.py. 

@tjprescott, what was the reason for this change?

**Comment by tjprescott** [comment]
The reason is that not every error that originates in a validator is a validation error (since validator itself is a misnomer) and thus printing the usage string is either completely inappropriate or misleading (when the usage string doesn't actually convey the usage). In the case of change #1307 this was the first case, where the error was such that printing a usage string made no sense.

If you want the usage string printed, you can raise a ValueError instead of a CLIError.
