### ISSUE TITLE
Unable to run az storage copy

### ISSUE THREAD

**Issue by planteman** [Azure/azure-cli#12578]
## Describe the bug

**Command Name**
`az storage copy`

**Errors:**
```
Not valid file
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
command_modules/storage/operations/azcopy.py, ln 83, in storage_copy
    source_blob, source_share, source_file_path, source_local_path)
command_modules/storage/operations/azcopy.py, ln 76, in get_url_with_sas
    raise ValueError('Not valid file')
ValueError: Not valid file
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage copy`

## Environment Summary
```
Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
hi @Juliehzl could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S167

**Comment by Juliehzl** [comment]
@planteman Sorry for the late response. Could you please share with us the command debug information for your scenario with `--debug` in your command? The Debug information will help us figure out what happened in your issue.

According to the error thrown, it is caused by no valid url, storage account or local path information found. In this way, I am guessing if there is wrong usage in your command. You can take a look at the examples and provide debug information with us to let me find what happened.

**Comment by planteman** [comment]
Please close this request.  It is created by running az storage without
arguments and of no concern.

Stephane
