### ISSUE TITLE
Unable to delete Application security Group

### ISSUE THREAD

**Issue by cspadmin** [Azure/azure-cli#12591]
Im unable to delete ASG with error: Failed to delete the application security group 'myAsgWebServers'. Error: Application Security Group myAsgWebServers cannot be deleted because it is referenced by IpConfiguration(s) ipconfig1.

Tried the portal and PS but to no avail. there are no resources in the RG, only the ASG but cant delete it

**Comment by yungezz** [comment]
HI @MyronFanQiu could you pls have a look?

**Comment by yonzhan** [comment]
add to S167

**Comment by cspadmin** [comment]
its ok now. i deleted the other resource group. and was able to delete the ASG. not sure why it happened. i did not associate the ASG to another resources on that resource group.

**Comment by MyronFanQiu** [comment]
good to know you have been unblocked. 😄

**Comment by MyronFanQiu** [comment]
close this issue since it's resolved.

**Comment by rajeshsura189** [comment]
I'm Still facing the same issue unable to delete the ASG we don't have any resources in the same RG Can someone help me to fix the issue?

**Comment by Agamiru** [comment]
I can confirm I'm facing this same issue, no RG references the ASG yet I get the message that it is referenced by IpConfiguration(s) ipconfig1.

**Comment by krishnamiriyala** [comment]
Seeing same issue, is there a workaround to delete the security group?

**Comment by krishnamiriyala** [comment]
[Failed to delete the application security group](https://portal.azure.com/#)
Failed to delete the application security group 'nsx-650cc841-dd2c-4cd1-919d-8207fdd84b9e'. Error: Application Security Group [*****-gw-910fc68f-855d-48c9-aca2-214343695f35](https://portal.azure.com/#resource%3Ca%20href=)-rg/providers/Microsoft.Network/applicationSecurityGroups/nsx-650cc841-dd2c-4cd1-919d-8207fdd84b9e'>nsx-650cc841-dd2c-4cd1-919d-8207fdd84b9e cannot be deleted because it is referenced by IpConfiguration(s) ipconfig1.
