### ISSUE TITLE
az vmss update fails JSON serialization on windows

### ISSUE THREAD

**Issue by AgSync-Aaron** [Azure/azure-cli#12623]
## Describe the bug

I am unable to run `az vmss update` with JSON parameters in windows; the equivalent works fine in bash. Here is a script I was working on...
```powershell
param ($resource_group, $vmss_name, $vault_cert_name)

# Get the latest certificate from Azure Key Vault
$cert=(az keyvault secret list-versions --vault-name=vault_name --name=$vault_cert_name | ConvertFrom-Json) | Sort-Object -Property attributes.expires | Select-Object -First 1

# Format the cert ID into a "secrets" format usable by the azure CLI
$secret=$(az vm secret format --secrets=$($cert.id))

# Update the VMSS with the new secrets for the SSL cert
az vmss update --resource-group=$resource_group --name=$vmss_name --query virtualMachineProfile.osProfile.secrets --set="virtualMachineProfile.osProfile.secrets=$secret"
```

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Cannot deserialize as [VaultSecretGroup] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [VaultSecretGroup] an object of type <class 'str'>
Traceback (most recent call last):
pip-install-3pnsb50r\msrest\msrest\serialization.py, ln 577, in body
pip-install-3pnsb50r\msrest\msrest\serialization.py, ln 1298, in _deserialize
pip-install-3pnsb50r\msrest\msrest\serialization.py, ln 1298, in _deserialize
pip-install-3pnsb50r\msrest\msrest\serialization.py, ln 1298, in _deserialize
...
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [VaultSecretGroup] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [VaultSecretGroup] an object of type <class 'str'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Setup an azure vault
- Store a secret in the vault
- Run the powershell script above 

## Expected Behavior
Update the secrets in the VMSS image

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.1.0 *

```

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look, thanks.

**Comment by houk-ms** [comment]
@AgSync-Aaron Thanks for the feedback. I hope this reply finds you well, although we know it's been a lit long since you opened the issue.

**Short Answer**
`az vmss update --resource-group=$resource_group --name=$vmss_name --add virtualMachineProfile.osProfile.secrets @path_to_your_secrets.json`

**Long Answer**
What you were encountering is an issue most possibly caused by quoting in powershell, see [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues).

When using the generic update methods to update a complex property, I recommend to use json file to avoid any possible string parsing problems that come from command line tools.

See [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#generic-update-arguments) to learn the different ways to pass arguments to the generic update methods of AzureCLI.

**Comment by yungezz** [comment]
Hi @AgSync-Aaron does above solutions work for you?

**Comment by houk-ms** [comment]
Closed due to no response for long time.
