### ISSUE TITLE
az resource create example with json file as property input unclear

### ISSUE THREAD

**Issue by cwickham33** [Azure/azure-cli#12646]
The example for reading properties from a file shows @filename. I'm assuming that the @ is the splatting operator and I can't find any documentation that is consistent with this usage. Splatting is meant to supply an array of key-value pairs for parameters and not to read input from a file. It could be my file isn't formatted properly too so showing the contents of a sample file would be really useful so I don't have to guess like I've been doing for the past 2 hours.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @zhoxing-ms could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S167

**Comment by zhoxing-ms** [comment]
@cwickham33 Hi, here is a document that contains the instructions on how to use `@`: [Tips for using Azure CLI effectively](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues)
> 7. Use CLI's @<file> convention to load from a file so to bypass the shell's intepretion mechanisms:
    `az ad app create --display-name my-native --native-app --required-resource-accesses @manifest.json`

The data structure used in the input file is JSON.
> Create a resource by loading JSON configuration from a file.
        az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object
        --properties @jsonConfigFile

Do you have any other questions?

**Comment by cwickham33** [comment]
The original problem is that the workflow was designed to run with powershell except for this step and it wasn’t clear on that page, that you had to break to the cmd.exe line in order to have the @ recognized. I was working from a windows machine and not linux. This page is linux oriented so, no, it doesn’t help in the windows case.

c

**Comment by zhoxing-ms** [comment]
@cwickham33 Do your mean that your workflow executed in PowerShell was interrupted because `@` could not be properly recognized?
If so, what you said before is right, this problem is caused by `@` being [splatting symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7) in powershell. So you need to escape it or use [stop-parsing symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7). 

There are still some instructions in this document [
Tips for using Azure CLI effectively](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues)

> 9. When running Azure CLI commands in PowerShell, parsing errors will occur when the arguments contain special characters of PowerShell, such as at @. You can solve this problem by adding ` before the special character to escape it, or by enclosing the argument with single or double quotes '/". For example, az group deployment create --parameters @parameters.json dose't work in PowerShell because @ is parsed as a splatting symbol. To fix this, you may change the argument to `@parameters.json or '@parameters.json'.

> 10. .... To prevent this, you may use stop-parsing symbol --% between az and arguments like az --% vm create .... This can also solve the above-mentioned special character issue and is recommended whenever any issue happens when invoking a batch script from PowerShell.
The stop-parsing symbol (--%), introduced in PowerShell 3.0, directs PowerShell to refrain from interpreting input as PowerShell commands or expressions.
When it encounters a stop-parsing symbol, PowerShell treats the remaining characters in the line as a literal.

**Comment by cwickham33** [comment]
Yes. Including the stop parsing symbol in that workflow will help alot. Switching away from psh means the loss of the psh variables that are used in the script.

Thanks,
c
________________________________

**Comment by zhoxing-ms** [comment]
@cwickham33 Do you have any other questions?

**Comment by cwickham33** [comment]
No, you can close the issue.

c
________________________________
