### ISSUE TITLE
allow setting timeout for model register

### ISSUE THREAD

**Issue by ficocesari** [Azure/azure-cli#12651]
In COVID19 times we all work form home and network upload speeds are suboptimal. I can't upload a model that is ~500M
 $az ml model register --name sow2_macro_micro_5_class --model-path models/faster_rcnn_r101_fpn_1x_sow2_5cls_weights --workspace-name "sow2" --resource-group ml
{'Azure-cli-ml Version': '1.0.57', 'Error': AzureHttpError('Operation could not be completed within the specified time. ErrorCode: OperationTimedOut\n<?xml version="1.0" encoding="utf-8"?><Error><Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time.\nRequestId:2babcd2a-501e-0099-4f75-fd0e60000000\nTime:2020-03-18T22:35:23.0520830Z</Message></Error>')}
(base) (venv) federicocesari FedericsarisMBP ~/dev/ml-inference/examples/shell_sow2 
 $ls -allh models/faster_rcnn_r101_fpn_1x_sow2_5cls_weights/
-rw-r--r--  1 federicocesari  staff   456M Mar  5 14:57 epoch_24.pth
-rw-r--r--  1 federicocesari  staff   5.3K Mar  5 16:11 faster_rcnn_r101_fpn_1x_sow2_5cls.py
 
Would be useful to have a way to set the timeout to something other than 30 secs

This also happens with the python API
WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(32, 'EPIPE')"))': /azureml/LocalUpload/200318T144837-f2bf1d26/faster_rcnn_r101_fpn_1x_sow2_5cls_weights.tar.gz?sv=2019-02-02&sr=b&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D&st=2020-03-18T21%3A38%3A38Z&se=2020-03-19T21%3A48%3A38Z&sp=rcw&comp=block&blockid=TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNVEkxT0RJNU1USSUzRA%3D%3D&timeout=30
W

**Comment by yungezz** [comment]
thanks for reporting, we'll have a look

**Comment by azureml-github** [comment]
@Kevin Riehm<mailto:Kevin.Riehm@microsoft.com> @Salil Bapat<mailto:Salil.Bapat@microsoft.com>


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by keriehm** [comment]
Do you experience this with the most recent version of the AzureML CLI extension? Update instructions here: https://docs.microsoft.com/en-us/azure/machine-learning/reference-azure-machine-learning-cli#update-the-extension

**Comment by ficocesari** [comment]
Updated to latest
 
$az --version
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-cli-ml                       1.1.5

Python location '/opt/miniconda3/bin/python'
Extensions directory '/Users/federicocesari/.azure/cliextensions'

Python (Darwin) 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]


Still happening

DEBUG - Workspace:
	name: shell-sow2
	resource_group: ml
	location: westus2
	subscription_id: b5b12f4b-f282-41e3-b94f-92d6943ab2d2
WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(32, 'EPIPE')"))': /azureml/LocalUpload/200324T132629-0270daee/faster_rcnn_r101_fpn_1x_sow2_5cls_weights.tar.gz?sv=2019-02-02&sr=b&sig=wUTQhfVSVsPyjRYt7uiDU4N0Y9z4FWALwbdKCxQUYS4%3D&st=2020-03-24T20%3A16%3A30Z&se=2020-03-25T20%3A26%3A30Z&sp=rcw&comp=block&blockid=TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXhPVGN4TXpJeU9EZyUzRA%3D%3D&timeout=30
WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(32, 'EPIPE')"))': /azureml/LocalUpload/200324T132629-0270daee/faster_rcnn_r101_fpn_1x_sow2_5cls_weights.tar.gz?sv=2019-02-02&sr=b&sig=wUTQhfVSVsPyjRYt7uiDU4N0Y9z4FWALwbdKCxQUYS4%3D&st=2020-03-24T20%3A16%3A30Z&se=2020-03-25T20%3A26%3A30Z&sp=rcw&comp=block&blockid=TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXlNelE0T0RFd01qUSUzRA%3D%3D&timeout=30

**Comment by salilbapat** [comment]
We have filed an intenal bug to make this timeout configurable and have prioritized the fix. Will update the thread with ETA for when this will be available.

**Comment by ficocesari** [comment]
Great thanks!

**Comment by keerthiadu** [comment]
May I know the measured upload speed on your end?

**Comment by ficocesari** [comment]
~ 10M

**Comment by ficocesari** [comment]
The file I was uploading was 500M

**Comment by keerthiadu** [comment]
Unfortunately, the timeout parameter is of no significance and is ignored by the blob service when writing to a blobstorage as per[ https://docs.microsoft.com/en-us/rest/api/storageservices/Setting-Timeouts-for-Blob-Service-Operations#exceptions-to-default-timeout-interval]( https://docs.microsoft.com/en-us/rest/api/storageservices/Setting-Timeouts-for-Blob-Service-Operations#exceptions-to-default-timeout-interval) . 

The OperationTimedOut error(as per logs) is coming from the blobstorage service and most likely the error is due to "Calls to write a blob, write a block, or write a page are permitted 10 minutes per megabyte to complete. If an operation is taking longer than 10 minutes per megabyte on average, it will time out." 

As the timeout parameter is being ignored, bumping it and/or making it configurable wont help.

One thing we can try is, uploading the file directly from your local machine to azure blobstorage using AZCopy . 

[https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
)
[https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs
](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs
)

If you are able to upload the 500 MB file to azure blob storage using AZCopy, then I can come up with a work around on our end.

**Comment by keerthiadu** [comment]
[use-azcopy-for-model-upload.py](https://gist.github.com/keerthiadu/363e4e6cbae20e8b7a6f6f5cefbb0f89) has code snippet for uploading models using azcopy . This workaround is makeshift and future support and compatibility is not guaranteed.

**Comment by keerthiadu** [comment]
#please-close
