### ISSUE TITLE
I don't see all of the IP addresses that I have added in the Azure Portal reflected in the Portal

### ISSUE THREAD

**Issue by DrReedo** [Azure/azure-cli#12720]
Earlier I updated the IP addresses manually in the Portal but when I returned I couldn't see them all in the Azure Portal leading me to think they had been removed.  However, when I run the show command I can see them in the ip-range-filter.  Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by shurd** [comment]
Hi @DrReedo thank you for opening this issue. For clarification, you are saying that there is a discrepancy between the IP ranges shown in the portal and returned via the CLI? The CLI returns the exact list we store internally. In some cases, the portal might filter out certain IP addresses in the UI (the "allow access via portal" IP addresses are condensed into a checkbox). 

If the CLI is returning the expected values (and this is therefore just a portal display problem), could you open a support ticket via the Azure Portal so that the question can be routed to someone on our Portal team?

**Comment by DrReedo** [comment]
Hi @shurd , 
Yes, ok, that might make sense because I'm adding in the ipRange for the Azure Portal for 'All other regions' as described here:
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall
But you're saying they are automatically enabled?
It's not clear that the checkbox filters out these addresses though - one for the documentation team.  Shall I post it there?
thank you

**Comment by shurd** [comment]
Yes those IP addresses are added when you check the box next to "Allow access from Azure portal". I just confirmed also that if you leave the box unchecked but manually add those IP addresses, the box will appear checked and the IP addresses will not be listed when refreshed.

Raising an issue on the documentation page would be the right path forward for this.

**Comment by DrReedo** [comment]
OK, I will do that.  thanks.

**Comment by JasonWHowell** [comment]
I believe this is resolved by recent docs changes. #please-close
