### ISSUE TITLE
az resource create and x-ms-version

### ISSUE THREAD

**Issue by happyiphone** [Azure/azure-cli#12721]
## Describe the bug

**Command Name**
`az resource create`

**Errors:**
```
Unable to create domain name 'UniqueResourceDomainNameGoesHere': 'The x-ms-version header value '2020-02-01' is not one of the supported version headers.'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource create --location {} --name {} --properties {} --resource-group {} --resource-type {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S168

**Comment by zhoxing-ms** [comment]
@happyiphone Hi, I can't reproduce your question. Could you please provide more specific parameter information? Placeholders can be used instead of sensitive privacy information.

**Comment by thomhurst** [comment]
Hi I'm also getting this:

```
$productionSlot = Get-AzureRmResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.ClassicCompute/domainNames -ResourceName "$resourceName/slots/Production"
```

**Comment by zhoxing-ms** [comment]
@thomhurst Do you have this problem while using CLI commands?

**Comment by happyiphone** [comment]
Just tried again and I still get the same error:

`az resource create --location 'westus' --name 'DemoResource' --properties '{}' --resource-group 'Tg' --resource-type 'Microsoft.ClassicCompute/domainNames'      `                                                                                                                                             

**Unable to create domain name 'DemoResource': 'The x-ms-version header value '2020-02-01' is not one of the supported version headers.'.**

let me know if you need anything more specific than this. 

thanks!

**Comment by zhoxing-ms** [comment]
When the CLI calls the Service of [Resources - Create Or Update](https://docs.microsoft.com/en-us/rest/api/resources/providers/get) to query the api_version of domainNames for resource type under Microsoft.ClassicCompute provider, we get the latest version is `2020-02-01`.
Then CLI uses the api_version of `2020-02-01` to call the Service of [
Resources - Create Or Update](https://docs.microsoft.com/en-us/rest/api/resources/resources/createorupdate) in order to create a new resource of `Microsoft.ClassicCompute/domainNames`, the following error occurred:
> {"error":{"code":"DomainNameOperationFailed","message":"Unable to create domain name 'DemoResource2': 'The x-ms-version header value '2020-02-01' is not one of the supported version headers.'."}}

Request URL: `PUT https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{ResourceGroup}/providers/Microsoft.ClassicCompute/domainNames/{domainNames}?api-version=2020-02-01`

**Comment by navba-MSFT** [comment]
@happyiphone Apologies for the late reply. Could you please let us know if you are still facing this issue with [recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)of the CLI ? Awaiting your reply.
