### ISSUE TITLE
Attempting to add application-gatewate to a waf-policy

### ISSUE THREAD

**Issue by jrmilholland** [Azure/azure-cli#12763]
## Describe the bug
Command executes without errors, but doesn't actually update anything. Value for applicationGateways still is null.
Used syntax from:
https://github.com/Azure/azure-cli/issues/10011#issuecomment-520281381

**Command Name**
`az network application-gateway waf-policy update`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway waf-policy update --name {} --resource-group {} --add {} {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.71 *
azure-cli-ml 1.0.83

Extensions:
azure-cli-ml 1.0.83
azure-devops 0.12.0

```

**Comment by qwordy** [comment]
@MyronFanQiu

**Comment by MyronFanQiu** [comment]
@haroldrandom Could you please take a look?

**Comment by yonzhan** [comment]
add to S169

**Comment by haroldrandom** [comment]
@jrmilholland could you please provide the property name? (remove the sentisitive property value)

**Comment by yonzhan** [comment]
@jrmilholland any update ?

**Comment by haroldrandom** [comment]
Hi, @jrmilholland  I digged it out. The property `application_gateways` in data structure `WebApplicationFirewallPolicy` is read-only, it's not settable. That's why it could success without raising errors and update nothing becausing the framework never send it out.

Has to use another way to associate a waf-policy with an application-gateway, that is `--waf-policy` parameter in `az network application-gateway create`.

**Comment by jrmilholland** [comment]
Thanks!
