### ISSUE TITLE
Possible values for --action-name

### ISSUE THREAD

**Issue by ngnmhieu** [Azure/azure-cli#12857]
Please provide the possible values for `--action-name`. As reflected in azure cli code, those are: "CacheExpiration", "RequestHeader", "ResponseHeader", "CacheKeyQueryString", "UrlRedirect", "UrlRewrite".
See https://github.com/Azure/azure-cli/blob/836da4965ce6db2ffcf37f4d3790d61709267654/src/azure-cli/azure/cli/command_modules/cdn/custom.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @MyronFanQiu could you have a look?

**Comment by yonzhan** [comment]
add to S168

**Comment by yonzhan** [comment]
cdn

**Comment by hytao** [comment]
We'll add possible values for action-name in the future update.

**Comment by navba-MSFT** [comment]
@ngnmhieu Apologies for the late reply. I see that [this](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az-cdn-endpoint-rule-add-required-parameters) docs has been updated now with the below accepted values for the _--action-name_ parameter. Hope your ask is now addressed.

>accepted values: CacheExpiration, CacheKeyQueryString, ModifyRequestHeader, ModifyResponseHeader, OriginGroupOverride, RequestHeader, ResponseHeader, UrlRedirect, UrlRewrite, UrlSigning

Since this issue has been inactive for quite sometime, we will now proceed with closure. If you need any further assistance on this please feel free to reopen this thread.
