### ISSUE TITLE
Disconnected and Offline CLI Functionality Issues

### ISSUE THREAD

**Issue by rjaffee** [Azure/azure-cli#12938]
**Describe the bug**
CLI does not function correctly when run within a VNet that is isolated from having access to the Internet. CLI makes calls to the internet for commands such as AZ VM Create and AZ Copy and others. This presents an issue when the VNet is isolated from the internet or an organization is not able to download and install software on the fly.

**To Reproduce**
1)	Setup a VNet with a windows VM inside.
2)	Install CLI (2.2.0/2.3.1) on Windows VM (Server 2016)
3)	Isolate Subnet (NSG) by denying all Internet traffic inbound and outbound (ability to still reach internal Azure Endpoints)
Examples: 
•	For authorization, in the python adal library az cli uses, there is a hardcoded whitelist of known AAD endpoints and if it cannot find the endpoint, it makes a call to logon.windows.net.  
•	Attempt to create a VM (Az VM Create) – Issue #12902
•	Attempt to Copy files to VHD (Az Storage Copy) – Calls to internet to download AzCopy if AZCopy doesn’t exist already.

**Expected behavior**
CLI should have full functionality when the ability to make calls to the internet and/or download additional content is restricted or unavailable. CLI commands should not be restricted based on internet availability of the end point they are being run from. 

**Environment summary**
•	Windows Server 2016 VM on an Azure VNet Isolated from the internet
•	CLI 2.2.0/2.3.1 and PowerShell 7.0 

**Additional context**
Requesting a code review to enable full CLI functionality when internet access is not available or heavily restricted on what can be downloaded and installed.  
Suggestion - a standalone or offline installer package for CLI that includes additional files and packages that would normally be checked for and downloaded if not available locally. 

Example environment(s): 
•	Isolated VNet or resource from Internet
•	Disconnected Azure Stack 
For disconnected stack the following addition command was needed for Azure Copy functionality:
$env:AZCOPY_DEFAULT_SERVICE_API_VERSION="2017-11-09"

CLI should set these types of environmental variables based on the registered Azure cloud profile - (Az Cloud Register). In this case the profile was 2018-03-01-hybrid.

**Comment by yonzhan** [comment]
add to S168

**Comment by jiasli** [comment]
According to [constants.py](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/2a1c7ffabda0d79548533434db0cc9bbae6eefcf/adal/constants.py) from ADAL, if Azure CLI is run in a private cloud, the authority may be `https://login.microsoftonline.my.azurestack.com/common/oauth2/authorize?...`. Since this URL doesn't match any endpoint in
```py
WELL_KNOWN_AUTHORITY_HOSTS = [
    'login.windows.net',
    'login.microsoftonline.com',
    'login.chinacloudapi.cn',
    'login-us.microsoftonline.com',
    'login.microsoftonline.us',
    'login.microsoftonline.de',
    ]
```
it will try to perform an instance discovery at 
```py
INSTANCE_DISCOVERY_ENDPOINT_TEMPLATE = 'https://{authorize_host}/common/discovery/instance?authorization_endpoint={authorize_endpoint}&api-version=1.0'
```
with 
```py
WORLD_WIDE_AUTHORITY = 'login.windows.net'
```
thus making an internet request to
```
https://login.windows.net/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.my.azurestack.com/common/oauth2/authorize&api-version=1.0
```

This causes Azure CLI to crash because internet access is not available in a private cloud.

Luckily it is possible to disable the validation by setting [`validate_authority`](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/3581edf8b2df9e91553abed2dc57336c367f8cb0/adal/authentication_context.py#L49) to `False`, but Azure CLI hard-codes it to `True` while [creating `adal.AuthenticationContext`](https://github.com/Azure/azure-cli/blob/806e4318d058c3037566fa5a7a07cfc99d1ff51d/src/azure-cli-core/azure/cli/core/_profile.py#L103). We need to sync with PM @achandmsft to decide the best way to let users control the behavior. 

Furthermore, as we are migrating to MSAL, MSAL also has [`validate_authority`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/57236a23d904a6ef70392a7b4a1326ad287c13db/msal/application.py#L93). +@rayluo for awareness.

However, it seems [Azure Identity](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity) doesn't expose this flag. +@chlowell to confirm. 

For AZCopy, I will leave that part to @Juliehzl .

**Comment by rjaffee** [comment]
Thanks Jiashuo,

+@David Bowen<mailto:Bowen.David@microsoft.com> for visibility/comments on the Auth findings below. Would this have the same effect with Sovereign regions?

Thanks,
Robert

**Comment by chlowell** [comment]
> Furthermore, as we are migrating to MSAL, MSAL also has [`validate_authority`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/57236a23d904a6ef70392a7b4a1326ad287c13db/msal/application.py#L93). +@rayluo for awareness.
> 
> However, it seems [Azure Identity](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity) doesn't expose this flag. +@chlowell to confirm.
> 

azure-identity itself doesn't perform any AAD discovery. Credentials instead take discovery information as arguments, e.g.:
```py
from azure.identity import ClientSecretCredential

custom_authority = 'login.microsoftonline.my.azurestack.com'
credential = ClientSecretCredential(
    'tenant id', 'client id', 'secret', authority=custom_authority
)

# KnownAuthorities contains authorities for common clouds
from azure.identity import KnownAuthorities

credential = ClientSecretCredential(
    'tenant id', 'client id', 'secret', authority=KnownAuthorities.AZURE_GERMANY
)
```
Also, in the latest preview version (1.4.0b2 at time of writing) credentials will prefer the value of environment variable `AZURE_AUTHORITY_HOST`.

All that said, MSAL applications do perform discovery, so credentials based on them (`DeviceCodeCredential`, `InteractiveBrowserCredential`, `UsernamePasswordCredential`) provoke discovery requests but don't themselves see the responses.

**Comment by rjaffee** [comment]
Thanks  + @David Bowen<mailto:Bowen.David@microsoft.com> for visibility


Thanks,
Robert
