### ISSUE TITLE
Add support to populate a CosmosDB collection with az cli

### ISSUE THREAD

**Issue by jabrena** [Azure/azure-cli#12985]
**Is your feature request related to a problem? Please describe.**

When you are designing Serverless solutions, you execute some scripts to deploy an immutable infrastructure and it is very common to use az cli. If the solution includes CosmosDB, it is not easy to populate some collections from the beginning if the solution include some predefined data.

**Describe the solution you'd like**

I would like to add in the az cli a new option to send a json file with data that you want to store in CosmosDB.

**Describe alternatives you've considered**

Currently, I don´t see an easy way to do it except to create a azure function to populate the collection manually and remove after the process, but that solution is not elegant. You replace a Bash Script with an Azure Function.

**Additional context**

Initial discussion in StackOverflow:
https://stackoverflow.com/questions/61077774/how-to-populate-a-cosmosdb-collection-by-command-line/61078919#61078919

Many thanks in advance

Juan Antonio

**Comment by yonzhan** [comment]
CosmosDB

**Comment by jabrena** [comment]
Related issue:
https://github.com/Azure/azure-cli/issues/6171

**Comment by shurd** [comment]
Hi @jabrena thank you for opening this issue. The Cosmos DB command module focuses on management and control plane operations rather than data plane operations. As mentioned in the issue you linked, we are not currently planning on supporting data plane operations via the CLI. We offer other SDKs optimized for these operations. [This page](https://docs.microsoft.com/en-us/azure/cosmos-db/) provides links to SDK tutorials and examples based on the account API type.
