### ISSUE TITLE
HPC Cache - az hpc-cache nfs-storage-target update 

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-cli#13005]
```
az hpc-cache nfs-storage-target add --resource-group "asc-cmk-test-remakar" --cache-name "makarcli" --name test --nfs3-target 10.0.0.4 --nfs3-usage-model WRITE_AROUND --junction namespace-path="/test1" nfs-export="/datadisk1" target-path="" --junction namespace-path="/test2" nfs-export="/datadisk2" target-path="" --junction namespace-path="/test3" nfs-export="/datadisk3" target-path=""

az hpc-cache nfs-storage-target update --resource-group "asc-cmk-test-remakar" --cache-name "makarcli" --name test --nfs3-target 10.0.0.4 --nfs3-usage-model WRITE_AROUND --junction namespace-path="/test1" nfs-export="/datadisk1" target-path="
```

1. Create new ST
2. Update that ST junctions = Operation failed with status: 202. Details: Resource state Updating.

NUMBER 2 is bug since it is actually updating the storage target but returns to user that it is an error. Looks like mapping may be wrong somewhere.

**Comment by yonzhan** [comment]
add to S169

**Comment by zhoxing-ms** [comment]
This problem is due to the Python SDK throws an exception when `response.status_code` is 202, [code link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_storage_targets_operations.py#L326)

> status: 202. Details: Resource state Updating

In fact, it should not throw an exception directly in a scenario where the resource is being updated, 
Therefore, the SDK needs to do some compatible logic when `response.status_code` is 202

@romahamu Could you please help to have a look~

**Comment by rebecca-makar** [comment]
@zhoxing-ms we do have a bug in our swagger, we only accept 200 and 201 even though we are returning a 202.
Have a bug opened on our RP for this. Sorry about confusion.

**Comment by rebecca-makar** [comment]
Closing this bug, as mentioned in 2020 there was a bug in our RP.
We have automation running using the azcli for 'az hpc-cache nfs-storage-target update` and it is successful.
