### ISSUE TITLE
Validation failures give error location based on minified arm template

### ISSUE THREAD

**Issue by Tyriar** [Azure/azure-cli#13159]
Repro:

1. Create `arm-test.json` with this content
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "appservice_name": {
            "defaultValue": "testing",
            "type": "string"
        },
        "location": {
            "defaultValue": "West US",
            "type": "string"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Web/serverfarms",
            "apiVersion": "2018-02-01",
            "name": "[parameters('appservice_name')]",
            "location": "[parameters('location')]",
            "sku": {
                "name": "P1v2",
                "tier": "PremiumV2",
                "size": "P1v2",
                "family": "Pv2",
                "capacity": 1
            },
            "kind": "linux",
            "properties": {
                "perSiteScaling": false,
                "maximumElasticWorkerCount": 1,
                "isSpot": false,
                "reserved": true,
                "isXenon": false,
                "hyperV": false,
                "targetWorkerCount": 0,
                "targetWorkerSizeId": 0
            }
        },
    ]
}
```
2. Set $vSubscription and $vResourceGroup
3. Run `az deployment group create --subscription $vSubscription -g $vResourceGroup--template-file arm-test.json`

Result:

![image](https://user-images.githubusercontent.com/2193314/80231640-7ccea800-8608-11ea-9105-6891165f1558.png)

So I think there is a bug here and I also have a suggestion. The error says line 1 column 679 clearly the arm template is not that long, it's complaining about some minified version of it being validated.

If that gets fixed, the suggestion is to print this with the path to the file, that way using VS Code's integrated terminal you can click the error and go directly to the problem line, for example:

![image](https://user-images.githubusercontent.com/2193314/80232032-15fdbe80-8609-11ea-994d-2ce19fe562d2.png)

Compilers/linters normally do this which makes it convenient to fix the problem.

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@Tyriar Thank you for your feedback and suggestions~ As you said, this problem is caused by the validation after the ARM template is compressed and comments are deleted.

Because we don't have a proper way to solve this problem at the moment ( There is no Python open source library for JSON format validation that can ignore the comments contained in JSON. If we did this ourselves, the cost would be much higher ), So we decided not to expose the specific error location in the template for the time being, but it will prompt the wrong file.

Therefore, I will close this issue first. If there are more customers feedback that need to expose the specific error position in template in the future, I will follow up to improve it again~
