### ISSUE TITLE
az aks install-connector doesn't recognize --name param

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [Azure/azure-cli#13318]
**Describe the bug**
When I use the --name parameter in the az aks command with the install-connector switch, the output states that the --name switch isn't recognized. However, it is shown in the documentation here: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-connector

![image](https://user-images.githubusercontent.com/28905827/80961789-adb59680-8dd9-11ea-9a26-464082665799.png)

**To Reproduce**
Run: az aks install-connector --name MyManagedCluster --resource-group MyResourceGroup
  --connector-name virtual-kubelet --os-type Both

**Expected behavior**
To have the ACI connector attached to my AKS cluster

**Environment summary**
MacOS 10.15.4. Azure CLI install via the Microsoft website.

**Comment by yonzhan** [comment]
aks

**Comment by AdminTurnedDevOps** [comment]
This bug has been going on for months in the community (https://stackoverflow.com/questions/59968396/az-aks-install-connector-fails-name-uknow-parameter)... When we can expect this to be resolved?

**Comment by jluk** [comment]
@AdminTurnedDevOps please use the enable-addons command instead of install-connector.

You can follow the official instructions here:
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#enable-virtual-nodes-addon
```
az aks enable-addons \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --addons virtual-node \
    --subnet-name myVirtualNodeSubnet
```
The install-connector was a command set used during preview, which is set for removal.

**Comment by AdminTurnedDevOps** [comment]
Okay great, thanks. Is that something that will be updated in the Azure CLI docs? Because a ton of the docs still point to use install-connector.

**Comment by jluk** [comment]
The CLI reference is autogenerated (like here: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-connector), so that will get removed there when the code is deprecated. That should be happening this month.

Please point me to any other docs recommending that command and we can get that fixed.

**Comment by yungezz** [comment]
Docs at docs.ms is refreshed when Azure CLI release. next release is May 19th. As long as code change in help.py merged before that, docs will be updated then.

**Comment by jluk** [comment]
cc @macoslo from ACI / VN team

**Comment by Jen7714** [comment]
Closing this issue for now as the doc issue should've been resolved in the latest CLI release.
