### ISSUE TITLE
Why does "az --version" try to connect to "example.org"?

### ISSUE THREAD

**Issue by jms1voalte** [Azure/azure-cli#13385]
## Describe the bug

**Command Name**
`az --version`

**Errors:**

Attempts to connect to `example.org` port 443/tcp.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Install "Little Snitch" or some other mechanism to observe outbound traffic.
- `az --version`

## Expected Behavior

Software reports its version numbers without trying to connect to any outside servers.

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.1

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks

**Comment by arrownj** [comment]
Hi @jms1voalte , CLI use it to check whether it can access the internet. We will consider change it to an official website in the future.

**Comment by yungezz** [comment]
Thanks for reporting the issue. To use the url is to just check network connectivity without real connection. Actually the url is configurable inside CLI code. Hope this clarifies. Would like to close the issue for now, feel free to open issue if any other ask. thanks.

**Comment by tkoestler** [comment]
Why was this closed? example.org is a Chinese site. This should be pointed to an MS site.  How do we not example.org is not collecting IP addresses to attack.  This is a real security issue and should be fixed yesterday.

**Comment by yungezz** [comment]
make sense. @fengzhou-msft could you pls help take care of the fix? thanks.

**Comment by shunkino** [comment]
Any update on this issue? I think it's better to use some azure related domain (e.g. https://azure.microsoft.com) to check the connection as suggested by limingu in original [PR](https://github.com/Azure/azure-cli/pull/8922#discussion_r270499824). 

I am not concerned that this communication will be abused because "example.org" is reserved by IANA as in [RFC2606](https://tools.ietf.org/html/rfc2606). However, users in monitored corporate network will prefer more explainable domain to clarify the purpose of each communication.

**Comment by yungezz** [comment]
hi @BigCat20196 can you help on this? thanks

**Comment by BigCat20196** [comment]
hi @shunkino Thank you for your advice.

I also think it is necessary to change the address of the test network connection to the Microsoft address.
BTW, I am considering fixing it.

**Comment by shunkino** [comment]
Hey @BigCat20196, glad to see this change merged! Thank you.
