### ISSUE TITLE
Completion throws error under zsh under normal conditions

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1342]
If I try to `source az.completion.sh` in `zsh`, I get this:

```
(eval):9: command not found: complete
```

This was not happening a week or so ago.

It goes away if I run `source <(kubectl completion zsh)` beforehand. I think this is because the kubectl completion enables ZSH's completion compatibility mode. `azure-cli` should do the same.

**Comment by derekbekoe** [comment]
Thanks for the feedback.
So running `autoload bashcompinit && bashcompinit` before `source az.completion.sh` resolves this.

I'm hesitant to add `autoload bashcompinit && bashcompinit` to `source az.completion.sh` as a quick fix because this command fails on bash and I couldn't find a good way to determine if the user is using zsh.

If we implement a feature like `az completion bash/zsh`, we'll be able to do this automatically as the user will specify the shell they are using - https://github.com/Azure/azure-cli/issues/630

**Comment by colemickens** [comment]
Hm, can you check `${SHELL}` against `*zsh*` ? Not perfect, but maybe close enough for now?
