### ISSUE TITLE
Add Portal options that missing to create Cosmos DB using CLI

### ISSUE THREAD

**Issue by epomatti** [Azure/azure-cli#13535]
**Describe the solution you'd like**

On the Portal there are two options that I can't find when using Azure CLI:

- Apply Free Tier Discount (Apply / Do not apply)
- Account Type (Production / Non-production)

![image](https://user-images.githubusercontent.com/6530769/82135960-f6f4e580-97de-11ea-94b4-9e424c0d05f9.png)

I would like to be able to create a Cosmos DB resource with these options using Azure CLI.

**Describe alternatives you've considered**

Use the Portal is an alternative.

**Comment by yungezz** [comment]
routing to service team to have a look

**Comment by shurd** [comment]
Hi @evandropomatti thank you for opening this issue. We are working on adding the "free tier" option in the CLI. We are waiting on the SDK that has those options to be generated.

The "Account Type" option just adds an additional tag to the account ("CosmosAccountType"). You can manually add the "Production" or "Non-Production" tag if you want them on your account. We do not want to add duplicate places to update the same field, so we do not plan on adding a specific flag for this option in the CLI.

**Comment by evandropomatti** [comment]
@shurd thanks for the response.

1. The "free tier" option would be great. I believe we keep this issue opened then until it is released? In that would be a good idea to add it to the internal tool so it can be closed and tested in the future.

2. The "Account Type" implemented as a tag sounds strange to me, and it is not obvious to someone using the API. It looks like something that should be part of the model of the resource. It should be possible to have it updated in one place, even if it is a tag.

**Comment by shurd** [comment]
We are adding the free tier option to the swagger now, which will add it to the auto-generated SDKs. This is a pre-requisite to adding it to the CLI.

For the "Account Type", this tag does not impact the behavior or functionality of the account. It is used to label accounts either for portal experience or metrics. If you want the tag on the account, you can provide it using the --tags option when creating or updating an account. Because it is just a label and can already be added if desired, we do not plan on adding it as a stand-alone parameter at this time.

**Comment by shurd** [comment]
We have introduced free tier as a part of this change: https://github.com/Azure/azure-cli/pull/13985. It was included in version 2.9.0, which was released earlier this week.
