### ISSUE TITLE
enable-managed-identity true causes 'ApiManagementServiceResource' object does not support item assignment

### ISSUE THREAD

**Issue by jt000** [Azure/azure-cli#13613]
## Describe the bug
When running `az apim create` with `--enabled-managed-identity true` you get the below error

**Command Name**
`az apim create`

**Errors:**
```
'ApiManagementServiceResource' object does not support item assignment
Traceback (most recent call last):
Temp\pip-install-z6h9b3s8\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-z6h9b3s8\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\apim\custom.py, ln 31, in create_apim
TypeError: 'ApiManagementServiceResource' object does not support item assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim create --name "any" --publisher-email "any@example.com" --publisher-name "any" -g "any" --enable-managed-identity true`

## Expected Behavior
Should deploy a new APIM instance

NOTE: Using `az apim update --enable-managed-identity true ...` doesn't return error

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
apim

**Comment by sireza** [comment]
Just experienced the same issue, would appreciate an update on this. Thanks

**Comment by nicolas-martin-dte** [comment]
About a year later and I'm still getting this error. Get on it!

This was my last hope to get around an idiotic Key Vault circular reference in my ARM template. I need to create the APIM resource with custom host names where certs are sourced from Key Vault, but Key Vault needs access policy to the APIM instance's Managed Identity. My attempt to circumvent was Azure CLI to create the APIM instance and Key Vault access policy before the ARM template runs which does the proper configuration (source of truth). @Microsoft it is so idiotic that you don't have this scenario covered easily and is a major barrier to your customers following proper security practices! I try to love Azure because I've been MSFT stack my whole career, but the automation tooling is such a pitiful second-class citizen, evidenced by lack of attention to documented "features" that are so blatantly broken for so long. I need to move on so guess I'm stuck doing some manual configuration. 👎

**Comment by adeliab** [comment]
This error still happens 👎 👎

**Comment by yonzhan** [comment]
API management service team should take a look

**Comment by navba-MSFT** [comment]
@jt000 Apologies for the late reply. I was able to run the below command in azure cloud shell and it worked fine.

>***/Azure:~$ az apim create --name MyApim -g MyRG -l eastus --publisher-email [Myemail@contoso.com](mailto:Myemail@contoso.com) --publisher-name Contoso **--enable-managed-identity true**

More Info [here](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest). Could you please test the same using [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of AzCLI and let me know if you face any issues ? Awaiting your reply.
