### ISSUE TITLE
webapp: Az CLI command fails to create app service managed certificate(preview)

### ISSUE THREAD

**Issue by DeepGit01** [Azure/azure-cli#13647]
A customer has reported that Az CLI command to create app service managed certificate(preview) doesn’t work anymore. It used to work earlier. 
https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-create
https://docs.microsoft.com/en-us/cli/azure/functionapp/config/ssl?view=azure-cli-latest#az-functionapp-config-ssl-create

Customer had got error:
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Web/certificates/xxxxxxxx?api-version=2019-08-01 (Caused by ResponseError('too many 500 error responses',))
 
I tested using latest Az CLI version(2.6.0). It fails with error. The custom domain was already added to the app service.
Error:  "Hostname(Custom domain) 'xxxxxx' is not registered with app"

The difference in the error may be because of Az CLI version used by the customer and me. Not sure though. The point is even with the latest version of Az CLI, it doesn't work.

 I’m able to create the managed certificate using PowerShell and through the Azure Portal. 

Customer created the managed certificate through the Portal as a workaround. Reporting the Az CLI command issue.

**Comment by yonzhan** [comment]
app service

**Comment by zsolt-halo** [comment]
Hi!

I was the customer :)

I'll copy-paste some info here from the initial analysis I did during the troubleshooting:

I continued my research about what was causing this issue, and I think I found the reason. 
If you do not have a CNAME entry in your DNS zone, pointing to the web-app domain, the process fails.

On the GUI (Azure portal) the error message states the reason very clearly, but in the CLI you receive HTTP 500 only.

Also, another thing that will lead to confusion is that the CLI command for adding a custom domain to a function app requires you to use the awverify prefix. In contrast, if you do that, the certificate creation (the app service managed one) will fail since the eligibility check that is running before cert creations, checks for the CNAME without the awverify prefix.

This results in having to create both two CNAME records, one with awverify and one without it.

**Comment by panchagnula** [comment]
@zsolt-halo in CLI please run the command with --debug to check if you get a useful error message. let us know if that helps.

**Comment by panchagnula** [comment]
Also regarding this "Also, another thing that will lead to confusion is that the CLI command for adding a custom domain to a function app requires you to use the awverify prefix. "

which specific functionapp command are you referring to - please file a separate issue, if this is function app specific Thank you.

**Comment by panchagnula** [comment]
@zsolt-halo any updates here?

**Comment by panchagnula** [comment]
closing due to lack of response.
