### ISSUE TITLE
incorrect optional/required parameters

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13677]
for `az cdn endpoint show` the CLI states that either the Id is required or name, resource group, and profile name. 

The documentation doesn't mention the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by lsmith130** [comment]
The id, name, resource group, and profile name are all listed under optional parameters in the documentation because there is at least one situation where each of these is optional, (ie. `--ids` is optional when specifying the endpoint name, resource group, and profile name individually, and vice-versa). However, the requirement to provide one of the two sets is stated in the description of `--ids`. If you're trying to get all available endpoints, please use the command `az cdn endpoint list`.
