### ISSUE TITLE
Deployment failed. Correlation ID: c6882a90-c481-4051-9e2f-f6fd35aa595b. Internal server error.

### ISSUE THREAD

**Issue by medavamshi** [Azure/azure-cli#13727]
This is another error as well following the guide using default vnets 
az aro create --resource-group $RESOURCEGROUP --name $CLUSTER --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --client-id xxxxxxxxxxxx --client-secret XXXXXXXXXXX

Deployment failed. Correlation ID: c6882a90-c481-4051-9e2f-f6fd35aa595b. Internal server error.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/aro/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/aro/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aro

**Comment by mjudeikis** [comment]
Hey @medavamshi . This is not the repo we are monitoring constantly. If you raise issue in `Azure/ARO-RP` we will get into it faster for bugs, not questions, it this relates to service itself, not CLI,

This particular failure is because of `CSX Master Policy` failure. And few other failures. I would be reluctant to share more details here as it might be sensitive information for you. And this is not the right place to do this kind of support. 

If you raise an incident with msft support and ask it to be assigned into "Azure Red Hat OpenShift / RP" queue, we will pick it up with more details and particular polies in question here.

**Comment by medavamshi** [comment]
I actually tried to created it under the ARO , and it accidentally created it here.  Tried to delete it and couldnt find it. thank you.  Appreciate your help
