### ISSUE TITLE
Deployment failed.  invalid: custom DNS servers are not supported.

### ISSUE THREAD

**Issue by medavamshi** [Azure/azure-cli#13723]
**Resource Provider**

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
Please let us know your detailed command and error.

**Comment by medavamshi** [comment]
az aro create --resource-group $RESOURCEGROUP --name $CLUSTER --vnet /subscriptions/XXXXXXXX/resourceGroups/XXXXXXXXXXXXXXXX/providers/Microsoft.Network/virtualNetworks/XXXXXXXXXX --master-subnet nonproduction-web --worker-subnet openshift-worker --client-id XXXXXXXXXX --client-secret XXXXXXXXXXXXXX --worker-count 4 --pull-secret @pull-secret.txt

Deployment failed. Correlation ID: b114e550-a967-4590-80aa-69cf901b24ef. The provided vnet '/subscriptions/xxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxx/providers/Microsoft.Network/virtualNetworks/xxxx' is invalid: custom DNS servers are not supported.

**Comment by medavamshi** [comment]
We are trying to deploy ARO cluster to our existing vnets.  so a vnet with custom dns servers is not supported?

**Comment by medavamshi** [comment]
This is another error as well following the guide using default vnets 
az aro create --resource-group $RESOURCEGROUP --name $CLUSTER --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --client-id xxxxxxxxxxxx --client-secret XXXXXXXXXXX

Deployment failed. Correlation ID: c6882a90-c481-4051-9e2f-f6fd35aa595b. Internal server error.

**Comment by mjudeikis** [comment]
@medavamshi see https://github.com/Azure/azure-cli/issues/13727 for an answer. This looks like service support questions, and because failures are due your internal subscription policy configurations I would be reluctant to have these conversations here. Please reach out via MSFT support to the queue provided with as many details as you can and links to these issues too. And we will provide all the details via official secure support channel. Thanks!

**Comment by medavamshi** [comment]
I figured out the issue with my policy.   this can be deleted now.  Appreciate your help.
