### ISSUE TITLE
Fail when invoking "az aks get-credentials"

### ISSUE THREAD

**Issue by sshiba** [Azure/azure-cli#13735]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1184, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1120, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {}`

## Environment Summary
```
Linux-5.3.0-53-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.6.0

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by palma21** [comment]
I couldn't repro in 2.6.0

@wenwu449 could you take a look

**Comment by navba-MSFT** [comment]
@sshiba Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required keys which must be present: clusters, contexts and users. May be due to an empty section under clusters you might be facing this issue. You can also rename or delete the file and az aks get-credentials should start working again.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

This issue is open for quite sometime now. Please let us know if you still need assistance on this. Awaiting your reply.

**Comment by sshiba** [comment]
No, it can be closed. Thanks!

**Comment by navba-MSFT** [comment]
@sshiba  Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
