### ISSUE TITLE
az event-grid event-subscription list does not show all subscriptions

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-cli#13781]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.5.1 (Azure CloudShell) & 2.6.0 (local install)

**Describe the bug**
When using the following command with an Azure Storage Account not all subscriptions on the Account are included in the output.

az eventgrid event-subscription list --source-resource-id $resourceid

In my case I have a storage account that has a Logic App and Azure Function (Consumption Plan) subscription - both filtered for the BlobCreated Event.

Only the Logic App subscription appears in the command output. Even recreating the Function App connection makes no difference, despite the Function being triggered by Events published to the Topic.

**To Reproduce**

1. Create Azure Storage Account
2. Create Azure Logic App and add Subscription for Azure Storage Account BlobCreated Event.
3. Create Azure Function (C#) and add Subscription for Azure Storage Account BlobCreated Event.
4. Log into CloudShell and lookup Resource ID for Storage Account.
5. Invoke command to list subscriptions with this Resource ID.

**Expected behavior**

All Subscriptions for the supplied Resource ID are displayed.

**Environment summary**

Using Azure Cloud Shell (2.5.1) and the local install (2.6.0) is running on Windows 10.

**Additional context**

All components involved were moved between Resource Groups in the same Azure Subscription after the Event Grid subscriptions were setup. The recreation of the Functions subscription was done after the move but did not result in a change in behaviour.

The solution works fine (new Events trigger both the Logic App and the Function), so this problem appears to be tied to enumerating subscriptions using the command.

Same behaviour occurs when using PowerShell Cmdlets.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by ahamad-MS** [comment]
Thanks for reporting this issue @sjwaight   .. Can you please provide additional info for us to help investigate this issue:

1. Can you please provide us the out of az version (This allows us to determine if you are using GA'ed CLI or CLI extension).

2. If you not using Event Grid extension, will you be able to use latest CLI event grid extension (0.4.9)? and see if this repro the issue?

3. Can you please provide when the move was done for the resources? Date/Time?

4. Can you please provide when the list operation was done?

4. Please provide  full information about:
a. The Azure Sub Id
b. Resource Group
c. Event subscriptions names expected to be listed?
d. Region
e. Date/Time for list and move operation.

If you prefer to share this info privately, please either email me directly at (ahamad@microsoft.com) or (Ask Event Grid <askgrid@microsoft.com>)

Thanks

**Comment by sjwaight** [comment]
Dropped you an email with details (in case anyone else is following this thread).

**Comment by ahamad-MS** [comment]
Hello @sjwaight 

I followed up with the subId and resources details you provided and I believe the issue is due to the fact that you are using old CLI module. Here is the follow up info from the email:

===================================
Can you please provide the output of this command [az version] in shell.azure.com? 

It seems you are using the older CLI module or CLI Extension. The –source-id parameter is now deprecated and we have multiple destination types (including function as destination) where they are available only in latest CLI extension. The event subscription for Azure Function destination will be filtered out if old CLI clients (using older API versions) are used to list the resources.

To confirm, please do the following steps:

•	Remove any existing eventgrid extension, if any:
$ az extension remove -n eventgrid
•	Add new eventgrid extension:
$ az extension add -n eventgrid
•	Make sure the new version is 0.4.8 or higher
$ az extension list
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.8"
  }
]


Please retry the command az eventgrid event-subscription list with –source-resource-id and let me know if this fixes the issues.

Additional points:
1.	We are in the process of adding support for all destination types to mainstream CLI and there will be no need to CLI Extension in near future.
2.	The system topic resource is a new resource we added as part of 2020-04-01-preview and we just released the portal support for it.

HTH
Thanks
Ashraf

**Comment by sjwaight** [comment]
Noting here that installing the extension and not just using the currently shipped CLI capabilities has resolved my issue. As per Ashraf's feedback this will be fixed completely in a future CLI release and until then ensure you have the extension installed using

```
az extension add -n eventgrid
```
