### ISSUE TITLE
az ad command group for role is missing

### ISSUE THREAD

**Issue by avbhaskar** [Azure/azure-cli#13838]
command group for managing ad roles is missing from Azure CLI.  It would be really useful to have a command group like so:
<h1>az ad role: Manage Azure AD roles </h1>
<h2>commands:</h2>
list: List of roles in in Azure Active Directory
create: Create a custom role in Azure Active Directory
delete: Delete a custom role in Azure Active Directory
enable: Enable in Azure Active Directory
show: show details of role in Azure Active Directory
<h2>subgroups:</h2>
<h3>assignment: </h3> 
create: create new assignment for a role in in Azure Active Directory - object-id, user, group, principal
list: list assignments for a role in in Azure Active Directory
delete: Delete a assignment from role in in Azure Active Directory
show: Show details of a role assignment in Azure Active Directory

Equivalent Powershell module AzurAD has commands like so:
Add-AzureADDirectoryRoleMember
Enable-AzureADDirectoryRole
Get-AzureADDirectoryRole
Get-AzureADDirectoryRoleMember
Get-AzureADDirectoryRoleTemplate
Remove-AzureADDirectoryRoleMember

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa048db2-b924-889c-c105-2a676714b0ee
* Version Independent ID: 5774d883-1b16-d4b9-8d61-4694af8d9341
* Content: [az ad](https://docs.microsoft.com/en-us/cli/azure/ad?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by yungezz** [comment]
hi @arrownj  pls evaluate the work and let's sync.

**Comment by jiasli** [comment]
The equivalent of Azure CLI `az ad` command group is [`AzAD`](https://docs.microsoft.com/en-us/powershell/module/az.resources/?view=azps-7.3.2#active-directory) from Azure PowerShell. `AzureAD` on the other hand is a module developed by Azure Active Directory.

`az ad` commands are designed and implemented to assist integrating AAD with Azure, instead of as a fully functioning client to interact with AAD. You may use `az rest` with Microsoft Graph API to manipulate those properties. See https://github.com/Azure/azure-cli/issues/12946 for examples.
