### ISSUE TITLE
Remove doc for command `az network application-gateway frontend-ip update` because it is not works.

### ISSUE THREAD

**Issue by fiftin** [Azure/azure-cli#13852]
Command:

`az network application-gateway frontend-ip update`

not working for public ip address. Issue https://github.com/Azure/azure-cli/issues/4133 created in Aug 2017, but M$ never fixed it.

Please remove from docs if it is not works!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22983291-ef1b-2d38-a378-a87533f9167f
* Version Independent ID: ed056af3-1e62-b953-39ea-6e968f47ce14
* Content: [az network application-gateway frontend-ip](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/frontend-ip?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by subhasishdc** [comment]
@MyronFanQiu @tjprescott : Seeing this same issue too. Issue https://github.com/Azure/azure-cli/issues/4133 was created previously for this. It was closed without removing it from the `az network application-gateway frontend-ip update --help` section or the documentation since the service may change in future to permit this behavior. 

Is there any update on the future roadmap of the service to support this? If not, it would be best to remove it from the `--help` section as well as from the documentation to avoid confusion.

**Comment by subhasishdc** [comment]
PR (https://github.com/Azure/azure-cli/pull/14098) has been merged to deprecate the `--public-ip-address` parameter.

**Comment by MyronFanQiu** [comment]
Thanks for @subhasishdc's contribution. Closed this issue since it's solved.
