### ISSUE TITLE
az storage cors add returns no success status

### ISSUE THREAD

**Issue by Tim-Hodge** [Azure/azure-cli#13971]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az storage cors add` command does not return json to indicate success, which is different to the majority of other az cli operations.

**To Reproduce**
az storage cors add ...

**Expected behavior**
Expect a json response to indicate success; ideally an object representing the added CORS rule.

**Environment summary**
Windows 10 2004 19041.329
```az --version

azure-cli                          2.7.0

command-modules-nspkg              2.0.3
core                               2.7.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.8
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\tim\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)
```

**Additional context**
Command is not idempotent - unsure whether duplicate CORS rules should be allowed?

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @Tim-Hodge, thanks for your feedback. It is because there is no response in SDK design. In addtion, there is only SDK to get/list all cors in a storage account not specific cors properties.

Adding additional operations will increase the cost to maintain in CLI and it may cause breaking change for existing customers if we change the response.

Considering above concern and limited bandwidth, it is hard to add such support in current Azure CLI. To see if the add operation works, please use `az storage cors list`. In addition, it should mean success for each command when no error occurs.
