### ISSUE TITLE
Unicode character corrupts .azure json files

### ISSUE THREAD

**Issue by cchildress** [Azure/azure-cli#13980]
**Describe the bug**
Trying to create a subscription policy with `az policy definition create` fails with `Expecting value: line 1 column 1 (char 0)` (I suspect this will be a problem with multiple azcli commands).

In looking around for where there might be a config file with invalid data at the start of the file I looked at the json files in `~/.azure` and found that `az.json`, `az.sess`, and `azureProfile.json` all contain `<U+FEFF>` as the first character in the files. This isn't visible with `cat` or `vim`, but does show in `less` (I'm on version 487).

**To Reproduce**
1. `rm -rf ~/.azure/*`
2. `az login`
3. `less ~/.azure/az.json`

**Expected behavior**
These configuration files should be valid json

**Environment summary**
azcli version 2.7.0 on Ubuntu 18.04.
Python2 is 2.7.17 and Python3 is 3.6.9.

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@cchildress Hi, could you please show me the specific parameters you used? please add --debug to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
As I communicated with @cchildress offline, the feedback was as follows：
> I did rm ~/.azure/* to clear the azure dir and then ran `az login`. Go back to the azure directory and the config files have unicode in them. Here's my az.json file for example: `<U+FEFF>`{}

This issue seems to be related to `az login`, @jiasli could you please help to have a look~

**Comment by jiasli** [comment]
`<U+FEFF>` is the [Byte Order Mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark). **UTC-8 with BOM** is used as the encoding method since the dawn of Azure CLI (516f4faf9173fd32efdbbf708ba4ceb9ada28b3b):

https://github.com/Azure/azure-cli/blob/026016e7bf205bfa378f79351f99c9d536efa3d5/src/azure-cli-core/azure/cli/core/_session.py#L38

See the Python doc [Encodings and Unicode](https://docs.python.org/3/library/codecs.html#encodings-and-unicode) for the detailed description of `utf-8-sig`.

But according to [`man less`](https://man7.org/linux/man-pages/man1/less.1.html), `less` can't handle UTF-8 with BOM and displays `<U+FEFF>`. However, this won't be a problem in pipelines, as most programs can handle it correctly, like `jq` and `more`:

```
$ jq ".subscriptions" azureProfile.json 
[
  {
    "id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "user": {
      "name": "45ee948b-9214-4d23-9a52-1a641c7c8009",
      "type": "servicePrincipal"
    },
    "isDefault": true,
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "environmentName": "AzureCloud"
  }
]

$ more accessTokens.json 
[{"servicePrincipalId": "45ee948b-9214-4d23-9a52-1a641c7c8009", "servicePrincipalTenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a", "accessToken": "4a89108f-2c01-4f94-a5fa-33d9400ee7ad"}]
```

Maybe we can use `utf-8` so that BOM is not added to the file? @achandmsft @chenlomis
