### ISSUE TITLE
Deploy container instances into an Azure virtual network

### ISSUE THREAD

**Issue by Darsan04** [Azure/azure-cli#14017]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
'HTTPError' object has no attribute 'error'
Traceback (most recent call last):
cli/command_modules/container/custom.py, ln 251, in _get_resource
    resource = client.get(resource_group_name, *subresources)
network/v2018_08_01/operations/_subnets_operations.py, ln 182, in get
    raise exp
msrestazure.azure_exceptions.CloudError: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/c2d714ab-8bdd-4f92-bd1e-c7f23834dccc/resourceGroups/Demo/providers/Microsoft.Network/virtualNetworks/Demo-vnet%2Fdefault/subnets/Demo-Vnet?api-version=2018-08-01

...

cli/command_modules/container/custom.py, ln 254, in _get_resource
    if ex.error.error == "NotFound" or ex.error.error == "ResourceNotFound":
AttributeError: 'HTTPError' object has no attribute 'error'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create --name {} --resource-group {} --image {} --vnet {} --vnet-address-prefix {} --subnet {} --subnet-address-prefix {}`

## Environment Summary
```
Linux-4.15.0-106-generic-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
container

**Comment by navba-MSFT** [comment]
@Darsan04 Apologies for the late reply. If you want to deploy ACI to a new VNET then follow [this](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet#deploy-to-new-virtual-network). If you want to deploy to existing VNET then follow [this](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet#deploy-to-existing-virtual-network). Please use the most [recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the Azure CLI. This issue is open for quite sometime now. Please let me know if you need any further assistance on this. Awaiting your reply.
