### ISSUE TITLE
Missing Azure CLI features for Azure AD App registrations

### ISSUE THREAD

**Issue by damienbod** [Azure/azure-cli#14086]
The signInAudience, groupMembershipClaims, accessTokenAcceptedVersion cannot be set, updated. For example, it is not possible to set the value AzureADandPersonalMicrosoftAccount for the signInAudience. 

## Missing Azure CLI features for Azure AD App registrations

- Not possible to set all 4 values of the `signInAudience` property
- Not possible to assign the Application to the Azure AD group (Or not documentated)
- Cannot update the `groupMembershipClaims` to one of the 3 values
- It is not possible to create return URLs of type SPA
- `accessTokenAcceptedVersion` cannot be set
- `oauth2Permissions` gets a default value which is not needed

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
`az ad` commands are designed and implemented to assist integrating AAD with Azure, instead of as a fully functioning client to interact with AAD. You may use `az rest` with Microsoft Graph API to manipulate those properties. See https://github.com/Azure/azure-cli/issues/12946 for examples.

**Comment by damienbod** [comment]
Maybe you should remove the **az ad app update** and **az ad app create**  if it is not possible to use these or update the docs to recommend az rest. 

https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest

**Comment by jiasli** [comment]
`az ad app update` and `az ad app create` do work for basic application operations. `az rest` is purely for advanced operations out of the scope of the current Azure CLI implementation. 

We plan to migrate them to use Microsoft Graph instead in the future, but now many customers are still using them.

**Comment by damienbod** [comment]
So Azure CLI cannot be used to create Azure APP registrations, Graph API should be used, correct? Some of the missing featurea are basic operations. Using `az rest` (Graph API call) together with `az ad app update` and `az ad app create` in an automated process does not work together.

**Comment by jiasli** [comment]
Azure CLI **can** be used to create Azure APP registrations. It internally uses AD Graph (we plan to migrate to MS Graph).

Using `az rest` (Graph API call) together with `az ad app update` and `az ad app create` in an automated process **do work together**.

You can use `az ad app update` and `az ad app create` for basic operations and `az rest` for advanced operations. 

If you have a repro, please kindly share the steps.

**Comment by damienbod** [comment]
@jiasli  Thanks for you answer. 

I have a basic example here:

https://damienbod.com/2020/06/22/using-azure-cli-to-create-azure-app-registrations/

scripts:

https://github.com/damienbod/AzureAD-Auth-MyUI-with-MyAPI/tree/master/CreateAppRegistrations

When using `az rest` after the `az ad app`, it does not work for n-seconds. If I wait a small amount of time before calling the `az rest` graph api call, then it will work.

A basic use case for me is an Azure App Regirstation with a SPA redirect URL and `"signInAudience" : "AzureADandPersonalMicrosoftAccount"`

Greetings Damien

**Comment by SvenHamers** [comment]
@damienbod 

I use something like this for registering spa url, works fine all the times.
https://gist.github.com/SvenHamers/880c9a8e5a588ccfcbc69652bfb31cef

**Comment by jiasli** [comment]
> When using `az rest` after the `az ad app`, it does not work for n-seconds. If I wait a small amount of time before calling the `az rest` graph api call, then it will work.

This is the expected behavior of AAD service that the application is not immediately available after creation. The AAD server is doing replication/propagation during the "n-seconds". As AAD Graph API doesn't support [async operations](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations) like ARM to query the creation result, your script needs to 

- sleep for a while, or
- retry the operation until it succeeds. 

Azure CLI also uses this **retry** approach in `az ad sp create-for-rbac`:

https://github.com/Azure/azure-cli/blob/5b644cffa190e4b5aa397a2f10151f1d51adf9aa/src/azure-cli/azure/cli/command_modules/role/custom.py#L1370-L1387

**Comment by stewartadam** [comment]
@jiasli imho this issue should not be closed, it is an active issue with the Azure CLI:
1. The `az ad app update` has a `--set` flag that fails on certain values or properties
2. The docs and helpstring don't mention what the "complex" unsupported scenarios are

This should at least be documented, and while I understand AD Graph vs MS Graph is the technical reason behind the limitation, from a user perspective that doesn't matter -- the flag is broken and can't automate the properties available.

**Comment by jiasli** [comment]
@stewartadam, `--set` won't work without the underlying API support. AD Graph API simply doesn't have those functionalities. 

The available properties that Azure CLI supports is described in the [AD Graph 1.6 REST spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json).

The plan to migrate to MS Graph is being tracked at https://github.com/Azure/azure-cli/issues/12946. However we currently haven't started working on it given we have other priorities like MSAL integration. Thanks for your understanding.

**Comment by stewartadam** [comment]
> @stewartadam, --set is a generic operation and relies on the underlying API to work. In other words, it won't work without the underlying API support. AD Graph API simply doesn't have those functionalities.
> The available properties that Azure CLI supports is described in the [AD Graph 1.6 REST spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json).

Thanks for the explanation, although this is why I'm this issue should not be closed: from a user-facing perspective this `--set` feature *is* broken. Internal technical debt and AD Graph schema specs aren't something we should expect all users of `az ad` to be familiar with.

> The plan to migrate to MS Graph is being tracked at #12946. However we currently haven't started working on it given we have other priorities like MSAL integration. Thanks for your understanding.

In the interim I would suggest documenting this issue, certainly in the error responses if someone tries to set an unsupported value.

**Comment by jiasli** [comment]
Hi @stewartadam, I think the topic has diverged. 

> 1. The `az ad app update` has a `--set` flag that fails on certain values or properties

I tried to update `groupMembershipClaims` and it is working as expected. 

```pwsh
> az ad app update --id b9df9246-f8c2-4505-8556-814b7ecc95a9 --set groupMembershipClaims=SecurityGroup

> az ad app show --id b9df9246-f8c2-4505-8556-814b7ecc95a9 | Select-String groupMembershipClaims

  "groupMembershipClaims": "SecurityGroup",
```

Could you create a new issue and provide the actual command with `--set` that fails for you? We can see how we can improve the error message.

**Comment by stewartadam** [comment]
Hi @jiasli, the topic is as described by OP - many of the new App Registration experience features are not available through the CLI. I also cannot repro the issue with groupMembershipClaims, but the other properties mentioned fail in various different ways, for example signInAudience:
```
# works, property is not read only
$ az ad app update --id 5971ddef-6bb5-49b3-8175-94c50ad72506 --set signInAudience=AzureADMyOrg

# fails
$ az ad app update --id 5971ddef-6bb5-49b3-8175-94c50ad72506 --set signInAudience=AzureADandPersonalMicrosoftAccount
Property 'signInAudience' is read-only and cannot be set.
```

accessTokenAcceptedVersion:
```
az ad app update --id 5971ddef-6bb5-49b3-8175-94c50ad72506 --set accessTokenAcceptedVersion=2
Property 'accessTokenAcceptedVersion' not found on root. Send it as an additional property .
One or more property values specified are invalid.
```

As you mention this is due to AD vs MS graph under the hood, which if that's going to be accepted tech debt due to other priorities then error messages need to be better presented/documented:

> from a user-facing perspective this --set feature is broken. Internal technical debt and AD Graph schema specs aren't something we should expect all users of az ad to be familiar with.

**Comment by jiasli** [comment]
`Property 'signInAudience' is read-only and cannot be set.` is returned by AD Graph API when setting `signInAudience`, instead of Azure CLI. 

```
> az ad app update --id b9df9246-f8c2-4505-8556-814b7ecc95a9 --set signInAudience=AzureADandPersonalMicrosoftAccount --debug

msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/applications/502912d6-eda3-4eb0-a3e1-5918dba268c3?api-version=1.6'
msrest.http_logger : Request method: 'PATCH'
msrest.http_logger : Request body:
msrest.http_logger : ... "signInAudience": "AzureADandPersonalMicrosoftAccount", ...

msrest.http_logger : Response status: 400
msrest.http_logger : Response content:
msrest.http_logger : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Property 'signInAudience' is read-only and cannot be set."},"requestId":"6ca4e14c-7f9a-4bba-a40d-f78bd5bee197","date":"2020-08-19T03:28:24"}}
```

Same for `accessTokenAcceptedVersion`

```
> az ad app update --id b9df9246-f8c2-4505-8556-814b7ecc95a9 --set accessTokenAcceptedVersion=2 --debug

msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/applications/502912d6-eda3-4eb0-a3e1-5918dba268c3?api-version=1.6'
msrest.http_logger : Request method: 'PATCH'
msrest.http_logger : Request body:
msrest.http_logger : ... "accessTokenAcceptedVersion": 2...

msrest.http_logger : Response status: 400
msrest.http_logger : Response content:
msrest.http_logger : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"One or more property values specified are invalid."},"requestId":"a34ff994-1883-4e6b-a750-885d9a2deb55","date":"2020-08-19T03:31:24"}}
```

So these issues should rather go to AAD support and service team. 

**It is not very practical for Azure CLI to know _in advance_ which property is support by AD Graph API or not.** `--set` is just a generic operation, without caring about the actual business logic. We can't blame a REST client for not knowing the business logic, right?

Without the migration to MS Graph, there is no elegant way to handle such scenario. That's why we recommend using `az rest` instead.

**Comment by jiasli** [comment]
> So why not use the AD Graph schema?

If the the schema you are talking about is the [application manifest](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest), unfortunately, this is **not an information source for Azure CLI** - **REST spec is the only source which CLI relies on**, as AAD service doesn't provide a JSON version of the schema (manifest) that can be consumed by SDKs like Azure CLI.

Besides, the AAD document [Azure Active Directory app manifest](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest) also mentions:

> For more info on the Application entity and its schema, see the [Graph API Application entity documentation](https://docs.microsoft.com/en-us/graph/api/resources/application).

This also indicates REST spec should be the only source, but we currently don't even have a REST spec for MS Graph yet, not to mention MS Graph SDK. That's why we can't move onto MS Graph in the near future.  

As for

> Ultimately, if passing values outside AD Graph are not supported then make that clear in the responses.

This is because there is **no way for Azure CLI to know whether a key/value is supported by AD Graph or not**. It is the responsibility of AD Graph to provide a more intuitive and instructive error message.

**Comment by Console32** [comment]
@jiasli Can you clarify how to do this using the REST API? 
I can not change the signInAudience using the azure ad graph api. The calls always fails with `ValidationError: Bad Request`

I created a question [here](https://stackoverflow.com/questions/64335377/setting-signinaudience-using-azure-graph-api-invalid-json). Basically the API tells me that the JSON is invalid. Is there a working example anywhere how to set the signInAudience?

**Comment by jiasli** [comment]
> @jiasli Can you clarify how to do this using the REST API?
> I can not change the signInAudience using the azure ad graph api. The calls always fails with `ValidationError: Bad Request`
> 
> I created a question [here](https://stackoverflow.com/questions/64335377/setting-signinaudience-using-azure-graph-api-invalid-json). Basically the API tells me that the JSON is invalid. Is there a working example anywhere how to set the signInAudience?

This is a separate issue. Let's work on https://github.com/Azure/azure-cli/issues/15512.
