### ISSUE TITLE
Executing az cli command that references a RG with resource in zonal mode should succeed even when zone is down

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14121]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

During canary DR drill, when one of the zone (zone 3) was down, we used the below az command which did not return even after waiting for several minutes.
##Get list of VMs tagged for redis/sentinel (mys)
vmspri=$(az vm list -d -g ${fo_prirg} --query "[?tags.role == '${fo_role}' ].id" --output tsv)
vmssec=$(az vm list -d -g ${fo_secrg} --query "[?tags.role == '${fo_role}' ].id" --output tsv)
vmsdum=' '
vms=${vmspri} 
vms+=${vmsdum}
vms+=${vmssec}
echo $vms
The reason for the hang is the az cli is referring to resource group (fo_prirg = hadr-prizone) that has some virtual machines in it which are deployed to zone 3 that went down as part of the DR drill.
So our understanding is querying a resource group that has resources in it in zonal mode and if that zone goes down the query fails to return.

In canary DR drill, when one of the zone (3) went down, running the below az commands does not return for several minutes and thus impacted the failover operations.

##Get list of VMs tagged for redis/sentinel (mys)
vmspri=$(az vm list -d -g ${fo_prirg} --query "[?tags.role == '${fo_role}' ].id" --output tsv)
vmssec=$(az vm list -d -g ${fo_secrg} --query "[?tags.role == '${fo_role}' ].id" --output tsv)
vmsdum=' '
vms=${vmspri} 
vms+=${vmsdum}
vms+=${vmssec}
echo $vms

Observation: It looks -d is the cause for the command taking longtime and resulting in timeout but need guidance and ability to execute az commands on VM that needs extended properties of VM during the zone or regional failover times. 

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
copied from https://dev.azure.com/AZGlobal/Azure%20Global%20CAT%20Engineering/_workitems/edit/24516/?triage=true for tracking purpose

**Comment by houk-ms** [comment]
The command `az vm list -d` will first call the `list` api to list all the vms, and then call the `instance view` api to get the details of each vm.

I checked that it works well if we deallocate or delete some vms manually in a certain Zone and then apply the `az vm list -d` command. 

So, the error occurs due to the unexpected failure of certain zone, which may cause the service-side behave unnormally. We should 

- Find the service team to verify the service behavior when Zone goes down.

- Find a way to simulate the Zone failure behavior if we want to verify it from CLI side.

**Comment by houk-ms** [comment]
As we sync on email thread, debug info needs to be recorded before we can take further investigations. This issue can be repoened after we have the error details.
