### ISSUE TITLE
az graph query -o table missing columns in output

### ISSUE THREAD

**Issue by doherty100** [Azure/azure-cli#14197]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az graph query command using -o table option is missing columns from output that are included when using other output formats such as -o tsv.

**To Reproduce**
* Write your query, e.g.:
`resources
| project
    id,
    type 
| summarize resourceCount=count() by type
| order by type asc`
* Save your query to a file e.g. `resource-summary.kql`
* Run your query using `-o table`, e.g.:
`az graph query -q "$(<resource-summary.kql)" --first 5000 -o table > resource-summary.kql.txt`
* Examine results, note that *type* column is missing.
* Run your query again using `-o tsv`, e.g.:
`az graph query -q "$(<resource-summary.kql)" --first 5000 -o tsv > resource-summary.kql.txt`
* Examine results, note that *type* column data is included.
**Expected behavior**

All columns in results should be included in -o table output.

[resource-summary.kql.table.txt](https://github.com/Azure/azure-cli/files/4866859/resource-summary.kql.table.txt)
[resource-summary.kql.tsv.txt](https://github.com/Azure/azure-cli/files/4866860/resource-summary.kql.tsv.txt)
**Environment summary**

* OS: Ubuntu 18.04.4 LTS on WSL 1
* Azure CLI Version: 2.8.0
* Azure CLI Install method: `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`
* Azure CLI resource-graph extension version: 1.1.0

**Additional context**

See file attachments for actual output.

**Comment by yonzhan** [comment]
add to S173

**Comment by yonzhan** [comment]
resource graph

**Comment by snaheth** [comment]
Nice catch @doherty100! Looks like this happens because the ``--out table`` does not produce the expected behavior in the CLI code. We'll update the ARG extension code to account for newer API changes and we'll make sure the behavior for this scenario is correct.

**Comment by ankitsrao** [comment]
Hi Team,

Just following up on this ticket as this issue still seem to persist with the latest az cli module. 
Refer version details below:
![image](https://user-images.githubusercontent.com/41519748/123402901-d8f2da80-d5c5-11eb-935e-b2408b909bd0.png)

The command works perfectly fine with --output json but fails when --output table is used. Screenshot below:
![image](https://user-images.githubusercontent.com/41519748/123403105-0b043c80-d5c6-11eb-9571-978de5feaac5.png)

Also, I happend to have an old az cli version [ v2.7.0 ] on my local machine, where the command runs perfectly fine with --output table. Screenshot below:
![image](https://user-images.githubusercontent.com/41519748/123403350-51599b80-d5c6-11eb-8775-e597c05db2d5.png)

Do we have any ETA for this fix, and any possible workaround like downgrading the az-cli version [ I may be able to downgrade the azcli version on my local machine, I'm looking out for similar version downgrade solution for Azure Cloudshell for the time being]

Thanks,

**Comment by fenwickt** [comment]
Hi ankitsrao,

Sorry for the delayed reply. The first part of your question about id and type columns are not printed in table format is actually by design of Azure CLI. Please find the docs and the workaround [in the 'note' section](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli#table-output-format). Looks like you're already using another workaround of renaming type column to a different name within the graph query itsef: "`project resource=type`".

Regarding your 2nd question of the newer az cli version, the output of az graph cmdlet is changed for the pagination purposes to return a 'skip_token', 'count; and 'total_records' properties along with the 'data'. So output of --table format is actually showing the top level properies which are now not your custom data properties but the default ones that I just mentioned.

As a workaround please try using [JMESPath extension](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli). Here is an example of rewriting your query with the newest az cli version:
`az graph query -q " summarize count() by type | where type =='microsoft.compute/virtualmachines' | project resource=type, total=count_ | order by total desc" --query 'data[].{resource:resource, total:total}' -o table`

To downgrade the resource-graph extension please try to remove it and add with the older version:
```
az extension remove --name resource-graph
az extension add --name resource-graph --version 1.1.0
```
