### ISSUE TITLE
Unable to use MSI on Ubuntu

### ISSUE THREAD

**Issue by anduran** [Azure/azure-cli#14347]
## Describe the bug
Hi,

I'm following this guide: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication-managed-identity#example-2-access-with-a-system-assigned-identity on a MSI enabled HDInsight cluster. 

I have written my own python code to access AKV today, so I know MSI works on this machine. However, the CLI to auth into ACR is broken.

**Command Name**
`az login`

**Errors:**
```
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 703, in reraise
    raise value
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Expected Behavior
I should able to authenticate as the machine.

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
add to S173

**Comment by cpdohert** [comment]
I am having the same problem, albeit in a different context.

I have two Ubuntu VMs hosted in Azure: "Production" and "Staging".  Each VM is in a dedicated Subscription.  Both VMs were instantiated with the same terraform 0.12 script.  Each VM has its own system-assigned identity.

There is a single ACR in the Production subscription.  Both the Production and Staging VM identities have been granted the AcrPull role assignment on the ACR.  Note that this means the Staging VM lives in the staging Subscription, but its identity has a role assignment on a resource in a different subscription. This may be relevant.

Each VM has had the Azure Pipelines Environment agent installed on it following the instructions here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops
The agent has been installed under, and runs as, the default user created for the VM.

I have a multi-stage Azure Pipeline that targets the VM resources as described here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#target-an-environment-from-a-deployment-job
The pipeline runs a short script that downloads and runs a single container on the VM.  The first line in that script is `az login --identity`

In Production, everything runs correctly.  The pipeline executes the individual steps in the script without issues.

In Staging, if I log in to the VM and run the steps in the short script manually, everything runs correctly.  If I run `az login --identity`, the command returns the JSON describing the account context successfully, as expected.
If I run the short script via the agent, the very first line `az login --identity` consistently throws this exception:

`
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 493, in get_current_account_user
    active_account = self.get_subscription()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 502, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 57, in _decorator
    val = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 426, in _get_user_azure_id
    return _get_profile().get_current_account_user()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 495, in get_current_account_user
    raise CLIError('There are no active accounts.')
knack.util.CLIError: There are no active accounts.

Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 436, in _get_azure_subscription_id
    return _get_profile().get_subscription_id()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 519, in get_subscription_id
    return self.get_subscription(subscription)[_SUBSCRIPTION_ID]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 502, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

Command ran in 1.116 seconds (init: 0.076, invoke: 1.040)
`

**Comment by cpdohert** [comment]
I tried this with a user-assigned managed service identity instead:

Run on the Staging VM by logging in directly and executing `az login --identity --username <objId>`: works correctly, JSON returned.

Run on the Staging VM under the Azure Pipelines Environment agent:
`Failed to connect to MSI, check your managed service identity id.`

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/13987

Could you follow [Get a token using CURL](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-curl) to get an access token directly with `curl` instead of `az`?

If you are receiving an error using `curl`:

```json
{"error":"invalid_request","error_description":"Identity not found"}
```

this suggests that Managed Identity is not turned on. Please see these docs on managed identity:

- [Configure managed identities for Azure resources on an Azure VM using Azure CLI](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm)
- [Sign in with a managed identity](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-with-a-managed-identity)

If you encounter difficulties while setting up managed identity. You may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) and a support engineer will help you with it.

**Comment by cpdohert** [comment]
@jiasli You've been called out elsewhere for copy-pasting this onto open issues without actually reading the description of the faulting behaviour.

To summarize: both @anduran and I have the same behaviour: a VM or cluster where managed identity **is** set up and working correctly, but where the AzureCLi cannot authenticate properly.

I'll allow @anduran to elaborate, but I'll reiterate my issue here:

On the "Staging" VM, logging in via ssh and running `az login --identity` **or** the `curl` command works, and returns the proper authentication response.
Running either the `az login --identity` or `curl` commands via an Azure DevOps Pipelines Environment agent causes either an exception to be thrown (`az login`) or the error `{"error":"invalid_request","error_description":"Identity not found"}` to be returned (`curl`).

I cannot reproduce this behaviour on the "Production" VM, where authenticating with the  system-assigned managed identity works correctly either manually or via the agent.

The system-assigned managed identity is set up correctly.  It **must** be, or else manually running `az login --identity` when logged in via SSH would not successfully authenticate.

On a related note, if the error returned when a managed identity does not exist is well known, why is the AzureCLI throwing an exception instead of a meaningful error message and a graceful exit?

**Comment by anduran** [comment]
@cpdohert I need to make an important distinction. My issue was with an HDI cluster, which nodes do use Ubuntu. But these cases are completely separate, because [as I learned afterwards] HDI implements MSI in an unorthodox way.

Long story short, after talking with a CSS I understood what the issue was and accepted that at least for HDI this wouldn't work and moved to other alternatives for auth.

I don't really know about VMs case, as it sounds like it should work so I will let @jiasli answer that one, just wanted to be clear that from the HDI support side, I consider this one closed :)

**Comment by jiasli** [comment]
@cpdohert I understand you are having problems with Managed Identity. I am sorry for the inconvenience caused. 

However, as I commented in https://github.com/Azure/azure-cli/issues/14587#issuecomment-666364865, Azure CLI is just a client-side tool like `curl`. If `curl` also reports the error `{"error":"invalid_request","error_description":"Identity not found"}`, that indicates there is some problem on the agent:

> Running either the `az login --identity` or `curl` commands via an Azure DevOps Pipelines Environment agent causes either an exception to be thrown (`az login`) or the error `{"error":"invalid_request","error_description":"Identity not found"}` to be returned (`curl`).

In that case, you may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to have a support engineer help you take a look from back-end or have a remote session. I don't have the permission to access your resources or set up a remote sessions. Thank you very much for your understanding.  

------

As for 

> On a related note, if the error returned when a managed identity does not exist is well known, why is the AzureCLI throwing an exception instead of a meaningful error message and a graceful exit?

This is a very nice suggestion. I will draft a PR to improve the error message of course.

**Comment by jiasli** [comment]
I will improve the error message in the [Azure Identity Integration](https://github.com/Azure/azure-cli/labels/Azure%20Identity%20Integration) process.

Meanwhile, if you are still facing issue getting an access token with Azure CLI or `curl`. You may reach out to customer support to troubleshoot on the machine-side.
