### ISSUE TITLE
Unable configure kubectl after creating a AKS cluster

### ISSUE THREAD

**Issue by sivaramsk** [Azure/azure-cli#14445]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.8/site-packages/six.py, ln 703, in reraise
    raise value
...
cli/command_modules/acs/custom.py, ln 3259, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path, overwrite_existing, context_name)
cli/command_modules/acs/custom.py, ln 1183, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1119, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.4
Installer: HOMEBREW

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
aks

**Comment by sivaramsk** [comment]
I deleted the ~/.kube/config and retried the command and it worked as expected. The issue for me is resolved, I guess it needs a --overwrite flag.

**Comment by navba-MSFT** [comment]
@sivaramsk Apologies for the late reply. Thanks for sharing an update on this. You can use _--file_ or _--overwrite-existing_ parameters with [az aks get-credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials). Hope this helps. Since this issue is resolved now, we will proceed with closure. If you need any further assistance on this, please feel free to reopen this github thread. We would be happy to help.
