### ISSUE TITLE
Webapp:az webapp config access-restriction show - broke on powershell

### ISSUE THREAD

**Issue by klemenberti** [Azure/azure-cli#14469]
**Describe the bug**
az webapp config access-restriction show when used with powershell hangs without response.

**To Reproduce**
az webapp config access-restriction show --resource-group group --name name -o json | ConvertFrom-Json
or
$var=az webapp config access-restriction show --resource-group group --name name

**Expected behavior**
List of rules should be returned.

**Environment summary**
azure-cli                          2.9.1
command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

PSVersion                      5.1.19041.1

MSI - Windows 10 Powershell

**Additional context**
Same behaviour with powershell 7.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
This is because in Powershell the pipe character (|) has special meaning and the parsing on Powershell is different. See this 
[https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues](url)
to know how to escape character to Use CLI commands in Powershell. In general the recommendation is to Use CLI commands with Bash & use azure-powershell commands if you are using Powershell. Thanks!
