### ISSUE TITLE
Validation of resource group name has a bug!

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14481]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

```
> az group show -g '""'
validation error: Parameter 'resource_group_name' must have length greater than 1.
```

Resource group name can be one character. The message misleads users.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
add to S174

**Comment by zhoxing-ms** [comment]
This is a issue related to `msrest`, I have opend a issue on their repo: https://github.com/Azure/msrest-for-python/issues/219

**Comment by qwordy** [comment]
It is not a feature request. It is an error in output. @houk-ms

**Comment by RakeshMohanMSFT** [comment]
@qwordy This is fixed with valid error message now. 
az group show -g '""'
(InvalidResourceGroup) The provided resource group name '''' has these invalid characters: ''''. The name can only be a letter, digit, '-', '.', '(', ')' or '_'.
Code: InvalidResourceGroup
Message: The provided resource group name '''' has these invalid characters: ''''. The name can only be a letter, digit, '-', '.', '(', ')' or '_'.
