### ISSUE TITLE
Error text verbiage while creating a new cosmosdb using Azure CLI

### ISSUE THREAD

**Issue by avanishkdev** [Azure/azure-cli#14627]
I was trying to create a azure comosdb using CLI. Got it error a few times , but was not able to identify what the issue was. Syntactically looked like the key value pairs in locations is good. After reviewing it several times identified that it was not the format thats incorrect but  one of the property name itself was incorrect,

![image](https://user-images.githubusercontent.com/66087777/89199003-f79a4e00-d57b-11ea-9977-4b993e13c3d1.png)

Would it be possible to display a different error message for this , something like  "Unknown property name {propertyname}". It would have been easier to debug.

![image](https://user-images.githubusercontent.com/66087777/89199182-30d2be00-d57c-11ea-8bef-218c40e8b199.png)

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Hey @avanishkdev thanks for your feedback. We will investigate further and decide if that is possible. I will update here in sometime

**Comment by MehaKaushik** [comment]
Hi @yonzhan do you know if the CLI team is aware of any in-progress feature development which can potentially address this ASK. This issue is not service-related. It is CLI infra issue.

**Comment by yonzhan** [comment]
@jiasli to help.

**Comment by jiasli** [comment]
This `--locations` is not the global parameter `--location`, so this issue is not related to CLI infrastructure.

https://github.com/Azure/azure-cli/blob/4aee466f6fce5db00db61639545e98712e6263b6/src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py#L54-L57

And the error `usage error: --locations [KEY=VALUE ...]` is thrown at

https://github.com/Azure/azure-cli/blob/17015379924a13b12a48781469c8b0e5021c7c2a/src/azure-cli/azure/cli/command_modules/cosmosdb/actions.py#L40-L43

\+ the author @shurd

**Comment by shurd** [comment]
The improved error messaging is in PR, and we are working on getting it merged.

**Comment by shurd** [comment]
We are still waiting for the PR to be reviewed, but it should be in the next CLI release.

**Comment by shurd** [comment]
Fixed in 2.14.0
