### ISSUE TITLE
Not sure how to resolve storage blob upload error

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14781]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Trying out QS on creating/uploading/downloading blob but unable to resolve error

**To Reproduce**
Doc here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli 
This is the command that failed:
![image](https://user-images.githubusercontent.com/30876406/90192722-5f207c80-dd78-11ea-92a0-3824b35ce06e.png)
![image](https://user-images.githubusercontent.com/30876406/90192736-63e53080-dd78-11ea-8fef-2296b121b805.png)

**Expected behavior**
No error with upload success

**Environment summary**
working on CMD, on cli version 2.7.0
![image](https://user-images.githubusercontent.com/30876406/90192777-7b241e00-dd78-11ea-8592-348b0750e67e.png)

**Additional context**

Some other weird behavior that I can't list storage container after creating it...
![image](https://user-images.githubusercontent.com/30876406/90194880-128b7000-dd7d-11ea-80b5-383033c39a08.png)

**Comment by yonzhan** [comment]
add to S175

**Comment by Juliehzl** [comment]
Hi @chenlomis, thanks for your feedback. Listing containers is data plane operations and will need specific credentials provided and we have a plan to migrate to mgmt plane, which will not require specific credentials for container level operations.

For uploading error, the value of `--file` is local file path. You should make sure your local path have the file named `helloworld`.

**Comment by chenlomis** [comment]
@Juliehzl  Thanks for the investigation!
Surprisingly I actually do have the _helloworld_ file in the directory... 
And gave it another try given your recommendation
But it seems like there's additional permissions needed/required ...
![image](https://user-images.githubusercontent.com/30876406/90277106-d9550d80-de19-11ea-8f41-edbcd5a1bb80.png)

**Comment by Juliehzl** [comment]
It is because you doesn't grant RBAC roles for your storage account. To grant rbac roles, you could refer to the document here https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal in portal and  https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli?toc=/azure/storage/blobs/toc.json in azure cli.

I will recommend you to grant at least `Storage Blob Data Contributor` for upload opetaion.

In addition, you could also use account key and sas token as credential which will not need special rbac roles. For storage command usage, you could refer to here https://github.com/Azure/azure-cli/blob/3113258ba38f0415cae2c30347491030e76c08f4/doc/use_cli_effectively.md#using-storage-commands.
