### ISSUE TITLE
Webapp:No module named 'decorator'

### ISSUE THREAD

**Issue by ayush3298** [Azure/azure-cli#14800]
## Describe the bug

**Command Name**
`az webapp config container set`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config container set --name {} --resource-group {} --docker-custom-image-name {} --docker-registry-server-url {}`

## Environment Summary
```
Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13343. hi @ayush3298 did you install azure-cli via pip? If yes, it might caused by situation in https://github.com/Azure/azure-cli/issues/13343#issuecomment-635811624.  Could you pls install decorator? Recommended way to install azure cli is there: https://github.com/Azure/azure-cli/issues/14011

**Comment by fengzhou-msft** [comment]
Close duplicate issue.
