### ISSUE TITLE
Feature request for new feature Virtual Router

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#14917]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
AZ CLI support for virtualrouter and virtualrouterpeering is already there. We are changing the behavior where we would want to introduce HostedSubnet. Backend resource would also change. For HostedSubnet, backend resource that needs to be created is Microsoft.Network/virtualHubs and Microsoft.Network/virtualHubs/ipConfigurations. For virtualrouterpeering, backend resource is Microsoft.Network/virtualHubs/bgpConnections

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9357 

Please refer VirtualHubBgpConnections and VirtualHubIpConfigurations

**Target Date**
Ignite 2020 - September 21

**Comment by yonzhan** [comment]
Network

**Comment by jsntcy** [comment]
Summary after meeting discussion.
- This feature will be announced as Public Preview in Ignite.
  - @naveenchekuri will help add the following aliases to their test subscription so that CLI can test the feature: ychenu, fan.qiu, Jianhui.zeng
    - After the aliases are added to test subscription, we can test the feature in centraluseuap region.
  - It’s better to make the feature available in canary regions before Sep 14 as our code freeze for Ignite is Sep 14. (Earlier is better considering buffer time for test.)
- The spec link for the feature: https://microsoft-my.sharepoint.com/:w:/p/nachekur/EYymB7IvREtEsLNyprJ_M9ABZ3caceqyn7hjVY_nicwRWQ
  - Changes for `az network vrouter create`:
    - Command interface change:
      - Deprecate the existing argument `--hosted-gateway`
      - Add a new argument `--hosted-subnet`
    - Implementation will be changed to (Will not use the resource type "Microsoft.Network/virtualRouters" any more):
      - Create a virtual hub without virtual wan (from 2020-05-01, we can create vhub without vwan)
      - Create IpConfigurations with the subnet (--hosted-subnet) under the virtual hub.
- Changes for `az network vrouter peering create`:
  - No command interface change.
  - Implementation will be changed to (Will not use the resource type "Microsoft.Network/VirtualRouterPeering" any more):
    - Create BgpConnections under the virtual hub instead of Microsoft.Network/VirtualRouterPeering.
- The minimum API version is 2020-05-01.

**Comment by haroldrandom** [comment]
**Sync details:**

As for `vrouter create`: replace the API of VirtualRouter with VirutalRouter + VirtualHub and check name confliction before creating it.

As for `vrouter list`: show all results of VirtualRouter + VirtualHub
As for `vrouter show`: try to show VirtualRouter first and then VirtualHub.
As for `vrouter delete`: delete the name specified VirtualRouter first and then VirtualHub. Before deleting the VirtualHub, it's required to delete the corresponding ipConfiguration of it.
