### ISSUE TITLE
Updating extensions fails in certain circumstances.

### ISSUE THREAD

**Issue by josh-ferrell** [Azure/azure-cli#14945]
**Describe the bug**
I was unable to update the aks-preview extension from 0.4.50 to 0.4.61 and kept receiving the following error. 

Command '['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/home/joferr/.azure/cliextensions/aks-preview', '/tmp/tmpqo7exm6p/aks_preview-0.4.61-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Pip failed so deleting anything we might have installed at /home/joferr/.azure/cliextensions/aks-preview
An error occurred whilst updating.
An error occurred. Pip failed with status code 1. Use --debug for more information.

After manually trying to run the upgrade using the command I received this;

WARNING: Target directory /home/joferr/.azure/cliextensions/aks-preview/azext_aks_preview already exists. **Specify --upgrade to force replacement.** 

Once I ran the command with the --upgrade flag the extension updated successfully. 

**To Reproduce**
az extension update -n aks-preview

**Expected behavior**
Upgrade as intended, pass pip error through to user with --debug flag.

**Environment summary**
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.0

**Comment by fengzhou-msft** [comment]
@josh-ferrell in the implementation of `az extension update`, it first backup the current extension in a temp directory and removes it, then use `pip install` to add the new version.

If using `pip install` directly, you're right to add the `--upgrade` option.

**Comment by josh-ferrell** [comment]
For some reason the upgrade via `az extension update -n aks-preview` would fail every time. Fixing it with `pip install` works one you see the `--upgrade` flag recommended but it's preferable to find out why the backup and removal of the extension wasn't working via the CLI.

**Comment by fengzhou-msft** [comment]
`Pip failed with status code 1`. `1` means `Operation not permitted`.
I think some file in `/home/joferr/.azure/cliextensions/aks-preview/azext_aks_preview` cannot be moved to a temp directory due to permission issue and that's why `azure-cli` cannot use `pip install` without the `--upgrade` option to install the latest `aks-preview` extension as the directory is not empty.

Please manually delete the `/home/joferr/.azure/cliextensions/aks-preview` directory and reinstall with `az extension add -n aks-preview`. `az extension update -n aks-preview` should work afterwards.

B.T.W., we now have `az extension add --upgrade -n aks-preview` to cover both the install and update case.
