### ISSUE TITLE
`az role assignment create` errors out (azure-xplat-cli succeeds with same command)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1496]
**Problem:**

I am unable to create role assignments with the new az cli.

**Observe:**

```
$ az role assignment create --assignee 35c7b4bc-0000-1111-2222-123456123456 --role Contributor --scope '/subscriptions/c1089427-0000-1111-2222-123456123456/resourceGroups/colemick-test-584767ea'
 
Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://graph.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/getObjectsByObjectIds?api-version=1.6-internal
```

```
$ azure role assignment create -o Contributor -c '/subscriptions/c1089427-0000-1111-2222-123456123456/resourceGroups/colemick-test-584767ea' --objectId 35c7b4bc-0000-1111-2222-123456123456
...
info:    role assignment create command OK
```

I use a nightly version (all modules are on the same version):

```
$ az version

azure-cli (0.1.0b10+1.dev20161204)
```

**Comment by colemickens** [comment]
cc: @yugangw-msft

**Comment by yugangw-msft** [comment]
@colemickens, could you run the `az ad sp show --id 35c7b4bc-0000-1111-2222-123456123456` to verify it is a valid object id? I suspect this id belong to a non-existing  graph object. 
xplat-cli works because it doesn't do any validations on object-id, nor does PAS system on creating the assignment at server end

**Comment by colemickens** [comment]
I'm very sure that it's a valid object ID. After making the assignment in
the legacy CLI, I was able to make requests for that resource group.

The error the new CLI is reporting is a 403 not a 404.

**Comment by yugangw-msft** [comment]
Hmm, i am not able to reproduce it

**Comment by colemickens** [comment]
Let me ensure that I'm not logged in as different users. I may have crossed
wires and be logged into the CLI with an SP with lots of permissions but
not enough permissions to talk to that Graph endpoint. Will confirm one way
or the other within an hour.

Actually... I'm not sure how to tell what user I'm logged in as in the new
CLI.

**Comment by yugangw-msft** [comment]
@colemickens, run `az account show`

**Comment by colemickens** [comment]
So, I am logged into the new CLI as the Service Principal...

But I **also** am in the legacy CLI.

The RBAC role assignment *shouldn't* need access to talk to Graph anyway though.

**Comment by yugangw-msft** [comment]
The role assignments configure access to azure assets for principals managed in directory graph. The integration is very tight, particularly the rbac service only accepts graph object_id, so for any logic name (unp, spn, group name, etc), commands will resolve to object_ids before submit the request. Even for xplat, the `create` command exposes more common flags to take logical name, and the same with `delete`, and `list`.  For xplat, through object_id you can by-pass the graph access for that step, but there is no end-to-end story though, because you have no way to query for the right SP based on logical names unless you remember the guid, which is hard. 
Of course if it becomes a mainline that SP should be able to create assignments, we can update cli, but so far i have not got user data to justify it.

**Comment by colemickens** [comment]
I see. I don't feel a need to push for it right now either, so I'll go ahead and close this for now.

If it's needed in the future, maybe we can just have a `--force` flag or something, just so we close the gap with azure-xplat-cli.

Thanks @yugangw-msft .
