### ISSUE TITLE
Improve start-up time

### ISSUE THREAD

**Issue by cveld** [Azure/azure-cli#15007]
**Describe the bug**
The start-up time of Az is not ideal. I ran the following:
```
    $stopWatch = New-Object -TypeName System.Diagnostics.Stopwatch
    $stopWatch.start()
    az
    $stopWatch.stop()
    $stopWatch.Elapsed
    $stopWatch.start()
    az
    $stopWatch.stop()
    $stopWatch.Elapsed
```

The result:

```
TotalSeconds      : 13,5638617
TotalSeconds      : 26,9985588
```

**Expected behavior**
The first time the Az cli runs, should start some smart server for a short time like the dotnet cli does. The second time the Az cli runs it can work against this server.

```
    $stopWatch = New-Object -TypeName System.Diagnostics.Stopwatch
    $stopWatch.start()
    dotnet
    $stopWatch.stop()
    $stopWatch.Elapsed
    $stopWatch.start()
    dotnet
    $stopWatch.stop()
    $stopWatch.Elapsed
```

Results in:

```
TotalSeconds      : 0,3562207
TotalSeconds      : 0,7270052
```

**Environment summary**
Installed by MSI. 

```
az --version

azure-cli                          2.1.0 *

command-modules-nspkg              2.0.3
core                               2.1.0 *
nspkg                              3.0.4
telemetry                          1.0.4 *

Extensions:
aks-preview                       0.4.33
azure-cli-ml                       1.2.0
azure-devops                      0.17.0
dev-spaces-preview                 0.1.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\caveld\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Comment by yonzhan** [comment]
Improve start-up time

**Comment by jiasli** [comment]
It looks like you are using a very old version (2.1.0) of Azure CLI. Please consider [installing the latest Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest).

We have improved the performance of Azure CLI to about ~300ms for client-side command with [several PRs](https://github.com/Azure/azure-cli/pulls?q=is%3Apr+label%3APerformance+is%3Aclosed).

```
> Measure-Command {az version}
TotalMilliseconds : 374.4923

> Measure-Command {az account show}
TotalMilliseconds : 362.1273

> Measure-Command {az}
TotalMilliseconds : 1252.3701
```

The raw `az` is slow because it is discovering all modules.

Under the hood, Azure CLI just calls `python.exe` and `python.exe` doesn't provide a server like `dotnet` does. We think the current start-up time is acceptable.
