### ISSUE TITLE
az aks instal-cli command error in Azure CloudShell

### ISSUE THREAD

**Issue by maheshsabnis** [Azure/azure-cli#15059]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
Connection error while attempting to download client ([Errno 13] Permission denied: '/usr/local/bin/kubectl')
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
That's by design AFAIK. 
Why do you want to run az aks install-cli ?

@edyoung might be able to provide more context.

**Comment by edyoung** [comment]
In Cloud Shell only your home directory is writable, you can't update /usr.

**Comment by navba-MSFT** [comment]
@maheshsabnis Apologies for the late reply. This is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions) as you do not have full access to the cloud shell environment. So you can follow the below steps:

To install in cloud shell you can use the `--install-location` and download to a specified path in the home folder, for example:

>**Azure:~$ az aks install-cli --install-location mykubetools/kubectl1.19.1 --client-version 1.19.1 --kubelogin-install-location mykubetools/kubelogin

>
>Downloading client to "mykubetools/kubectl1.19.1" from [https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl]
Please ensure that mykubetools is in your search PATH, so the kubectl1.19.1 command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from [https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip]

Please ensure that mykubetools is in your search PATH, so the kubelogin command can be found.

>**Azure:~$ ./mykubetools/kubectl1.19.1 version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Hope this helps. This issue is open for quite sometime. Please let me know if you need any further assistance on this.
