### ISSUE TITLE
az resource show does not populate linuxfxversion in function apps

### ISSUE THREAD

**Issue by divyagandhisethi** [Azure/azure-cli#15171]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
This issue was found in https://github.com/Azure/azure-functions-nodejs-worker/issues/283#issuecomment-692506951 . Linux function apps use linuxfxversion to specify what language version the app is running on. The issue is that linuxfxversion does not get populated in 'az resource show', although it is set in backend.

**Comment by yonzhan** [comment]
add to S176

**Comment by zhoxing-ms** [comment]
@divyagandhii Could you please show me the specific parameters you used? please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by divyagandhii** [comment]
I have sent the email with command and the result.

**Comment by zhoxing-ms** [comment]
This issue seems to be caused by the missing data returned by REST API when `GET /subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Web/sites/{webapp-name}?api-version=2020-09-01` is requested.

The value of `LinuxFxVersion` returned in `siteProperties` is `Node|12`, but the value in `siteConfig` is null, this requires the service team to investigate if it's as expected.

```
{
...
    "properties":{
        ...
        "siteProperties": {
            ...
            "properties": [
                {
                    "name": "LinuxFxVersion", 
                    "value": "Node|12"
                }, 
                {
                    "name": "WindowsFxVersion", 
                    "value": null
                }
            ], 
            ...
        }
        ...
        "siteConfig": {
            ...
            "linuxFxVersion": null, 
            "windowsFxVersion": null
            ... 
        }
        ...
    }
...
}
```
**correlation-id: efd70ac6-4895-4918-80ae-834803f771f0**

**Comment by pragnagopa** [comment]
cc @gzuber @anatolib - as this is related to function apps

**Comment by divyagandhisethi** [comment]
This issue can be closed.
