### ISSUE TITLE
Replace internal/backend QuickPrint subsystem with displacing automation

### ISSUE THREAD

**Issue by igniterwick** [Azure/azure-cli#15193]
**Is your feature request related to a problem? Please describe.**
Currently using AZ-CLI to, for example, delete a resource group with even just a simple application gateway in it can take up to 584.816 seconds.  This solution would speed it up to *sub-second* response time.

**Describe the solution you'd like**
Replacing the Quickprint System with an automation would solve this:  When provisioning or deprovisioning resources, instead of az-cli or the portal generating a PostScript formatted image and sending it to a dot matrix printer in one of the data centers and then requiring a person to walk across the data center, read the physical ticket, and then go wire up a server to those specifications after running cat5 cables (which, let's be honest, that's hard work and sometimes requires a toner, I've had to do it) and then sending the error code back to a relay attached to a multiplexer feeding the user's frontend cli utilities -- instead of the magnificently complex (it's best quality) Quickprint Deluxe 9000 system, I propose completely deleting your entire codebase and redesigning this entire provider ecosystem from the ground up using entirely new people with entirely new paradigms.  If this solution is considered it may even end up with Azure still existing in 5-10 years after the nation's CFO's start doing transition and operational overhead cost comparisons with other provider transitions in a way that doesn't rely exclusively on account management's relationship building and overengineered security theatre.
 
**Describe alternatives you've considered**
Swearing, begging, even filing polite tickets that get closed, additional training, and even resorting to debugging the portal with the browser's debugger features to observe the silent errors.

**Additional context**
There is humour intended here, but read between the lines:  This ecosystem is not sustainable and you should already know it.  If you don't, then Azure may have already failed.  (How could you not know?)

**Comment by yonzhan** [comment]
@jiasli  please help with this.

**Comment by achandmsft** [comment]
Thanks for your feedback. 

If your issue is specifically regarding performance of resource group deletion in Azure CLI, we have an option called `--no-wait` to make the command asynchronous and unblock you. For example, when you run ...
```
az group delete -n xxx --no-wait
```
the command won't block and will return immediately.  

That said, Azure CLI is just a client tool calling into Azure services. So performance of commands like resource group deletion varies depending on Azure services in the resource group.  

So to help with that, if your issue is regarding performance of Azure services, we suggest that you post this to [feedback.azure.com](https://feedback.azure.com/forums/34192--general-feedback) so other users can also vote on importance of the same. We do take this feedback seriously and have addressed performance feedback in that forum by making optimizations to the platform as shown [here](https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/19119910-application-gateway-management-operations-are-agon)
