### ISSUE TITLE
Support Conditional Access

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#15220]
**Is your feature request related to a problem? Please describe.**
Azure CLI does not support [Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/) currently. For cases that require MFA for specific resources (VM for example), CLI will not be able to  handle it. We need to define a flow to communicate with user in this case.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yungezz** [comment]
for VM SSH.

**Comment by avanigupta** [comment]
We want to support Conditional Access for Azure App Configuration service too (`az appconfig` command module). Currently, assigning multi-factor authentication as a Conditional Access policy and trying to access App Config using AAD authentication fails with the following error:
`AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, 
you must use multi-factor authentication to access 'REDACTED'`
What is the timeline for this support in CLI?

**Comment by jiasli** [comment]
@avanigupta we have made some progress with VM SSH (https://github.com/Azure/azure-cli/pull/17093). 

**Conditional Access** for **Azure Storage** is currently being developed. I guess **Azure App Configuration** will catch the same train 🚄 . 

Let's talk offline with PM to get it scheduled!
