### ISSUE TITLE
[Billing] bump API version to 2020-05-01

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#15473]
**Spec Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/billing/resource-manager/Microsoft.Billing/stable/2020-05-01

release request link:
https://github.com/Azure/azure-rest-api-specs/pull/10585

**Is your feature request related to a problem? Please describe.**

Upgrading billing commands' SDK and some features are introduced

**Describe the solution you'd like**

1. Upgrade billing SDK to a newer version and remain `enrollment-account` and `period` command groups unchanged.
2. `Invoice ` commands' response has break changes and support BillingAccount, BillingProfile, and existing scope subscriptions.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
add to S177 with high priority

**Comment by msyyc** [comment]
(1)please use the package and check whether it works well :  https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/azure-rest-api-specs/10585/azure-sdk-for-python/azure-mgmt-billing/azure_mgmt_billing-0.2.0-py2.py3-none-any.whl @haroldrandom 
(2)please confirm the CHANELOG and version : https://github.com/Azure/azure-sdk-for-python/pull/14491/files#diff-a333e1ac506a3485e89c33171d5712659e54c23e6daf482c354db1fd5a362e13 (since the version from preview to stable, so version number will change to stable number 1.0.0) @bradenwatkins
