### ISSUE TITLE
Getting queue messages requires 'Microsoft.Storage/storageAccounts/listKeys/action' permission

### ISSUE THREAD

**Issue by hilaco10** [Azure/azure-cli#15569]
According to the documentation, in order to get queue messages, the following permissions are required-

> Microsoft.Storage/storageAccounts/queueServices/queues/messages/process/action or (Microsoft.Storage/storageAccounts/queueServices/queues/messages/delete and Microsoft.Storage/storageAccounts/queueServices/queues/messages/read)

I created a role with these permissions but when I try to get queue messages using the CLI command- 
`az storage message get --queue-name <queue name> --account-name <storage account name>`

I get the following error-

> "az storage message get: error: Azure Error: AuthorizationFailed
> Message: The client 'userCanGetMessages@mycompany.onmicrosoft.com' with object id '33fsfg43-35gd-d98d-l209-m38djan38fv2' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action'........."

**Comment by yonzhan** [comment]
add to S178

**Comment by evelyn-ys** [comment]
Hi @hilaco10, thanks for your report.
The reason 'Microsoft.Storage/storageAccounts/listKeys/action' permission is required is that queue service need credentials for authentication. Since you provide `--account-name` without `--account-key`, CLI will query account key inside your storage account, which need 'Microsoft.Storage/storageAccounts/listKeys/action' permission.
There are two solution for you:
- Use `az storage message get --queue-name <queue name> --account-name <storage account name> --account-key <account key>`
or
- Add 'Microsoft.Storage/storageAccounts/listKeys/action' permission to your role.

If you still have any questions, feel free to leave comments here.
