### ISSUE TITLE
[Storage] az storage container policy create erase the permission setting

### ISSUE THREAD

**Issue by hasonmsft** [Azure/azure-cli#1561]
As you can see that after creating new container policy, the original container level public permission is erased and changed back to off. 

```
C:\tmp>az storage container show-permission -n hasontestsetacl
{
  "publicAccess": "container"
}

C:\tmp>az storage container policy list -c hasontestsetacl
{
  "acl1": {
    "expiry": "2017-12-12T00:00:00+00:00",
    "permission": "rwdl",
    "start": null
  },
  "acl2": {
    "expiry": "2017-12-12T00:00:00+00:00",
    "permission": "rwdl",
    "start": null
  }
}

Add new policy here

C:\tmp>az storage container policy list -c hasontestsetacl
{
  "acl1": {
    "expiry": "2017-12-12T00:00:00+00:00",
    "permission": "rwdl",
    "start": null
  },
  "acl2": {
    "expiry": "2017-12-12T00:00:00+00:00",
    "permission": "rwdl",
    "start": null
  },
  "acl3": {
    "expiry": "2018-01-01T00:00:00+00:00",
    "permission": "r",
    "start": null
  }
}

C:\tmp>az storage container show-permission -n hasontestsetacl
{
  "publicAccess": "off"
}


```

**Comment by tjprescott** [comment]
This is another manifestation of this issue that I opened against the Python storage SDK months ago: https://github.com/Azure/azure-storage-python/issues/220.

While we can do this in the CLI, it seems to me that the SDK is the appropriate place to split these functions. Any customer that tries to use the `get/set_container_acl` methods is going to experience the same issue. While I understand that they are tied together in the service, no one would expect setting the container permission to wipe their ACL or adding an ACL entry to wipe their container permissions. They are logically completely separate.

Separating these service calls would also work, but it would be just as acceptable (and easier) to simply have the SDK implement the workaround instead of asking every client application do so.
