### ISSUE TITLE
Fixing netappfiles test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15620]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

There are 9 failed test cases in netappfiles in a recent test run. Can you have a look? Thanks!
https://clitestresultstac.blob.core.windows.net/latest/index.html
https://clitestresultstac.blob.core.windows.net/20201113-054322-540793/netappfiles.report.parallel.html
https://clitestresultstac.blob.core.windows.net/20201113-054322-540793/netappfiles.report.sequential.html

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
netappfiles

**Comment by fengzhou-msft** [comment]
There are now more failures in the latest [test](https://clitestresultstac.blob.core.windows.net/20201211-043721-979918/netappfiles.report.parallel.html). Some new failures are caused by location [eastus2euap](https://github.com/Azure/azure-cli/blob/425a0b6247797f05e41280f4c075a6c101c8125c/src%2Fazure-cli%2Fazure%2Fcli%2Fcommand_modules%2Fnetappfiles%2Ftests%2Flatest%2Ftest_backup_policy_commands.py#L6) no longer available.  I tried to use `eastus2`, but got other errors. @hildurhodd can you help fix it?

**Comment by hildurhodd** [comment]
Hi @fengzhou-msft, yes, I'll take a look at this.

**Comment by hildurhodd** [comment]
Hi, eastus2euap is still available and I am able to run the tests live. This has probably something to do with the subscription. But why are you running the tests live? @fengzhou-msft

**Comment by audunn** [comment]
Old stale issue
