### ISSUE TITLE
[Network] `dns record` vs `dns record-set show` take type differently

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1576]
`record` takes the type as a sub-command `az network dns record A ...` vs `record-set show` which takes it as a flag: `az network dns record-set show --type A ...` 

Is this intentional? Take a bit to get the hang of the DNS commands since the record subcommands are set operations.

**Comment by tjprescott** [comment]
@colemickens this was intentional, but that doesn't mean it's the best way to do it! We put the record types as subcommands because trying to make a unified "add" command was confusing since certain parameters only applied to certain record types.

However, we do have a "remove" command in each subgroup. We could have a "list" operation for each subcommand which would essentially be an alias of `dns record-set show --type {type}`. We have this kind of redundancy sparingly, but it does exist (`vm nic show` is the only one I can think of). 

Thoughts?

**Comment by tjprescott** [comment]
This discussion is covered in issue #1134.
