### ISSUE TITLE
Interesting issues with az translator

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15787]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

(including expected behavior in the same section)

1) One specific error is calling out that --template and --parameters are missing... although what actually triggered the error is that _-- resource-group_ is misspelled...  
![image](https://user-images.githubusercontent.com/30876406/98051362-8f604000-1de8-11eb-941c-7181ef7b273f.png)

and I attempted the commands 3-4 times before coming to that realization

Perhaps we could be more concise with the error call out...?

2) translator didn't work when I use the *.json downloaded from portal
![image](https://user-images.githubusercontent.com/30876406/98051568-ff6ec600-1de8-11eb-95a0-4245b832faa2.png)

Not sure if this is an edge case but it is a bit concerning if the translator is suppose to support (all) VM creation use cases and 

**To Reproduce**
See above

**Environment summary**
![image](https://user-images.githubusercontent.com/30876406/98051680-3b099000-1de9-11eb-9e4f-0a3e283c46c5.png)

**Additional context**
Followed up in email

**Comment by yungezz** [comment]
hi @arrownj could you pls check it? thanks

**Comment by arrownj** [comment]
Hi @chenlomis , for the first problem, actually it's not a problem of the cli-translator extension. It's an error message reported by CLI argument parser. Actually if you run `az vm create -- resource-group <rg> --name <vm_name> --image UbuntuLTS`, it will report a similar error message. In your case, you must set default resource-group before(try to run `az configure list-defaults`, you should see the default `group` value there). Otherwise, the error should be something like this:
> RequiredArgumentMissingError: the following arguments are required: --template, --parameters, --resource-group/-g

And this is by design.

For the second problem, could you please send me your template.json/parameters.json file. Currently there are some vm properties not supported. Let's identity this problem via email. Thanks
