### ISSUE TITLE
az ad sp create-for-rbac and the --name parameter

### ISSUE THREAD

**Issue by stevenfollis** [Azure/azure-cli#1596]
Hi,

When creating a SP for use with a Container Registry, I ran the following with the name **sfacr** (per [docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-azure-cli)):

```bash
az ad sp create-for-rbac --name sfacr --scopes /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/sfacr --role Owner --password <password>
```

I expected the resulting SP to be named **sfacr**, and the URI to be something like **http://sfacr**. The response says that a SP was created named **sfacr**, however under closer inspection it is actually named **azure-cli-2016-12-19-20-42-08**.  

Looking at the `-h` documentation it does say that `--name` is for "An unique uri. If missing, the command will generate one" but that feels unnatural when throughout the CLI, `-n --name` is used for display names. 

Would it be better to use `-n` for the display name, and a `-u` or `--uri` to designate the App ID URI?

Thanks!

![image](https://cloud.githubusercontent.com/assets/5393923/21328623/e548e5b8-c602-11e6-91e1-cf0d4602f9d4.png)

**Comment by yugangw-msft** [comment]
I agree this is not very clear. Couple of explanations here:
The `display-name` is not useful for service principal created for RBAC, and in cli you probably will never use it. Because of this, we associate `-n and --name` with `app-id-uri` which people will use the same value to login or assign roles to it. This is not a perfect association, but in AAD graph database, the `app-id-uri` is mapped to one of the `servicePrincipalNames`, so the name still makes some sense. Also we don't want to expose too many arguments from this command which has already got too many.
Let me know if you have any other comments. For now I will leave this issue open and see whether there are more people get confused.

**Comment by colemickens** [comment]
@yugangw-msft This leads to the App ID URI being wrong in many, many cases though. I'm surprised AAD even let you do that. The new and legacy portal require the App ID URI be an actual URI.

**Comment by colemickens** [comment]
I offered up my expectation in the dupe bug: https://github.com/Azure/azure-cli/issues/1698

**Comment by yugangw-msft** [comment]
The expectionations are reasonable. I will fix it

**Comment by stevenfollis** [comment]
Thanks!
