### ISSUE TITLE
CLI for Time Series Insights (TSI)

### ISSUE THREAD

**Issue by jatinas** [Azure/azure-cli#15971]
**Resource Provider**
Microsoft.TimeSeriesInsights

**Description of Feature or Work Requested**
CLI for TSI
Speclet - https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EeASGSS9OH5EoETiy56ZqKYBr85-KD5u6uxLJt3QIVNg8A?e=vhq48x

**Minimum API Version Required**
2020-05-15

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/stable/2020-05-15/timeseriesinsights.json

**Target Date**
end of Fe.

**Comment by yonzhan** [comment]
TSI

**Comment by kairu-ms** [comment]
@jatinas For P1 Sku, which kind of environment should I use? Because in swagger, it only mentions S1 and S2 for Gen1 and L1 for Gen2.  https://github.com/Azure/azure-rest-api-specs/blob/dbb0a6fd623196f0db6b461b0f3f54e284e3a9e4/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/stable/2020-05-15/timeseriesinsights.json#L1357
