### ISSUE TITLE
webapp:az webapp up doesn't work

### ISSUE THREAD

**Issue by hursic** [Azure/azure-cli#16008]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
code: InvalidResourceLocation - , The resource 'TheCrownAppservicePlan' already exists in location 'northeurope' in resource group 'TheCrown'. A resource with the same name cannot be created in location 'westeurope'. Please select a new resource name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {} --html`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@hursic - unable to repro the issue. can you please provide `-debug` log .

**Comment by btardif** [comment]
@calvinsID I think this should be re-using the app service plan

**Comment by calvinsID** [comment]
@hursic it seems like the app you are running `az webapp up` in has been deployed to azure using CLi before, and has defaults configured in the '.azure' directory, and has the plan 'TheCrownAppservicePlan' configured. Since you are overriding the location using `--location` flag, the error is showing that you cannot create a new appservice plan named 'TheCrownAppservicePlan' in this new location. Please either remote the defaults by deleting the '.azure' directory, or use a new appservice plan by specifying using `--plan` flag.

**Comment by calvinsID** [comment]
Hey @hursic , it seems like you've deployed that app to azure before (thus causing defaults to be created), or have configured a default appservice plan. Please check your root directory for a folder named '.azure', which shows if there are defaults. The error message is showing that you cannot create a new appservice plan in the location specified, since there already exists an appservice plan with that name in a different location. Please either re-run the command without the default plan, or override the plan name using `--plan` flag.

**Comment by calvinsID** [comment]
Will add better error handling and get rid of the `code: InvalidResourceLocation - ,` in the beginning of the error message
