### ISSUE TITLE
VM created using --ssh-key-values but comment from public key was removed

### ISSUE THREAD

**Issue by devcovato** [Azure/azure-cli#16049]
A created a VM as reported in #16048 where I end up using only one key. 

I logged in on the remote VM, run `cat ~/.ssh/authorized_keys` finding out the comment was removed.

On ssh-key generation, I always add a comment (usually an email address). But I found convenient using a tag that let me recognise the purpose of the key since I use many.

Is there a reason having removed the comment? Please, don't tell me security!

**Comment by yungezz** [comment]
hi @qwordy could you pls help on this?

**Comment by qwordy** [comment]
I check `--debug` logs. Comments after `=` are reserved in `vm create` request. According to your description, service removes it.

**Comment by Drewm3** [comment]
@avirishuv, could you check with the dev team to see if they know why the comments are being removed.

@devcovato, this area of the product has been consistent for many years. So, we may not be able to get to the bottom of your question as to why a specific design decision was made. Of course, if you feel that the design should be changed, then please open a suggestion at: https://feedback.azure.com/forums/216843-virtual-machines

**Comment by Drewm3** [comment]
Hi @devcovato, the reason that comments are being removed is due to the process in which SSH keys are pushed from the API down to the VM. Unfortunately, the current process is built over an existing process for secrets which lead to a loss of comments through some of the transforms that are done on the keys. We are looking at possibly changing this behavior in the future, but there are no timelines that I can share at this time because it is still in the discussion phases.
