### ISSUE TITLE
[Question] How to work around "@" parsing in command args

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1610]
I was trying to set an environment variable on an App Service web app (using the `az appservice web config appsettings update` command), whose value is a MongoDB connection string. Unfortunately, the connection string includes the following substring within it: `=@n`. This triggers [this line of code](https://github.com/Azure/azure-cli/blob/575de6b7894ce60ed3182c3a51e269f4b2b063b2/src/azure-cli-core/azure/cli/core/application.py#L213) in the CLI parser, and since the substring following the `@` isn't a file path, it fails with a `Failed to open file` error.

Is there a way to work around this? It seems a little odd for the CLI to assume this is a file, and just outright fail if it can't find the file, as opposed to failing back to treating the value as a string literal.

In the meantime, I just set the env var via the Azure portal, but it's non-ideal to have to do that. The `@` character is the standard separator in a MongoDB connection string between the authenticating account password and server host name, and so any time that the password ends in an `=` sign, it would hit this same issue (as just one example of a tangible scenario that is impacted by the current behavior).

**Comment by tjprescott** [comment]
Can you provide an example of the connection string with bogus values?

**Comment by tjprescott** [comment]
`@name` is a CLI feature to load a value from file, most useful for loading JSON that is painful and awkward to type on the command line. The reason it parses `this=@that` is because argparse allows space or = as a separator between an argument and its value and we needed to preserve the ability for `--arg=@filename` to work correctly.

We tried a couple different implementations and the current one is simplified for performance reasons. Based on the format of your connection string, we may need a more complex regex implementation.

**Comment by lostintangent** [comment]
Sorry for the late reply. The connection string value would have the format of `{user}:{pass}@{server}`, and unfortunately in my case, the password ended in `=`, which seems to have triggered this issue (e.g. `foo:bar=@server.com`). The test case you added in #1648 should account for this scenario, and I can test out your fix as well.
