### ISSUE TITLE
az cli does not handle expansion of file paths

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-cli#1614]
On Ubuntu, if you use `~` to represent the home directory, the Azure CLI seems unable to expand from `~` to the actual use home directory.

```bash
az group deployment create --resource-group="deisprodk8s" --template-file=~/flow/k8s/output/azuredeploy.json --parameters @/home/jims/flow/k8s/output/azuredeploy.parameters.json
File '~/flow/k8s/output/azuredeploy.json' contains error: [Errno 2] No such file or directory: '~/flow/k8s/output/azuredeploy.json'
```

**Comment by brendandburns** [comment]
To be fair, that expansion happens inside of bash, not in the executable, the executable sees: '/home/.../'

But we should consider supporting the expansion in the az CLI also.

**Comment by johanste** [comment]
We have tried to stay away for extra expansions inside of the CLI wherever we can since that makes it harder to understand the escaping/expansion that will yield the eventual value. As @brendandburns points out, the expansion in this case is normally done by the shell. The reason it doesn't happen here is because of the (optional) '=' between the option name and the value. If you drop that, it should expand as you expect (assuming that you are using bash that is :))

Is that an acceptable solution?

**Comment by tjprescott** [comment]
Our @file notation allows for @~/path and does the expansion, regardless if the property is specified as `foo @~/path` or `foo=@~/path`. There are only a handful of parameters that are specifically paths, so I think we could pretty easily add the expansion logic in, and it would work in CMD as well.

**Comment by brendandburns** [comment]
I tend to agree with @tjprescott users are going to expect `--foo=~/bar/baz` to work, and the few expansions are well known.

**Comment by johanste** [comment]
If we are OK with the (admittedly degenerate) case of someone having a file (or directory) with the name '~' not being supported, I can get behind this :)
