### ISSUE TITLE
az aks get-credentials fails with error AADSTS70043 - The refresh token has expired or is invalid due to sign-in frequency checks by conditional access

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/azure-cli#16209]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2020-12-07T12:15:47.8520000Z and the maximum allowed lifetime for this request is 172800.
Trace ID: 9958a6aa-3e9b-4470-9df7-7d0603262301
Correlation ID: c215e3d3-39fa-42e5-855c-4d93e362d308
Timestamp: 2020-12-09 13:10:42Z
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks get-credentials --resource-group {} --name {}`

## Expected Behavior

I expect that I get valid credentials. If not working, due to some expired token, I expect that I am asked to relogin and fetch a valid token. If not, at least some information what to do to resolve the error.

## Environment Summary
```
Linux-5.9.11-100.fc32.x86_64-x86_64-with-glibc2.2.5
Python 3.8.6
Installer: RPM

azure-cli 2.16.0

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
aks

**Comment by MartinPlay01** [comment]
i have the same error but executing this command: 
`az resource delete --ids exampleResourceID`

**Comment by JerrySantana92** [comment]
@BenjaminHerbert were you able to fix it? I'm facing the same issue!

**Comment by jongio** [comment]
I'm seeing this with `az account get-access-token` as well.

```
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-01-21T18:58:33.5955295Z and the maximum allowed lifetime for this request is 43200.\r\nTrace ID: 663734d6-d237-4d25-a2e9-5c0db0e79600\r\nCorrelation ID: d2aee7e8-ca4d-4448-a3c1-a97b2fcbc2ff\r\nTimestamp: 2021-01-23 00:02:57Z","error_codes":[70043],"timestamp":"2021-01-23 00:02:57Z","trace_id":"663734d6-d237-4d25-a2e9-5c0db0e79600","correlation_id":"d2aee7e8-ca4d-4448-a3c1-a97b2fcbc2ff","suberror":"token_expired"}
```


This shouldn't throw an exception. It should fail gracefully.

azsdke2e
azsdke2e2

**Comment by fengzhou-msft** [comment]
Rerun `az login` and CLI should get a new refresh token and fix the error. @jiasli @houk-ms to follow up on better error handling for this case.

**Comment by jongio** [comment]
Yeah, az login fixes it, just shouldn't be a code exception, more like an error would be great.

**Comment by amitlalaawaz** [comment]
I received this error while pulling heavy-weight docker to my registry, what should I do? any inputs highly appreciated.

AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-02-24T05:50:44.4338824Z and the maximum allowed lifetime for this request is **43200**

**Comment by debugdana** [comment]
az login doesn't fix it for me

**Comment by jiasli** [comment]
@debugdana, running `az login` should retrieve a new refresh token from AAD. Could you **clear the browser cache** and run it again? We did observe some rare cases where the browser still somehow uses the old cache.

**Comment by jiasli** [comment]
Regarding error

```
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. 
The token was issued on 2021-02-23T05:06:57.0691981Z and the maximum allowed lifetime for this request is 3600.
Trace ID: ab764987-048b-4745-bc32-ba7d16840b00
Correlation ID: a2d45c9f-41de-4e18-8bf5-8368975c7561
Timestamp: 2021-02-24 06:54:48Z
To re-authenticate, please run `az login`. If the problem persists, please contact your tenant administrator.
```

It is thrown because your tenant administrator has configured [Refresh Token Max Inactive Time](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#refresh-token-max-inactive-time).

If you are a tenant administrator, you may change it via [configuring Sign-in frequency control in Azure Portal](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#policy-1-sign-in-frequency-control).

We have created PR #17072 to show a better recommendation message after encountering this error.

**Comment by shalin231** [comment]
There is a folder with name .azure in my local system, I deleted it and tried again...it fixed the problem..

**Comment by jiasli** [comment]
@shalin231, `~/.azure` is where Azure CLI's configuration and token cache is stored. Running `az login` again will also refresh the token cache and achieve the same effect of directly deleting it.

**Comment by lucen-ms** [comment]
fyi I had the same issue when running e.g. `kc get services`

`E0322 17:45:49.947710   13076 azure.go:154] Failed to acquire a token: unexpected error when refreshing token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body:{"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-03-19T13:32:04.3618936Z and the maximum allowed lifetime for this request is 43200.\r\nTrace ID: 0d6edd7e-dc33-46aa-a299-06fc10673401\r\nCorrelation ID: bca2694e-c9b1-4b9c-a8a5-54bc4c3815c0\r\nTimestamp: 2021-03-22 16:45:49Z","error_codes":[70043],"timestamp":"2021-03-22 16:45:49Z","trace_id":"0d6edd7e-dc33-46aa-a299-06fc10673401","coE0322 17:45:50.829281   13076 azure.go:154] Failed to acquire a token: unexpected error when refreshing token: refreshing token: adal: Refresh request failed. Status Code = '400'. `

`az login` nor clearing browse cache did not help me. I had to use `kubelogin.exe convert-kubeconfig` to fix it (https://github.com/Azure/kubelogin).

**Comment by amorphina** [comment]
> @shalin231, `~/.azure` is where Azure CLI's configuration and token cache is stored. Running `az login` again will also refresh the token cache and achieve the same effect of directly deleting it.

I had some old login files with my personal account stored in the .azure directory.
Logging out and then logging in with a service principal didn't seem to overwrite everything.
Removing the .azure directory and logging in with the service principal resolved the issue.

**Comment by josephalterbaum** [comment]
I had the same issue (AADSTS70043 expired refresh token) with the Azure Account extension for VS Code. Neither using az login, nor deleting .azure or the browser cache fixs it for me. 

Any ideas would be appreciated.

**Comment by dylanw-oss** [comment]
I met the same issue but `az login` can't resolve it, `az login --scope https://graph.microsoft.com//.default` works for me, and if you're using WSL, you probably need to manually copy the URL to web browser to login.
