### ISSUE TITLE
Using the --pattern for `az storage blob delete-batch`

### ISSUE THREAD

**Issue by gjdonkers** [Azure/azure-cli#16248]
When using the following command on macOS terminal the container is cleared keeping the folder data and files in the container, this is what I would expect. But when this command is executed within the AzureCLI@2 task in Azure DevOps there are other files/folders that are not deleted. How is this possible?

`az storage blob delete-batch --source '$web' --account-name $STORAGE_ACCOUNT --pattern '[!data&&!files]*' --output table`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_delete_batch)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @gjdonkers, as you mentioned, the command works in your local machine.
For Azure DevOps CLI task, they may have their rule to read cli commands. I will recommend you to add `--debug` in your command to see the debug log in your Azure DevOps machine. In the log, you could see how you command and parameter values are read. I am afraid that your pattern parameter is not read correctly. otherwise the command should work as expected if the storage account and container are the same.

But for how to use Azure DevOps CLI task, you may need to find Azure DevOps community for help. We have no idea about that, either.

**Comment by gjdonkers** [comment]
Hi @Juliehzl Thanks for your response. I found an other solution in implementing azcopy sync in the pipeline, now it works as expected.
