### ISSUE TITLE
Add python 3.6 configuration & support

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1626]
Python 3.6 was released on December 23, 2016. The current matrix of Travis CI run includes 2.7, 3.5, 3.5-dev.  It worths to consider replace 3.5-dev with 3.6.

**Comment by derekbekoe** [comment]
According to https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against, 3.6 is not yet available on Travis CI. Only `"3.6-dev" # 3.6 development branch` is.

**Comment by troydai** [comment]
What's the plan for 3.5-dev then?

**Comment by derekbekoe** [comment]
Open to suggests:
- We could leave 3.5-dev as 'allowed failures' or we can now require that 3.5-dev always passes since the 'import error' issue we had has been resolved.
- We could also include 3.6-dev in our builds as 'allowed failures'?

The development branches get updated frequently so can break unexpectedly.

**Comment by troydai** [comment]
Per conversation with @derekbekoe, here's what we come to conclusion.
1. Replace python 3.5-dev with 3.6-dev configuration. 
2. If build fails under 3.6-dev, allow the failure temporarily.

**Comment by derekbekoe** [comment]
Python "3.6" is now available on Travis CI
