### ISSUE TITLE
`--assign-identity` flag being ignored when running aks create

### ISSUE THREAD

**Issue by bcaton85** [Azure/azure-cli#16280]
**Describe the bug**
We have a pre-made managed identity in our resource group. We want to assign this managed identity during the cluster creation process. We are running the following command to create the AKS cluster:
```
az aks create --name $clusterName
    --resource-group $resourceGroup
    --subscription $subscription
    --enable-managed-identity
    --assign-identity /subscriptions/$subscription/resourcegroups/$resourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$miName
    --node-vm-size Standard_D2_v3
    --node-count 1
    --location eastus2
    --generate-ssh-keys
    --load-balancer-sku basic
```

The issue being when we run the command the `--assign-identity` flag is ignored and the az cli attempts to create the cluster with the service principle anyway.

**To Reproduce**
Run the previous command.

**Expected behavior**
For the cluster to be created with the assigned managed identity and not attempt to create a new service principal.

Or at least some output notifying us why it's resorting to create the cluster with the service principal rather than the managed identity. 

**Environment summary**
az: 
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.68"
  }
}

**Comment by yonzhan** [comment]
aks

**Comment by noamichael** [comment]
I think the issue can be found in the [Azure Extension for AKS](https://github.com/Azure/azure-cli-extensions/blob/a05d404fce609fb3d0580949c7b8edcd5cd73fa1/src/aks-preview/azext_aks_preview/custom.py#L990). The `_ensure_aks_service_principal` function is always called even if `enabled_managed_identity` is passed:

```python
principal_obj = _ensure_aks_service_principal(cmd.cli_ctx,
                                                  service_principal=service_principal, client_secret=client_secret,
                                                  subscription_id=subscription_id, dns_name_prefix=dns_name_prefix,
                                                  location=location, name=name)
 ```

It works in some environments for me because [it loads a cached version of the service principal from disk](https://github.com/Azure/azure-cli-extensions/blob/a05d404fce609fb3d0580949c7b8edcd5cd73fa1/src/aks-preview/azext_aks_preview/custom.py#L2238):


```python
 principal_obj = load_acs_service_principal(subscription_id, file_name=file_name_aks)
 ```
It is not validating the `client_secret` of the service principal. It just wants it to be in the request body. I will try uninstalling the extensions and previews to see if this resolves the error.

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
