### ISSUE TITLE
azure-cli-core has hard dependency on previous version of azure-mgmt-core

### ISSUE THREAD

**Issue by fhoy** [Azure/azure-cli#16290]
Similarly to https://github.com/Azure/azure-cli/issues/15496, `azure-cli-core` has a hard dependency on the previous version of `azure-mgmt-core`. While the problem of https://github.com/Azure/azure-cli/issues/15496 was worked around by vendoring the code in question, an older `azure-mgmt-core` is still required, which means that we have to keep using an older version of `pip` and ignore its warnings about version mismatches. Interestingly enough, `azure-mgmt-core` 1.2.2 was actually released _before_ the change in `azure-cli-core` to upgrade from 1.2.0 to 1.2._1_ was merged (see https://github.com/Azure/azure-cli/issues/15766).

Would it be a problem to at least allow _patch_-level-upgrades of this dependency, instead of requiring an exact version?

**Comment by yonzhan** [comment]
azure-cli-core

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/16074 was opened by a contributor to unpin `azure-mgmt-core`.

**Comment by jiasli** [comment]
Mgmt SDKs like `azure-mgmt-network` requires

https://github.com/Azure/azure-sdk-for-python/blob/ab12b048ddf676fe0ccec16b2167117f0609700d/sdk/network/azure-mgmt-network/setup.py#L85

```py
'azure-mgmt-core>=1.2.0,<2.0.0',
```

But `azure-cli-core` requires 

https://github.com/Azure/azure-cli/blob/7ef9f617f9f54a5ea3537b824a1ef43eaa6401cd/src/azure-cli-core/setup.py#L61

Because mgmt SDKs are installed before Azure CLI core, `pip` will install `azure-mgmt-core==1.2.2` first and shows warning when installing `azure-cli-core`:

```
azure-cli-core 2.17.11 requires azure-mgmt-core==1.2.1, but you'll have azure-mgmt-core 1.2.2 which is incompatible.
```

**Comment by jiasli** [comment]
We have now loosened the dependency on `azure-mgmt-core` in #16074.
