### ISSUE TITLE
Feature manager filter parameters parsed incorrectly

### ISSUE THREAD

**Issue by HarrowinG** [Azure/azure-cli#16374]
**Describe the bug**
Hello, I have an issue with Feature Manager stuff (I know that it is in preview).
In particular it is command "az appconfig feature filter add" and "--filter-parameters" part.
Documentation said it is space separated pairs Key=Value but they work not as expected.
1. Any Value treated as string and wrapped into double quotes. So no chance to set any non string value.
2. Array parsed with error: KeyName=[arrayValues] results into 2 keys: 
"KeyName"="[arrayValues"
"]"=""
(closing bracket becomes new key and again array is a string now, moreover if there was an array of strings inner values have NO string quotes anymore)
3. If a value is an Object type then it fails the command entirely. (maybe the command doesn't like curly braces)

**To Reproduce**
Just call this command.
az appconfig feature filter add --feature "FlagName" --label "testEnv" --filter-name "FilterName" --filter-parameters PropertyName="UserName" IsOneOf=["user1","user2","user3","user4"] IntValueCheck=50 BoolValueCheck=true --yes

For object test something like this.
az appconfig feature filter add --feature "FlagName" --label "testEnv" --filter-name "FilterName" --filter-parameters ObjectValueCheck={"a": 50, "b": true}  --yes

**Actual behavior**
"parameters": {
     "PropertyName": "UserName",
     "IsOneOf": "[user1,user2,user3,user4",
     "]": "",
     "IntValueCheck": "50",
     "BoolValueCheck": "true"
    }

**Expected behavior**
"parameters": {
     "PropertyName": "UserName",
     "IsOneOf": ["user1","user2","user3","user4"],
     "IntValueCheck": 50,
     "BoolValueCheck": true
    }
Ability to pass an object should exist.
I would be grateful if you could allow this command to take a json as input.
I think it is the simplest and convenient way to take a json as it is. Because currently I'm parsing json to make space separated pairs which in turn should create the same json as I've parsed.

**Environment summary**
Azure Powershell Task in Azure DevOps 5.179.0, azure-cli 2.11.0, Az-Account 1.9.3

**Additional context**
I've tried it by installing azure cli on local PC, result is the same

**Comment by yungezz** [comment]
route to appropriate team

**Comment by avanigupta** [comment]
Hi @HarrowinG, we only support adding filter parameters which are strings, or array of strings. Other data types such as numbers, booleans and JSON objects will be converted to strings. However, we are considering changing this behavior to allow storing data types other than strings as filter parameter values. But this will not be a trivial change and might take some time to release. In the meantime, you might be able to achieve what you want by **_importing_** your feature flags from a JSON file. 

Since you already have a JSON file where your filter parameters are stored, you might be able to tweak your original JSON file in order to import it. The JSON schema to denote feature flags is described [here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-feature-flags-dotnet-core#feature-flag-declaration). 

In your case, your JSON file being imported should look like this:
```
{
  "FeatureManagement": {
    "FlagName": {
      "EnabledFor": [
        {
          "Name": "FilterName",
          "Parameters": {
            "PropertyName": "UserName",
            "IsOneOf": [
              "user1",
              "user2",
              "user3",
              "user4"
            ],
            "IntValueCheck": 50,
            "BoolValueCheck": true,
            "ObjectValueCheck": {
              "a": 50,
              "b": true
            }
          }
        }
      ]
    }
  }
}
```

You can import this file into your App Configuration by running this command:
`az appconfig kv import -s file -n <storeName> --format json --path <filePath> --label testEnv`

Let me know if this workaround doesn't work for you.

**Comment by HarrowinG** [comment]
Hi @avanigupta, thanks for your answer. But the logic a bit more complex. When service is deploying it knows which flags it needs. But if such flags already there we need to skip it to not override existing configuration. As I understand it will just replace all flags or filters. Can this command handle partial flag names extraction?

**Comment by avanigupta** [comment]
Hi @HarrowinG, you are right, importing from file will update all feature flags which match the specified label in AppConfig with the values from file. 

If I understand correctly, your current approach is to fetch each feature flag that the service needs and perform some checks:

1. If the feature flag exists, check its filter parameters. 
    - If the feature flag in AppConfig has all the filter parameters that your service needs, do nothing.
    - If the filter parameters required by the service are missing, update that feature flag with new filter parameters without overriding existing filter parameters.

2. If the feature flag does not exist, add a new feature flag.

Can you confirm if my understanding is correct?

**Comment by HarrowinG** [comment]
Hi @avanigupta, yes, you are right.

**Comment by avanigupta** [comment]
Hi @HarrowinG, this feature will be available in the next release of Azure CLI.
