### ISSUE TITLE
az ad app update for app roles erases saml2Token optional claims

### ISSUE THREAD

**Issue by AndriiOmelianenko** [Azure/azure-cli#16739]
**Describe the bug**

I have application manifest that has optional claims that look like this:
```json
{
  "optionalClaims": {
    "idToken": [],
    "accessToken": [],
    "saml2Token": [
      {
        "name": "groups",
        "source": null,
        "essential": false,
        "additionalProperties": ["sam_account_name"]
      }
    ]
  }
}
```
As far as I understood from other opened issues, this az-cli doesn't support update of `saml2Token`

However!, when I update application roles (don't do anything with optional claims), `saml2Token` gets erased:
```json
{
  "optionalClaims": {
    "idToken": [],
    "accessToken": [],
    "saml2Token": []
  }
}
```
**To Reproduce**

Put something in `optionalClaims.saml2Token`

```bash
az ad app update --id <id> --app-roles @manifest.json
```

Verify `optionalClaims.saml2Token` is empty now

**Expected behavior**
Well, changes in roles applied, and other fields shouldn't be touched.

**Comment by yonzhan** [comment]
Graph

**Comment by jiasli** [comment]
The `idToken` and `accessToken` support is added by #12954. However as for `samlToken`, as #12954 pointed out, Azure CLI still uses Graph API v1.6, and the service side does not accept `samlToken` anymore. 

For the time being, we recommend using `az rest` to directly invoke the Microsoft Graph API [Update application](https://docs.microsoft.com/en-us/graph/api/application-update) to specify [`optionalClaims`](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) with `saml2Token`. See #12946.

### Example

Bash:

```sh
az rest --method PATCH --url https://graph.microsoft.com/v1.0/applications/<object_id> --body '{
  "optionalClaims": {
    "idToken": [],
    "accessToken": [],
    "saml2Token": [
      {
        "name": "groups",
        "source": null,
        "essential": false,
        "additionalProperties": ["sam_account_name"]
      }
    ]
  }
}'
```

In PowerShell, make sure line breaks are removed and double quotes are escaped ([Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md)):

```pwsh
az rest --method PATCH --url https://graph.microsoft.com/v1.0/applications/<object_id> --body '{\"optionalClaims\":{\"idToken\":[],\"accessToken\":[],\"saml2Token\":[{\"name\":\"groups\",\"source\":null,\"essential\":false,\"additionalProperties\":[\"sam_account_name\"]}]}}'
```

**Comment by AndriiOmelianenko** [comment]
dear @jiasli, there is some confusion.
I've figured this part already. the problem is - that I had no intentions to update optional claims.

As I specified, I have tried to update **application roles only**.
`az ad app update --id <id> --app-roles @manifest.json`, and don't change optional claims whatsoever.
however seems this operation changes optional claims as well, while it shouldn't do that.

**Comment by jiasli** [comment]
> `saml2Token` is lost during `az ad app update` because Graph API v1.6 REST spec only allows `samlToken` and `saml2Token` is lost during serialization.

Allow me to explain how `az ad app update` works further:

CLI first gets the application JSON from AD Graph API v1.6, which has 
```
"optionalClaims": {
    "accessToken": [],
    "idToken": [],
    "saml2Token": [
    {
        "additionalProperties": [
        "sam_account_name"
        ],
        "essential": false,
        "name": "groups",
        "source": null
    }
    ]
},
```

Python SDK [`OptionalClaims`](https://github.com/Azure/azure-sdk-for-python/blob/fc2efcc6413da2dd0543940e5c398626f49b5b67/sdk/graphrbac/azure-graphrbac/azure/graphrbac/models/optional_claims_py3.py#L31) auto-generated by [REST spec](https://github.com/Azure/azure-rest-api-specs/blob/32e56f061668a1bf1eeca6209000fad4c09afca8/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L2583-L2589) only defines `saml_token`, but not `saml2_token`.

```py
    _attribute_map = {
    'id_token': {'key': 'idToken', 'type': '[OptionalClaim]'},
    'access_token': {'key': 'accessToken', 'type': '[OptionalClaim]'},
    'saml_token': {'key': 'samlToken', 'type': '[OptionalClaim]'},
}
```
When CLI deserializes the application JSON, `saml2Token` is not recognized and gets discarded.

If you would like to update the application without affecting the `saml2Token` field, using `az rest` to call Microsoft Graph API is the only solution.

**Comment by AndriiOmelianenko** [comment]
@jiasli I see. I personally expected it to do something like a patch operation on approles only, without touching other parts of manifest.

for now I've doing workaround like this:
`az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/{object_id} --headers Content-Type=application/json --body {"appRoles": {...}}`
and it works fine. it changes only approles in manifest, without changing anything else.

**Comment by jiasli** [comment]
I got your concern. This is definitely something that should be fixed. However, the reason is complicated (shown below). 

As [AD Graph API is already deprecated](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api), we are not actively maintaining the REST spec anymore. `az rest` should be the right path.

## Too long; don't read

If you are interested, the code (introduced by #9616) is actually at 

https://github.com/Azure/azure-cli/blob/74ea23bc805d57e3cf68cc9a4396141975acb580/src/azure-cli/azure/cli/command_modules/role/custom.py#L1037-L1043

which copies all existing properties into `ApplicationUpdateParameters` so that `az ad app update` complies with [generic update](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#generic-update-arguments), otherwise `--remove` will error out due to non-existing attribute. 

`saml2Token` will be saved in `additional_properties` of the parent `optional_claims` attribute. However, as the SDK doesn't define 
`additional_properties` for `OptionalClaims` like `RequiredResourceAccess` does,

[`OptionalClaims`](https://github.com/Azure/azure-sdk-for-python/blob/fc2efcc6413da2dd0543940e5c398626f49b5b67/sdk/graphrbac/azure-graphrbac/azure/graphrbac/models/optional_claims_py3.py#L28-L32): 

```py
    _attribute_map = {
        'id_token': {'key': 'idToken', 'type': '[OptionalClaim]'},
        'access_token': {'key': 'accessToken', 'type': '[OptionalClaim]'},
        'saml_token': {'key': 'samlToken', 'type': '[OptionalClaim]'},
    }
```

[`RequiredResourceAccess`](https://github.com/Azure/azure-sdk-for-python/blob/fc2efcc6413da2dd0543940e5c398626f49b5b67/sdk/graphrbac/azure-graphrbac/azure/graphrbac/models/required_resource_access_py3.py#L41-L45):

```py
    _attribute_map = {
        'additional_properties': {'key': '', 'type': '{object}'},
        'resource_access': {'key': 'resourceAccess', 'type': '[ResourceAccess]'},
        'resource_app_id': {'key': 'resourceAppId', 'type': 'str'},
    }
```

`saml2Token` gets lost during [serialization](https://github.com/Azure/msrest-for-python/blob/9b67deacc860e10cd95eb968cfa770fe475f7d8e/msrest/serialization.py#L508-L511), 

```py
                if attr_name == "additional_properties" and attr_desc["key"] == '':
                    if target_obj.additional_properties is not None:
                        serialized.update(target_obj.additional_properties)
                    continue
```

therefore also lost when the application is patched back:

```
{
    "appRoles": [],
    ...
    "optionalClaims": {
        "idToken": [],
        "accessToken": []
    },
    ...
}
```

### Possible Solutions

The REST spec of [`OptionalClaims`](https://github.com/Azure/azure-rest-api-specs/blob/32e56f061668a1bf1eeca6209000fad4c09afca8/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L2565-L2591) should define either:

- `saml2Token`
- `additional_properties`

so that `saml2Token` can be preserved during `az ad app update`.
