### ISSUE TITLE
az backup restore files mount-rp | --container-name

### ISSUE THREAD

**Issue by maxleonalbrecht** [Azure/azure-cli#16784]
After hours of testing I found the following error in the documentation.

The --container-name does not needs be the "Name of the backup container" as stated in the documentation.
I found out that the --container-name should be equal to the --item-name.

When you don't do that Az CLI will prompt to you, that the --item-name is wrong. (https://github.com/Azure/azure-cli/issues/16769) 

`az backup restore files mount-rp --container-name $vmName --item-name $vmName --rp-name $recoveryPointName --resource-group $resourceGroup --vault-name  $vaultName`

**Please** fix the documentation example of az backup restore files mount-rp and change the description of the required --container-name parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ed72499-d2ca-ba5b-78a1-e2c3cb22e729
* Version Independent ID: c19c500f-78d6-1f00-f42d-5492aa99257c
* Content: [az backup restore files](https://docs.microsoft.com/en-us/cli/azure/backup/restore/files?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/backup/restore/files.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/backup/restore/files.yml)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@maxleonalbrecht : Thanks. I have raised few queries in the other thread. Also mentioning it here since it could be useful for anyone viewing this thread alone.

In this case, the VM name, container name and item name are one and the same and I agree. But if you abstract this case out, and get the container name from the relevant command, the item name from the relevant command and pass to this command, it should work. So, curious to know what you were passing as container name before passing the VM name.

**Comment by pvrk** [comment]
@maxleonalbrecht : A gentle reminder to respond

**Comment by pvrk** [comment]
Closing the thread as mentioned in this [bug](https://github.com/Azure/azure-cli/issues/16769)
