### ISSUE TITLE
az account list still lists accounts after 'az logout'

### ISSUE THREAD

**Issue by aronchick** [Azure/azure-cli#16841]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az account list` still lists accounts after `az logout`

**To Reproduce**
`az account list`
`az logout`
`az account list`

**Expected behavior**

**Environment summary**
Installed via apt on Ubuntu 20.04

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
`az logout` only logs out the selected user.

https://github.com/Azure/azure-cli/blob/bfc0ef95c40040a0cc5c1a80d349e09ed8c7185f/src/azure-cli/azure/cli/command_modules/profile/custom.py#L190-L198

In order to log out all users, please use

```
az account clear
```

**Comment by aronchick** [comment]
Oh interesting – definitely didn’t understand that.

This does solve it (maybe it’s worth letting someone know after they logout that there are still other users logged in?)

**Comment by jiasli** [comment]
Thanks @aronchick for the feedback. We will definitely consider this nice idea as feature request.

**Comment by ssanbeg** [comment]
Another related issue to this. Assume I'm logged in as myself. Now I want to logout and re-login as a higher privileges user. Here is something that makes zero sense altogether:
`az account show
...
"user": {
    "name": "myself@somewhere.io",
    "type": "user"

az logout
az account clear

az account show
Please run 'az login' to setup account.

az login
https://login.microsoftonline.com/common/oauth2/authorize... and shows two accounts to choose, myself and my priveledged account. I select the latter and supply the 2FA information.

az account show
...
"user": {
    "name": "myself@somewhere.io",
    "type": "user"
`

Why ask for an account? The myself account cannot view anything sensitive.

**Comment by jiasli** [comment]
> az login
https://login.microsoftonline.com/common/oauth2/authorize... and shows two accounts to choose, myself and my privileged account. I select the latter and supply the 2FA information.

The web page displayed in https://login.microsoftonline.com/common/oauth2/authorize is controlled by Azure Active Directory (AAD), not Azure CLI. 

> Why ask for an account? The myself account cannot view anything sensitive.

Could you elaborate the question? If you logged in twice with different accounts, AAD's login page (https://login.microsoftonline.com/common/oauth2/authorize) will remember both of them and surely prompt you to select one.

**Comment by ssanbeg** [comment]
The issue is that the Azure cli logs me in with the 'myself' or user account. Or are you impying that the Azure cli has nothing to do with login but merely reads from AAD?

The result, either way, is that the wrong user is logged in.

**Comment by jiasli** [comment]
> ... are you impying that the Azure cli has nothing to do with login but merely reads from AAD?

Yes. Azure CLI uses [authorization code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) to read from AAD,

Could you clear the browser cache and run `az login` again? Maybe something wrong is happening with AAD's login web page.

**Comment by ssanbeg** [comment]
Incognito, nothing worked, except… clearing cache and losing the other 11
logins I had. Alright, thanks Jiashou. This is not a cli issue then.

Regards,
Scott


From: Jiashuo Li ***@***.***> ***@***.***>
Reply: Azure/azure-cli
***@***.***>
***@***.***>
Date: May 5, 2021 at 8:11:29 PM
To: Azure/azure-cli ***@***.***>
***@***.***>
Cc: Scott Sanbeg ***@***.***> ***@***.***>, Comment
***@***.***> ***@***.***>
Subject:  Re: [Azure/azure-cli] az account list still lists accounts after
'az logout' (#16841)

... are you impying that the Azure cli has nothing to do with login but
merely reads from AAD?

Yes. Azure CLI uses authorization code flow
<https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow>
to read from AAD,

Could you clear the browser cache and run az login again? Maybe something
wrong is happening with AAD's login web page.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-cli/issues/16841#issuecomment-833192037>,
or unsubscribe

**Comment by ssanbeg** [comment]
That did the trick.

**Comment by adrkar** [comment]
Hi, 3 years passed and still:
az logout  --> logs out specific user
az account clear --> logs out all users

Dont you think it would be much better to have for example:
az logout --> logs out specific user
az logout --all ---> logs out all users
??
Comparing this implementation to for example driving a car you have created something like:
PUSH gas pedal ---> increase the speed
RELEASE TRAILER pedal AND DROP some FUEL ---> lower the speed
you guys actually thinks before writing something ?
