### ISSUE TITLE
az resource update tag: Missing required property: aadProfile. Paths in payload: '$.properties.aadProfile' 

### ISSUE THREAD

**Issue by hetii** [Azure/azure-cli#16982]
Hello

I play with az to attach ARC enabled Kubernetes to insights.
in short when I add tag by:

`az resource update --set tags.logAnalyticsWorkspaceResourceId=$workspaceResourceId -g arc-cluster-rg -n arc-cluster --resource-type "Microsoft.Kubernetes/connectedClusters"`

The tag is added but it seam that below object
`  
"aadProfile": {
    "clientAppId": "",
    "serverAppId": "",
    "tenantId": ""
  }`

is removed from the resource and when I enter to arc cluster or his insights I see error like:

`Failed to create HTTP response as per the API specification with one or more errors. Please see details for more information. (Code: HttpResponsePayloadAPISpecValidationFailed) Missing required property: aadProfile. Paths in payload: '$.properties.aadProfile' (Code: ObjectMissingRequiredProperty)`

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@hetii Hi, in fact, the command `az resource update` queries the existing attributes of the target resource through `GET` request, adds the change of `--set` parameter, and finally updates the resource through `PUT` request. So I assume this is because the `GET` request of the service does not return this property. Could you please add parameter `--debug` to the executed command and rerun it, then send the printed debug information to me? My email address is Zhou.Xing@microsoft.com, thanks~

By the way, for the scenario when only the tags of resources are updated, I recommend using the command `az tag update --resource-id {resource-id} --operation replace --tags your_key=your_value`. Please have a try~
