### ISSUE TITLE
VMSS Flex does not require an image

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#17036]
## Describe the bug
In this release, we changed the --orchestration-mode parameter name from VM to flexible. But now CLI says I need to have an image. THis is incorrect; image is not required for VMSS Flex ode
**Command Name**
`az vmss create`

**Errors:**
```
incorrect usage: --image IMAGE | --attach-os-disk DISK
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create --orchestration-mode {} -g {} -l {} -n {} --platform-fault-domain-count {} --debug`

## Expected Behavior
Should create VMSS without needing image parameter
## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1

Extensions:
interactive 0.4.4

```

**Comment by yungezz** [comment]
HI @qwordy could you take a look?

**Comment by qwordy** [comment]
@fitzgeraldsteele Thank you for finding this bug. It is a validation rule for traditional VMSS. It should be updated. It blocks basic usage of VMSS Flex. I will prioritize it and try to fix it before Ignite. It is not hard to fix. I will update progress soon.
I searched test cases for VMSS Flex and found they are not enabled because the subscription is not allowed according to my comment in code. So this bug is not revealed. I run it again and no subscription error now.
