### ISSUE TITLE
az keyvault security-domain download does not support --id parameter for Managed HSM

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#17040]
## Describe the bug

**Command Name**
`az keyvault security-domain download`

**Errors:**
```
security_domain_download() got an unexpected keyword argument 'vault_base_url'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault security-domain download --sd-quorum {} --sd-wrapping-keys {} {} {} --id {} --security-domain-file {}`

## Expected Behavior
Managed HSM URLs used as --id should be supported - for example: https://mhsmdemo2.managedhsm.azure.net/
## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.0

```

**Comment by yungezz** [comment]
hi @houk-ms could you pls take a look?

**Comment by houk-ms** [comment]
I could reproduce the bug and will fix it.

About the design of  `--id`  parameter here, by CLI convention, `--id` is usually used to pass the ARM id of an Azure resource. So does it make more sense to accept an ARM id of the managed HSM here rather than the URL of the HSM? (I know with this design, the dogfood enviroment still cannot work.)

Or have you ever seen other keyvault commands using `--id` to pass a keyvault URL? What do you think? @amitbapat

**Comment by yungezz** [comment]
second on above. It's more appropriate to use `--hsm_url` to pass in hsm url, keep extensibility of `--id`.

**Comment by houk-ms** [comment]
Seems `az keyvault backup start` already use `--id` to accept the managedHSM url, but its help message is `Id of the HSM`. 

So, maybe we can support `--id` to accept the url for other necessary command and also update the help message of the parameter
