### ISSUE TITLE
[Context] Modify/set commands aren't consistent with the equivalent commands in the account group

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1712]
The `update` verb seems to be pretty prevalent throughout the CLI, so it was unexpected to see that the `az context` command group uses `modify` instead. Additionally, `az context` uses the `switch` verb, when `az account` uses `set` for (what I can tell) a conceptually similar action. 

Is there a reason for these differences? For ergonomic/muscle memory purposes, it would be great to have as much consistency in the CLI as possible.

**Comment by derekbekoe** [comment]
This is good feedback on the `az context` commands, thanks.

There is a bit of ambiguity between `az context`, `az account` and `az cloud` commands right now. This is partly due to the `az account` commands being ported directly from xplat CLI and xplat did not have a comprehensive 'multi-cloud' solution.
We plan to have `az` support Azure Stack and multiple API versions in the future so we needed a more comprehensive solution than what existed in xplat so the context/account/cloud commands in `az` is what we have right now.

Please comment on https://github.com/Azure/azure-cli/issues/1633 if you have any ideas on how you think this can be improved!

Also related to https://github.com/Azure/azure-cli/issues/1559
