### ISSUE TITLE
az login fails from Linux 

### ISSUE THREAD

**Issue by fboylu** [Azure/azure-cli#17273]
az login produces the following errors on Ubuntu 18.04, which was working since yesterday. 
![image](https://user-images.githubusercontent.com/11618557/110707262-0d818880-81c7-11eb-8ceb-59b896ccfdda.png)
![image](https://user-images.githubusercontent.com/11618557/110694087-30577100-81b6-11eb-9f72-0f804dd16d5e.png)
![image](https://user-images.githubusercontent.com/11618557/110694129-406f5080-81b6-11eb-8f31-465f526210ce.png)

**Comment by jiasli** [comment]
As the error indicated

![image](https://user-images.githubusercontent.com/11618557/110694129-406f5080-81b6-11eb-8f31-465f526210ce.png)

your login is blocked by [Conditional Access: Require compliant devices](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device) because Ubuntu is not a supported device.

Several solutions:

- `az login` with a user account on a supported system - Windows or MacOS, and make the device complaint
- Contact your tenant admin (MSFT IT if it is Microsoft tenant) to turn off **Conditional Access: Require compliant devices** for your account and Azure CLI
- `az login --service-principal` with a Service Principal which doesn't have compliance check (https://github.com/Azure/azure-cli/issues/16401#issuecomment-752837821)

**Comment by stuartatmicrosoft** [comment]
I am encountering this issue as well, however I am using an iPhone with the latest 14.4.1 iOS.

**Comment by stuartatmicrosoft** [comment]
I also get the message:

Sorry, but we’re having trouble signing you in.

AADSTS900561: The endpoint only accepts POST requests. Received a GET request.

**Comment by jiasli** [comment]
Putting the error message here for searching purpose:

> Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource.
