### ISSUE TITLE
unable to set tde-key to a customer managed key imported from another keyvault

### ISSUE THREAD

**Issue by manishtulsiani** [Azure/azure-cli#17337]
When trying to set the tde-key to a customer managed key that was imported from another keyvault, the az sql server tde-key set returns: key not found. 

The sql server and the keyvault are in the same subscription, same region, same resource group. And the key exists in the keyvault

az sql server tde-key set --server <sqlservername> --resource-group <resourcegroup> --server-key-type AzureKeyVault --kid <kid>

response:
"error":{"code":"ServerKeyNotFound","message":"The requested server key was not found."}}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea369391-5bd1-845a-83c8-f544d30728db
* Version Independent ID: 251e46ee-9f7a-2e64-8ae0-30837b23897b
* Content: [az sql server tde-key](https://docs.microsoft.com/en-us/cli/azure/sql/server/tde-key?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/sql/server/tde-key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sql/server/tde-key.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql

**Comment by sujitdmello** [comment]
Just wanted to add some more detail here as I was assisting @manishtulsiani with this issue.

This AZ command (**az sql server tde-key set**) fails when it is invoked on a _newly restored key_. The workaround is to use the Portal to set the TDE encryptor on this newly restored key, which works without errors. 

The odd thing is that after associating the customer key with the SQL TDE encryption via the Portal, the AZ CLI command above _works without error_. Even if the key is deleted/purged from Key Vault and restored again, the command will work thereafter on that key. So this issue is only when the AZ CLI command is issued on a newly restored customer key.

**Comment by sujitdmello** [comment]
Steps to reproduce:
- Create Azure SQL server instance - by default a system managed key is configured for encryption.
- Create Key Vault  A and Key Vault B in the same subscription as the SQL Server.
- Generate a new Key in Key Vault B.
- Take a Backup of the Key and Restore it into Key Vault A.
- Issue the **az sql server tde-key set** command to configure the SQL server to use the newly restored key in Key Vault A for TDE.
- It will result in a 'Key Not Found' error, although the key is clearly there.
- Go the SQL Server resource in the Azure Portal.
- Use the TDE menu and set the encryption ley to the newly restored key in Key Vault A.
- This will work as expected without any errors.
- Subsequently issuing the **az sql server tde-key set** command will work as expected.
