### ISSUE TITLE
Value should be set as required

### ISSUE THREAD

**Issue by gsuttie** [Azure/azure-cli#17461]
[Enter feedback here]
The docs say that for creating a keyvault secret that the -value isnt required but it is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az_keyvault_secret_set)
* Content Source: [latest/docs-ref-autogen/keyvault/secret.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault/secret.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @BigCat20196 could you pls help to have a look? thanks

**Comment by BigCat20196** [comment]
hi @gsuttie  The docs say that for creating a keyvault secret that -value isn required is because the parameter '--value' or '--file' can be selected in the optional parameter description, and they cannot exist simultaneously.
I guess when you use the 'az keyvault secret set' command and only enter the parameters ' -- name ' and '-- vault name',  an error statement like 'incorrect usage: [Required] - value | - file path' appears. It makes you feel uncomfortable.
 So what form do you want to upgrade the document to help us read and understand the use of commands? Please give your opinion on the revision. We are very grateful.

**Comment by gsuttie** [comment]
Hi There 

I think it needs to be a little clearer, if you try this

az keyvault secret set --name $secretname --vault-name $keyvaultName

It doesnt work so it needs to be pointed out that you should supply a --value or --file.

I see the same issue with az keyvault secret show if you dont supply a --vault-name

I think some examples of each should be included in the docs so that its clearer that in some instances if lets say you dont know the --id then you need to supply the --vault-name.
