### ISSUE TITLE
Update Kali Linux image version in Azure Marketplace

### ISSUE THREAD

**Issue by usrme** [Azure/azure-cli#17469]
**Is your feature request related to a problem? Please describe.**

When using the latest available Kali Linux image in the Azure Marketplace I have to go through an arduous and time-consuming process to update the operating system to the latest available version. This takes several hours and upgrade path is riddled with pitfalls as the image is so dated that you can't just do an `apt dist-upgrade` to get going, but instead have to go through multiple hoops.

**Describe the solution you'd like**

I would like for the Kali Linux image being offered in the Azure Marketplace be updated to the actually latest image which is at least **2021.1** (https://www.kali.org/releases/) or greater, if there is a new release in the interim.

**Describe alternatives you've considered**

I considered going through the process of creating my own Kali Linux image and uploading it, but given that some team in Azure has already done that once before then it makes sense, in my eyes, for that to be repeated by them to continue offering what is really the latest.

**Additional context**

```console
$ az vm image list --all --offer kali
[
  {
    "offer": "kali-linux",
    "publisher": "kali-linux",
    "sku": "kali",
    "urn": "kali-linux:kali-linux:kali:2019.2.0",
    "version": "2019.2.0"
  }
]
```

**Comment by yungezz** [comment]
route to compute service team. The offer is managed by service team.

**Comment by Drewm3** [comment]
Actually the offers in the marketplace are supported by the publishers. In this case the publisher is [Offensive Security](https://www.offensive-security.com/). The link the company has provided for support is: https://www.kali.org/community/. Please use that link to request for the publisher to update the image in the Azure Marketplace. 

I also suggest that you leave a review for other users at https://azuremarketplace.microsoft.com/en-us/marketplace/apps/kali-linux.kali-linux?tab=Reviews. The top review is already that the image is out of date, but it doesn't hurt to have multiple similar reviews to hopefully get the publisher to take action.

I am going to close this issue, though, because the Azure VM team is unable to update this image.

**Comment by usrme** [comment]
Just for the information of others: it now seems that the official Kali Linux image, outdated as it was, is now gone entirely from the Azure Marketplace. I've created a yet-to-approved thread in the [Kali Linux forums](https://forums.kali.org/forum.php) about this.

**Comment by ntegral** [comment]
Kali Linux on Azure is available in the Azure Marketplace and is accessible via RDP.

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/ntegralinc1586961136942.ntg_kali_linux?tab=Overview

**Comment by cloudu99** [comment]
Latest Kali Linux with GUI is available on Azure Marketplace. Check it out at - [Kali GUI Linux by Techlatest.net](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/techlatest.desktop-linux-kali)
GUI is accessible via VNC client and it comes with preinstalled kali tools.

![image](https://user-images.githubusercontent.com/128018630/225530481-054a7405-b234-49ac-8e01-c8de76af8332.png)
