### ISSUE TITLE
Passing empty string to 'az vm list --resource-group' acts as a wildcard

### ISSUE THREAD

**Issue by usrme** [Azure/azure-cli#17537]
## Describe the bug

**Command Name**
`az vm list --resource-group`

## To Reproduce:

Call `az vm list --resource-group` with an empty string in quotes:

- `az vm list --resource-group ''`

## Expected Behavior

For the command to **not** return all virtual machines in a subscription and for the command to display an identical error message as is the case when just `az vm list --resource-group` is called.

This can have **major** detrimental effects if, for example, the name of the resource group is a variable whose value is undefined and then the result of that command is used as an input to something like `az vm stop` or even `az vm delete`.

## Environment Summary

```text
Linux-5.11.10-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.2
Installer: RPM

azure-cli 2.21.0
```
## Additional Context

I have not tested other `list`-type sub-commands that also have a `--resource-group` parameter defined, but I believe those should be checked for this regression as well.

**Comment by yungezz** [comment]
hi @qwordy, could  you pls have a look?

**Comment by BigCat20196** [comment]
hi @usrme, thank you for your feedback.
When you pass empty string to 'az vm list --resource-group', it really return all VM information.
I went through the source code and it was designed like this. And only the 'az vm list' command allows this.

I tested the following lines of commands：
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

> az vm delete --resource-group '' -n MyVM
> az vm delete --resource-group MyResourceGroup -n ''
> az vm stop --resource-group '' -n MyVM
> az vm stop --resource-group MyResourceGroup -n ''

The results show that due to the lack of required parameters, these commands can not be executed correctly, which is the expected result.
So what you're worried about won't happen, and you can try it if you want.

**Comment by usrme** [comment]
Thanks for getting back to me, @BigCat20196!

However, I disagree with your conclusion and here's an example scenario I ran into (using Bash):

1. Create a variable with an empty string: `resource_group=''`
2. List virtual machine IDs and store result in a variable: `vm_ids=$(az vm list --resource-group "$resource_group" --query "[].id" --out tsv)`
3. Stop (for example, but I guess `delete` would work just the same) based off of IDs: `az vm stop --ids "$vm_ids"`

**Comment by qwordy** [comment]
@usrme, Azure CLI can configure a default resource group. Empty string is allowed in `az vm list` command so that it can remove the resource group value and list all VMs in a subscription. It is deliberate. We don't plan to change the behavior for now. We'll add more clarification in help message.
