### ISSUE TITLE
azure-cli-core is incompatible with modern pip

### ISSUE THREAD

**Issue by sodul** [Azure/azure-cli#17598]
We install many python packages as part of our internal use and the Azure packages are difficult to install with modern pip.
It seems to have problems with its own internal dependencies:

```
azure-cli 2.21.0 requires azure-mgmt-authorization~=0.61.0, but you have azure-mgmt-authorization 1.0.0 which is incompatible.
azure-cli 2.21.0 requires azure-mgmt-compute~=19.0.0, but you have azure-mgmt-compute 20.0.0 which is incompatible.
azure-cli 2.21.0 requires azure-mgmt-resource==12.0.0, but you have azure-mgmt-resource 16.0.0 which is incompatible.
azure-cli-core 2.21.0 requires cryptography<3.4,>=3.2, but you have cryptography 3.4.7 which is incompatible.
azure-cli-core 2.21.0 requires PyJWT==1.7.1, but you have pyjwt 2.0.1 which is incompatible.
```

Can the dependency requirements be relaxed so that pip will no longer have trouble installing the Azure stack?

See https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html for more context.

**Comment by jiasli** [comment]
On the contrary, these warnings are given by legacy `pip`. 

Take `cryptography` as an example:

1. `pip` first installs `cryptography` (without a version specifier), which is required by some underlying packages. It installs the latest `3.4.7`.
2. `pip` then installs `azure-cli-core` which requires `cryptography<3.4,>=3.2`.
3. The legacy `pip` is not smart enough to figure out a `cryptography` that satisfies both specifier, so it gives the warning.

The installation order matters:

1. `pip` first installs  `azure-cli-core` which requires `cryptography<3.4,>=3.2`. It installs `3.3.2`.
2. `pip` installs `cryptography` without a version specifier, which is required by some underlying packages.
3. This time it works because `cryptography<3.4,>=3.2` is smaller than `cryptography` (without a version specifier).

Please double confirm you have the modern `pip` installed:

```
pip --version
```

**Comment by sodul** [comment]
@jiasli We are using Python 3.94 with Pip 21.0.1.

In order to not get an error with modern pip we had to use the `--use-deprecated=legacy-resolver` command line option, without it installing our dependencies with the Azure packages resulted in an actual error. It seems that the rules are less strict in newer versions of the Azure API and we should be able to relax our requirements.txt file and drop the legacy resolver.

Thank you.

**Comment by jiasli** [comment]
`--use-deprecated=legacy-resolver` is exactly the cause for the warning message. You may remove `--use-deprecated=legacy-resolver` and see what error `pip` gives. If there is anything we can be of help, please kindly let us know.
