### ISSUE TITLE
Installing azure-cli in linux fails 403 Forbidden

### ISSUE THREAD

**Issue by fbuitron** [Azure/azure-cli#17666]
**Describe the bug**
According to the official docs: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script

This command is used for installing azure-cli in any linux distribution:

```
curl -L https://aka.ms/InstallAzureCli | bash
```

Yesterday that command in my CI (Codeship) was failing with the following error:

```
Get:26 https://cli-assets.heroku.com/branches/stable/apt ./ Packages [612 B]
Err:2 https://dl.bintray.com/apache/cassandra 21x InRelease
403 Forbidden [IP: 52.35.132.179 443]
```

I was digging all day yesterday and found out that Bintray was doing a brown-out session in anticipation of May1st deprecation: https://status.bintray.com/incidents/x1dvhtdqkcnx

**To Reproduce**
Cannot be reproduced now. It works. 
But will this work after May 1st Bintray deprecation?

**Environment summary**
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Additional context**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look?

**Comment by fengzhou-msft** [comment]
According to the log, it may be related to this repo: https://cli-assets.heroku.com/branches/stable/apt

Close as it's caused by other apt repos. Azure CLI is not using bintray for the debian package.

**Comment by jiasli** [comment]
As the error message indicates:

```
Err:2 https://dl.bintray.com/apache/cassandra 21x InRelease
403 Forbidden [IP: 52.35.132.179 443]
```

this issue is not caused by Azure CLI. Instead, it is caused by the invalid `https://dl.bintray.com/` added to the [SourcesList](https://wiki.debian.org/SourcesList):

- `/etc/apt/sources.list`, or
- `/etc/apt/sources.list.d/`

You may confirm this by checking these locations:

```
cat /etc/apt/sources.list
ls /etc/apt/sources.list.d/
```

You may delete the problematic `https://dl.bintray.com/`, then follow [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) to install Azure CLI from Microsoft Linux repo.
