### ISSUE TITLE
Unable to print special characters to console output

### ISSUE THREAD

**Issue by avanigupta** [Azure/azure-cli#17994]
## Describe the bug

I am from the Azure App Configuration team and I work on the `az appconfig` module. I noticed that when our output contains characters like `汉` or ` 𐐷` , CLI outputs a question mark character instead: ` �`.
Moreover, if we try to print a warning message containing one of these characters, we get an exception. Although this exception doesn't block the operation, it still pollutes the output and cannot be suppressed even if we supply `--only-show-errors` argument.

This is how we print a warning:

```
from knack.log import get_logger
logger = get_logger(__name__)
logger.warning(json.dumps(record, ensure_ascii=False))
```

**Errors:**
This is the exception:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u6c49' in position 127: character maps to <undefined>
Call stack:
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\code\appconfig\azure-cli\src\azure-cli\azure\cli\__main__.py", line 48, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "d:\code\appconfig\azure-cli\src\azure-cli\azure\cli\__main__.py", line 35, in cli_main
    return cli.invoke(args)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 650, in execute
    results, exceptions = self._run_jobs_serially(jobs, ids)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "d:\code\appconfig\azure-cli\src\azure-cli\azure\cli\command_modules\appconfig\keyvalue.py", line 139, in import_config
    need_kv_change = __print_preview(
  File "d:\code\appconfig\azure-cli\src\azure-cli\azure\cli\command_modules\appconfig\_kv_helpers.py", line 639, in __print_preview
    logger.warning(json.dumps(record, ensure_ascii=False))
Message: '{"key": "Chinese", "value": "�"}'
Arguments: ()

Do you want to continue?
 (y/n): y
```

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0 *

Extensions:
azure-devops 0.18.0

```

**Comment by jiasli** [comment]
> I noticed that when our output contains characters like `汉` or ` 𐐷` , CLI outputs a question mark character instead: ` �`.

This is because you are using the legacy terminal. Even though the terminal itself supports UTF-8, the default non-Unicode font (like [Cascadia Code](https://github.com/microsoft/cascadia-code) or [Consolas](https://docs.microsoft.com/en-us/typography/font-list/consolas)) doesn't define Unicode characters: 

![image](https://user-images.githubusercontent.com/4003950/117395809-4457ee80-af2b-11eb-99e2-c8850be00056.png)

In order to show Chinese characters, you need to use a Unicode font in the terminal like [SimSun](https://docs.microsoft.com/en-us/typography/font-list/simsun) (宋体) or [SimHei](https://docs.microsoft.com/en-us/typography/font-list/simhei) (黑体). 

![image](https://user-images.githubusercontent.com/4003950/117395471-8e8ca000-af2a-11eb-9cd4-c2ad9b863200.png)

We recommend using [Windows terminal](https://github.com/microsoft/terminal) which automatically falls back to a Unicode font if the current font doesn't have the Unicode character.

![image](https://user-images.githubusercontent.com/4003950/117395519-a8c67e00-af2a-11eb-9c9e-2fa8b18e4b04.png)

> ... it still pollutes the output and cannot be suppressed even if we supply `--only-show-errors` 

The reason why `--only-show-errors` doesn't work is because you have config option `logging.enable_log_file` enabled (see [CLI configuration values and environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables) for more info). The `UnicodeEncodeError` error is triggered by `RotatingFileHandler`:

https://github.com/microsoft/knack/blob/4830dab42bc77e99cb8805e49798f80e073a6f67/knack/log.py#L166

```py
logfile_handler = RotatingFileHandler(log_file_path, maxBytes=10 * 1024 * 1024, backupCount=5)
```

If you are using Windows with English as the system language (without UTC-8 enabled), the system encoding by default is `cp1252` (Western Europe), and Python will use `cp1252` as the file encoding. The error can be easily reproduced with 

```py
with open("test.txt", "w") as f:
    print(f.encoding)
    f.write("汉字")
```

```
cp1252
Traceback (most recent call last):
  File "D:/cli/testproj/test1.py", line 2, in <module>
    f.write("汉字")
  File "C:\Users\jiasli\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```

## Solution

You may adopt either of these solutions:
- Disable file logging with `az config unset logging.enable_log_file`
- Follow https://github.com/microsoft/knack/pull/178 to enable UTF-8 `cp65001` support on your Windows system.

## References

- Standard Encodings: https://docs.python.org/3/library/codecs.html#standard-encodings

**Comment by jiasli** [comment]
I have submitted PR https://github.com/microsoft/knack/pull/247 and https://github.com/Azure/azure-cli/pull/17996 to force to use UTF-8 for log files so that you don't need to disable file logging with `az config unset logging.enable_log_file` anymore.
