### ISSUE TITLE
Default subscription not being saved / respected

### ISSUE THREAD

**Issue by lazarillo** [Azure/azure-cli#18036]
## Describe the bug

When I log in to my tenant using `az` cli, the default subscription is always the "wrong" subscription (not the one that I want).  I will change the subsciption, but that will not be respected when I log out and log in again.

**Command Name**
```bash
az account set --subscription
```

**Errors:**

It is not an error, just that the subscription is not remembered.  See below.

## To Reproduce:

```bash
❯ az logout                                                    
~
❯ az login --tenant <removed for privacy> -o table               
The default web browser has been opened at https://login.microsoftonline.com/<removed for privacy>/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
You have logged in. Now let us find all the subscriptions to which you have access...
CloudName    HomeTenantId                          IsDefault    Name                     State    TenantId
-----------  ------------------------------------  -----------  -----------------------  -------  ------------------------------------
AzureCloud   <removed for privacy>                 True         SubscriptionA            Enabled  <removed for privacy>
AzureCloud   <removed for privacy>                 False        SubscriptionB            Enabled  <removed for privacy>
AzureCloud   <removed for privacy>                 False        SubscriptionC            Enabled  <removed for privacy>
~
❯ az account set --subscription "SubscriptionB"        
~
❯ az account show -o table                                       
EnvironmentName    HomeTenantId                          IsDefault    Name                     State    TenantId
-----------------  ------------------------------------  -----------  -----------------------  -------  ------------------------------------
AzureCloud         <removed for privacy>                 True         SubscriptionB            Enabled  <removed for privacy>
~
❯ az logout                                                      
~
❯ az login --tenant <removed for privacy> -o table               
The default web browser has been opened at https://login.microsoftonline.com/<removed for privacy>/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
You have logged in. Now let us find all the subscriptions to which you have access...
CloudName    HomeTenantId                          IsDefault    Name                     State    TenantId
-----------  ------------------------------------  -----------  -----------------------  -------  ------------------------------------
AzureCloud   <removed for privacy>                 True         SubscriptionA            Enabled  <removed for privacy>
AzureCloud   <removed for privacy>                 False        SubscriptionB            Enabled  <removed for privacy>
AzureCloud   <removed for privacy>                 False        SubscriptionC            Enabled  <removed for privacy>
~
```

## Expected Behavior

`az account set --subscription` is supposed to change my default subscription.  In the case above, once I set it to `"SubscriptionB"`, it should stay at that subscription even when I log out and log in again.

## Environment Summary
```
macOS-11.3.1-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
azure-devops 0.16.0
storage-preview 0.2.12
account 0.2.1

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is the designed behavior because `az logout` removes both

- token cache file `~/.azure/accessTokens.json`
- profile file `~/.azure/azureProfile.json`

`az login` simply selects the first `enabled` subscription returned by [Subscriptions - List](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list) REST API.

Also, there is no [Azure REST API](https://docs.microsoft.com/en-us/rest/api/azure/) to save and retrieve the selected subscription for a user.

Let me mark this issue as a feature request and see if other people want this behavior too.

**Comment by lazarillo** [comment]
So, @jiasli , are you saying that the following are true:

- There is no way to specify a default subscription that persists as I would wish (beyond `az logout`).
- There is no interest or effort within the MS / Azure team to address this so that the default subscription can persist.

It is not *the biggest* issue I have, needing to set this every time I work with `az`, but I would say that defaulting just to "the first subscription found" is not very user-friendly.

Could a config file be made that lives in `~/.azure`?  Maybe something like `userConfig.json` where a user can set all these things on a more permanent basis?

Also, as an aside, I therefore do not understand exactly what `az account set --subscription` is doing or what its purpose is.  Is it merely so that I do not have to pass `--subscription` with every `az` command I use?  I guess that is helpful, but then the command name is confusing.

**Comment by jiasli** [comment]
> There is no way to specify a default subscription that persists as I would wish (beyond `az logout`).

> I therefore do not understand exactly what `az account set --subscription` is doing or what its purpose is.  Is it merely so that I do not have to pass `--subscription` with every `az` command I use?

Exactly, `az account set --subscription` persists the subscription in `~/.azure/azureProfile.json` by setting `"isDefault": true` so that you don't need to specify `--subscription` for every `az` command. The default subscription is also persisted when you close and reopen the terminal.

> There is no interest or effort within the MS / Azure team to address this so that the default subscription can persist.

If I understand correct, what you want is to persist the subscription even after `az logout` and `az login`. This is not the designed behavior, as `az logout` is designed to be "forget everything about me". If we still persist the subscription after `az logout`, we will definitely need another file to save this info and another command or parameter to clear that info. This makes `az` overly complex (2 levels of subscription persistence) and more difficult to understand. 

The same behavior also applies to Azure PowerShell [`Connect-AzAccount`](https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-5.9.0) and [`Disconnect-AzAccount`](https://docs.microsoft.com/en-us/powershell/module/az.accounts/disconnect-azaccount?view=azps-5.9.0).

**Comment by lazarillo** [comment]
Hi @jiasli , yes, you understood me correctly:  I would like for metadata to persist - at least locally on my machine - beyond `az logout`.  Current behavior is in fact persisting information right now:  it persists the "decision" to choose the first subscription listed in my account alphabetically.

Regardless, I understand your point that it makes `az` overly complex; I will create an `az` alias on my machine to simplify this process.

Thanks for your patience and understanding in working with me!  😄

**Comment by lazarillo** [comment]
Oops, I forgot to close the issue with my last comment.  😉

**Comment by jiasli** [comment]
> I would say that defaulting just to "the first subscription found" is not very user-friendly.

We are considering not to select the default subscription in the future: https://github.com/Azure/azure-cli/issues/27915. Any idea or feedback is welcome!
