### ISSUE TITLE
Trying to get a reference to Workspace fails when deploying using CLI

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/azure-cli#18175]
My scoring function needs to refer to a registered Dataset for which I need a reference to the AzureML Workspace object. When including this in the `init()` function of scoring script it  gives the following error:

```
 "code": "ScoreInitRestart",
      "message": "Your scoring file's init() function restarts frequently. You can address the error by increasing the value of memory_gb in deployment_config."
```

On debugging the issue is:

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code [REDACTED] to authenticate.
```
How can I resolve this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110fd5df-299e-f288-867f-c307a2f2ba9f
* Version Independent ID: ac8d15ce-b17b-8da8-8d60-cf98d448c9bd
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by harneetvirk** [comment]
Looks like, interactive authentication is being used in the script. Could you switch to automated authentication like service principal authentication
Reference: https://docs.microsoft.com/azure/machine-learning/tutorial-pipeline-batch-scoring-classification

**Comment by anirbansaha96** [comment]
> Looks like, interactive authentication is being used in the script. Could you switch to automated authentication like service principal authentication
> Reference: https://docs.microsoft.com/azure/machine-learning/tutorial-pipeline-batch-scoring-classification#publish-and-run-from-a-rest-endpoint

@harneetvirk Adding SPN credentials in Scoring Script is not a safe option for me. While deploying the model that is the only viable option. It will be difficult.

**Comment by harneetvirk** [comment]
@anirbansaha96 : You can mount the dataset and pass the mounted path as an argument to the training script
Here is an example on how to train with datasets: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/train-with-datasets/train-with-datasets.ipynb

**Comment by needuv** [comment]
@anirbansaha96- trying to understand your scenario a bit more. From the information you've provided here, it seems like you already have some data, and you want to test your model against that data, which sounds like offline batch scoring. You can refer to the docs here: https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-pipeline-batch-scoring-classification on how to do batch scoring. This kind of model scoring lets you access datasets registered in your workspace inside your scoring script.

**Comment by anirbansaha96** [comment]
I want real-time inferencing. In my score.py script, I want to refer to a Registered Dataset to get populate some values required for the solution.

**Comment by needuv** [comment]
If this is a `FileDataset`, you can use either the `mount()` or `download()` functions of the `FileDataset` class: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets#explore-data to download or mount a dataset that you've already registered inside your scoring script. Here is the documentation for `FileDataset` for your reference: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.filedataset?view=azure-ml-py#download-target-path-none--overwrite-false-. If your dataset is of type `TabularDataset`, you can convert the dataset into another format your scoring script understands, such as a pandas `DataFrame`: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.tabulardataset?view=azure-ml-py#to-pandas-dataframe-on-error--null---out-of-range-datetime--null--. 

However, you will also need to use a different authentication method (i.e. not interactive authentication) for retrieving your workspace information inside your scoring script. Otherwise, you will still run into your initial issue of your scoring script's `init()` restarting too frequently. We have a notebook tutorial describing some of the different authentication methods in AzureML: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb. We additionally have some documentation here on authentication:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication.

**Comment by ynpandey** [comment]
@anirbansaha96 Please let us know if you were able to resolve this issue based on previous answer(s).

**Comment by anirbansaha96** [comment]
Using Service Principal Authentication is not a proper alternative for me.
