### ISSUE TITLE
Error on creating VM from azure container instance using ARM template

### ISSUE THREAD

**Issue by sarthakvijayvergiya** [Azure/azure-cli#18223]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az create group deployment exit without giving output result
**To Reproduce**
az deployment group create \
                        --resource-group "$RESOURCE_GROUP" \
                        --template-uri "https://aka.ms/iotedge-vm-deploy" \
                        --parameters dnsLabelPrefix="$PREFIX" \
                        --parameters adminUsername="$ADMIN_USER_NAME" \
                        --parameters deviceConnectionString=$(az iot hub device-identity connection-string show --device-id "$DEVICE_NAME" --hub-name "$IOTHUB_NAME" -o tsv) \
                        --parameters authenticationType='password' \
                        --parameters adminPasswordOrKey="$ADMIN_PASSWORD" --query 'properties.outputs."public SSH".value' -o tsv

**Expected behavior**
It should give output 

**Environment summary**
Azure container instance with azure cli 2.24.0 version 

**Additional context**

**Comment by yonzhan** [comment]
ARM

**Comment by sarthakvijayvergiya** [comment]
@yonzhan Is this a bug?
If yes then when can we expect a fix ?

**Comment by yonzhan** [comment]
@zhoxing-ms will take a look

**Comment by zhoxing-ms** [comment]
@sarthakvijayvergiya Hi, at present, the command `az deployment create` can output the result normally in my side, but there is a parameter `--query` which will filter the original result. So it may be because the output result does not meet the data required by `--query 'properties.outputs."public SSH".value'`

Could you please add the parameter `--debug` after the executed command and send the printed information to me? My email address is Zhou.Xing@microsoft.com, thanks

**Comment by zhoxing-ms** [comment]
Since I haven't received reply for a long time, so I close this issue first. If you still have this problem, please email me the specific information and I will reopen this issue
