### ISSUE TITLE
Remove colors from Azure CLI text output

### ISSUE THREAD

**Issue by Dragas** [Azure/azure-cli#18298]
I am appalled by the usage of colors to denote types of output in azure cli on bash. Having light background in terminals makes it impossible to read what cli is outputting.
![image](https://user-images.githubusercontent.com/6078508/120118834-4bc28e80-c19d-11eb-9738-f6084b01a644.png)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
You may turn off color with 

```
az config set core.no_color=true
```

To turn color back on, use

```
az config unset core.no_color
```

You may also switch to the experimental **light** theme:

```
az config set core.theme=light
```

To reset to the default **dark** theme, use

```
az config unset core.theme
```

This feature is not yet documented.

**Comment by Dragas** [comment]
Why is this feature enabled by default to begin with?

**Comment by jiasli** [comment]
Most users of Azure CLI are using a standard dark theme terminal to invoke Azure CLI. We are aiming to provide better readability on a dark theme terminal.

Previously the color for warning is **yellow** and we changed it to **bright yellow** because of the low accessibility of yellow on dark theme terminals, according to user experience study (https://github.com/Azure/azure-cli/pull/16258).

If bright yellow is not readable on PyCharm, this problem should be reported to PyCharm as well to make the visibility of bright yellow better. 

We will also evaluate your feedback and make better documentation regarding this topic as well.

**Comment by pamelafox** [comment]
I am experiencing this issue as well, it is nearly impossible to read the text. I didn't even realize there'd be a command to change the colors, as I've never had to do that with other CLI tools, so I didn't go looking. I did just do a web search now for what I might have searched, and it looks like I wouldn't have found the right command anyway.

I am on a Mac OS X, which defaults to a white terminal, so I think many Mac users would be affected, especially those that are new to develop and environment customization.

Is there some way that you can detect the terminal mode and change the colors accordingly? In my terminal, "defaults read com.apple.Terminal " does give back a JSON of settings with the colors, though you'd have to wrap that in a guard since it wouldn't work cross-OS.

Or perhaps if you detected someone was on a Mac, you could suggest the configure command the first time they run an az command.

**Comment by charris-msft** [comment]
@yonzhan - should we open a new issue to track @pamelafox's feedback about default experience on Mac?

**Comment by jiasli** [comment]
@pamelafox, @charris-msft, I have proposed a solution in https://github.com/Azure/azure-cli/pull/24804. However, using `light` theme by default may also cause readability issues on dark backgrounds, so I am still hesitating on whether that change should be made.
