### ISSUE TITLE
Each of your CLI descriptions could sorely use an example output!

### ISSUE THREAD

**Issue by sonnyrajagopalanuptycs** [Azure/azure-cli#18335]
[Enter feedback here]

Each of your CLI descriptions could sorely use an example output!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by rayoef** [comment]
Thank you for your feedback. At this time, we haven't been able to review this recommendation, and we apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. 

#please-close

**Comment by tamram** [comment]
#please-close
