### ISSUE TITLE
[App Service] Allow configuring auto-scaling rules

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1834]
The `az appservice plan update` command allows you to manually scale the number of workers up and down, however, there doesn't appear to be a way to configure the auto-scale rules like you can in the portal. It would be great if this capability was exposed via the CLI.

**Comment by yugangw-msft** [comment]
Please check out `az monitor autoscale-settings create` command, which got in this week.

**Comment by tjprescott** [comment]
We should leave this issue open to track implementation of the webapp autoscale convenience commands, just as we have an issue open for VMSS autoscale commands.

**Comment by yugangw-msft** [comment]
(I should have put in more comment when i closed it.)
I am fine to leave it open. The difference from vmss is for a webapp, portal doesn't offer the simple gesture of turning on "auto-scale" which can be modeled after using a convenient method like we did for VMSS.  At the same time there are [lots of](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-monitor) metrics you can create scale rule for a web. Since webapp stays at a higher stack, limiting to CPU only metric  won't get the command any useful

**Comment by tjprescott** [comment]
Well, VMSS won't be limited to a single profile either--it will look more like webapp--which is why we delayed the autoscale commands for VMSS. Once we have the new profiles from the portal team, we can try and design a convenience command that will cover 80% of the scenarios. For advanced scenarios there's always the raw Monitor autoscale commands.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by ahmedelnably** [comment]
Reopening as this is still going to be done

**Comment by yugangw-msft** [comment]
@troydai, please let us know the right set of monitoring metrics we should pick up and the right command pattern we should follow.

**Comment by yugangw-msft** [comment]
this is tracked through #5690 now
