### ISSUE TITLE
The test log generated by nosetest is empty

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1847]

**Comment by mayurid** [comment]
@troydai : Moved to S13. Lets discuss if you have concerns,

**Comment by tjprescott** [comment]
ETA on this? Because of the cluttered output on test failure (#2513) when I run all tests, I can only see the output for the last test because it prints so much stuff that the earlier stuff is pushed out of the window buffer. This wouldn't be as much of a problem if I could at least look in these logs, but they are always empty.

**Comment by troydai** [comment]
I can pick this up later this week.

**Comment by mayurid** [comment]
@troydai : i have moved this to the current sprint to close on this. Please close if already addressed.

**Comment by troydai** [comment]
Many things have changed since this issue was filed:
1. The trace logs are removed from the test output. Today only test names and failed tests' stack traces are printed.
2. The xunit log can't be generated when tests are run in parallel, that is the default setting. To mitigate, you can feed `--non-parallel` to the `run_test` command.

Given the item has greatly improved the test results readability. I'll close this issue now. @tjprescott please feel free to update or reopen this issue if you deem fit.
