### ISSUE TITLE
Inconsistent naming between server/SDK properties and CLI arguments.

### ISSUE THREAD

**Issue by rohitsud** [Azure/azure-cli#1853]
When omitting the resource ID param, we get an error 
> The **'resourceTargetId'** property of endpoint 'work' is invalid or missing. The property must be specified only for the following endpoint types: AzureEndpoints, NestedEndpoints. You must have read access to the resource to which it refers.

However, in other error strings the param is different.

> Incorrect options for profile routing method 'Priority' and endpoint type 'nestedEndpoints'.
Supply the following: **--target-resource-id**, --min-child-endpoints

**Comment by tjprescott** [comment]
The second message is generated by the CLI's validation. The first looks like a server response. Were type of endpoint were you trying to create?

**Comment by rohitsud** [comment]
The issue is that the naming is not consistent - see word ordering.

**Comment by tjprescott** [comment]
You are correct, but this reflects a difference between the property name on the server and the argument name in the CLI, which is not specific to Traffic Manager.

I'll reopen this and generalize it so that we can decide if there's a good solution for "translating" server side or SDK property names into CLI arguments for a more consistent experience.

**Comment by yugangw-msft** [comment]
let us live with it till we have more user voices
