### ISSUE TITLE
`az ad app permission admin-consent` results in a "Not Found" error

### ISSUE THREAD

**Issue by Michael-Coetzee** [Azure/azure-cli#18603]
## Describe the bug

**Command Name**
`az ad app permission admin-consent`

**Errors:**
```
Not Found(<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `API=00000002-0000-0000-c000-000000000000`                                                                          
- `RWDDR=78c8a3c8-a07e-4b9e-af1b-b5ccab50a175=Scope`                                                                   
- `RWDR=aaff0dfd-0295-48b6-a5cc-9f465bc87928=Role`                                                                     
- `RWDDS=78c8a3c8-a07e-4b9e-af1b-b5ccab50a175=Role`                                                                    
- `az ad app permission add --api $API --id <sp-id> --api-permissions $RWDDS $RWDDR $RWDR`

- `az ad app permission admin-consent --id {}`

## Environment Summary
```
Linux-5.12.1-arch1-1-x86_64-with-glibc2.33
Python 3.9.5
Installer: 

azure-cli 2.25.0

Extensions:
azure-devops 0.17.0
aks-preview 0.4.57
log-analytics-solution 0.1.1
vm-repair 0.3.2
log-analytics 0.2.1

```
## Additional Context

Adding graph api directory read write permissions. 
Also tried with microsoft graph - same error as above.
Trying across different tenants also yield the same error.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
## Cause

This issue is caused by the sudden shutdown of `https://main.iam.ad.ext.azure.com/api/RegisteredApplications/{}/Consent?onBehalfOfAll=true` internal AAD API (https://github.com/Azure/azure-cli/pull/8804). We are communicating with AAD service team for a solution.

## Workaround

For now, you may follow https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 and

- use `az ad app permission grant` to grant **Delegated Permissions**
- use `az rest` to directly call Microsoft Graph API to grant **Application Permissions**

**Comment by jiasli** [comment]
The recent change on the AAD API `https://main.iam.ad.ext.azure.com/` has been rolled back and `az ad app permission admin-consent` is now working again. 

Please retry the command and let us know if the issue is resolved. Thank

**Comment by jiasli** [comment]
A hotfix has been deployed to the AAD API. `az ad app permission admin-consent` should now be working.

Please retry the command and let us know if the issue is resolved. Thanks.

**Comment by b3ndill** [comment]
We've tested the original command (`az ad app permission admin-consent`) that was failing in our workflows and it is now working again. Thanks a lot for the fast turn-around!

**Comment by petereitz** [comment]
Confirmed working in our workflow.  Thanks @jiasli.

**Comment by Michael-Coetzee** [comment]
Thanks, indeed working now.

**Comment by Yvand** [comment]
@jiasli I used your [great comment](https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479) to grant permissions using "az rest" and it works great.
But then, I did a diff of the appmanifest.json: If permissions are granted from the UI (in app registration), they can be seen in "requiredResourceAccess" (it's empty if using "az rest").
And when granting permissions using "az rest": In App registration > "API permissions": Permissions appear under "Other permissions granted for Contoso"

I think it is because permission is granted to service principal VS permission granted to app registration. But I wonder if this is of any importance?

**Comment by jiasli** [comment]
@Yvand, I am glad to know it works for you.

> But then, I did a diff of the appmanifest.json: If permissions are granted from the UI (in app registration), they can be seen in "requiredResourceAccess" (it's empty if using "az rest").
> And when granting permissions using "az rest": In App registration > "API permissions": Permissions appear under "Other permissions granted for Contoso"

This is because you didn't explicitly require permissions for the app via `requiredResourceAccess` first. `requiredResourceAccess` is a property of the app. It is added when you click the **Add a permission** button in Azure Portal:

![image](https://user-images.githubusercontent.com/4003950/123729014-deeb0300-d8c6-11eb-8e14-990a514d9570.png)

When using Azure CLI, you may do the same thing with `az ad app update --required-resource-accesses` (and of course `az rest` with [Update application](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http) API).

In Azure Portal, if you click the **three dots (...)** and then **Remove permission**, the permission will be removed from `requiredResourceAccess`:

![image](https://user-images.githubusercontent.com/4003950/123729195-2c677000-d8c7-11eb-96c6-138be4e0d38f.png)

Then you will see the same effect when you only grant permissions using `az rest` - the removed permission will appear under **Other permissions granted for <tenant_name>**:

![image](https://user-images.githubusercontent.com/4003950/123729239-38533200-d8c7-11eb-8b20-3100fb5db632.png)

For other questions regarding `az ad` or `az rest` with Microsoft Graph API, please don't hesitate to create a new issue. I would be more than happy to help. 😊

**Comment by Yvand** [comment]
@jiasli with all your comments and explanations, all of this makes a lot more sense to me now.
You should make a documentation out of your multiple comments, that would be very valuable to many people, many thanks for your time to write such clear explanations!
