### ISSUE TITLE
az account management-group = too many 500 error responses

### ISSUE THREAD

**Issue by dmraymond** [Azure/azure-cli#18617]
## Describe the bug

**Command Name**
`az account management-group list`

**Errors:**
```
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.Management/managementGroups?api-version=2018-03-01-preview (Caused by ResponseError('too many 500 error responses'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account management-group list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
@jiasli  for awareness

**Comment by jiasli** [comment]
The error `Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.Management/managementGroups?api-version=2018-03-01-preview (Caused by ResponseError('too many 500 error responses'))` is caused by ARM service.

You may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) and provide the `--debug` log. A support engineer will gladly help you with it.
