### ISSUE TITLE
[DNS] Deleting a zone that does not exist gives no feedback

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1865]
If I delete a zone that does not exist, I get no feedback. The command just exits without giving any kind of message at all. That leaves the user unclear as to the status.

You should be able to detect this case via the HTTP status codes, and give an appropriate message (e.g. 'DNS zone <...> in resource group <...> not found.')

**Comment by tjprescott** [comment]
The service returns a 204 response, which is acceptable to the SDK. What arrives at the CLI is simply empty content, which is the same as when a delete is successful. At the CLI level we cannot examine the HTTP error codes and thus have no way to distinguish between the two cases.

Most services return a 404 if the targeted resource is not found. This translates to a CloudError in the SDK which surfaces as an error message in the CLI.

**Comment by jtuliani** [comment]
The Resource Provider contract is very explicit about this: Resource Providers should return 204 and not 404 when a call is received to delete a resource that does not exist.

The only case where 404 is returned is when a call is made to delete a resource from a resource group that does not exist. In this case, ARM returns the 404, and the call never reaches the Resource Provider.

Why can't the CLI give a message in this case? A normal delete (of a resource that does exist) returns a message, after all, so the CLI is already differentiating 200 from 204.

**Comment by tjprescott** [comment]
You are correct--I tried a variety of deletes and they all exhibit the same behavior. If you try and delete something that does not exist, you get nothing. DNS is unique in that the majority of resource providers also return the same nothing when the delete is successful, whereas DNS returns an object.

If we were to change this behavior, we would presumably do so for the entire CLI. @johanste, do you have an opinion on this?

**Comment by johanste** [comment]
Unfortunately, I believe that the *correct* way of supporting this is to support if-match on the service side, which would have resulted in a 412/precondition failed from the service. Which I don't believe that the service supports today. 

I would really like to avoid doing double-pumps (query if it exists and then do a delete) since that would be a performance issue in general.

**Comment by johanste** [comment]
...and reading up on RPC, I believe that the guidance that @jtuliani refers to is 204 on well formed delete for non-existent resource and 200 otherwise (or a full 202/accepted dance). We would have to check how many SDKs actually conform to this (the service may, but the swagger that drives the SDK may be incorrectly authored) before we can make a wholesale change...

**Comment by johanste** [comment]
@jtuliani, which specific endpoint is it that returns the 204 in this specific use case?

**Comment by jtuliani** [comment]
Azure DNS does support If-Match on zone delete (and record set delete), so if you can use that, that's fantastic!

Azure DNS returns 204 from https://docs.microsoft.com/en-us/rest/api/dns/zones#Zones_Delete (and also from https://docs.microsoft.com/en-us/rest/api/dns/recordsets#RecordSets_Delete)
