### ISSUE TITLE
az acs kubernetes install-cli should default to %programfiles%\kubernetes\kubectl.exe

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1871]
According to the docs: ```az acs kubernetes``` install-cli installs to ```C:\Program Files\kubectl.exe```
Installs should not place exe's in the root of program files.
They should be placed in a sub directory. 
Suggest:
```C:\Program Files\kubernetes\kubectl.exe```
Or, since this requires administrative privileges, perhaps install in a per user directory, that's already on path.

**Comment by brendandburns** [comment]
@SteveLasker Do you think that we should default to install system wide or install per-user?

Thanks
--brendan

**Comment by SteveLasker** [comment]
@brendandburns considering we're trying to avoid admin requirements, perhaps moving to per-user is a better model. It's one less place a developer requires admin privileges to get started. It also means they're more secure by default if they don't require admin rights.

**Comment by sergiomcalzada** [comment]
And should be added to PATH

**Comment by squillace** [comment]
+1 on both, FWIW.

**Comment by sabbour** [comment]
@brendandburns any updates on this? Currently running **az acs kubernetes install-cli** then trying to o something like **az acs kubernetes browse** results in
**Can not find kubectl executable in PATH**

**Comment by kirodge** [comment]
I had the same error as @sabbour. Even though Windows was able to locate kubectl.exe from the command prompt, **az acs kubernetes browse** resulted in **Can not find kubectl executable in PATH** (from the same command prompt).

For me the culprit was the case sensitive **os.path.exists** in custom.py. My PATH contained C:\Windows\system32\ while **where kubectl.exe** returned C:\Windows\System32\kubectl.exe

(See **which** in azure-cli/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py for the usage of the case sensitive os.path.exists)

**Comment by dazdaz** [comment]
I have the same issue with az cli 2.0.21, my workaround is

I copied kubectl.exe into C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin

**Comment by MichalKoscielniak** [comment]
So ... is there a workarround for this ? I'm trying to install cli but i can't because of this error. ( when i specify install-location the same issue appears )

**Comment by yugangw-msft** [comment]
Hi folks, because I am fixing related #6928, I will also address this one as the potential fix will be the same. Here are my ideas:

1. kubectl.exe will be copied to user home folder, say “c:\users\jon\\.azure-kubectl”. Right now copying to “program files” is not ideal as it is still not in search PATH and also doing it requires elevation.
2. After download, CLI will check whether it is in OS's PATH env variable. If not (likely first time download),  CLI will emit out the following warning text:
```
Please add "C:\Users\jon\.azure-kubectl" to your search PATH so the `kubectl.exe` can be found. 2 options:
    1. Run "set PATH=%PATH%;C:\Users\jon\.azure-kubectl" or "$env:path += 'C:\Users\jon\.azure-kubectl'" for PowerShell. 
       It is good for the current command session.
    2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables",
       and re-open the command window. It is once for all.
```
If you do the 2nd, then CLI will never warn any more.
Letting CLI update the PATH is doable by tweaking the PATH's registry value. I am not so sure whether we need to go that far, also, users still need to reopen the command window unless CLI broadcasts it which is a native Win/API invocation. But anyway, if you really like CLI to do this, please let me know.

**Comment by kishoreachint** [comment]
Hello I got the same issue. I re-install the azure cli by using az aks install-cli. After that added the same in environmental variable. Make sure that you add the C:\Users<user>.azure-kubectl" to your search path.

For current session, run Run "set PATH=%PATH%;C:\Users\achin.azure-kubectl" or "$env:path += 'C:\Users\achin.azure-kubectl'" for PowerShell.

For future, Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window.

**Comment by meghad1906** [comment]
Hello I am getting the same issue. I re-install the azure cli also and while fire this command  az aks install-cli. getting below 

C:\Users\dell>az aks install-cli Downloading client to "C:\Users\dell\.azure-kubectl\kubectl.exe" from "https://storage.googleapis.com/kubernetes-release/release/v1.16.3/bin/windows/amd64/kubectl.exe" Please add "C:\Users\dell\.azure-kubectl" to your search PATH so the `kubectl.exe` can be found. 2 options: 1. Run "set PATH=%PATH%;C:\Users\dell\.azure-kubectl" or "$env:path += 'C:\Users\dell\.azure-kubectl'" for PowerShell. This is good for the current command session. 2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window. You only need to do it once
