### ISSUE TITLE
"Value cannot be null" error when deleting AAD applications

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-cli#18738]
**Describe the bug**
I'm running following command to delete some test AAD applications
`az ad app delete --id {client id}`
However, I cannot delete some of my applications with following error:
```
Value cannot be null.
Parameter name: requestContext
```
I have tried to pass both client id and object id to the command, they all failed. But I can delete same AAD application in Azure Portal.

**To Reproduce**
Not sure how you can reproduce this error. Maybe you can try to delete your test applications and see whether any application has same issue.

**Expected behavior**
The `az ad app delete` command can delete the application successfully.

**Environment summary**
Azure CLI 2.24.1, installed via winget.
OS: Windows 10 Build 19043.1052
Shell Type: Powershell 7.1.3

**Additional context**
N/A

**Comment by yonzhan** [comment]
Graph

**Comment by jiasli** [comment]
I have observed this error myself when I try to delete an AAD application that are created by Azure Portal through Microsoft Graph API [Create application](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http).

`az ad app delete` still uses AD Graph to delete the application, so it seems **one can't use AD Graph to delete some applications created by Microsoft Graph**, though I don't know the exact root cause.

I then used `az rest` to invoke Microsoft Graph API [Delete application](https://docs.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-1.0&tabs=http) and the application is successfully deleted:

```
az rest --method DELETE --url https://graph.microsoft.com/v1.0/applications/{application_object_id}
```

The `application_object_id` can be retrieved with 

```
az ad app show --id <appId/clientId> --query objectId --output tsv
```

**Comment by blackchoey** [comment]
Thank you @jiasli ! The az rest way you shared solved my problem. Closing this issue.
