### ISSUE TITLE
 az backup container unregister doesn't work

### ISSUE THREAD

**Issue by mimergel** [Azure/azure-cli#18745]
**Describe the bug**
The command " az backup container unregister " doesn't remove the backup data from the vault. Example: 

az backup protection disable  --container-name "IaasVMContainer;iaasvmcontainerv2;rg-sap-sid;saptestsid" -g "SAPonAzureFrance" -v "rsv-sap-francecentral-001" --item-name saptestsid --yes
=> this works OK

 az backup container unregister --container-name "IaasVMContainer;iaasvmcontainerv2;rg-sap-sid;saptestsid" -g "SAPonAzureFrance" -v "rsv-sap-francecentral-001" --backup-management-type AzureIaasVM --yes
=> this has no effect, expected outcome is that the backup item is removed from the vault

**To Reproduce**
see description above

**Expected behavior**
the Backup Items (Azure Virtual Machine) "saptestsid" is removed from the vault

**Environment summary**
Standard OS IaaS backups.

**Additional context**
The procedure is used in automation scripts where VMs are automatically deployed and after some time removed. With this bug the backup items are not properly cleaned up and there stays a lot of non-existing VMs and backup data in the vault.

**Comment by yonzhan** [comment]
route to service team

**Comment by pvrk** [comment]
@mimergel : To delete backup items, we have the 'az backup protection disable' command. You need to disable protection and delete data (check whether soft-delete is disabled) for ALL items within a container and THEN we can unregister a container. The purpose of 'unregister' command is to remove any link from the container to the vault and allow it to be protected to another vault. In case of Azure VMs, since the backup item and container are the same, once you disable the protection, unregister happens automatically. Unregister is required for SQL/HANA/AFS backups since backup item and container are different.

In your case, to clean-up vault after a test run for Azure VMs,

1.  First make sure that the 'soft-delete' feature is disabled using [```az backup vault backup-properties set``` command](https://docs.microsoft.com/cli/azure/backup/vault/backup-properties?view=azure-cli-latest#az_backup_vault_backup_properties_set)
2. Delete all backup items along with backed up date using [```az backup protection disable``` command](https://docs.microsoft.com/cli/azure/backup/protection?view=azure-cli-latest#az_backup_protection_disable) with delete-backup-data as true.
3. Then unregister all containers using the ```az backup container unregister``` command, if there are any non IaaS VM backups
4. Delete the vault.

**Comment by pvrk** [comment]
@mimergel : Can you please confirm if this explanation makes sense and that we can close the issue?

**Comment by mimergel** [comment]
@pvrk: explanation makes perfectly sense, thanks! I was missing the option: "--delete-backup-data true". With this option now everything works as expected.
