### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by aishanibhalla** [Azure/azure-cli#18764]
[The comands](https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest#az-ml-endpoint-delete) on the page won't redirect me to the full documentation https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest#az_ml_endpoint_delete ; looks like the links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7cdb58-f4a5-8eb1-3e41-cb86398c04a2
* Version Independent ID: a830092e-9e53-4996-70f6-f8caf123ec21
* Content: [az ml endpoint](https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
I can repro. This issue doesn't only happen on `ml`, but on all commands.

In the page https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest

![image](https://user-images.githubusercontent.com/4003950/124857166-64b13180-dfde-11eb-91b2-5508e3c7d85b.png)

If I click the command name on the left, say `az ml endpoint create`, it redirects to

```
https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest#az-ml-endpoint-create
```

which incorrectly uses dash `-` instead of underscore `_` in the destination link.

Meanwhile, when I click the same command on the right, it redirects to 

```
https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest#az_ml_endpoint_create
```

which correctly uses underscore `_`.

I will report this issue to our docs team to further investigate.

**Comment by jiasli** [comment]
This issue has been resolved - the link of `az ml endpoint create` now correctly redirects to https://docs.microsoft.com/en-us/cli/azure/ml/endpoint?view=azure-cli-latest#az_ml_endpoint_create
