### ISSUE TITLE
appconfig kv export useful undocumented parameter behavior (--label).

### ISSUE THREAD

**Issue by MarkAtAgilliance** [Azure/azure-cli#18845]
[Enter feedback here]
For the [export](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_export)
I think this section should point out that on export, the **--label** can accept '--label \0,myLabel' which will bring back both the myLabel taged entries and those without a tag.  This is important for combining defaults (null label) and a specific label.

However, if there is any overlap, then the export fails.  As additional product feedback, it may be nice to follow the SDK order of precedence - that the right most labels have precedence and this does not fail (issues warning instead).

I have not tested this on other appconfig kv commands (it would not be appropriate for import for example).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35da3a9-05a9-7727-fcc2-da501e89ee3f
* Version Independent ID: 679c47ba-0478-2023-a188-71d2d91ed903
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/appconfig/kv.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/appconfig/kv.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by shenmuxiaosen** [comment]
@MarkAtAgilliance  You mentioned that SDK supports multiple labels and follow the order of precedence. Can you share an example or link of that?

**Comment by MarkAtAgilliance** [comment]
sure - there is a detail in that it is the way we are recommended to use the config builder like below (I guess this is explicit layering vs implicit in the call).

Below, the builder will bring over the default labelled settings first then layer on top the Production labelled settings.  In this case we do not have to protect against setting appearing in both - the latest select call overwrites earlier ones.

In the CLI export, it does not allow for the same setting in default(null) and in a labelled setting.  It would be great if these instead could be layered too.

Hope this helps.

` 

            builder.ConfigurationBuilder
                .AddAzureAppConfiguration(action =>
                {
                    action
                        .Connect(configUri, new DefaultAzureCredential())
                        //---common settings for Function Apps (incl AI and Logging)---
                        .Select("appSettings:*", LabelFilter.Null)
                        //-- env specific settings
                        .Select("appSettings:*", "Production");
                }.AddEnvironmentVariables();

`

**Comment by shenmuxiaosen** [comment]
The configuration provider doesn't support multiple labels in one shoot. It actually rely on caller to decide the order explicitly by calling Select(). And then they will trigger separate request for each Select(). For the same concept, CLI can only export **one** label per command call. In the helper message for --label, it says that filters are not supported either ```*``` or ```,```. So the suggested way to export multiple labels is exporting multiple times to different files. 

The main reason for not supporting multiple labels in CLI export is because that's won't be a complete story. Many combinations can happen especially with key filter. For instance one combination can overwrite another one and one can have prefix removed but others may not. Therefore, it is explicit to call export command multiple times like invoking Select(). Then the downstream configuration system can load those files and decide the overwrite behavior.

**Comment by MarkAtAgilliance** [comment]
Ok, thanks for the response.  I guess the main inconvenience (especially when the nesting is deep) is that it produces several json outputs that will then need to be combined.  Probably easiest to convert to powershell hash tables then merge in preferred sequence.   I appreciate the CLI is keeping it simple and straight forward. 

Of course this work is done for us by the sequence of IConfigurationProviders in the SDK.

I'll go ahead and close
