### ISSUE TITLE
Shared gallery VM deployment CLI extension request

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#18870]
**Resource Provider**

Azure compute

**Description of Feature or Work Requested**

Gallery team currently has a feature called shared gallery, user can directly share their gallery to another subscription/tenant. This request is to allow user to deploy VM from these shared gallery.

The proposed CLI extension cmd for this new parameter is like: 
<strong>az vm create -g MyResourceGroup -n MyVm -–image sharedGalleryImageUniqueId </strong>
(I believe currently “--image” is already an overloaded parameter which targets to different api model parameters according to https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest). 

**Minimum API Version Required**

2021-03-1

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/14922

**Target Date**

private preview - August 1st, 2021

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl l Hi,  at present, there seems to be no extension related VM deployment in CLI. Do you need us to develop based on an existing extension or build a new extension?

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl Hi, at present, there seems to be no extension related VM deployment in CLI. Do you need us to develop based on an existing extension or build a new extension?

Hi Xing Zhou, yes, there was no extension. So this is the first time we try the path of CLI extension. We want to try it for this small feature and see how much it improves our experience. I think you guys can build a new extension. And when our swagger goes to stable folder, you can just merge the CLI extension to official CLI. Thanks!

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl  Hi, in fact, our extension is usually used to implement new command groups or sub commands that are different from official CLI. Because this can avoid storing the same code logic both in CLI and CLI extension, otherwise it will increase our workload and make the subsequent code maintenance and bug fix more difficult. *(Because it needs to keep the new logic on both sides in sync)*

We usually use extension for several purposes:
1. To support breadth coverage, add new RP, new command groups, and new commands to extension.
2. There are huge modifications that may cause an unstable experience for users, such as Track 2 SDK migration
If only modify the logic for an existing parameter, we recommend updating it based on the previous logic in CLI.


Moreover, I also have some concerns about creating a new extension just to increase the value range for a parameter, because this may not be convenient for users:
If users install an extension only for the sake of more support for a parameter, it will cost them cognition and introduce more operation steps.
If users finds that shared gallery image id is not supported after uninstall this extension, he is more likely to be confused by mistaking it as a bug.

**Comment by zhoxing-ms** [comment]
So may I ask do we have some reasons that it must need to be implemented in CLI extension? If not, I personally suggest that it be implemented in CLI.

**Comment by kangsun-ctrl** [comment]
> So may I ask do we have some reasons that it must need to be implemented in CLI extension? If not, I personally suggest that it be implemented in CLI.

Hi Xing, I understand what you were meaning above. For my team, we never used cli extension before and we want to know how it works by trying it on a very small change. That's why we are targeting CLI extension for current change before we use it for any big changes you mentioned above.

Another reason is that we have a tight schedule and CLI extension can be released by our own pace(that's what I heard), the swagger for this change has not been merged, so that's another reason we want to use CLI extension for this time.

Let me know if you have any suggestion, thanks!

**Comment by zhoxing-ms** [comment]
Because it's just a small change of the existing parameter logic, I personally suggest putting it in the normal CLI. Otherwise, we will create and maintain an new extension containing `az vm create` command, which is high maintenance cost
