### ISSUE TITLE
'NoneType' object is not callable error

### ISSUE THREAD

**Issue by anu-01** [Azure/azure-cli#18899]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build -t {} -r {} {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Haeavar** [comment]
We have the same issue. 

azure-cli                         2.26.0 *

/usr/bin/az acr build --verbose...............................
# WARNING: Packing source code into tar to upload...
# WARNING: Uploading archived source code from '/tmp/build_archive_26c136d5fb6b4acdbc0e3ec950eb0b6f.tar.gz'...
# INFO: Client-Request-ID=e2a70822-e65e-11eb-ad45-890782afddf6 Outgoing request: Method=PUT, Path=/3d0bd885ce5c439e8ab52f41f31d13cf-sxiup8zvid/source/202107160000/b34c3fc0-b071-4f7a-b8ea-ff725cc4e8ca.tar.gz, Query={'timeout': None, 'sv': '2018-03-28', 'sr': 'b', 'sig': 'REDACTED', 'se': '2021-07-16T18:54:36Z', 'sp': 'cw'}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'Content-Length': '36313099', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.10; Linux 5.8.0-1036-azure)', 'x-ms-client-request-id': 'e2a70822-e65e-11eb-ad45-890782afddf6', 'x-ms-date': 'Fri, 16 Jul 2021 17:54:36 GMT'}.
# INFO: Client-Request-ID=e2a70822-e65e-11eb-ad45-890782afddf6 Receiving Response: Server-Timestamp=Fri, 16 Jul 2021 17:54:37 GMT, Server-Request-ID=b2a36326-301e-0095-1a6b-7a504a000000, HTTP Status Code=201, Message=Created, Headers={'content-length': '0', 'content-md5': 'p7G4i7xbo1wZxO2UmIEySw==', 'last-modified': 'Fri, 16 Jul 2021 17:54:37 GMT', 'etag': '"0x8D94882C7326F06"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'b2a36326-301e-0095-1a6b-7a504a000000', 'x-ms-version': '2018-11-09', 'x-ms-request-server-encrypted': 'true', 'date': 'Fri, 16 Jul 2021 17:54:37 GMT'}.
# WARNING: Sending context (34.631 MiB) to registry: ************************
# ERROR: The command failed with an unexpected error. Here is the traceback:
# ERROR: 'NoneType' object is not callable
# Traceback (most recent call last):
#   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
#     cmd_result = self.invocation.execute(args)
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
#     raise ex
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
#     results.append(self._run_job(expanded_arg, cmd_copy))
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
#     result = cmd_copy(params)
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
#     return self.handler(*args, **kwargs)
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
#     return op(**command_args)
#   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
#     variant=platform_variant
# TypeError: 'NoneType' object is not callable
# To open an issue, please run: 'az feedback'
# INFO: Command ran in 14.969 seconds (init: 0.108, invoke: 14.861)

**Comment by luisdlp** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

**Comment by Haeavar** [comment]
> Thanks for reporting it and sorry for the inconvenience.
> 2.26.1 has been released to address the issue.
> https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

Great news. How can I make my .yml build files to use the 2.26.1 instead of 2.26.0?

I'm using the AzureCLI like following
`    - task: AzureCLI@2
      displayName: 'AcrBuild Container'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr build .........................
`

**Comment by Haeavar** [comment]
Calling `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash -s -- -y` in a previous task solved this for us.

**Comment by anu-01** [comment]
After upgrading to 2.2.6.1, the issue is resolved. Thanks Luis.
