### ISSUE TITLE
[ACR] Should a location be required for creating an instance?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1889]
I noticed that the `az acr create` command requires a location parameter in addition to a resource group. Isn't that inconsistent with most other `create` commands (e.g. `az appservice plan create`)? It would be great if the location defaulted to that of the specified resource group, with the `--location` parameter allowing you to override it.

**Comment by johanste** [comment]
@lostintangent, that is indeed inconsistent, and it is something of an implementation leaking out (there are two different ways to implement a create command - using a template vs. using a HTTP PUT request to create an individual resource. For the former, we currently default the location, for the latter, we do not unless the command does an additional query to get the location of the resource group). 

This is related to #1771, since if we do implement that, the story gets slightly more complicated in the case where we do not have a resource group, and thus the location becomes required again (or we have a configurable default location for create commands in general)

**Comment by djyou** [comment]
ACR is currently in preview and only launched in several regions. If we default to the location of the resource group now, it is quite unlikely that one of the 30+ regions from resource groups would be one of the 5 regions we support. Once we move to GA, this restriction can then be removed. /cc @SajayAntony
