### ISSUE TITLE
`az group delete` is no longer quiet, spits out "null".

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1908]
I have a script that can take a prefix and delete all RGs that match the prefix and lack a certain "persist" tag on the RG. Super useful, I use it everyday.

I noticed it broke (it now requires `--force` for scripting), but the output also changed.

1. It's no longer silent.

2. It prints out this:

```
Deleting colemick-testrg-0123
null
```

**Comment by derekbekoe** [comment]
In https://github.com/Azure/azure-cli/issues/575#issuecomment-243302507, we got feedback that we the output type is set to `json`, commands should always return valid JSON and **empty string is not valid JSON** (https://github.com/Azure/azure-cli/issues/794#issuecomment-252692389).

The PR went in earlier this week (https://github.com/Azure/azure-cli/pull/1854).

So now we return the string `null` for commands that prev. returned nothing, `[] `for empty lists, `{}` for empty dictionaries, etc. according to https://docs.python.org/3/library/json.html#json.JSONEncoder.

We could change it so only if the result is an empty list we return `[]` and otherwise return empty but then we wouldn't be strictly following JSON.

**Comment by tjprescott** [comment]
I would agree with @colemickens that this is kind of wonky. For example, running `az configure` does the same thing. There are presumably a whole host of situations where getting "null" as an output would be annoying and/or confusing. I would +1 the idea of returning "[ ]" for empty lists but otherwise nothing.

**Comment by derekbekoe** [comment]
> I would +1 the idea of returning "[ ]" for empty lists but otherwise nothing.

Will implement this.
