### ISSUE TITLE
Prompts for yes / no should use the -y option rather than --force

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1911]
I have a feeling this one might be a bit controversial, but I think this would be a good discussion to get down if it hasn't already been discussed ad nauseum. 

Rather than using --force for assumptions about confirmation, could we use -y (--assume-yes)? I think this could serve two goals. One, it would be more clear in situations of confirmation. Two, it can reserve --force for actions of great danger.

`az storage account delete ... -y` rather than `az storage account delete ... --force`

**Comment by lostintangent** [comment]
I would tend to agree with this. I've seen a mix of `--yes` (e.g. `apt-get install`, `now rm`), `--confirm` (e.g. `heroku apps:delete`), and `--force` used for equivalent behavior in different CLIs, but the `--force` flag seems to be typically used for operations that require "special" confirmation, due to them breaking some kind of invariant and/or having downstream consequences (e.g. deleting a Docker image that is used by a running container).
