### ISSUE TITLE
Managed identity token retrieval for RBAC does not work with Cosmos DB dedicated gateway URL.

### ISSUE THREAD

**Issue by JereStay** [Azure/azure-cli#19269]
## Describe the bug
With a Cosmos Db configured with dedicated gateway, there is a different URL to use to go through the gateway. This URL does not seem to work with the Get Token request based on the error below.

I have checked that the direct URL does work in my code but that bypasses the gateway and I lose out on integrated caching feature.

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://learncachedev.sqlx.cosmos.azure.com was not found in the tenant named 72f988bf-86f1-41af-91ab-2d7cd011db47. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 13935e08-be30-4d90-ac87-fb9536752c01\r\nCorrelation ID: 0c217a39-ce3f-4029-aff3-513c1299ec50\r\nTimestamp: 2021-08-18 20:15:24Z","error_codes":[500011],"timestamp":"2021-08-18 20:15:24Z","trace_id":"13935e08-be30-4d90-ac87-fb9536752c01","correlation_id":"0c217a39-ce3f-4029-aff3-513c1299ec50","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Traceback (most recent call last):
Temp\pip-unpacked-wheel-lhx4371t\knack\cli.py, ln 215, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Configure Cosmos DB with dedicated gateway provisioned
- Setup user or azure service (function app) to have RBAC permissions with the Cosmos DB
- Setup Cosmos Client to connect with dedicated gateway url and DefaultAzureCredential so that managed identity is used
- I think under the hood this is the command called (this was generated by az feedback for me):
-- `az account get-access-token --output {} --resource {}`

## Expected Behavior
I expect that using the dedicated gateway URL to connect to Cosmos is able to retrieve a token just like the direct url does.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0 *

I am actually seeing this error in my .NET Core 3.1, Azure Function app. It looks like the SDK is making these az cli commands for getting/refreshing the token.
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`--resource` specified in `az account get-access-token` should be the **resource/audience** for the access token, because

- the gateway (proxy) simply passes the access token to the backend Cosmos DB without checking it
- AAD doesn't recognize the gateway   URL.

In your case, it should be the URL of the backend Cosmos DB, instead of the proxy's URL `https://learncachedev.sqlx.cosmos.azure.com`.

I am not quite familiar with Azure .NET SDK, but for Python SDK, you may override 

https://github.com/Azure/azure-sdk-for-python/blob/599ef478da0e7bdbf95bec203043c50437046feb/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2021_04_01/_configuration.py#L52

**Comment by jiasli** [comment]
`--resource` specified in `az account get-access-token` should be the **resource/audience** of the access token (`aud` claim). You should use the backend Cosmos DB's URL, instead of the dedicated gateway (proxy)'s URL `https://learncachedev.sqlx.cosmos.azure.com`, because

- the dedicated gateway (proxy) simply passes the access token to the backend Cosmos DB without checking it
- AAD doesn't recognize the gateway URL

I saw you are using `DefaultAzureCredential` from .NET SDK. I am not quite familiar with Azure .NET SDK, but for Python SDK, you may override `base_url` by specifying a `credential_scopes`.

https://github.com/Azure/azure-sdk-for-python/blob/599ef478da0e7bdbf95bec203043c50437046feb/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2021_04_01/_resource_management_client.py#L64

```py
class ResourceManagementClient(object):    
    def __init__(
        ...
        base_url=None,  # type: Optional[str]
```

https://github.com/Azure/azure-sdk-for-python/blob/599ef478da0e7bdbf95bec203043c50437046feb/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2021_04_01/_configuration.py#L52


```py
    def __init__(...):
        ...
        self.credential_scopes = kwargs.pop('credential_scopes', ['https://management.azure.com/.default'])
```

Previously I submitted this feature request in .NET SDK (https://github.com/Azure/azure-sdk-for-net/issues/13603, https://github.com/Azure/autorest.csharp/issues/972), but it doesn't seem to have been implemented yet.
