### ISSUE TITLE
ANSI escape color codes broken on Git Bash in Windows Terminal

### ISSUE THREAD

**Issue by tiesmaster** [Azure/azure-cli#19391]
**Describe the bug**
Running the az CLI on Windows using Git Bash in the Windows Terminal shows color output is broken. This is specific to this situation (see below for more context). When running `$ az help`, the output ends with:

```
[...more output elided for brevity...]
←[1mFor more specific examples, use: az find "az "←[0m

←[0mPlease let us know how we are doing: ←[96mhttps://aka.ms/azureclihats←[0m
←[0mand let us know if you're interested in trying out our newest features: ←[96mhttps://aka.ms/CLIUXstudy←[0m
```

**To Reproduce**
1. Install latest Windows Terminal
2. Install latest Git Bash, and enable the checkbox to add [the "Windows Terminal" profile](https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.1)
3. Install latest Azure CLI
4. Start Windows Terminal, and open the Git Bash profile
5. Run: `$ az help`

**Expected behavior**
Output is showing colors.

**Environment summary**
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.1

Windows Terminal
Version: 1.9.1942.0

Git for Windows: 2.33.0.2
```

**Additional context**
I ran into this when setting up a new dev box, and also found out the following details:
 * when starting the powershell profile within Windows Terminal, the output **is** colored correctly
 * when starting Git Bash from the Start Menu (this uses the mintty terminal that comes preinstalled with the Git for Windows install), the output is **not** colored, but the escape codes don't appear
 * when running the Azure CLI on my old system, the coloring output is working inside the Windows Terminal (same version) in Git Bash. The version of the Azure CLI that's installed there is: `2.15.1`
 * running ANSI escape sequences [like this](https://www.shellhacks.com/bash-colors/) does ouput colors

---

## UPDATE: Results of some additional testing

I wanted to be sure that the reproduction steps are sound on a new system, with pretty much all the defaults, and installing from MSI, or Windows Store (for the Windows Terminal). So I created a new VM in Azure with Windows 10 Pro 20H2, and managed to reproduce this in this fresh box.

I also did some additional research where this broke, so I did a "git bisect" but then via installing the MSIs, and there are my results:
 * 2.18: PASS
 * 2.20: PASS
 * 2.21: PASS
 * 2.22: FAIL
 * 2.23: FAIL
 * 2.27.2: FAIL

Needless to say, version 2.22 broke this.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Azure CLI has been affected by colorama bugs for a long time (https://github.com/microsoft/knack/pull/209). That's why we stopped initializing colorama in Linux terminals (https://github.com/microsoft/knack/pull/238).

If we check `isatty` in the original Git Bash terminal, it shows:

```
$ "/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/python.exe" -c "import sys; print(sys.stdin.isatty())"
False
```

This corrupts the color detection logic:

https://github.com/microsoft/knack/blob/03b46abc9735fdc88e90b89b9c88192758a83277/knack/cli.py#L276-L278

```py
        if sys.stdout.isatty() and sys.stderr.isatty() and self.out_file is sys.stdout:
            self.init_debug_log.append("Enable color in terminal.")
            return True
```

CLI thinks this is not a TTY and turns off the color, even though escape sequences are indeed supported.

```
$ "/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/python.exe" -c 'print("\x1b[36mhello world\x1b[0m")'
```

![image](https://user-images.githubusercontent.com/4003950/131769485-c30a4410-310f-4f10-b991-a101a822c19f.png)

Found these discussions:
- https://stackoverflow.com/questions/40912072/git-for-windows-mintty-sys-stdout-isatty-returns-false
- https://github.com/git-for-windows/git/issues/2594

However, in Git Bash running in Windows Terminal, `isatty` returns `True`:

```
$ "/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/python.exe" -c "import sys; print(sys.stdin.isatty())"
True
```

But escape sequences can't be displayed correctly:
```
$ "/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/python.exe" -c 'print("\x1b[36mhello world\x1b[0m")'
```

![image](https://user-images.githubusercontent.com/4003950/131769345-c2beb70b-3543-479b-a0df-7de807c3ea48.png)

Discussions on the topic:

- https://github.com/git-for-windows/git/issues/2483
- https://github.com/microsoft/terminal/issues/1965

So this is actually a "Git Bash in Windows Terminal" problem. 

For now, I would recommend these workarounds:

- Disable color with the [`no_color` configuration](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables):
    ```
    az config set core.no_color=True
    ```
- Use other shells (like PowerShell, WSL) officially supported by Azure CLI

**Comment by tiesmaster** [comment]
@jiasli Thanks for the detailed write-up. I suspected it was a _simple_ regression, perhaps pulling in a new version of a 3rd party dependency that regressed, however, it's not unsurprising that the plot thickens this much with things like git-for-windows, and the WT 😅 

The workaround is really helpful, I didn't knew about that. It really makes the output usable, and made my day ❤️  Thnx!

**Comment by jiasli** [comment]
I am glad to know the workaround works for you! Please free feel to contact us if there are any problems. 😊
