### ISSUE TITLE
az vm create fails when user account name is too short

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1943]
When running `az vm create` without specifying an admin-username and having a login name that is 'david' (I'm guessing anything 5 letters or less), your vm deployment fails.

`az vm create` should not use the current logged in username if it doesn't fit admin-username criteria.

**Comment by derekbekoe** [comment]
Similarly with when you're logged into a machine as `root`.
CRP does not accept `root` as a valid admin username.

**Comment by johanste** [comment]
To make things even more interesting, the validation rules for user names and such can depend on which image is being used.

**Comment by reyk** [comment]
My username "reyk" worked just fine before this change, now it complains.

Why is this even needed and does it really fix a thing? I also do not like the fact that the CLI 2.0 started asking interactive questions again, this is bad for scripting. It should just fail with an error message.

btw., "root" is less than 6 characters so the or check is never evaluated and not needed:
`if len(namespace.admin_username) < 6 or namespace.admin_username.lower() == 'root':`

**Comment by tjprescott** [comment]
@reyk in a scripting scenario, this does automatically fail.

**Comment by reyk** [comment]
OK, I see. It is still a terrible thing that the CLI is asking questions now (and the colors...). This doesn't feel like UNIX and I hoped that CLI 2.0 is not going down the same road as the old CLI.

But anyway, the issue is about username. So why is the limitation of >= 6 characters that stops me from using my login name that just worked perfectly fine before? Could this "fix" be reverted?

**Comment by tjprescott** [comment]
Any prompting is designed to be as minimal as possible and specifically to not interfere with scripting scenarios, so we definitely hear you. The only colors (aside from the JSON color output format) are yellow for logger warnings and red for logger errors.

As far as the length limit, we can reinvestigate this. Different images have different restrictions. Rather than have the VM create process go along for several minutes and then fail because of the admin username, we aimed to provide a consistent bar that would work across all VM images.

**Comment by derekbekoe** [comment]
Linking this to https://github.com/Azure/azure-cli/issues/2010 as that also commented on the prompting.

**Comment by yugangw-msft** [comment]
I am fixing this. Shorter name will be accepted as long as it is not in the black list

**Comment by reyk** [comment]
Thanks, great!

**Comment by dt** [comment]
Why is `david` in the blacklist?!

**Comment by yugangw-msft** [comment]
`david`, and any human name, will be out of blacklist this week, see #4257. This is involving service side change as well, so we are coordinating. I don't exactly know why such ban happened but it was started from a long time ago when in RDFE mode.

**Comment by omichels** [comment]
as of 08/20/2018 this issue still occurs.

# az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
This user name 'root' meets the general requirements, but is specifically disallowed for this image. Please try a different value.

bash-4.4# adduser user
bash-4.4# su - user
$ az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
This user name 'user' meets the general requirements, but is specifically disallowed for this image. Please try a different value.

bash-4.4# adduser oliver_michels
bash-4.4# su - oliver_michels
$ az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
SSH key files '/home/oliver_michels/.ssh/id_rsa' and '/home/oliver_michels/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage, back up your keys to a safe location.
