### ISSUE TITLE
Cannot use the azure-mgmt-resourcegraph python library on the CLI

### ISSUE THREAD

**Issue by DevenJnando** [Azure/azure-cli#19528]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Part 1 of the issue:

When using the version of `azure-common` which is bundled into `azure-cli` we hit the following error when attempting to obtain a list of Subscriptions through the `get_client_from_cli_profile(SubscriptionClient)` function:

`  File ".azdev/azdev-env/lib/python3.8/site-packages/azure/common/client_factory.py", line 100, in get_client_from_cli_profile
    return _instantiate_client(client_class, **parameters)
  File "azdev/azdev-env/lib/python3.8/site-packages/azure/common/client_factory.py", line 35, in _instantiate_client
    return client_class(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'credential'`

This seems to be due to the fact that a `credential` argument is expected in the `azure.mgmt.resource` class, when a `credentials` argument is being provided in the `get_client_from_cli_profile()` function in `azure.common`

Part 2 of the issue:

If we update our dependencies manually to ensure that `azure-common`, `azure-mgmt-resource` and `azure-mgmt-resourcegraph` are all version `1.1.27`, `19.0.0` and `8.0.0` respectively, we can consume the `credentials` change to `credential`. However, when attempting to iterate over a list of Subscriptions obtained using the `get_client_from_cli_profile(SubscriptionClient)` function, the following error is thrown:

` File "/.azdev/azdev-env/lib/python3.8/site-packages/azure/common/credentials.py", line 72, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
TypeError: _retrieve_token() missing 1 required positional argument: 'token_resource'`

**To Reproduce**

Reproduce part 1:
`azure-mgmt-resource` and `azure-mgmt-resourcegraph` should be listed as azdev dependencies and the following code should be run:

`subsList = []
 subsDict = []
 subsClient = get_client_from_cli_profile(SubscriptionClient)`

Reproduce part 2:

`azure-common` `azure-mgmt-resource` and `azure-mgmt-resourcegraph` should be listed as azdev dependencies using versions `1.1.27`, `19.0.0` and `8.0.0` respectively, and the following lines of code should be run:

`subsList = []
 subsDict = []
 subsClient = get_client_from_cli_profile(SubscriptionClient)

 for sub in subsClient.subscriptions.list():
     subsDict.append(sub.as_dict())`

**Expected behavior**

Part 1:

It is expected that a subscription client should be returned.

Part 2:

It is expected that each subscription should be added to the `subsDict` list object.

**Environment summary**

OS - Linux Mint
OS version - 20.1 (Ulyssa)
CLI version - 2.28.0
CLI Core version - 2.28.0
Installation method - azdev
azure-mgmt-resource version - 19.0.0
azure-mgmt-resourcegraph version - 8.0.0

Part 1 only:
azure-common version - 1.1.22

Part 2 only:
azure-common version - 1.1.27

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
## Part 1: TypeError: __init__() missing 1 required positional argument: 'credential'

```
File ".azdev/azdev-env/lib/python3.8/site-packages/azure/common/client_factory.py", line 100, in get_client_from_cli_profile
  return _instantiate_client(client_class, **parameters) 
File "azdev/azdev-env/lib/python3.8/site-packages/azure/common/client_factory.py", line 35, in _instantiate_client 
  return client_class(**kwargs) 
TypeError: __init__() missing 1 required positional argument: 'credential'
```

`azure-mgmt-resource` v13.0.0 -> v15.0.0 is Track 1 -> Track 2 version bump and introduces several breaking changes. `credentials` -> `credential` is one of them. `azure-mgmt-resource` currently used by Azure CLI is now Track 2 (https://github.com/Azure/azure-cli/pull/17783) which uses `credential`.

Track 1 v13.0.0: https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_13.0.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L57

```py
class SubscriptionClient(SubscriptionClientOperationsMixin, MultiApiClientMixin, SDKClient):
    def __init__(self, credentials, api_version=None, base_url=None, profile=KnownProfiles.default):
```

Track 2 v15.0.0: https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_15.0.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L57

```py
class SubscriptionClient(SubscriptionClientOperationsMixin, MultiApiClientMixin, _SDKClient):
    def __init__(
        self,
        credential,  # type: "TokenCredential"
```

`azure-common` doesn't make the change to adapt to Track 2 SDKs accordingly.

## Part 2: TypeError: _retrieve_token() missing 1 required positional argument: 'token_resource'

That change on `_retrieve_token` was made to implement Conditional Access with MFA (https://github.com/Azure/azure-cli/pull/17738).

Track 1 SDK doesn’t manage `resource`(`scopes`) - CLI manages `resource`, but Track 2 SDK manages `scopes`(`resource`) by itself. CLI made this change according to the Track 2 SDK design so that `_token_retriever` should always be called with a `resource`. This provides a consistent way to display a re-login message if MFA is required.

`azure-common` is incorrectly using the private method `_token_retriever`. Azure CLI doesn't guarantee the interface of private methods like `_token_retriever`.

https://github.com/Azure/azure-sdk-for-python/blob/7373db2a493e23bb03a4d8d2f74fff9767f0cb94/sdk/core/azure-common/azure/common/credentials.py#L72

```py
_, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
```

The pylint error `protected-access` should serve as a sign of warning, but is ignored.

All incorrect usages have been removed from Azure CLI code: https://github.com/Azure/azure-cli/pull/17812

Instead, `azure-common` should call public methods like

1. `azure.cli.core._profile.Profile.get_raw_token `
2. `azure.cli.core._profile.Profile.get_login_credentials`
3. `azure.identity.AzureCliCredential`
4. subprocess `az account get-access-token`

In the MSAL migration (https://github.com/Azure/azure-cli/issues/18944), `_token_retriever` will be removed. 

## Solution

**`azure-common` has been deprecated and out of maintenance.**

The right way to create an SDK client is to call [`azure.cli.core.commands.client_factory.get_mgmt_service_client`](https://github.com/Azure/azure-cli/blob/672837983df7e6f4cb55fadd30ed375bfd53df21/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L50) which automatically 

- (part 1) handles Track 1 and Track 2 difference on `credential`
- (part 2) uses the correct public method [`azure.cli.core._profile.Profile.get_login_credentials`](https://github.com/Azure/azure-cli/blob/14cc787d0f58bc649d402b486fdecc5625eee9ac/src/azure-cli-core/azure/cli/core/_profile.py#L549) to get an access token

**Comment by DevenJnando** [comment]
I see, that does help a lot, I'm still a little uncertain about a few things though; when calling the `get_mgmt_service_client` function, where would I obtain the object which is used as the `cli_ctx` argument? There are other uses of `cli_ctx` in other parts of the application, but I don't know how to actually retrieve the `cli_ctx` object. Apologies if this is a stupid question.

**Comment by jiasli** [comment]
@DevenJnando, are you developing an Azure CLI extension? If so, you can follow the official way to register commands: https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules. This will provide `cli_ctx` to `get_mgmt_service_client` automatically:

https://github.com/Azure/azure-cli/blob/166f0506371ce45d982ea7b7876e246757caba61/src/azure-cli/azure/cli/command_modules/resource/_client_factory.py#L7-L10

If you are creating an SDK client from a function defined in `custom.py` file, `cli_ctx` can be retrieved from `cmd.cli_ctx`:

https://github.com/Azure/azure-cli/blob/1698aa3ccc081ae791084b7fa0cafb7d320c0db4/src/azure-cli/azure/cli/command_modules/resource/custom.py#L1286

**Comment by DevenJnando** [comment]
The `cmd` arg was not present in the command, adding it took care of that problem nicely - thanks! I have another issue now though which is also confusing me: when I create the `SubscriptionClient` and try to iterate through each subscription using this loop:

`for sub in subsclient.subscriptions.list`

I get the following error:

`File "/home/james/Documents/frp/az-cli/.azdev/azdev-env/lib/python3.8/site-packages/azure/mgmt/resource/subscriptions/_subscription_client.py", line 151, in subscriptions
    raise ValueError("API version {} does not have operation group 'subscriptions'".format(api_version))
ValueError: API version 7f62c189-2d3d-4ff4-8ddd-4c7d1899ada8 does not have operation group 'subscriptions'`

It seems to be taking my `id` field from my account on the cli instead of an api version.

**Comment by jiasli** [comment]
Per the signature of 

https://github.com/Azure/azure-cli/blob/672837983df7e6f4cb55fadd30ed375bfd53df21/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L50-L51

you could be passing arguments in the wrong order - using `subscription_id` as `api_version`.

You may create a break point and debug the code to see what is really passed to the function.

**Comment by DevenJnando** [comment]
Figured it out - had nothing to do with arguments in the wrong order; it seems that I was using the client_factory functions incorrectly. Thanks very much for all your help! 😄 

For anybody with similar issues I shall post my full solution here:

Imports:

 `import azure.mgmt.resourcegraph as arg
  from azure.cli.core.commands.client_factory import get_subscription_service_client, _get_mgmt_service_client`



To obtain subscription client object:

 `subslist = []
  subsdict = []

  # azure.cli.core.commands.client_factory provides a function for this exact purpose and returns a tuple containing the 
  # subscription client object and the subscription id it belongs to
  substuple = get_subscription_service_client(cmd.cli_ctx) 

  subsclient = substuple[0] # the subscription client object is returned as the first element`



To iterate through each subscription within the subscription client:

   `for sub in subsclient.subscriptions.list():
        subsdict.append(sub.as_dict())
    for sub in subsdict:
        subslist.append(sub.get('subscription_id'))`



To obtain the resource graph client:

   `# We set subscription_bound to False - the subscriptions in the resource graph client come later
    argtuple = _get_mgmt_service_client(cmd.cli_ctx, arg.ResourceGraphClient, subscription_bound=False)
    argclient = argtuple[0]`



To write and execute the resource graph query:

   `strquery = "Your ARG query goes here"

    argqueryoptions = arg.models.QueryRequestOptions(result_format="objectArray")
    argquery = arg.models.QueryRequest(subscriptions=subslist, query=strquery, options=argqueryoptions)
    argresults = argclient.resources(argquery)`

**Comment by wesmadrigal** [comment]
FYI getting these errors on:

pip install azure-cli azure-core

ERROR: azure-cli-core 2.28.1 has requirement azure-mgmt-core<1.3.0,>=1.2.0, but you'll have azure-mgmt-core 1.3.0 which is incompatible.
ERROR: azure-cli-core 2.28.1 has requirement requests[socks]~=2.25.1, but you'll have requests 2.26.0 which is incompatible.
