### ISSUE TITLE
Some storage commands do not output the response body received from the service

### ISSUE THREAD

**Issue by seguler** [Azure/azure-cli#1955]
Few examples that don't output anything. Both the service and the underlying client library returns results for these requests. Could we output those ?

az storage entity insert -t users --entity RowKey=key PartitionKey=key name=value
az storage message put -q $queue_name --content 
az storage file upload --source $full_path_to_file -s $share_name -p $directory_name

**Comment by seguler** [comment]
Same with this one:
az storage account delete --resource-group $resource_group_name -n $storage_account_name

**Comment by jahongirman** [comment]
I also wanted to create an Issues on this. 

In my case, 'az group list' also do not return any message.

I know that I don't have any Resource Groups, however, I am expecting some output that will inform me that I don't have resource groups.

**Comment by johanste** [comment]
@seguler, the problem with az storage account delete is that it is actually incorrectly described in swagger (assuming that the service indeed returns a 200 w. a body for a successful delete). The response schema is not provided, and thus and management SDKs (and thus the CLI) will not be able to get the response.

`az storage entity insert` should indeed return a value since that is what the SDK does. 

In general, we try to avoid making multiple rest calls for any given command. 

For the `az storage message put` command, it does not look like storage message put/QueueService.put_message in the storage data plane library returns anything, nor does FileService.create_file_from_path/`az storage file upload` return any value. They should ideally be addressed in the Python dataplane SDK since if this is interesting information from a CLI perspective, it stands to reason that other application developers would want the same information returned from the SDK. 

@jahongirman, we are intentionally avoiding spurious output from the CLI at this point. We are discussing alternate ways of providing user feedback for primarily interactive use. Feel free to open a separate issue if you want to continue the discussion - we'd like to use this issue to track the specific issues that @seguler mentioned above.

**Comment by johanste** [comment]
I've created PR #1972 for `az storage entity insert`.

**Comment by tjprescott** [comment]
@seguler `file upload ` and `put queue` don't return what the service returns because the storage SDK methods that underpin these commands do not return what the service does. Please file an issue here:  https://github.com/Azure/azure-storage-python

**Comment by tjprescott** [comment]
Except for `storage entity insert` (which has been fixed in #1972) the rest of the commands which return nothing do so because either the service returns nothing or the SDK doesn't pass the response back to the client.
