### ISSUE TITLE
[Storage] `storage account update` does not expose Generic Update arguments

### ISSUE THREAD

**Issue by robbiezhang** [Azure/azure-cli#1956]
Recommend to support to add 1 tag, or support JSON input for the --tags.
Here is the current script to add one tag.
```
NEW_TAGS=$(az storage account show -g "$resourceGroup" -n "$storageAccount" | jq -r "[.tags + {\"$key\": \"$value\"} | to_entries | .[] | if (.value | contains(\" \")) then .key + \"=\\\"\" + .value + \"\\\"\" else .key + \"=\" + .value end ] | join(\" \")")
CMD="az storage account update -g $resourceGroup -n $storageAccount --tags $NEW_TAGS"
eval $CMD
```
Do you have any recommendation?

**Comment by tjprescott** [comment]
Hi @robbiezhang the `--tags` option does replace tags entirely. What you are trying to do is certainly possible using the generic update commands... the problem is, `storage account update` doesn't expose those!  When it does, the command would be:

`az storage account update -g {rg} -n {sa} --set tags.key=value`

This will preserve your existing tags and simply add to them (or overwrite that key if it already exists).

**Comment by robbiezhang** [comment]
Hi Travis, thank you for the quick answer! One more question: What's the syntax for value of --set? What if the 'key' is not a valid property name, e.g. my-tag-1. Can I use `--set tags["my-tag-1"]=value`?

**Comment by tjprescott** [comment]
For set, it should see that tags is a dictionary and you would still use `--set tags.my-tag-1=value`. If it doesn't, then that would be a bug.
