### ISSUE TITLE
az acr connected-registry install show does not return useable connection-string

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cli#19609]
We're experimenting with the Connected ACR functionality and are in the progress of creating a script to automate the deployment of a connected registry.

At a certain point, we need to retrieve the connection-string of the connected registry.  This should be possible via the `az acr connected-registry install show` command.  This command returns the connection-string that must be used , however, the returned connection-string does not contain the required password.
When I execute this command for a connected registry that I've created, the returned information looks like this:

```
{
  "ACR_REGISTRY_CONNECTION_STRING": "ConnectedRegistryName=<redacted>;SyncTokenName=<redacted>-sync-token;SyncTokenPassword=<sync token password>;ParentGatewayEndpoint=<redacted>.westeurope.data.azurecr.io;ParentEndpointProtocol=https",
  "ACR_REGISTRY_LOGIN_SERVER": "<Optional: connected registry login server. More info at https://aka.ms/acr/connected-registry>"
}
```
As you can see, the `SyncTokenPassword` key contains a placeholder instead of the password.

I'm currently working around this by executing the `install renew-credentials` command, which returns a connection-string where the password is present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10fe848-12b5-1373-1e08-9bda5cd017e9
* Version Independent ID: 257c7de7-3d90-0735-5d61-a86e346c10b8
* Content: [az acr connected-registry install](https://docs.microsoft.com/en-us/cli/azure/acr/connected-registry/install?view=azure-cli-latest#az_acr_connected_registry_install_info)
* Content Source: [latest/docs-ref-autogen/acr/connected-registry/install.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/acr/connected-registry/install.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jaysterp** [comment]
@fgheysels Once an ACR token password is generated, it cannot be retrieved by the user again, but a new one can be generated. In order to view the connection string with password included, the user must run `az acr connected-registry install renew-credentials` command. This command will print the connection string with a renewed sync token password. The `az acr connected-registry install info` command is for users who want to view their connection string without generating a new password. This is why there is a placeholder in the returned connection string. @rosanch @northtyphoon

**Comment by yonzhan** [comment]
route to service team

**Comment by fgheysels** [comment]
> @fgheysels Once an ACR token password is generated, it cannot be retrieved by the user again, but a new one can be generated. In order to view the connection string with password included, the user must run `az acr connected-registry install renew-credentials` command. This command will print the connection string with a renewed sync token password. The `az acr connected-registry install info` command is for users who want to view their connection string without generating a new password. This is why there is a placeholder in the returned connection string. @rosanch @northtyphoon

But, if I create a new connected - registry, a sync token is automatically generated.  Then, this means there's no way to retrieve the connection-string without regenerating the credentials ?  When you create a new connected registry (`az acr connected-registry create`) doesn't return you the initial connection-string / password either.

**Comment by jaysterp** [comment]
@fgheysels yes, when a connected registry is created via CLI we automatically create a corresponding sync token. However, the sync token resource is created without any passwords generated. The password is first created when the user runs `az acr connection string install renew-credentials`. Once generating this connection string, the user is responsible for saving it since the password cannot be retrieved again. Otherwise, they can generate a new connection string by running the `az acr connection string install renew-credentials` command again.

We will add info to the `az acr connected-registry install info` output in order to communicate that this command does not show a password. @rosanch @northtyphoon @toddysm

**Comment by fgheysels** [comment]
Ok thx, that's clear.  

Just out of curiosity: why do we have the `az acr connected-registry install info` command ?  I don't actually see any reason why we should use it ?

And, was it not an option then to create a sync token and password when creating the connected-registry (`az acr connected-registry create`) and return the connection-string (incl. pwd) with the response of that command ?  It saves us for executing the 'renew credentials' command).

**Comment by toddysm** [comment]
@fgheysels good feedback. Let us look at the flows again and see what improvements we can make.

**Comment by fgheysels** [comment]
Is this issue solved by introducing the [`get-settings`](https://docs.microsoft.com/en-us/cli/azure/acr/connected-registry?view=azure-cli-latest#az_acr_connected_registry_get_settings) subcommand in Azure CLI ?

**Comment by fgheysels** [comment]
Actually, upon creation of a connected registry instance, you can call the `get-settings`  command, but this command also does not return a usable connection-string; you need to generate one.  This is not a problem but I don't see any advantage over the (deprecated) `install renew-credentials` command.

**Comment by jaysterp** [comment]
@fgheysels the new `get-settings` command exposes additional configuration info for the connected-registry alongside the connection string, including the configured login server. Similar to the legacy `install renew-credentials` command, the default output does not show a password in the connection string. If the user wants credentials shown, then they must select which of the 2 available token passwords to generate/rotate.

We do not return the connection string or token credentials in the "az acr connected-registry create" flow in order to adhere to CLI best practices that recommend we only return the connected registry resource itself. @toddysm @northtyphoon

**Comment by fgheysels** [comment]
I think this can be closed :)
