### ISSUE TITLE
Azure Image Builder | CLI issue 

### ISSUE THREAD

**Issue by sourp2693** [Azure/azure-cli#19702]
We are trying to create an image in Azure Image Builder , and getting the error below :

**Command:-** 

az resource create \
    --resource-group $imageResourceGroup \
    --properties @helloImageTemplateWin.json \
    --is-full-object \
    --resource-type Microsoft.VirtualMachineImages/imageTemplates \
    -n helloImageTemplateWin01

Ref:- https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder

**Error:-**

The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
found_value = key_extractor(attr, attr_desc, data)
File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
return attribute_key_case_insensitive_extractor(key, None, working_data)
File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
return data.get(found_key)

Any insights as to what could be the cause ?

**Comment by yonzhan** [comment]
ARM

**Comment by sourp2693** [comment]
> ARM

@yonzhan Any update on the query ?

**Comment by zhoxing-ms** [comment]
@sourp2693 May I ask what version of CLI you are using? Could you add parameter `--debug` to the executed command and then send the printed debug log to me? My email address is Zhou.Xing@microsoft.com

**Comment by zhoxing-ms** [comment]
This is a python SDK related issue, code link: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2021_04_01/models/_models_py3.py#L1407
The `'type': '{IdentityUserAssignedIdentitiesValue}'` should be `'type': '{IdentityUserAssignedIdentitiesValue}'`, otherwise an error will occur during deserialization.

**Comment by zhoxing-ms** [comment]
@msyyc Could you please help to have a look at this Python SDK issue

**Comment by sourp2693** [comment]
@msyyc Any update on the issue ?

**Comment by sourp2693** [comment]
@yonzhan @msyyc  Any update on the reported issue ?

**Comment by yonzhan** [comment]
You could ping @msyyc from Python SDK team for help

**Comment by msyyc** [comment]
Hi @sourp2693 I will investigate it asap. Thank you for your feedback.

**Comment by sourp2693** [comment]
@msyyc  Any update /Proceedings ?

**Comment by msyyc** [comment]
Hi @sourp2693, according to [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/3eaa729b3686f20817145e771a8ab707c739dbbd/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L5577-L5595) and the error message, the root cause is that your input parameter is not right. the [helloImageTemplateWin.json](https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/0_Creating_a_Custom_Windows_Managed_Image/helloImageTemplateWin.json) indicates that `{}`  should be `dict` instead of `string`
![image](https://user-images.githubusercontent.com/70930885/136905908-8bdcc619-c15f-4804-8a88-04c8c2c12e76.png)

@zhoxing-ms shared .json file of yours and `userAssignedIdentities` should make some change:
![image](https://user-images.githubusercontent.com/70930885/136906868-1457751c-ef23-490b-83ae-86105ce3b85d.png)

Hope it could resolve your problem.

**Comment by navba-MSFT** [comment]
@sourp2693 Could you please let us know if you had a chance to follow the above action plan and see if that fixes your issue ? Awaiting your reply.
