### ISSUE TITLE
az aks get-credentials changes casing of the cluster name

### ISSUE THREAD

**Issue by CoRlfKrl** [Azure/azure-cli#19723]
## Describe the bug
az aks get-credentials changes casing of the cluster name

```
az aks get-credentials -o table -g "dev-cluster-env_res" -n "dev-cluster"
```
returns
```
Merged "Dev-cluster" as current context in C:\Users\XXXX\.kube\config
```

**Command Name**
`az aks get-credentials`

**Errors:**
changes the casing of the cluster name
when you try to set the context in kubectl
```
kubectl set config
```
the cluster will not be found because the clustername is case sensitive.

DID WORK on 28 September 2021
DID NOT WORK sind 29 September 2021

We didn't change CLI Version.

## To Reproduce:

Try to get the credentials of a cluster
the name will be modified

## Expected Behavior

The cluster-name muss not be changed.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@CoRlfKrl Apologies for the late reply. I wasn't able to replicate this issue in my box. I am using version Az CLI 2.33.1.
Could you please let me know if you are still seeing this issue with the [recent version of the CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)? Also this issue is open for quite sometime. Please do let me know if you still need assistance on this issue. Awaiting your reply.
