### ISSUE TITLE
az aks update --assign-identity doesn't update the identity

### ISSUE THREAD

**Issue by rafagsiqueira** [Azure/azure-cli#19733]
**Describe the bug**
After running az aks update --assign-identity <identity id> --enable-managed-identity, the cluster identity remains the same, after the update process.

**To Reproduce**
az aks show -g <rg> -n <name> --query "identity"
az aks update --assign-identity <identity id> --enable-managed-identity
az aks show -g <rg> -n <name> --query "identity"

**Expected behavior**
The cluster managed identity should have been updated

**Environment summary**
apt-get install on Windows WSL2 (Ubuntu)
version 2.28.0

**Comment by yonzhan** [comment]
route to service team

**Comment by norshtein** [comment]
What do you mean by "the cluster identity remains the same"? Could you please paste the full command you were running and the output of `az aks show`?

**Comment by ms1111** [comment]
We ran into this, where it's not possible to change the user-assigned managed identity after the cluster is created. Through a series of config changes, we got ourselves in a position where Terraform had deleted the user-assigned managed system identity the cluster was using, but the cluster was still trying to use it. After rebooting some nodes, they were unable to update routing tables because the old identity no longer existed. Since we were unable to change the (now dead) user-assigned managed identity to a new one, we had to recreate the cluster to get things back online.

**Comment by navba-MSFT** [comment]
@rafagsiqueira Apologies for the late reply. Please find below the below commands which you can execute using the most [recent version of Az CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and let me know if the issue occurs.

Update the cluster to use system assigned managed identity in control plane.
>az aks update -g MyResourceGroup -n MyManagedCluster --enable-managed-identity


Update the cluster to use user assigned managed identity in control plane.
>az aks update -g MyResourceGroup -n MyManagedCluster --enable-managed-identity --assign-identity <user_assigned_identity_resource_id>
