### ISSUE TITLE
[Storage] Help text implies that account name and key are required

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1988]
If I try to run `az storage share create -n <name>` without an account name, the command prints out the following error message:

```
No credentials specifed to access storage service. Please provide any of the following:
    (1) account name and key (--account-name and --account-key options or
        set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables)
    (2) connection string (--connection-string option or
        set AZURE_STORAGE_CONNECTION_STRING environment variable)
    (3) account name and SAS token (--sas-token option used with either the --account-name
        option or AZURE_STORAGE_ACCOUNT environment variable)
```

However, if I simply add the `--account-name` flag and re-run the command, it succeeds (as I had hoped). #1 and #3 above imply that I needed to also specify either an `--account-key` or `--sas-token` value, but that doesn't seem to be the case.

Am I missing something, or could this help text be updated to reflect this behavior?

As an aside, "specified" is spelled incorrectly in the message above.

**Comment by tjprescott** [comment]
Account name and key ARE required. In your case, if you specify just the account name, the CLI goes behind the scenes to try and retrieve the key. This is not encouraged because the key is not cached and adds additional REST calls, making it more likely to hit your rest call quotas.

**Comment by lostintangent** [comment]
Ah OK that makes sense. It would be cool if that explanation was added to the help text, since it's super helpful. Thanks!

**Comment by JasonRShaver** [comment]
Cleaning up old issues, reopen if this is still active.

**Comment by TomasHubelbauer** [comment]
This should be changed, because running `az storage account create --help` gives an example:

```
az storage container create -n MyStorageContainer
```

Which doesn't work and there is no explanation as to where to go from there. I tried to follows [Specify storage account credentials](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli#specify-storage-account-credentials) but found the current documentation page insufficient as well. So I filed MicrosoftDocs/azure-docs#21964. In the end I figured it out (see the linked issue), but it was not straightforward and the error text is not helpful.
