### ISSUE TITLE
ProductFunction - ProductDetails function not created , same issue for OrderFunction

### ISSUE THREAD

**Issue by alwisr** [Azure/azure-cli#20035]
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp create --resource-group {} --consumption-plan-location {} --name {} --storage-account {} --functions-version {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by navba-MSFT** [comment]
@alwisr Apologies for the late reply. There is not much information about the error in your issue details section. Were you getting a similar error that is reported in https://github.com/Azure/azure-cli/issues/19903? If Yes, then that issue is now fixed. So please upgrade to the most [recent version of Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)and test the behavior. Also since this github thread has been open for quite sometime, so please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@alwisr Please let us know if you are still facing this issue. If no further assistance is required on this, can we proceed with closure of this issue? Awaiting your reply.

**Comment by alwisr** [comment]
Thank you. I am sorry. I couldn't respond to you promptly.
