### ISSUE TITLE
`az vm create` fails for Flatcar distro alias because plan information is unset 

### ISSUE THREAD

**Issue by jepio** [Azure/azure-cli#20174]
## Describe the bug

**Command Name**
`az vm create --image Flatcar`

**Errors:**
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMMarketplaceInvalidInput\",\r\n        \"message\": \"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: '/subscriptions/47635d02-50bb-4f1f-8b44-e9e9518015e6/resourceGroups/group7088/providers/Microsoft.Compute/virtualMachines/flatcar-k8s-001'.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create --image Flatcar --size {} -g {} -n {} --storage-sku {} --public-ip-sku {} --admin-username {}`

## Expected Behavior

Expected success. `az vm create --image kinvolk:flatcar-container-linux-free:stable:latest --size {} -g {} -n {}` works correctly, so this looks to be a client-side issue.

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
Compute

**Comment by yonzhan** [comment]
Compute

**Comment by jepio** [comment]
Is there an update on this issue? @yonzhan @zhoxing-ms

**Comment by zhoxing-ms** [comment]
> Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request.

@jepio In fact, this error message is returned by the REST service, so we need the service team to tell us the root cause of this error first~

**Comment by zhoxing-ms** [comment]
@jepio Hi, this issue should be by design.

When the parameters passed in as : `az vm create -g group_name -n vm_name --image 'kinvolk:flatcar-container-linux-free:stable:latest'`

Since the URN pattern specified usrs conforms to `([^:]*):([^:]*):([^:]*):([^:]*)`, CLI automatically weill create a plan based on the URN pattern entered by users.
code link: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L253-L267

When the parameters passed in as : `az vm create -g group_name -n vm_name --image 'Flatcar'`
Since the URN entered as only one alias and other information comes from the default configuration according to the alias, so we will not create a plan when we are not sure whether other information meets the user's needs for creating a plan.

> Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request.

Therefore, according to the error information from REST service, we should need to explicitly specify plan related information, such as: `az vm create -g group_name -n vm_name --image 'Flatcar' --plan-name plan_name --plan-publisher plan_publisher --plan-product plan_product`

**Comment by jepio** [comment]
Thanks for finding the spot @zhoxing-ms. In that case I believe the correct fix is to do the same for the alias, as otherwise user has to provide more information when using the alias compared to URN, which makes alias pointless.

I have prepared PR #21028, can you take a look if it's OK?

**Comment by jepio** [comment]
Thank you @wangzelin007 and @zhoxing-ms !
