### ISSUE TITLE
FunctionApp:`az functionapp deployment source config-zip` does not respect `--slot` argument

### ISSUE THREAD

**Issue by wcislo-taxy-io** [Azure/azure-cli#20240]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
Despite specifying slot (named `test`) new version of source code is deployed to default (production) deployment slot. Regardless slots is specified or not, new version of code is deployed to default (production) slot.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create Azure Function, create deployment slot.
- Deploy one version of code (in my case sample function Python code) to default slot.
- `az functionapp deployment source config-zip -g {} -n {} --src {} --debug`
- Deploy other version of code (in my case sample function Python code) to non-default (test) slot.
- `az functionapp deployment source config-zip -g {} -n {} --src {} -s {} --debug`

## Expected Behavior
Two different versions of code are in default slot and test slot.

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Unable to repro the issue. Please share the `--debug` to analyze further.

**Comment by wcislo-taxy-io** [comment]
Sure, I can do that. Is there any information that I am supposed to hide from `--debug` output because it could be considered sensitive information?

**Comment by Kotasudhakarreddy** [comment]
Yes you can mask your input data from `Request` object or output data from `Response` Object.

**Comment by JessLight** [comment]
Hi get the same issue, zipped packages are uploaded but appsettings are updates to production slot rather than new-release slot. 

I am using the following command 

az functionapp deployment source config-zip \
      -g "${resource_group}" -n "${name}" \
      --src "${package_file_location}" --slot "${slot}"

When running with --debug

az_command_data_logger: command args: functionapp deployment source config-zip -g {} -n {} --src {} --slot {} --debug
....
Does a get to 
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01?api-version=2020-09-01'
..
then does a get to
 
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/serverfarms/NorthEuropeLinuxDynamicPlan?api-version=2020-09-01 
..
then does a Post to 
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01/slots/new-release/config/appsettings/list?api-version=2020-09-01'
... 
Gets a response with setting the run package 
WEBSITE_RUN_FROM_PACKAGE":"https://{storageaccount}.blob.core.windows.net/{container}/20211117103912-{someid}.zip?
..
Does Get to 
Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01/config/slotConfigNames?api-version=2020-09-01'
.. 
Then does GET of container
urllib3.connectionpool: https://{storageaccount}.blob.core.windows.net:443 "GET /{container}?restype=container 
.. 
Uploads new package with PUT
urllib3.connectionpool: https://{storage-account}.blob.core.windows.net:443 "PUT /{container}/20211119081711-{some-id}.zip
..
**Then updates the production slot app setting to use the new package instead of new-release**

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01/config/appsettings/list?api-version=2020-09-01'

Setting production to "WEBSITE_RUN_FROM_PACKAGE":"https://{storage-account}.blob.core.windows.net/{container}/20211119081602-{some-id}.zip?
.. 
Does two PUTs at the end to production slot too
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01/config/appsettings?api-version=2020-09-01'

.. It correctly then syncs triggers to the new-release slot
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.Web/sites/function-01/slots/new-release/syncfunctiontriggers?api-version=2020-09-01'

**Comment by wcislo-taxy-io** [comment]
I can confirm that in my logs the same thing is visible. `WEBSITE_RUN_FROM_PACKAGE` app setting is updated in production slot instead of in the selected slot.

**Comment by Kotasudhakarreddy** [comment]
Checking it.

**Comment by navba-MSFT** [comment]
@wcislo-taxy-io Apologies for the late reply. We will look into this issue and get back with an update.
@Kotasudhakarreddy Could you please provide an update on this?

**Comment by Treybleed** [comment]
@Kotasudhakarreddy @navba-MSFT Any update on this? I'm still getting this issue.

**Comment by Kotasudhakarreddy** [comment]
Yes, I am able to repro the issue. It requires code fix. We will plan for a fix in the coming releases. 
@panchagnula FYI

**Comment by tombellshield** [comment]
This should be fixed by #21698.

**Comment by panchagnula** [comment]
Closing this since this is fixed.

**Comment by Quanalogy** [comment]
@tombellshield @panchagnula  either the fix never got out to azure.com or it have reintroduced itself because we are experiencing this now.
