### ISSUE TITLE
error - multiple accounts with same user name - requested to report it to GITHUB

### ISSUE THREAD

**Issue by lostinlux** [Azure/azure-cli#20243]
Hi,
I am doing Microsoft learn training and am receive issue with too many accounts?

Current exercise: Explore Azure Resource Manager template structure

https://docs.microsoft.com/en-us/learn/modules/create-azure-resource-manager-template-vs-code/2-explore-template-structure

When I try to run command : az account list-locations  I am told this:

Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This issue is being discussed at #20168. @lostinlux, have you logged in twice with the same email address as both

- Microsoft Account
- AAD Account

Could you follow https://github.com/Azure/azure-cli/issues/20168#issuecomment-958765085 and share your account information?

For now, you may follow https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 to get unblocked.
