### ISSUE TITLE
Option to remove a backup ?

### ISSUE THREAD

**Issue by StefH** [Azure/azure-cli#20616]
Is there also a command to remove / delete a specific backup by the `id` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae944b4-aa1b-4bc7-5f3c-1e645c792e86
* Version Independent ID: 06e361cb-035c-0b20-1b85-6532e551a35a
* Content: [az webapp config backup](https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/backup.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config/backup.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
@AzureAppServiceCLI, @antcp, please help take a look.

**Comment by seligj95** [comment]
@StefH - at this time it looks like you only have the ability to delete using the `name` via the `az storage blob delete` command - https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_delete

Routing to storage team for confirmation.

**Comment by StefH** [comment]
Hello @seligj95, thanks for your reply, however I know to delete a backup from storage, I did that:
![image](https://user-images.githubusercontent.com/249938/145109293-411f47e3-3b41-46b7-ad35-937f3471515a.png)


However, this deleted backup is still visible in the backup list from the web-app:
![image](https://user-images.githubusercontent.com/249938/145109357-250f0709-116c-493d-bed2-70ed19b71750.png)

**Comment by seligj95** [comment]
@StefH - were you able to restore from the backup you deleted from storage? I deleted the relevant storage blobs and the backup is still visible as you pointed out, but I get an error when trying to restore that backup since the underlying files no longer exist.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/11475594/145234938-0fb2bc83-deee-466b-808f-f8ae1a8fe267.png">

There doesn't seem to be a way to delete a specific backup from the App Service portal but you can delete the underlying files. I will take this back to the team to confirm and see if this is something on the roadmap.

**Comment by StefH** [comment]
@seligj95

> There doesn't seem to be a way to delete a specific backup from the App Service portal but you can delete the underlying files. I will take this back to the team to confirm and see if this is something on the roadmap.

This is what I also would like to know. If you have any news on this, please keep me informed.

**Comment by vkarasala** [comment]
Please find the CLI command to delete the backup by id here : https://learn.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#az-webapp-config-backup-delete

Thanks,
Ashok.
