### ISSUE TITLE
aka.ms/slb link points to an internal Microsoft location

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#20734]
**Describe the bug**

`aka.ms/slb` points to https://sharepoint/sites/autopilot/wiki/Software%20Load%20Balancer.aspx

See #20693 for context.

**To Reproduce**

Simulate error as described in #20693, observe that error message refers users to an `aka.ms/slb` link for more details.

**Expected behavior**

Use publicly-available links that are relevant to Azure infra, not Autopilot.

**Environment summary**

```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
aks-preview 0.5.47
azure-devops 0.22.0
front-door 1.0.16
log-analytics 0.2.1
resource-graph 2.1.0
```

**Additional context**

See #20693

**Comment by jiasli** [comment]
Routing to service team.

**Comment by navba-MSFT** [comment]
@wasker Apologies for the late reply. Thanks for sharing the feedback. We are looking into this ask and we will update this thread once we have more details. 

@Azure/aks-pm Could you please look into this issue once you get a chance ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@wasker This issue is now fixed. Thanks again for raising this issue. 

>(InvalidLoadBalancerProfileOutboundIPs) Error in validating load balancer profile outbound IPs, error details: Load balancer profile outbound IP /subscriptions/XXXXXXXXXX/resourceGroups/XXXXXXXXXX/providers/Microsoft.Network/publicIPAddresses/XXXXXXX is managed outbound IP, so it cannot be used as user specified outbound IP. Please refer to **http://aka.ms/aks/slb-byo-ip** for more details.
Code: InvalidLoadBalancerProfileOutboundIPs
Message: Error in validating load balancer profile outbound IPs, error details: Load balancer profile outbound IP /subscriptions/XXXXXXXXXX/resourceGroups/XXXXXXXXXX/providers/Microsoft.Network/publicIPAddresses/XXXXXXX is managed outbound IP, so it cannot be used as user specified outbound IP. Please refer to **http://aka.ms/aks/slb-byo-ip** for more details.
Target: networkProfile.loadBalancerProfile.outboundIPs

We will now proceed with the archival of this thread. If you need any further assistance on this in future, please feel free to reopen this thread.
