### ISSUE TITLE
Command az vmss list-instance-public-ips returns empty array instead of IPs

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-cli#20769]
## Describe the bug

Command `az vmss list-instance-public-ips` returns empty array.

My setup:

1. VMSS
2. Standard Load Balancer
3. Standard IP
4. Inbound rules
5. Health probes

means few web services are running and reachable from the internet. Also the VMSS is running a Service Fabric cluster so its management ports are also reachable.

## Actual Behavior

The output is:

```json
[]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
az vmss list-instance-public-ips --resource-group my-shared-dev-westus2-1 --name public
```

## Expected Behavior

The 3 public IPs are listed.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0
```
## Additional Context

Feel free to reach out internally, happy to help to troubleshoot.

**Comment by jiasli** [comment]
Thank you for reporting this issue. We will take a look.

**Comment by abatishchev** [comment]
hi @yonzhan, @jiasli, what does adding the issues to the `backlog` means? Would it be investigated anytime soon?

**Comment by zhoxing-ms** [comment]
@abatishchev At present, the `az vmss list-instance-public-ips` command directly returns the data from REST service without its own filtering logic, so this may be a issue related to service.
Could you add `--debug` parameter after the command you execute? Then please send the printed debug log to me by email (Zhou.Xing@microsoft), thanks~

**Comment by abatishchev** [comment]
Sent over email. Thanks!

**Comment by zhoxing-ms** [comment]
This issue is caused by REST [list-virtual-machine-scale-set-public-ip-addresses](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/public-ip-address-in-vm-ss/list-virtual-machine-scale-set-public-ip-addresses) not returning any data when CLI requests it. Therefore, this issue needs to be investigated by service team

**'x-ms-correlation-request-id': '421c926e-0a87-4d3b-9a57-425ccd7f1136'**

**Comment by abatishchev** [comment]
@Drewm3 can you please comment on the plans (if any) to fill the gap in the experience between the Azure Portal (that does additional API calls to support a more complex model of VMSS -> LB -> IP) and the CLI (which does not)?

**Comment by jaylabell** [comment]
@avirishuv can you please take a look at this issue?

**Comment by avirishuv** [comment]
investigating, will provide an update with more information here.

**Comment by avirishuv** [comment]
hi @abatishchev are you using public IP on the load balancer, or on the VMSS VMs, or both?

**Comment by abatishchev** [comment]
@avirishuv it's VMSS -> Standard LB -> Standard IP

**Comment by avirishuv** [comment]
@abatishchev in that case the IP would not be returned with this cmd, because this is for the IP address of the VMSS VM instances, not for the IP address of load balancer.

https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-list-instance-public-ips

**Comment by abatishchev** [comment]
yes, that's the current design and confirmed by the observations. However it contradicts the experience on the Azure Portal which is capable to derive the IP from the configuration and generate the correct link to it.

**Comment by Drewm3** [comment]
@abatishchev, it is debatable if what the portal is doing is really "correct". The portal does the same thing for a VM that is behind a load balancer where it has something that says "Public IP address" on the VM, but then proceeds to show the public IP address of the load balancer instead of the public IP address specific to the VM. In my opinion the appropriate thing to show as the public IP address **of the VM** is the Public IP address of the actual VM. If the VM is behind a load balancer it is useful to show that in the portal, but it should be clearly labeled as the IP address of the load balancer that the VM is behind instead of implying that it is the IP address of the VM. This is important because only certain traffic will make it from the LB to the VM through that IP based on LB Rules, but if the IP is a public IP resource then 100% of the traffic will be sent to the VM.

In the case of the API for VMSS it only returns actual Public IP addresses for the instances. If the instances are accessible through other mechanism then you will need to identify them in the same way that the portal is doing by finding the appropriate Load Balancer or App Gateway for the Backend pool where the instances are being placed, and then query the LB or AppGateway resource to identify the IP address of that resource.
