### ISSUE TITLE
VMSS VM Customization Properties

### ISSUE THREAD

**Issue by raktdas** [Azure/azure-cli#20786]
**Resource Provider**
Compute Resource Provider (CRP) - > Virtual Machine Scale Sets (VMSS)

**Description of Feature or Work Requested**
In VMScaleSet, a new property "HardwareProfile" has been added, which is a class containing an ApiEntityRef "vmSizeProperties" which tracks the association of the vCpusAvailable and vCPUsPerCore

Commands needed:

az vmss create [-vCPUsPerCore <String>] [-vCPUsAvailable <String>]
az vmss update [-vCPUsPerCore <String>] [-vCPUsAvailable <String>]

**Minimum API Version Required**
2021-11-01

**Swagger Link**
[](https://github.com/Azure/azure-rest-api-specs/pull/16723)

**Target Date**
Jan 1, 2022

**Comment by jiasli** [comment]
Thank you for reporting this issue. We will take a look.

**Comment by zhoxing-ms** [comment]
@raktdas At present, our subscription needs to register the feature of `Microsoft.Compute/VMCustomizationPreview`, otherwise we can't test this feature
For `az vm create/update`, we already have a PR to support `--v-cpus-available` and `--v-cpus-per-core`, but the related tests are blocked.
For `az vmss create/update`, if our subscription is not registered in time, we will plan it's development and release to the next sprint (03-01)

**Comment by raktdas** [comment]
> @raktdas Hi, at present, our subscription needs to register the feature of `Microsoft.Compute/VMCustomizationPreview`, otherwise we can't test this feature in our development process For `az vm create/update`, we already have a PR #20818 to support `--v-cpus-available` and `--v-cpus-per-core`, but the related tests are blocked. For `az vmss create/update`, if our subscription is not registered in time, we will plan it's development and release to the next sprint **(03-01)**

Its done

**Comment by zhoxing-ms** [comment]
> Minimum API Version Required
2021-11-01

@raktdas Since the directory for api-version `v2021-11-01` has not been released in latest package of `azure-mgmt-compute: 24.0.0`, if we want to release this feature in this sprint, we need to make the following decisions:

1. You need to release the latest package of `azure-mgmt-compute` containing version `v2021-11-01` directory before January 26, otherwise CLI cannot upgrade api-version for Compute RP to `2021-11-01` in this sprint
2. According to @PARADISSEEKR, this feature is also supported in api-version `2021-07-01`, so we may be able to keep the original api-version.

May I ask which way do you prefer?
