### ISSUE TITLE
Help message un-informative

### ISSUE THREAD

**Issue by VectorBCO** [Azure/azure-cli#21104]
This descriptions is not ok because they did not provide any reasonable information what this parameter is, where it can be find, how it can be used...:

--blob-container
Blob container Name. 

--namespace-name
Name of Namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-list)
* Content Source: [latest/docs-ref-autogen/eventhubs/eventhub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/eventhubs/eventhub.yml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @VectorBCO , thanks for bringing this to our attention. 

Cmdlet help is generated to facilitate any specific details that users might need help with. I would recommend to go through the product docs to understand more on the details like what exactly a namespace is and why would you need blob container ( for capture purposes). 

Here are few docs that could be helpful :

https://docs.microsoft.com/en-in/azure/event-hubs/event-hubs-capture-overview
https://docs.microsoft.com/en-in/azure/event-hubs/event-hubs-features 

Please feel free to write back if you observe any other missing information and I would be happy to revisit.

**Comment by VectorBCO** [comment]
are you sure i'm looking for some other docs when read that exact article? 
That is a worse possible practice for writing descriptions in that way `ServerName - server name parameter`. 
That not a description!

**Comment by Saglodha** [comment]
@VectorBCO - Sorry to hear about your experience, can you share the doc where you observe the description to have  ServerName - server name parameter? 

I couldn't find this parameter in the doc pinned to this issue: https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-list

**Comment by VectorBCO** [comment]
![Screenshot_20220322-105714_Chrome](https://user-images.githubusercontent.com/13451494/159454969-2fda2508-2af6-443f-8e9f-cd05643146b5.jpg)

**Comment by VectorBCO** [comment]
I'm not agree that this is ok for any type of documentation especially for technical docs

**Comment by Saglodha** [comment]
@VectorBCO, I appreciate your suggestions here. 

In this case, we could plan to update the description of --namespace-name to be: Name of Event Hubs namespace. Do you think this would be adequate for your use case?

**Comment by VectorBCO** [comment]
This is better than now, but nope it is still un-googlable

Imagine you need modify eventhub somehow. 
You have access to the portal where you can test some staff. Then you need prepare a command to do magic automatically. 
Where in a Portal I can find `Name of Eventhub NameSpace`? How can I find that namespace-name with `az cli` or `azure powershell`?

There no such information in the Portal in this words.
So, next you go to the Google and find some MS examples where provided `myeventhubnamespace` which also give you nothing. 
Next you will spend half of a day to become a EH specialist just because documentation is not clear, and do not provide simple answer for simple question.

**Comment by Saglodha** [comment]
@VectorBCO - I understand your concerns here and would like to provide some insights to the issue that you have been supposedly facing.

While you have to update event hub, you would need namespace name (namespace is just a logical container that stores different event hubs and namespace name is same as any resource name that you would create on Azure). On Azure Portal, we follow similar convention of showing up resource name on top left corner or properties of resource. Adding below screenshot here: 

<img width="518" alt="image" src="https://user-images.githubusercontent.com/62641016/159654714-3fcc2cec-f1ed-4175-a6fb-b4969c7be772.png">

For Azure CLI we have az eventhubs namespace list cmdlet that lists all event hubs namespaces under a subscription and has properties with name as the key and the value what would you be looking for. We have cmdlet for getting particular event hubs namespace as well (provided you have the details of event hub you are looking to update)
Here is how the output would look like: 

<img width="478" alt="image" src="https://user-images.githubusercontent.com/62641016/159654953-400cc2e3-2439-4eed-81e1-1ee23ea7f5de.png">

Similar experience is provided with Azure PowerShell by using the Get cmdlet for namespace: Get-AzEventhubnamespace.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/62641016/159655323-0261a344-a899-49a5-8813-262923bebe5a.png">

Its worthy to mention that the introduction of List command in CLI or Get cmdlet in PowerShell is common across Azure Services. The placement of name of resource on left corner of Azure portal is also something that is implemented similarly for all Azure Services to ensure better experience. 

I can agree that without having an idea of the property its harder to find it on the tools however CLI/PS help is not written or developed to answer terminology questions. Our public docs that I shared in my last comment is the right technical place to read through and find more details on different aspects of product.

As an example. our public docs being written and maintained here: https://docs.microsoft.com/en-us/azure/event-hubs/, should be one stop destination to find answers to any terminology that you would like to know about event hub. Our intention here is to ensure the transparency is maintained in consistent manner over any quick answers so that you could finally decide how our product as whole can help you and your use case. 

For now, we could stretch at most to add some specifics like event hubs namespace to the help like I mentioned before, please let me know if you would like that to be added.

**Comment by VectorBCO** [comment]
could you show me somewhere 
`NameSpace Name: testnamesaglodha`
on your screen I see just only `Name` and nothing about `NameSpace`

**Comment by Saglodha** [comment]
@VectorBCO - Sure, if I create a test event hub under the namespace and go to overview blade on portal, I can find the details. Here is a screenshot:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/62641016/159674493-fd22bcb8-a9cc-4082-ad72-8400749c70b1.png">

**Comment by Saglodha** [comment]
@VectorBCO . thanks for sharing the feedback, We would plan to add some part of description to cli help.
