### ISSUE TITLE
Duplicate title on login page

### ISSUE THREAD

**Issue by xisui-MSFT** [Azure/azure-cli#21169]
**Describe the bug**
Duplicate title on login page
![image](https://user-images.githubusercontent.com/44103947/152045624-f37d7707-9ba2-498d-94dc-72168d0138d4.png)

**To Reproduce**
`az login` on Linux.

**Expected behavior**
No duplicate title.

**Environment summary**
azure-cli                         2.0.81

core                              2.0.81
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location '/usr/bin/python3'
Extensions directory '/home/xisui/.azure/cliextensions'

Python (Linux) 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

**Additional context**
N/A

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I am able to reproduce with `az login --use-device-code`:

![image](https://user-images.githubusercontent.com/4003950/152735532-fd0fb391-824d-4aa9-b9bd-543c3c7c5a9b.png)

Azure PowerShell command `Connect-AzAccount -UseDeviceAuthentication` also shows duplicated title:

![image](https://user-images.githubusercontent.com/4003950/152735656-c0f3e6b0-6368-4d06-a387-52d896001bd2.png)

This is the behavior of AAD login page, instead of client tools. We will report this issue to AAD.

**Comment by jiasli** [comment]
I am not seeing duplicated title anymore:

![image](https://user-images.githubusercontent.com/4003950/153161438-9994e338-4f3a-4c0b-bf8a-0958bd4f2d98.png)

@xisui-MSFT, please check again to see if it has been solved for you.

**Comment by xisui-MSFT** [comment]
Checked just now, looks like this issue has been fixed. Thanks for the help!
