### ISSUE TITLE
Application Gateway start fails

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2120]
start fails with  "long running operation wait cancelled." message. Retrying start gives Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/providers/Microsoft.Network/locations/brazilsouth/operations/0b5c39d1-1f92-40f9-9450-3889bf7c4b55?api-version=2016-09-01.

**Comment by tjprescott** [comment]
This is working as intended. The majority of time, the polling will continue until the operation finishes. If the polling terminates because it takes too long (which is controlled by the SDK), then you can't retry because the service is still updating.

You can use `application-gateway wait -g {rg} -n {name} --updated` to resume polling.

**Comment by gitreelike** [comment]
@tjprescott I'm using ARM templates and i get that error in about 50% of the cases. That's usually after about 40-50 minutes (there are also some other resources that take time). I'm experiencing this in westeurope.

Is there anything I can do to resume polling with ARM templates?

**Comment by tjprescott** [comment]
There is a `group deployment wait` command that should do what you are looking for.

**Comment by gitreelike** [comment]
@tjprescott Thank you! I'll give it a shot on the next deployment.
