### ISSUE TITLE
Add WAM support in Azure CLI

### ISSUE THREAD

**Issue by medhir** [Azure/azure-cli#21201]
**Is your feature request related to a problem? Please describe.**

A near-term future release of MSAL Python will enable broker-based authentication through Web Account Manager (WAM) on Windows devices. The benefits of authentication through WAM are described [in this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam#wam-value-proposition) under the "WAM value proposition" heading. 

**Describe the solution you'd like**

Upgrade MSAL Python (upon release of the latest version including WAM support) and enable authentication through WAM. 

**Additional context**

@rayluo is currently driving the work to enable WAM support within MSAL Python and the functionality will be ready for testing by mid-February. Ahead of release we would like the Azure CLI team to run tests against WAM functionality / identify any bugs in a feature branch @rayluo will provide.

**Comment by yonzhan** [comment]
WAM support

**Comment by jiasli** [comment]
I think there is a lot more than bumping MSAL:

1. How will `az account clear` and `az logout` work? Currently `az account clear` deletes `~/.azure/msal_token_cache.bin`, if MSAL uses WAM, how can accounts be deleted?
2. Will Azure CLI and Azure PowerShell share the same login context? What if Azure CLI deletes an account that is currently used by PowerShell, will Azure PowerShell be affected?
3. Will WAM slow down the execution speed of MSAL and Azure CLI?
4. Will MSAL HTTP cache still work?
5. Will WAM work with getting VM SSH certificate through `data`?

**Comment by rayluo** [comment]
> I think there is a lot more than bumping MSAL:

Indeed. While the integration is currently designed to be as simple as bumping MSAL, the implication is serious.

> 
> 1. How will `az account clear` and `az logout` work? Currently `az account clear` deletes `~/.azure/msal_token_cache.bin`, if MSAL uses WAM, how can accounts be deleted?

There will be a new broker (WAM) layer operates beneath MSAL Python. Each layer has its own cache mechanism.

Based on your description, it sounds like Azure CLI simply deletes MSAL's token file without using [MSAL's `remove_account()` API](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.remove_account). Either way, it has been good enough to reset Azure CLI into an not-yet-signed-in state, although the subsequent `az login` sign-in might not actually prompt user to enter their password again (is that true?), because the browser still holds a valid signed-in state. After the broker integration, the `az login` experience would probably remain the same, it is just that the valid signed-in state is kept in broker (WAM), not in browser.

We are also looking into how MSAL's `remove_account()` will also wire up with broker's corresponding mechanism.

> 
> 2. Will Azure CLI and Azure PowerShell share the same login context? What if Azure CLI deletes an account that is currently used by Azure PowerShell, will Azure PowerShell be affected?

When/if MSAL's `remove_account()` removes the account in WAM, all apps using broker/wam mechanism will share the same signed state, so one app can affect the rest.

> 
>     3. Will WAM slow down the execution speed of MSAL and Azure CLI?

The `acquire_token_silent()` call feels still fast enough. The `acquire_token_interactive()` seems tangibly slower. MSAL does not really have a control on this part. Please test it and report back.

> 
>     4. Will MSAL HTTP cache still work with WAM?

Not for broker/wam. But broker/wam is only for public clients, AzureCLI and MSAL Python still need to support Confidential Clients i.e. Service Principals. And, currently broker only supports Windows, but the vast majority of MSAL downloads are from Linux platform (is it also true for Azure CLI?). So, our effort on `http_cache` will not be wasted.

> 
>     5. Will WAM work with getting VM SSH certificate through `data`?

We were not able to test this for you. You would need to follow our prerequisite No.1 to setup the proper redirect_uri, and then ping me, I'll test it for you.

> 
>     6. Is it possible to turn off WAM integration and use the current token cache file?

The MSAL layer operates on top of WAM layer. MSAL will already look for an access token (AT) from MSAL's own token cache first. If it finds an AT, broker/WAM will not kick in.

Currently, other than "prerequisite no. 2", MSAL Python does not provide a more granular way to turn on/off broker. Please conduct your integration tests and see whether we will run into any scenario that a more granular control is desirable.

> 
>     7. What if the system doesn't support WAM, like old versions of Windows, Windows Server?

MSAL Python will automatically fall back to the non-broker behavior.
