### ISSUE TITLE
Upgrade API version used for Azure Managed Identity

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-cli#21216]
**Resource Provider**

Microsoft.ManagedIdentity

**Description of Feature or Work Requested**

Update to API version 2018-11-30 using codegen

**Minimum API Version Required**

2018-11-30

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/476564a1aa6ddb38ec681c9f89d42f00c1becd25/specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2018-11-30/ManagedIdentity.json 

**Target Date**

To be included in April release

cc: @karavar

**Comment by yonzhan** [comment]
Managed Identity

**Comment by zhoxing-ms** [comment]
@dcaro Hi, since CLI depends on Python SDK, please release the new version of Python SDK `azure-mgmt-msi`.

In fact, we already have a module `identity` to implement the feature of RP `Microsoft.ManagedIdentity`. [code link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/identity/commands.py#L21-L27)
For this requirement, do we only need to upgrade the api-version for `Microsoft.ManagedIdentity`, or do we also need to add some new commands at the same time?

**Comment by zhoxing-ms** [comment]
> since CLI depends on Python SDK, please release the new version of Python SDK azure-mgmt-msi

At present, `azure-mgmt-msi 1.0.0` already supports api-version `2018-11-30`, so we don't need to release the new Python SDK
