### ISSUE TITLE
AppGW NSG management group check fails on redeploy

### ISSUE THREAD

**Issue by Gordonby** [Azure/azure-cli#21256]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I have an Arm json file that contains an NSG definition, which is used on an Application Gateway v2 subnet.
The deployment completes successfully the first time, however when deploying the arm template subsequent times (even when no changes are present, see what-if below) the deployment always fails with this message

> ApplicationGatewaySubnetInboundTrafficBlockedByNetworkSecurityGroup Network security group nsg-agw-nprd-euw-uk2s blocks incoming internet traffic on ports 65200 - 65535 to subnet appgw-sn, associated with Application Gateway agw-nprd-euw-uk2s. This is not permitted for Application Gateways that have V2 Sku.

**This is an idempotency issue around the Application Gateway NSG rule checking.**

### what-if output (no changes)

If instead of doing an az deployment group create, i perform a what-if - i can see that there are no changes.

```text
Scope: /subscriptions/REDACTED/resourceGroups/innerloop

  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s [2021-05-01]
  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s/providers/Microsoft.Insights/diagnosticSettings/diags-nsg-agw-nprd-euw-uk2s [2021-05-01-preview]
  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s/securityRules/Allow_AppGatewayManagement [2021-05-01]
  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s/securityRules/Allow_AzureLoadBalancer [2021-05-01]
  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s/securityRules/Allow_Internet_Http [2021-05-01]
  = Microsoft.Network/networkSecurityGroups/nsg-agw-nprd-euw-uk2s/securityRules/Deny_AllInboundInternet [2021-05-01]

Resource changes: 6 no change, 27 to ignore.
```

If I disassociate the delete the NSG, delete it, redeploy then associate with the AppGW subnet it works 🥇 

### Portal Experience

If I go into the Portal, i am prevented from deleting the management security rule - but can make any other changes to the NSG such as widening the port range used. 🥇 

### Idempotency

Even though there is no changes to the NSG, the ApplicationGatewaySubnetInboundTrafficBlockedByNetworkSecurityGroup check fails.

**To Reproduce**
1. Create a vnet, subnet, and deploy Azure Application Gateway to it.
2. Apply the [NSG](https://gist.github.com/Gordonby/a53ee984dd8b693da0763dd86f2ae73b#file-appgwnsg-json)
3. Redeploy the [NSG](https://gist.github.com/Gordonby/a53ee984dd8b693da0763dd86f2ae73b#file-appgwnsg-json) immediately and experience the idempotency issue

**Expected behaviour**
A redeployment of the NSG where no properties change should pass the ApplicationGatewaySubnetInboundTrafficBlockedByNetworkSecurityGroup check.

**Environment summary**
PowerShell using 2.26 and WSL using 2.33.0

**Comment by yonzhan** [comment]
network

**Comment by Gordonby** [comment]
I`ve just checked, and this is still an issue.

**Comment by YuanyuanNi** [comment]
Hi:
     @Gordonby, I have followed your steps in "To Reproduce“ and have not reproduce it in CLI 2.34.1, can you update to the latest version and try again? if still happen, pls attach more details in "To Reproduce“ module, thanks.
Best wishes.

**Comment by Gordonby** [comment]
Confirmed fix.

I've checked again with 2.34.1 as suggested - and it works as expected now. Thank you.

**Comment by bigglesuk69** [comment]
I'm getting the same issue but on a later version of Azure CLI. Clean deployment is fine, but any further deployment errors that the NSG rule is missing the required App GW rule, but it's there. I'm running CLI version 2.36.0 and Bicep 0.6.11

**Comment by michaeljsaxbury** [comment]
@YuanyuanNi @kairu-ms 
i am on version 2.84.0 and I am receiving the same error, exact same scenario as Gordonby provided.
Bicep config:
{
    name: 'nonfed-lt-agw-eu2-nsg-01'
    subscriptionId: '2b9a3333-a8cc-467c-babc-205e956443a9'
    resourceGroup: 'nonfed-lt-platform-network-eu2-rg-01'
    location: 'eastus2'
    ruleSet: ['akamaiRules']
    ruleSetFile: ['infra/platform/domains/network/variables/lt.akamai-rules.json']
    securityRules: [
      {
        name: 'Allow-AGW-Probe-In'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '65200-65535'
          sourceAddressPrefix: 'Internet'
          destinationAddressPrefix: '*' // app gateway deploy is failing with error, seems like it cannot see this allow rule, so try all addresses instead '10.20.218.0/28' // Updated to AGW subnet
          access: 'Allow'
          priority: 100
          direction: 'Inbound'
        }
      }
      {
        name: 'Azure-Out'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '*'
          access: 'Allow'
          priority: 110
          direction: 'Outbound'
          sourceAddressPrefixes: ['10.20.218.0/28'] // AGW subnet
          destinationAddressPrefixes: ['10.20.218.0/28'] // AGW subnet
        }
      }
    ]
  }

Pipeline output:
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Resources/deployments/platform-networks","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Resources/deployments/nsg_nonfed-lt-agw-eu2-nsg-01","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Resources/deployments/nsg_nonfed-lt-agw-eu2-nsg-01","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ApplicationGatewaySubnetInboundTrafficBlockedByNetworkSecurityGroup","message":"**Network security group** /subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Network/networkSecurityGroups/nonfed-lt-agw-eu2-nsg-01 **blocks incoming internet traffic on ports 65200 - 65535 to subnet** /subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Network/virtualNetworks/nonfed-lt-eu2-vnet-01/subnets/nonfed-lt-agw-eu2-snet-01, associated with Application Gateway /subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Network/applicationGateways/nonfed-lt-eu2-agw-01. This is not permitted for Application Gateways that have V2 Sku.","details":[]}]}]}]}} ]


azure json view of the nsg:
{
    "apiVersion": "2025-05-01",
    "id": "/subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Network/networkSecurityGroups/nonfed-lt-agw-eu2-nsg-01",
    "name": "nonfed-lt-agw-eu2-nsg-01",
    "type": "microsoft.network/networksecuritygroups",
    "location": "eastus2",
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "138f0a44-2ab1-4f87-a39a-2575fdfd85df",
        "securityRules": [
            {
                "name": "Allow-AGW-Probe-In",
                "id": "/subscriptions/2b9a3333-a8cc-467c-babc-205e956443a9/resourceGroups/nonfed-lt-platform-network-eu2-rg-01/providers/Microsoft.Network/networkSecurityGroups/nonfed-lt-agw-eu2-nsg-01/securityRules/Allow-AGW-Probe-In",
                "etag": "W/\"dacc32bd-3317-4d53-9eb0-b2b0665317c7\"",
                "type": "Microsoft.Network/networkSecurityGroups/securityRules",
                "properties": {
                    "provisioningState": "Succeeded",
                    "protocol": "*",
                    "sourcePortRange": "*",
                    "destinationPortRange": "65200-65535",
                    "sourceAddressPrefix": "Internet",
                    "destinationAddressPrefix": "*",
                    "access": "Allow",
                    "priority": 100,
                    "direction": "Inbound",
                    "sourcePortRanges": [],
                    "destinationPortRanges": [],
                    "sourceAddressPrefixes": [],
                    "destinationAddressPrefixes": []
                }
            }

I have tried protocol TCP, same error, deleting the nsg it works.
