### ISSUE TITLE
Updating device twin tags are not working

### ISSUE THREAD

**Issue by ikivanc** [Azure/azure-cli#21255]
I want to update my device twin's tags and based on official documentation. It suggests to use `--tags` to add a tag to a device twin, unfortunately I get error even I try the sample provided in the documentation.

![image](https://user-images.githubusercontent.com/118657/154146865-b60ed9df-cb80-4644-88cc-bf6211def942.png)

When I check the JSON samples in in error message, and suggests to use `--set tags={...}` I get the same error.
![image](https://user-images.githubusercontent.com/118657/153582077-4866cedb-e83a-4aad-8779-d45c9b1b05d2.png)

When I use `az iot hub device-twin replace` and provide full device twin json file it works.
`az iot hub device-twin replace -d windmill-rp2-01 -n iot-windmill -j rp2-device-twin.json`

Is it possible to check what's missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5c4040e-2a33-0065-5b6d-971f012d1f97
* Version Independent ID: ba28af00-d28a-5211-decd-95231198a54e
* Content: [az iot hub device-twin](https://docs.microsoft.com/en-us/cli/azure/iot/hub/device-twin?view=azure-cli-latest#az-iot-hub-device-twin-update)
* Content Source: [latest/docs-ref-autogen/iot/hub/device-twin.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/hub/device-twin.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by digimaun** [comment]
Hey @ikivanc thanks for submitting this issue. A problem with inline json input is syntax may change based on the shell.

In your screenshot, those attempts should work in bash -- are you using `cmd`? In that case try `"{\"country\": \"USA\"}"` i.e.

`az iot hub device-twin update -n iot-windmill -d windmill-rp2-01 --tags "{\"country\": \"USA\"}"`  

Please use `--desired` or `--tags` to update the respective properties rather than `--set`. Also both of those args should take file paths (where we have a gap in documentation).

We will need to update our wiki to be more clear on inline json syntax difference between shells and to show file input for --tags/--desired is possible.

**Comment by ikivanc** [comment]
Thank you so much @digimaun , error messages are a bit misleading, I totally missed that point. If there could be a clarification in `Tips` section that would be perfect!

**Comment by vilit1** [comment]
Closing since this seems to be solved. If there are any more issues, please comment on this issue thread.
