### ISSUE TITLE
aks list returns an empty array 

### ISSUE THREAD

**Issue by rozsapeter96** [Azure/azure-cli#21511]
### aks list returns an empty array 

Executing aks list CLI command after creating a Kubernetes cluster on the UI returns an empty array. The cluster got listed on the UI properly.

**Command Name**
`az aks list`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- create a Kubernetes service on the Azure portal
- `az aks list --debug`

## Expected Behavior
The result should contain the newly created Kubernetes service

## Environment Summary
```
Linux-5.4.0-1070-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.0 *

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
Kubernetes service created from the CLI is listed properly, and even the previously unlisted services will show up if one service is created by the CLI

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@rozsapeter96 Could you confirm if you are setting the right resource group? If you don't pass one, it will use the default from the config or a [persisted param](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-list).

**Comment by rozsapeter96** [comment]
@PramodValavala-MSFT I retried with --resource-group and with --subscription flags, I got the same result, unfortunately. In the meantime I noticed that the cluster has magically appeared after 3 hours of its creation, which is very odd, I think.

**Comment by PramodValavala-MSFT** [comment]
@rozsapeter96 Apologies for not getting back sooner on this! This is likely an intermittent issue which could have been simply due to a delay in data being synchronized across systems. It would be best to create a support ticket if you see this frequently though, to identify any other issue.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
