### ISSUE TITLE
Cannot set secret contains quotes, dollar sign, etc

### ISSUE THREAD

**Issue by aistvan** [Azure/azure-cli#21552]
```
$secret = 'ABC"$$123==)'
az keyvault secret set --vault-name MyKeyVault --name "Test" --value $secret
```

got

`ABC$$123==)`

with

`$secret = "ABC'$$123==)"` 

got

`ABC'$secret123==`

Wired.
What I expect, the ability to set secret contains ANY character from my keyboard. Like '"+!%/=()~ˇ^˘°˛`˙´˝¨÷×¤ß$Ł|\<>#&@{};*,-?:_

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
May I know which cmd are you using? Bash or Powershell or windows bash?

**Comment by aistvan** [comment]
@evelyn-ys Powershell

@jiasli The problem not only the usage of the `$` sign. My secret often contains single or double quotes and any other special character. I currently CAN'T set them with az+ps because the secret will not contains the quotes. I have to navigate to the portal to change it.

So, please do not concentrate to the `$`, please help me with the `'` or `"`.
Example:
`az keyvault secret set --vault-name MyKeyVault --name Test --value a+7%d"!k'/ky`

I tried backtick ``` ` ``` without any success.

**Comment by jiasli** [comment]
@aistvan, this is more of a problem of PowerShell, not Azure CLI. 

```
# PowerShell
> python -c "import sys; print(sys.argv[1])" 'a+7%d\"!k''/ky'
a+7%d"!k'/ky
```

For quotes, you are hitting a known issue of PowerShell (https://github.com/PowerShell/PowerShell/issues/1995) when calling native executables like Azure CLI which is actually a python application: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md

We really recommend using Bash with Azure CLI which doesn't suffer from this PowerShell issue:

```sh
# Bash
$ python3 -c "import sys; print(sys.argv[1])" $'a+7%d"!k\'/ky'
a+7%d"!k'/ky
```

See 

- https://www.baeldung.com/linux/single-quote-within-single-quoted-string
- https://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings

**Comment by ngcdev** [comment]
This might be helpful to some: In my case, I was storing some JSON data. Read it from a file and passed the variable. I tried even triple quotation marks, but the secret always got all of the quotation marks stripped, which made JSON invalid.
Fortunately in my case, I have a file with the text the way I want it. The `az keyvault secret set` has an option to read the value from a `--file` and that did the trick for me. No longer manipulating strings by Powershell (I wish it was that easy that I could just say "let's switch the entire company to bash because there's this issue with Powershell")

For OP, not sure if it's possible to send your string in question to a file. If it's possible, then you might be able to use `--file` parameter.
