### ISSUE TITLE
Warning for AHBForRHEL/AHBForSLES Azure VM Extension installation process

### ISSUE THREAD

**Issue by simratsatia** [Azure/azure-cli#21649]
**Is your feature request related to a problem? Please describe.**

Aim: We are introducing a two new Azure VM Extensions (Name: AHBForRHEL and AHBForSLES) as part of Azure Hybrid Benefit effort (Link to documentation: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-byos-linux). 

As part of the extension installation process that is done using the following command:
"az vm extension set -n AHBForRHEL --publisher Microsoft.Azure.AzureHybridBenefit --vm-name myVMName --resource-group myResourceGroup"
we want a warning to be displayed to the customer:
"Please ensure that you are provisioning AHBForRHEL extension on a Red Hat based operating system."

Similar warning to be displayed for AHBForSLES extension:
"Please ensure that you are provisioning AHBForSLES extension on a SLES based operating system."

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
Due to the Qingming Festival in China, our team aligned with Power Shell team and Cloud Shell team, the release time of this sprint is 04-06
If some customers want to experience those features in advance, we can provide them with the private CLI packages through [edge build](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md), they can install these private CLI packages by the end of March. Do you think this solution can meet your requirements?

**Comment by simratsatia** [comment]
Thanks for reaching out zhoxing. April 6 is doable for us.
