### ISSUE TITLE
No access ssh after the automatic update schedule on Azure

### ISSUE THREAD

**Issue by pci7** [Azure/azure-cli#21644]
**Describe the bug**
 Hi guys!

I have an automation account created by my client and have started scheduling automatic updates for a group of linux machines.

It was successful except in one machine, I wanted to verify the problem by connecting with azure-cli (via powershell on my local pc) with the command

`az ssh vm --ip 10.xxx.xxx.xxx`

But nothing happens, I noticed that I can no longer connect to any of the linux machines to which I started the scheduling except two of them.

<img width="399" alt="azurecli_ssh" src="https://user-images.githubusercontent.com/101636918/158361297-f6b8ffc9-c5b7-4ea8-ad97-b39d1db5d680.png">

I tried to reset ssh with the command `az vm user reset-ssh --resource-group linux_test --ip 10.xxx.xxx.xxx`, rebooted the machine linux and now it asks me for the password that I don't know which one it refers to since mine does not accept it .

Did the update do something to the ssh service? How can I be able to connect to this group of linux machines again?

Thank you and good day!

**To Reproduce**

**Expected behavior**

**Environment summary**
 

- Windows 10 
- azure-cli: 2.31.0 
- ssh: 1.0.0
- Python 3.8.2

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by pci7** [comment]
> route to CXP team

sorry, it's my first time. You can send me the link of CXP team, thanks

**Comment by SatishBoddu-MSFT** [comment]
Hello @pci7 Sorry for the delayed response!

Did you try logging from the Azure portal, try to reset the password?

**Comment by pci7** [comment]
> Hello @pci7 Sorry for the delayed response!
> 
> Did you try logging from the Azure portal, try to reset the password?

I usually use the command `az login` for authentication. If I reset the password only on that machine from the Azure portal, does it not compromise the authentication via az login?

**Comment by SatishBoddu-MSFT** [comment]
Hello @pci7 

Did you try this, from the portal?

[Troubleshoot SSH connections to an Azure Linux VM](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-ssh-connection#use-the-azure-portal)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/62923178/159794509-2fcf5444-42d0-45dd-8bfd-a580eef65d61.png">

**Comment by pci7** [comment]
Hi @SatishBoddu-MSFT ,
The key format with which I connect to linux machines on azure is `ecdsa-sha2-nistp256` (I saw on my pc in the path C:\Users\myuser\.ssh\known_hosts . On the portal, it asks the format starting with `ssh-rsa` .

If my colleague manages to log in to that machine, what can he changes to log me in? A copy and paste of my public key to the authorized_keys file?
How can I see the my key of my pc via powershell with azurecli? I tried with `az sshkey list --resource-group MyGroup` and I don't see anything although I'm able to connect in the other machines of the same resource group .

Thanks for your patience!

**Comment by pci7** [comment]
Hi @SatishBoddu-MSFT ,
through password reset, I created a new user and I was able to log in.
But how can I fix my account that I use through az login (used for authentication)? Do you have any commands that you can recommend?

Thanks!

**Comment by SatishBoddu-MSFT** [comment]
> Hi @SatishBoddu-MSFT Satish Boddu FTE , through password reset, I created a new user and I was able to log in. But how can I fix my account that I use through az login (used for authentication)? Do you have any commands that you can recommend?
> 
> Thanks!

Can you please add more info when you run the command 'az login'

To login to Azure Subscription tenant--> use 'Az Login'

To login to your Azure VM use the updated credentials which you have mentioned in your comment!

If you have a support option, then please file a support ticket for deeper investigation and help in this regard!
If you need one-time help with support ticket, then please send an email to us and we will help you further!

Please send an email to azcommunity@microsoft.com with the below details, so that we can work closely on this matter. 

**Thread URL:** Link to this thread.
**Your Azure Subscription ID**: 
**Email Subject** : Attn Satish Boddu 
Please let me know once you have done the same 



![image](https://user-images.githubusercontent.com/62923178/160673297-2de0331e-c057-4e2d-8d9b-24b63f5dc3e3.png)

Also read this similar issue:[ Error while login using Azure CLI](https://github.com/Azure/azure-cli/issues/16476)

**Comment by pci7** [comment]
Hi @SatishBoddu-MSFT ,
I have no problems authenticating via `az login` .
The problem I have when I try to connect via `az ssh vm`  to the machine because it asks me for the password of my user which I do not know which is since I authenticated with `az login`

<img width="653" alt="ssh" src="https://user-images.githubusercontent.com/101636918/160782083-38c38cd8-e424-497a-8c21-732302ec7fb0.png">

In the other machines I have not encountered this problem. 
I had to create a local test user to be able to log into the machine in question but I would like to use my account which I use for authentication. 
How can I solve it ? Do I need to make some changes to some files inside the linux machine?

Thanks for your patience!!

**Comment by SatishBoddu-MSFT** [comment]
Hello @pci7 No worries, please send an email to below group and we will help with the support ticket for further help!.

Please send an email to azcommunity@microsoft.com with the below details, so that we can work closely on this matter. 

**Thread URL:** Link to this thread.
**Your Azure Subscription ID**: 
**Email Subject** : Attn Satish Boddu 
Please let me know once you have done the same

**Comment by pci7** [comment]
Hi @SatishBoddu-MSFT ,
in this week I'll try to open a support ticket and forward to you!

Thank you so much!!

**Comment by SatishBoddu-MSFT** [comment]
Hello @pci7 thanks for understanding!

Please do share the support ticket reference number to our email and we will update this thread for further updates and outcomes!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and **we will reopen the issue**.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
