### ISSUE TITLE
Azure cli fails check when checking ACR connection for AKS cluster in same location

### ISSUE THREAD

**Issue by carvido1** [Azure/azure-cli#21650]
## Describe the bug

After AKS cluster creation, we attach a container registry which has a privatelink in the same VNET as the cluster. After this, we run the az command to check the connection between the AKS cluster and the container registry. What we get as output is that the cluster is running in different location to the privatelink, which is not true at all.

**Command Name**
`az aks check-acr`

**Errors:**

```
Merged "CURRENT-CONTEXT" as current context in /var/folders/2b/skmk9lmd057dw525xnyj_hr40000gn/T/tmprf_48m78
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ABCDEFGHI to authenticate.
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
Error attaching, falling back to logs: Internal error occurred: error attaching to container: container is in CONTAINER_EXITED state
[2022-03-15T17:38:22Z] Checking host name resolution (containerregistry.azurecr.io): SUCCEEDED
[2022-03-15T17:38:22Z] Canonical name for ACR (containerregistry.azurecr.io): containerregistry.privatelink.azurecr.io.
[2022-03-15T17:38:22Z] ACR location: privatelink
[2022-03-15T17:38:22Z] Loading azure.json file from /etc/kubernetes/azure.json
[2022-03-15T17:38:22Z] Checking ACR location matches cluster location: FAILED
[2022-03-15T17:38:22Z] ACR location 'privatelink' does not match your cluster location 'westeurope'. This may result in slow image pulls and extra cost.
[2022-03-15T17:38:22Z] Checking managed identity...
[2022-03-15T17:38:22Z] Cluster cloud name: AzurePublicCloud
[2022-03-15T17:38:22Z] Kubelet managed identity client ID: -
[2022-03-15T17:38:23Z] Validating managed identity existance: SUCCEEDED
[2022-03-15T17:38:23Z] Validating image pull permission: SUCCEEDED
[2022-03-15T17:38:23Z] 
Your cluster can pull images from containerregistry.azurecr.io!
```

## To Reproduce:

We have created an AKS cluster with managed identities and AAD in WESTEUROPE, where we also have a container registry running in this location.

```bash
az acr show -n containerregistry --query location -o tsv
westeurope
az aks show -g cluster-rg--name CURRENT-CLUSTER --query location -o tsv
westeurope
```

## Expected Behavior

The expected behaviour is a clean output with all the checks with a SUCCEEDED status, in this case the `Checking ACR location matches cluster location` as well.

## Environment Summary

```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@carvido1 Apologies for the late reply. Thanks for reaching out to us. Looking at the debug output, I see that the DNS resolution is happening just fine. Permissions are validated and it is correct. I also see that the command has succeeded as it says that -'Your cluster can pull images from containerregistry.azurecr.io!'.

```[2022-03-15T17:38:22Z] Kubelet managed identity client ID: -
[2022-03-15T17:38:23Z] Validating managed identity existance: SUCCEEDED
[2022-03-15T17:38:23Z] Validating image pull permission: SUCCEEDED
[2022-03-15T17:38:23Z] 
**Your cluster can pull images from containerregistry.azurecr.io!**
```
Are you saying that there is issue in pulling the image from ACR to your cluster ? though the command says its successful ? Awaiting your reply.

**Comment by carvido1** [comment]
Hello @navba-MSFT 
The cluster is pulling images from the ACR. The problem is related to the location of the resources. The ACR, the AKS cluster and the Privatlink to access the container registry are in westeurope. But the azure client tells it is not in the same location...

```bash
[2022-03-15T17:38:22Z] Checking ACR location matches cluster location: FAILED
[2022-03-15T17:38:22Z] ACR location 'privatelink' does not match your cluster location 'westeurope'. This may result in slow image pulls and extra cost.
```

BR

**Comment by navba-MSFT** [comment]
@carvido1 Thanks for getting back. I will look into this issue and get back once I have an update.

**Comment by navba-MSFT** [comment]
@carvido1 Thanks for your patience. After investigation, we indeed confirm that for acr and aks with private endpoint/link enabled, the warning message “ACR location 'privatelink' does not match your cluster location 'westeurope'. This may result in slow image pulls and extra cost.” is misleading.

The reason behind is that in the implementation of the check-acr command, we use the image [can-i-pull](https://github.com/Azure/aks-canipull) to check, and the location of acr is obtained by [parsing the cname](https://github.com/Azure/aks-canipull/blob/main/main.go#L60) corresponding to the fqdn of acr. For a normal acr fqdn, the result would be an address containing the corresponding region name (e.g., r0302eus-3.eastus.cloudapp.azure.com), but for the acr in this case, the parsing result is containerregistry.privatelink.azurecr.io. We have looked into the ask and the fix is pushed. No ETA for the release though. Sharing the details of the commit to address this issue:  https://github.com/Azure/aks-canipull/commit/625b7d5619f4079125e2c4210ac545dd9db0ce5f

**Comment by navba-MSFT** [comment]
@carvido1 I hope you had a chance to look at the above comment. Please let me know if you have any follow-up questions on this.

**Comment by navba-MSFT** [comment]
@carvido1 We will now proceed with closure of this github issue. The fix is been place. See the commit details in the above comment. No ETA for the release yet. Thanks again for sharing the feedback. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
