### ISSUE TITLE
Community gallery legal agreement acceptance during 'az vm'

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#21815]
**Resource Provider**

Azure Compute

**Description of Feature or Work Requested**

CELA team has an ask that when user creates a vm from community gallery, we should pop up an agreement acceptance line for user to accept/decline.

Design below:

1. If user uses 'az vm --image /CommunityGalleries/xxx/Images/xxx/Versions/xxx" or use 'az vmss --image /CommunityGalleries/xxx/Images/xxx/Versions/xxx"

follow up with question
"To create a VM from a community gallery image, you must accept the license agreement and privacy statement : https:/xxx. If you want to accept the legal terms by command, please use option '--accept-terms' for 'az vm', please now choose by Y/N:"

"To create a VMSS from a community gallery image, you must accept the license agreement and privacy statement : https:/xxx. If you want to accept the legal terms by command, please use option '--accept-terms' for 'az vmss', please now choose by Y/N:"

If user accepts, proceed to VM/VMSS creation. If user declines, do not create VM/VMSS.

2. If user uses 'az vm --image /CommunityGalleries/xxx/Images/xxx/Versions/xxx  --accept-terms' or  'az vmss --image /CommunityGalleries/xxx/Images/xxx/Versions/xxx  --accept-terms'
We think user has accepted the legal terms and we proceed to VM creation directly.

I already talked to Xing Zhou in CLI team about this.

3. One more change is to update description of eula when creating a community gallery, currently the description for 'eula' is 'Community gallery publisher eula', we intend to change it to 'community gallery license agreement and privacy statement'

**Minimum API Version Required**

2021-10-01

**Swagger Link**

None

**Target Date**

Start of April

**Comment by yonzhan** [comment]
Compute

**Comment by jepio** [comment]
Hi @kangsun-ctrl,
will there be a way to opt-out of this (by not supplying a privacy statement or license agreement)? I was looking forward to the community gallery feature, but this will break a lot of workflows in the same way that third-party images in marketplace do.

**Comment by kangsun-ctrl** [comment]
> place do.

Hi @jepio, community gallery is different from marketplace images. It is a gallery image and we only want this eula enforcement happens in gallery scope. This is a feature we are trying to do public preview, and also this is in cli extension.  I actually do not get the point "but this will break a lot of workflows in the same way that third-party images in marketplace do.", can you explain why it could happen?

**Comment by jepio** [comment]
Hi @kangsun-ctrl,

Will it be possible to mark a "community gallery" as "no EULA required", for example when the community gallery image is entirely based on open source software?

> I actually do not get the point "but this will break a lot of workflows in the same way that third-party images in marketplace do.", can you explain why it could happen?

First party marketplace images can be used by everyone with no additional setup required. Third party marketplace images require accepting an EULA and providing "plan information" with every VM create request. Forcing users to accept EULA causes friction and needs to be done for every subscription using a third party image (also every new image SKU). The "plan" information is problematic because most open source projects are are not prepared this. We are hoping to use community gallery instead of marketplace because of issues like this.

What I am saying is: forcing users to accept EULA for community gallery images brings the same kind of problems as third party marketplace images face.

**Comment by kangsun-ctrl** [comment]
> 

@jepio  the EULA requirement comes from CELA team, and we were asked to implement it like third party marketplace images. Actually this is not the proper thread to discuss this, please sent email to sigpmdev@microsoft.com for further discussion.

 So the community gallery image users, they just check out gallery publisher info to see whether it is a trust source. We are not relying on 'plan information' as marketplace images.
