### ISSUE TITLE
az resource delete not working as expected for Microsoft.EventHubs/namespaces

### ISSUE THREAD

**Issue by raribeiroMS** [Azure/azure-cli#21866]
## Describe the bug

**Command Name**
`az resource delete`

**Errors:**
```
(InvalidResourceType) The resource type 'locations' could not be found in the namespace 'Microsoft.EventHub' for api version '2021-11-01'. The supported api-versions are '2017-04-01,2018-01-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations' could not be found in the namespace 'Microsoft.EventHub' for api version '2021-11-01'. The supported api-versions are '2017-04-01,2018-01-01-preview'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a event hub namespace 
- Delete with the following command
- `az resource delete --ids "/subscriptions/xxxx/resourceGroups/RG/providers/Microsoft.EventHub/namespaces/rrtest1" --verbose --debug`

## Expected Behavior
No error should show up.
Delete is finished with success but an error occurs when getting the status of the operation.

## Environment Summary
```
Linux-5.4.0-1073-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

Adding full debug output for reference:
[deleteEHlog.txt](https://github.com/Azure/azure-cli/files/8379965/deleteEHlog.txt)

Adding a previous version explicitly works as a workaround.
- `az resource delete --ids "/subscriptions/xxxx/resourceGroups/RG/providers/Microsoft.EventHub/namespaces/rrtest1" --api-version "2018-01-01-preview" --verbose --debug`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@raribeiroMS Thanks for reaching out to us and sharing this feedback. I was able to repro this issue at my end. Could you please run the below command to delete the EH namespace ? 

>az resource delete --ids "/subscriptions/b83c1ed3-XXXX-XXXX-XXXX-XXXXXXXXX/resourceGroups/MyEHRG/providers/Microsoft.EventHub/namespaces/MyEH" 
--api-version "2021-06-01-preview" 

Awaiting your reply.

**Comment by raribeiroMS** [comment]
You are correct, it works like that. The thing is it should work without specifying a version, as it did.
If I use this command, with a list of multiple resources with different versions, I expect it to work without specifying a version.

**Comment by navba-MSFT** [comment]
@raribeiroMS I had reached out to the Product owners of EH and got an update from them. We could rule out that the error is not thrown via Event Hubs endpoint ( since it is not originating from the API which is responsible to delete the namespace).  

When you call `az resource delete –id `cmdlet on CLI, there is an async call that is done on the URI as mentioned here : [Namespaces - Delete - REST API (Azure Event Hubs) | Microsoft Docs.](https://docs.microsoft.com/en-us/rest/api/eventhub/stable/namespaces/delete). Once the delete call returns a 202, ARM offloads the work to the worker process which does the polling operation for the long running cmdlets like this one. You can find more details about the process here : [Status of asynchronous operations - Azure Resource Manager | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations).

Thus, the next set of API call( which is throwing the error) that you would observe, are targeted at URI: _https://management.azure.com/subscriptions/<subscription-id>/resourcegroups/<resource-group-name> /providers/Microsoft.EventHub/locations/eastus/operationStatus/<namespace-name>?api-version=2021-11-01&resourceType=Namespace_. This is not the same call as delete operation and is used by ARM to track the operation. 

I could notice that the namespace deletion is indeed successful (which is the API call that event hub RP would be serving).The error originates from the tracking call that ARM had been using. 

EH PG team has also confirmed that they would be adding updated api-version to the location ( tracking API call) which would fix this issue. No ETA for that yet. Until then you can use --api-version "2021-06-01-preview" parameter in the command. Hope this helps.

**Comment by navba-MSFT** [comment]
@raribeiroMS Hope you had chance to look at the above comment. Please let me know if you have any further questions on this.

**Comment by raribeiroMS** [comment]
I did thanks. No further questions. When can we expect an ETA for this issue.,

**Comment by navba-MSFT** [comment]
@raribeiroMS I have looped you offline with the Product Owners to keep the track of the release and tentative ETA for the fix. Until then you can use --api-version "2021-06-01-preview" parameter in the command. Please feel free to reopen this issue if you have any further queries.
