### ISSUE TITLE
Linux Version is too long. It cannot be more than 4000 characters

### ISSUE THREAD

**Issue by jwshive** [Azure/azure-cli#22022]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When attempting to create an Azure WebApp with Containers using Docker-Compose, our file is over 4000 characters when base64 encoded. As such, we can no longer run azure web app for containers.

**To Reproduce**
Create a docker-compose file with enough services to breach the 4000 character limit with base64 encoding.

**Expected behavior**
The backend storage should be able to have a more than 4000 character limit, or store the docker-compose file differently.

**Environment summary**
We are setting up the environment using terraform, but I know it's not a terraform limitation. It's not an azure cli issue either, but I can't find the right place to log this issue.;

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jwshive** [comment]
What is the recommended workaround for this?

**Comment by PramodValavala-MSFT** [comment]
@jwshive This limitation is [documented](https://docs.microsoft.com/en-us/azure/app-service/quickstart-multi-container#create-a-docker-compose-app) and since the feature is in preview, there is no near term plan to raise the limit.

You could however deploy multiple containers without the same limitation using [Azure Container Instances](https://docs.microsoft.com/en-in/azure/container-instances/tutorial-docker-compose).

Since there is no action here pertaining to Azure CLI, closing this issue.

**Comment by mlindgren** [comment]
This response is not helpful. It's been over a year and this issue still persists. It's not clear how Azure Container Instances allow one to work around this limitation; they don't appear to support Docker Compose at all. This might not be an Azure CLI bug, but it should be routed to the appropriate owner so it can be fixed.

**Comment by ffroliva** [comment]
I faced this issue today. I have a docker-compose with multiple services configured and I was not able to deploy the services because of this limitation. 

For example:

```bash
az webapp create --resource-group rmyResourceGroup --plan myAppServicePlan --name myAppName --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
```

It would be useful to be able to provide multiple `--multicontainer-config-file` in a similar way as docker compose work.

In docker compose if you provide multiple `docker-compose.yml` files  the second file acts as an overwrite.

```bash
docker compose -f compose.yml -f compose.overwrite.yml up -d
```

**Comment by greengumby** [comment]
Faced this limitation today...  Is there a workaround? 

For reference was using AzureWebAppContainer@1  to point to my docker-compose file
