### ISSUE TITLE
Unable to find IoT Hub:  {name} in current subscription with Service Principal login in az iot hub device-identity create

### ISSUE THREAD

**Issue by surenderssm** [Azure/azure-cli#22038]
**Describe the bug**

Running following command with logged in SPN, fails with error 
`Unable to find IoT Hub: ssmiothubdapr in current subscription <subid>`

    az iot hub device-identity create -n ssmiothubdapr -d certification-test-device

Please note this works as expected with user account login where a user has `owner` access on subscription.

This issue has been observer  with `az login --service-principal`, SPN in scope has IoT Hub Data Contributor

**To Reproduce**

- Create a SPN
- Create a IOT HUB
- Assign IoT Hub Data Contributor access role to SPN on the scope IoT hub.
- Login with SPN 
`az login --service-principal -u $AzureCertificationServicePrincipalClientId -p $AzureCertificationServicePrincipalClientSecret --tenant $AzureCertificationTenantId`
- Try to run commands to operate on IoT hub like creating a device or device simulate

      ` az iot hub device-identity create -n ${AzureIotHubName} -d ${IOT_HUB_TEST_DEVICE_NAME}`
      
      `az iot device simulate -n ${AzureIotHubName} -d ${IOT_HUB_TEST_DEVICE_NAME} --data 'testmessageForEventHubCertificationTest' --msg-count 2 --msg-interval 1 --protocol http --properties "iothub-userid=dapr-user-id;iothub-messageid=dapr-message-id"`

**Expected behavior**

Command should have been successful. 

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.1 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
application-insights 0.1.15
azure-iot 0.14.0
interactive 0.4.5

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by PramodValavala-MSFT** [comment]
@surenderssm The `IoT Hub Data Contributor` role provides access to data plane operations but it actually requires resource level permissions to manage it. You need to provide it permissions at the [resource scope](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-dev-guide-azure-ad-rbac#resource-scope) as documented, which is what you have done.

Based on your requirement, you could [create a custom role](https://docs.microsoft.com/en-us/azure/active-directory/roles/custom-create) for your SPN so that it may only access specific sub-resources to limit access.

Hope that clarifies the behavior. Since there is no change required here, closing this issue.
