### ISSUE TITLE
`az ssh vm` failure

### ISSUE THREAD

**Issue by siddharth234** [Azure/azure-cli#22084]
**Describe the bug**
`az ssh vm` command fails with the following error.

```
cli.azext_ssh.ssh_utils: __init__() got an unexpected keyword argument 'text'
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/home/bastion/.azure/cliextensions/ssh/azext_ssh/ssh_utils.py", line 65, in start_ssh_connection
    connection_status = subprocess.run(command, env=env, text=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/bastion/.azure/cliextensions/ssh/azext_ssh/custom.py", line 57, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/home/bastion/.azure/cliextensions/ssh/azext_ssh/custom.py", line 191, in _do_ssh_op
    op_call(op_info, delete_keys, delete_cert)
  File "/home/bastion/.azure/cliextensions/ssh/azext_ssh/ssh_utils.py", line 70, in start_ssh_connection
    const.RECOMMENDATION_SSH_CLIENT_NOT_FOUND)
azure.cli.core.azclierror.BadRequestError: Failed to run ssh command with error: __init__() got an unexpected keyword argument 'text'.

cli.azure.cli.core.azclierror: Failed to run ssh command with error: __init__() got an unexpected keyword argument 'text'.
az_command_data_logger: Failed to run ssh command with error: __init__() got an unexpected keyword argument 'text'.
Ensure OpenSSH is installed and the PATH Environment Variable is set correctly.
Alternatively, use --ssh-client-folder to provide OpenSSH folder path.
```

**To Reproduce**

**Expected behaviour**
The command should initiate the SSH connection. If it fails it should display a  helpful debug message. The message `Ensure OpenSSH is installed and the PATH Environment Variable is set correctly.` is misleading as `ssh` is accessible via the path and OpenSSH is updated to latest stable version;

**Environment summary**
OS: centos 7

```
azure-cli                         2.35.0

core                              2.35.0
telemetry                          1.0.6

Extensions:
ssh                                1.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/usr/bin/python3.6'
Extensions directory '/home/bastion/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Additional context**
The behaviour is not consistent as the same plugin works flawlessly on other systems.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@siddharth234 Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I was able to reproduce the same issue at my end. After I installed the OpenSSH, on my box and then created a PATH environment variable and used a new cmd session to run the same CLI command it worked fine. Could you please set the PATH env variable with the openssh installation path and then try running the same command and let me know if that helps. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@siddharth234 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by jeanbaptisteng** [comment]
Hi,

I got the same error message when executing **az ssh vm** and  **az ssh config** since the ssh update today morning (4 hours ago). 
I think we hit the bug. 

Here are the information that help your team to trace the issue

>az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ssh": "1.1.0"
  }
}

>az ssh config --file C:\Users\roqqett\.ssh\config --ip *
Failed to create ssh key file with error: [WinError 2] System cannot find the file。.
Ensure OpenSSH is installed and the PATH Environment Variable is set correctly.
Alternatively, use --ssh-client-folder to provide OpenSSH folder path.

>echo %PATH%
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.12.10983.0_x64__8wekyb3d8bbwe;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\System32\OpenSSH;C:\Users\roqqett\AppData\Local\Microsoft\WindowsApps;

> ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2


> python -V
Python 3.9.0

> ls c:\windows\system32\Openssh


Directory: C:\windows\system32\Openssh


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        04/06/2021  06:53 PM         307712 scp.exe
-a----        04/06/2021  06:53 PM         374272 sftp.exe
-a----        04/06/2021  06:53 PM         481280 ssh-add.exe
-a----        04/06/2021  06:53 PM         382976 ssh-agent.exe
-a----        04/06/2021  06:53 PM         662016 ssh-keygen.exe
-a----        04/06/2021  06:53 PM         557568 ssh-keyscan.exe
-a----        04/06/2021  06:53 PM         946176 ssh.exe


I did install OpenSSH-Client for a long time. Even I gave the  --ssh-client-folder parameter, the error is still the same. 

Please advice. If you want more information to trace the issue, please let me know.

Regards, 
Jean

**Comment by lbergeron01** [comment]
@navba-MSFT which path did you add to your ``PATH`` environment variable? We are facing the same issue, and ``C:\Windows\System32\OpenSSH`` is in our ``PATH``, and we are still receiving the error message.

**Comment by lbergeron01** [comment]
The new code of extension v1.1.0 is not able to translate `C:\Windows\System32\OpenSsh` to `c:\windows\sysnative\openssh`.

You can either :

- specify flag `--ssh-client-folder` with `c:\windows\sysnative\openssh`
- set `c:\windows\sysnative\openssh` to the `PATH` environment variable.

This is what fixed it for us.

**Comment by lbergeron01** [comment]
@navba-MSFT this issue is related to the same problem : https://github.com/Azure/azure-cli/issues/22144

**Comment by navba-MSFT** [comment]
@lbergeron01 Thanks for sharing an update and the workaround you followed. We have involved the Product Owners in the background and they are working on permanent fix. We will share an ETA on the fix release as soon as we have more details.

**Comment by navba-MSFT** [comment]
@lbergeron01 sharing the PR details for the fix https://github.com/Azure/azure-cli-extensions/pull/4728. This is under review phase now.

**Comment by siddharth234** [comment]
@vthiebaut10 / @navba-MSFT Thanks for the quick response. For me the issue was related to python version. With some basic digging around I was able to pin-point the cause. The `text` parameter in `subprocess.run` was introduced in python `3.7` and is absent in python `3.6` which is the default version for `centos7` distributions. IMO, A better `debug` or `error` message which points to the exact problem would be desirable.

**Comment by siddharth234** [comment]
@vthiebaut10 The issue has been resolved for me after updating the plugin to the latest version. Thanks. Closing the issue.
