### ISSUE TITLE
AAD Auth Support for Managed Disks

### ISSUE THREAD

**Issue by VikasMohandoss** [Azure/azure-cli#22134]
**Is your feature request related to a problem? Please describe.**
We are ready to start the CLI changes for supporting AAD Auth support for exporting and importing managed disks.

**Describe the solution you'd like.**
Currently for cli command "az disk create" and "az disk update",
add a new option "--data-access-auth-mode", and possible values are AzureActiveDirectory and None

**Additional context**
We are targeting public preview by the end of April and it will be good to have the CLI support by then.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@VikasMohandoss Since there are too many contents in the Swagger link in email, could you give us the specific PR link for the change, or give us the code link of Swagger code related to `--data-access-auth-mode`?

In addition, because the issue was created late, we will launch the release tomorrow, so it can't catch up with the release of the sprint. We plan to release it in the next sprint, is this time acceptable?

**Comment by chetmaddula** [comment]
This is the swagger link: https://github.com/Azure/azure-rest-api-specs/pull/17709

**Comment by VikasMohandoss** [comment]
Hi Xing,

When would the release land if it is a part of the next sprint? We are
looking to launch end of month ideally.

Thanks!
Vikas

When would the next

**Comment by zhoxing-ms** [comment]
@VikasMohandoss The release time of the next sprint is **05-24**. Before that, we can provide the private package of CLI to customers for installation through [edge build](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md), is this acceptable?

**Comment by VikasMohandoss** [comment]
Thanks Xing! That works for us.

Regards
Vikas
