### ISSUE TITLE
Disk Create/Update to PMK

### ISSUE THREAD

**Issue by VikasMohandoss** [Azure/azure-cli#22439]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
1. az disk update --name CrossSubCMKDisk4 --resource-group vimohand-XTCMK --encryption-type EncryptionAtRestWithPlatformKey
2. az disk create -g vimohand-XTCMK -n CrossSubCMKDisk2 --source CrossSubCMKDisk --encryption-type EncryptionAtRestWithPlatformKey

**Describe the bug**
1. Update encryption type to platform managed keys for a disk encrypted with cmk. I would expect this command to successfully complete. It looks like it is getting treated as cmk and sends a disk encryption set id and thus the error. 
2. Create new disk encrypted with PMK from a disk encrypted with CMK. This succeeds but the new disk is created with CMK.

**To Reproduce**
az feature registration create --namespace Microsoft.Compute --name AllowServerSideEncryptionSettingsChange
+ commands above

**Expected behavior**
1. Disk updated to PMK
2. Disk created with PMK

ETA needed - As soon as possible. Targeted ETA for feature public preview is 5/18

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@VikasMohandoss Thanks for creating this issue! 
However, because our work in this sprint has been fully arranged and the release for this sprint will be launched next week, so this requirement cannot catch up with the release of this sprint. Is it acceptable for us to release it in the next sprint **(07-05)**?
