### ISSUE TITLE
Unclear how to run az pipelines release create

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-cli#22597]
I am trying to use the `az pipelines release create` command. It is unclear what I need to pass to the `artifact-metadata-list` param.

I get the following error:
`The --artifact_meta_data_list argument should consistof space separated "alias=version_id" pairs. `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de490e1f-04b9-ee52-103c-1fa17f178290
* Version Independent ID: 18ee8e02-79d9-c0ac-1066-727ba97999ed
* Content: [az pipelines release](https://docs.microsoft.com/en-us/cli/azure/pipelines/release?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/pipelines/release.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/pipelines/release.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by rguptar** [comment]
@yonzhan Is this being looked into?

**Comment by yonzhan** [comment]
devops service team should take a look

**Comment by v-soujanya** [comment]
@rguptar we are trying to figure out the same and will share the updates asap.

**Comment by v-soujanya** [comment]
Hi @rguptar,
 az pipelines release create is based on [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-5.0#artifactmetadata) REST API.
 we found the similar issue link (mentioned below) which has the solution to try it out. Please check the issue link.[https://github.com/Azure/azure-devops-cli-extension/issues/872].
Thanks!

**Comment by rguptar** [comment]
@v-soujanya The solution presented there does not work for us. We see the following error:

Cannot retrieve the default version for artifact '<redacted>' because default version type is 'selectDuringReleaseCreationType'

**Comment by v-soujanya** [comment]
Hi @rguptar 
I am able to create a release successfully in my machine. Please find the image for reference.
![image](https://user-images.githubusercontent.com/101401302/172144902-6ca480bf-641c-44c4-b458-9360f581c463.png)



In our case, please go through the below information and try to set the artifacts version.

This check is introduced to prevent customers ending up choosing wrong version of artifact in their releases. When default version of an artifact (say A1) is specified as “Specify at the time of release creation” and a release gets auto-triggered due to another artifact (say A2) within the release definition, we had been choosing latest version of A1 for the release. However, this might not be what the user intended. So it will start failing saving of release definition if we find this combination among artifacts in the release definition.

In your case, since you have set an auto-trigger on one of your artifacts, you should change the default version type for the other two artifacts to pick the version that you intend for them to pick, when the release is auto-triggered.

**Comment by rguptar** [comment]
@v-soujanya 

Given the following URLs,
- build pipeline: https://dev.azure.com/ORG/PROJECT/_build?definitionId=BUILD_DEFINITION_ID
- specific build: https://dev.azure.com/ORG/PROJECT/_build/results?buildId=BUILD_ID&view=results
- release pipeline: https://dev.azure.com/ORG/PROJECT/_release?_a=releases&view=mine&definitionId=RELEASE_DEFINITION_ID
- edit release pipeline: https://dev.azure.com/ORG/PROJECT/_releaseDefinition?definitionId=RELEASE_DEFINITION_ID&_a=environments-editor-preview and then I click on the artifact to find the property called "Source alias" with value SOURCE_ALIAS

With the following command, I am able to create the release for some projects but not all.

`az pipelines release create --artifact-metadata-list "$SOURCE_ALIAS=$BUILD_ID" --definition-id=$RELEASE_DEFINITION_ID --organization https://dev.azure.com/$ORG --project $PROJECT`

When it fails, I get the following error:

`Page not found.  Operation returned a 404 status code.`

**Comment by v-soujanya** [comment]
Hi @rguptar,
For Some of the projects you are able to create a release then I think issue is not with cli command. Please guide me how to repro the issue in our machine for those projects in which you are facing issue.
Thanks!

**Comment by v-soujanya** [comment]
@rguptar Yes Please! Please create a support ticket.
