### ISSUE TITLE
az ad signed-in-user show in 2.37.0 does not work: ADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy.

### ISSUE THREAD

**Issue by ToruMakabe** [Azure/azure-cli#22629]
## Describe the bug

`az ad signed-in-user show` in 2.37.0 does not work in my env. The cause seems to be AD Conditional Access policy, but in the previous version (2.36.0), it works as expected without error.

[The migration doc](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=powershell) doesn't seem to have any known issues with this error.

This command is [used in in common packages](https://github.com/hashicorp/go-azure-helpers/blob/5a411a29fa0733ee422157d63aad09ba6c558038/authentication/auth_method_azure_cli_token.go#L260) for HashiCorp products such as Terraform, so has a big impact.

If it's a tenant configuration issue, I'll talk to the admin. However, it worked in the previous Azure CLI version, so could you please check it? Thanks!

**Command Name**
`az ad signed-in-user show`

**Errors:**
```
AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 0c31027b-05eb-4d4d-b600-1fec50530400
Correlation ID: 08abee16-3df6-480b-b128-2678be62ade3
Timestamp: 2022-05-26 03:04:09Z

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ad signed-in-user show -o {}`

## Environment Summary
```
Linux-5.15.0-33-generic-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
ssh 1.1.1
aks-preview 0.5.74

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by jiasli** [comment]
@ToruMakabe, Azure CLI 2.36.0 works before because it calls AD Graph. Now Azure CLI 2.37.0 calls Microsoft Graph, and **the error message comes from the underlying API which has Conditional Access policy configured**.

Could you try to run this command on a supported device (iOS, Android, Mac, and Windows flavors) which has Company Portal installed and is complaint?

I can successfully run it on my Microsoft-managed laptop:

```
> az ad signed-in-user show
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
  ...
  "userPrincipalName": "xxx@microsoft.com"
}
```
> If it's a tenant configuration issue, I'll talk to the admin.

Yes. This would be a reasonable approach to take.

**Comment by ToruMakabe** [comment]
@jiasli Thanks! Unfortunately, I'm running the Azure CLI on a Linux server... Logged in with --use-device-code option. There may be many users who have similar issues.

I'll talk to the tenant admin. Thanks!

**Comment by jiasli** [comment]
I think it is expected that Microsoft tenant `72f988bf-86f1-41af-91ab-2d7cd011db47` blocks Linux machines to call MS Graph API. You may consider using a service principal which is designed to be used on automated environments, like a server.

**Comment by ToruMakabe** [comment]
@jiasli As a result of additional verification, it was found that even Linux behaves differently depending on the login method.

* Can be performed without error in an environment where authentication can be redirected to the browser (like WSL2, Azure Cloud Shell via Windows Terminal)
* Error occurs in device flow authenticated environment. `az login --use-device-code`

Apart from conditional access settings, I think the difference in behavior should be clarified. Could you specify it in the document?

**Comment by jiasli** [comment]
I am able to reproduce on Linux VM:

```
$ az ad signed-in-user show
AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 8e0e3ae2-92a7-4dff-8070-ed99ff611b00
Correlation ID: c7fb3bec-5617-4b99-8d89-713bcbe3562e
Timestamp: 2022-05-26 10:47:01Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default
```

Then I ran

```
az login --scope https://graph.microsoft.com//.default
```

I got rejected by AAD in the browser:

![image](https://user-images.githubusercontent.com/4003950/170473494-1c771f88-6536-41df-a1ca-a903e2c3c31b.png)

> WSL2

WSL 2 works because it can utilize the [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

> Azure Cloud Shell via Windows Terminal

Per my understanding, Cloud Shell in Windows Terminal also uses [device code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code):

![image](https://user-images.githubusercontent.com/4003950/170473759-cacf88c5-6929-4c6b-92ce-6c918906ac76.png)

Are you able to use auth code for Cloud Shell in Windows Terminal?

> Apart from conditional access settings, I think the difference in behavior should be clarified. Could you specify it in the document?

This is more of a behavior determined by AAD tenant setting. Azure CLI as a client is not aware whether device code follow will trigger errors like this or not.

**Comment by janegilring** [comment]
I also ran into this issue from an Ubuntu 20.04-based dev-container in VS Code after upgrading Azure CLI from 2.36 to 2.37.

I have always used device codes to authenticate from device containers in order to run the authentication in the proper browser session:
`az login --use-device-code`

Authenticating using the scope suggested in the error message works fine for me:
`az login --scope https://graph.microsoft.com//.default --use-device-code`

Both `az ad signed-in-user show -o json` and `terraform plan` works fine now.

**Comment by janegilring** [comment]
@jiasli I just tried to reproduce where I performed the following in an existing devcontainer running Ubuntu 20.04:
- Ran `az ad signed-in-user show` successfully while using Azure CLI 2.36
- Updated devcontainer to use latest image version, latest updates via apt-get and Azure CLI 2.37
- Logged on to CLI using `az login --use-device-code`
- Ran `az ad signed-in-user` show without any errors

Hence, I can`t seem to re-produce now. Not sure what has changed besides updating OS image/patches.
I will report back should I be able to re-produce at a later time, but for now - all seems to be good.
