### ISSUE TITLE
Update VMSS + LB to use NATv2

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#22682]
**Related command**

az vmss

**Resource Provider**

Microsoft.compute

**Description of Feature or Work Requested**

With VMSS create there is currently client logic like:

- If VMSS Uniform, configure NAT Pool,
- If VMSS Flex, do not configure NAT pool

LB has recently launched an update to NAT rules that work for both VMSS Uniform and Flex. We would like to revise the VMSS create to always set up NAT rules via the new API:

https://azure.microsoft.com/en-in/blog/manage-port-forwarding-for-backend-pool-with-azure-load-balancer/

```
      {
        "name": "[concat(variables('lbName'), '/', 'natRule')]",
        "type": "Microsoft.Network/loadBalancers/inboundNatRules",
        "apiVersion": "2021-05-01",
	    "location":"[parameters('location')]",
	    "dependsOn":[
            "[concat('Microsoft.Network/loadBalancers/', variables('lbName'))]"
        ],
        "properties": {
      	  "frontendIPConfiguration": {
      	    "id": "[variables('frontendIPConfigID')]"
      	  },
      	  "protocol": "TCP",
      	  "frontendPortRangeStart": 50000,
      	  "frontendPortRangeEnd": 50100,
	  "backendPort": 3389,
      	  "idleTimeoutInMinutes": 4,
      	  "backendAddressPool": {
      	    "id": "[variables('backendaddressPoolID')]"
	    }
	  }

```

**Minimum API Version Required**

2022-03-01 compute
2021-05-01 network

**Swagger Link**

Normal CRP swagger
Normal NRP swagger

**Target Date**

7/30/2022

**Comment by zhoxing-ms** [comment]
For creating Uniform VMSS, if users do not specify the `--nat-pool-name`, CLI will take the load balancer name plus the suffix of `NatPool` as the default name of nat pool. code link: https://github.com/Azure/azure-cli/blob/74e96090f3a4283522f4b2f70e971abfc02a74ca/src/azure-cli/azure/cli/command_modules/vm/custom.py#L3114-L3118
@fitzgeraldsteele For Flex VMSS, do we need to keep the same logic?

**Comment by fitzgeraldsteele** [comment]
Nat Pool is not available for VMSS Flex (since they are just regular VMs).  Should fail deployment if Nat Pool and VMSS Flex are specified at the same time. That's why network team came up with Nat Rules V2, which works for VMSS Flex, Uniform and standard VMs.

The suggestion in this request was to replace Nat Pool with NAT Rules for both VMSS Uniform and Flex. Admittedly, I did not consider this case if the user specifies NAT pool.

Is there a way we can mat Nat Rules v2 the default, and allow customers to opt in to NAT Pool for VMSS Unform if they want?



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele Please note that since the current design has breaking change, so we can't directly implement it without full discussion. 
Please see if my suggestions above are acceptable and reply to me before Wednesday. Otherwise, if the problem is confirmed too late, this sprint will not have enough time for us to develop and test, so we will have to postpone it to the next sprint (**09-06**)
Thanks for your understanding~

**Comment by fitzgeraldsteele** [comment]
Thanks, @Xing ***@***.***>. For bringing this up and apologies for the delay.

@Load Balancer & NAT PM ***@***.***> - can I get some help on this issue with CLI? Was working with Irene to update AzCLI VMSS create to use NAT v2. Is this a breaking change? What should the experience be for customers to use NAT pool vs Natv2?



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
@anavinahar OK, thanks for your clarification. Since `Nat Rules V2` and `NAT Pool` have exactly the same functionality, and replacing `NAT Pool` with `Nat Rules V2` will not cause breaking change, so do we only need to support users to use `Nat Rules V2` to create Uniform and Flex VMSS? @anavinahar @fitzgeraldsteele

In other ways, may I ask do users still have the need or scenario to use `NAT Pool` to create Uniform VMSS? If not, we can consider only replacing `NAT Pool` with `Nat Rules V2` without adding additional parameters to support `NAT Pool` for Uniform VMSS? @fitzgeraldsteele

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele @anavinahar Since we will launch the release of this sprint next week, please answer these questions before tomorrow, otherwise we will not have enough time to develop and release this feature in this sprint, then we have to postpone it to the next sprint **(09-06)**

**Comment by anavinahar** [comment]
Yes both are the same functionality. We can replace with nat rules v2

For VMSS Uniform it is @fitzgeraldsteele's call.

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele) Because the modification of this feature is complex *(I found that the structure and level of these two resources in ARM template are inconsistent)*, and it affects many usages and tests. Since this sprint has less than five working days left,  we don't have enough time to develop and test it comprehensively in this sprint.
In order to avoid introducing unexpected risks and problems due to insufficient testing time, we plan to postpone it to the next sprint (**09-06**). Do you think it is acceptable?

**Comment by zhoxing-ms** [comment]
@mahipdeora @anavinahar @fitzgeraldsteele These two points have been implemented in draft PR. Do you have any suggestions on the third question?

In addition, can we hide the `--nat-pool-name` parameter in the help information. Users can continue to use it to avoid breaking change, but they will get the following prompt when using it:
![Screenshot 2022-09-19 162151](https://user-images.githubusercontent.com/16612065/190977181-22628418-b8c8-44c0-909b-7b05db9af91a.png)

Does this meet your expectations?
