### ISSUE TITLE
How to grant TrustFrameworkKeySet.Read.All to az cli

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-cli#22755]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
Forbidden({"error":{"code":"AADB2C","message":"The application does not have any of the required delegated permissions (TrustFrameworkKeySet.Read.All, TrustFrameworkKeySet.ReadWrite.All) to access the resource. ","innerError":{"correlationId":"e3062914-8c45-4904-a81d-7a8dc518323d","date":"2022-06-07T05:34:40","request-id":"fc0244a4-d8d7-4a3d-9f12-b81291542503","client-request-id":"fc0244a4-d8d7-4a3d-9f12-b81291542503"}}})

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- ` az rest --method get --url https://graph.microsoft.com/beta/trustFramework/keySets`

## Expected Behavior

az cli can retrieve the keyset

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
containerapp 0.2.0
spring-cloud 2.11.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

The following commands can be executed successfully.

`az rest --method get --url https://graph.microsoft.com/v1.0/applications`

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`https://graph.microsoft.com/beta/trustFramework/keySets` is [Get trustFrameworkKeySet](https://docs.microsoft.com/en-us/graph/api/trustframeworkkeyset-get?view=graph-rest-beta&tabs=http) API which requires **TrustFrameworkKeySet.Read.All**, **TrustFrameworkKeySet.ReadWrite.All** permissions. 

Azure CLI is a First Party App that doesn't have these delegated permissions.

![image](https://user-images.githubusercontent.com/4003950/172315620-b8698072-e2e1-42b7-883f-ba5952de6bb2.png)

There are 2 possible solutions:

1. (For us) Apply for **TrustFrameworkKeySet.Read.All**, **TrustFrameworkKeySet.ReadWrite.All** permissions in First Party App portal. You can't do that yourself.
2. Support custom client ID so that users can use Azure CLI with their own application.

**Comment by jiasli** [comment]
For above options, we did some internal discussion:

1. Applying for **TrustFrameworkKeySet.Read.All**, **TrustFrameworkKeySet.ReadWrite.All** permissions is certainly not an easy task for us. We need to work with security team, PM team, and AAD team to review the business justification and go through multiple reviews.

2. Supporting custom client ID will also take some time for development. For now, I think the best shot you can take is to 
   1. create your own AAD application
   2. grant it **TrustFrameworkKeySet.Read.All**, **TrustFrameworkKeySet.ReadWrite.All** permissions
   3. replace Azure CLI's client ID at `/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py` Line 22 with your own application ID: https://github.com/Azure/azure-cli/blob/1d973cceb38980181eeaa45934497d2148a3e7b2/src/azure-cli-core/azure/cli/core/auth/identity.py#L22

   but this is very hacky and we don't officially support it.

**Comment by m-moris** [comment]
Thanks for the discussion.

Indeed, I too think we should be cautious about granting for any authority to az cli tools.
I decided to use a workaround and have already written an automated script. This is a bit of a pain to manage the secret, though.
