### ISSUE TITLE
Azure Container Registry Trust Permissions 

### ISSUE THREAD

**Issue by vaishnavils97** [Azure/azure-cli#22856]
Hi Team, 
I would like to push signed images to a content trust-enabled ACR. I have implemented the content trust capability for signing the images digitally. But Are there any methods by that we could restrict unsigned images on ACR? Currently, we could push both images signed and unsigned images to ACR. Please provide a  mechanism where we can only push signed images to ACR.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vaishnavils97 Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@vaishnavils97 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by vaishnavils97** [comment]
Hi, @navba-MSFT Thanks for the update. I was looking for the ACR configurations. I have already implemented Docker trust. Thanks

**Comment by navba-MSFT** [comment]
@vaishnavils97 Thanks for getting back. As mentioned earlier, there is not such a feature to allow pushing signed images only to ACR. It is by design to allowing pushing both signed and unsigned images to ACR or any registries with content trust. With that, we will proceed with the closure of this GitHub thread. If you need any further assistance, please feel free to reopen this thread and we could be happy to help.
