### ISSUE TITLE
az mysql | Incorrect default value for --storage-size in autogenerated help

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#22926]
This bug is in response to MicrosoftDocs/azure-docs-cli issue [3113](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3113).  This fix needs to be routed to the `az mysql` service team as this module is [not owned](https://github.com/Azure/azure-cli/blob/dev/doc/modules_owned_by_cli_team.md) by the Azure CLI engineering team.

![image](https://user-images.githubusercontent.com/58762114/174334680-2783854c-db94-4fe4-a6c4-3a8c5f1f9dc6.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@dbradish-microsoft @rula88 This is the default set by the Azure CLI which is like the docs mentioned (since they are generated as mentioned in the other issue). Since you could always pass in your own value, I don't see why this has to be changed unless its an official decision to do so. Could you elaborate?
