### ISSUE TITLE
Installing arcdata extension on disconnected system fails

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli#22984]
**Command Name**
`az extension add`

**Errors:**
I am trying to install the arcdata on a disconnected system. All prerequisites are installed, however at every run, the error is shown that a dependent module is missing (the module will change at every run and it is installed, see attachment)

```
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

depending on the run, it will complain about different python modules missing, however, they are installed.

Output from first run: 

```
ERROR: Could not find a version that satisfies the requirement ndjson==0.3.1 (from arcdata) (from versions: none)
ERROR: No matching distribution found for ndjson==0.3.1
```

Output from second run: 

```
ERROR: Could not find a version that satisfies the requirement kubernetes==12.0.1 (from arcdata) (from versions: none)
ERROR: No matching distribution found for kubernetes==12.0.1
```

## To Reproduce:
Steps to reproduce the behavior. 

- Download the arcdata extension whl
- Download all required python modules (and their dependencies) and install them
- `az extension add --source arcdata-1.4.1-py2.py3-none-any.whl --debug`

## Expected Behavior

This should add the arcdata extension to the CLI.

## Environment Summary

```
Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-redhat-8.6-Ootpa, Red Hat Enterprise Linux 8.6 (Ootpa)
Python 3.6.8
Installer: RPM

azure-cli 2.37.0
```
## Additional Context

[az_extension_add_1.txt](https://github.com/Azure/azure-cli/files/8966614/az_extension_add_1.txt)
[az_extension_add_2.txt](https://github.com/Azure/azure-cli/files/8966616/az_extension_add_2.txt)
[pip list.txt](https://github.com/Azure/azure-cli/files/8966617/pip.list.txt)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@bweissman Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@bweissman Azure-cli's extensions internally use pip to download an ext's dependencies when running:

> az extension add --source XYX.whl

This is how all azure-cli exts work. I think we just need to bring them over too. Is it possible to:
1.	First get a machine that does have network access and install "az extension add --name arcdata"
2.	zip up the ext install from $USER/.azure/cliextensions/arcdata
3.	Move zip file over to disconnected machine and explode the zip file to the same location $USER/.azure/cliextensions
4.	az arcdata dc --help   (hopefully no errors)

Note: With this approach it might be best to use the same target OS flavor as the disconnected machine (e.g windows to windows or linux to linux, etc.. rather than say windows to linux)

Let me know if the above suggestion helps. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bweissman I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by bweissman** [comment]
@navba-MSFT Sorry for the delay, the customer is closed this week because of a holiday. I will get back to you asap but would assume, this should work when using an identical system (probably even same python, linux distro etc.).

Thank you!

**Comment by navba-MSFT** [comment]
@bweissman Sure. I shall wait for the updates from you.

**Comment by navba-MSFT** [comment]
@bweissman Could you please let me know if you had a chance to follow the above suggestions ? Please provide an update on this.

**Comment by bweissman** [comment]
Sorry, only got access today - this worked as expected! Thank you again!
