### ISSUE TITLE
az storage blob delete-batch do not remove non-empty folders 

### ISSUE THREAD

**Issue by Niviral** [Azure/azure-cli#23062]
## Describe the bug
`az storage blob delete-batch --auth-mode login --account-name storage_account -s container_name --dryrun` provided correct output with a list of paths to delete, however running the command without --dryrun return error as folders are non-empty. 
**Command Name**
`az storage blob delete-batch`

**Errors:**
```
This operation is not permitted on a non-empty directory. ErrorCode: DirectoryIsNotEmpty
<?xml version="1.0" encoding="utf-8"?><Error><Code>DirectoryIsNotEmpty</Code><Message>This operation is not permitted on a non-empty directory.
RequestId:fca372b8-a01e-0040-12b9-8bd758000000
Time:2022-06-29T13:11:34.0224646Z</Message></Error>

```

## To Reproduce:
- `az storage blob delete-batch --auth-mode login --account-name storage_account -s container_name`

## Expected Behavior
Remove everything from container leaving it empty 

## Environment Summary
```
Linux-5.11.0-1022-azure-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
datafactory 0.5.0
databricks 0.8.0
storage-preview 0.8.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
storage

**Comment by calvinhzy** [comment]
Sorry, I was not able to recreate this issue. Can you provide some info on files within the container and other info that might be useful? 
![image](https://user-images.githubusercontent.com/17182306/176610533-55e92ac4-2df3-4488-b094-1cf138d65f0e.png)

**Comment by Niviral** [comment]
This is part of the structure. 
![obraz](https://user-images.githubusercontent.com/33926911/176618148-8d425cee-04b8-4a87-b8cf-1f15e237cfb8.png)
Output is the same for ` --pattern '*' ` and without it. 
Yesterday every time I tried to run command I reacived error as in the report. However today command fail for some files/folders only 
![obraz](https://user-images.githubusercontent.com/33926911/176618840-b5c95bc2-c161-4b2b-9ea9-951292ce6060.png)
![obraz](https://user-images.githubusercontent.com/33926911/176619123-3dd86059-e254-48b4-8447-995a4f4c070d.png)

**Comment by Niviral** [comment]
Example from today Azure DevOps pipline, same structure as the previous screenshot but different blob container https://user-images.githubusercontent.com/33926911/176618148-8d425cee-04b8-4a87-b8cf-1f15e237cfb8.png

**Comment by calvinhzy** [comment]
Still trying to recreate this issue. Will update when found.

**Comment by calvinhzy** [comment]
Another client reached out to me with similar issue. It seems the top-level directories are becoming 0b blobs. I will try with more directories.

**Comment by victorwegeborn** [comment]
Any news on this?

**Comment by calvinhzy** [comment]
I have not been able to find any way to recreate this issue, bring in the service team to see if they have seen this error.

**Comment by marcgs** [comment]
I encountered the same problem with `az storage blob delete-batch` where non-empty directories in ADLS Gen2 weren't being removed with similar warnings `33 of 59 blobs not deleted due to "Failed Precondition"`, and the command execution being notably slow:

```
az storage blob delete-batch \
      --auth-mode login \
      --account-name <ACCOUNT_NAME> \
      --source <CONTAINER_NAME> \
      --pattern <PATH>
```

I found a workaround using the `az storage fs directory delete` command, which effectively resolved my problem:

```
az storage fs directory delete \
  --auth-mode login \
  --account-name <ACCOUNT_NAME> \
  --file-system <CONTAINER_NAME> \
  --name <PATH> \
  --yes
```

One limitation to note is the absence of wildcard support for directory patterns. However, this wasn't a significant concern in my use-case.

**Comment by jjolidon** [comment]
How is this still an issue?

In my situation, I had

- Hierarchical and NFSv3 enabled
- Files copied with azcopy cp --recursive=$true

This apparently creates blobs for the folders themselves instead of just having them as logical entities. Then:

- I could not remove them with azcopy rm
- I could not remove them with az storage blob delete
- I could not remove them with Azure Powershell (error 400 The requested operation is not supported on a directory)

**Comment by jjolidon** [comment]
Thank you very much @marcgs for your workaround! I have been struggling to delete those folders but your suggestion nailed it!
