### ISSUE TITLE
az ad app update --id $clientId --reply-urls $oauthCallbackURL returns unrecognized arguments: --reply-urls

### ISSUE THREAD

**Issue by dbiegunski** [Azure/azure-cli#23193]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az ad app update --id $clientId --reply-urls $oauthCallbackURL 

**Describe the bug**
unrecognized arguments: --reply-urls

Was this flag changed by another one ? What would be the new equivalent ?

Thank you so much

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is due to the Microsoft Graph migration.

- We documented the Microsoft Graph migration at https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration:
   > Split `--reply-urls` into `--web-redirect-uris` and `--public-client-redirect-uris`
- In Azure CLI 2.34.0~2.37.0, we print a warning for the Microsoft Graph migration: https://github.com/Azure/azure-cli/pull/21302
- We also pinned issue https://github.com/Azure/azure-cli/issues/22580

**Comment by farchide** [comment]
We have a managed service fabric deployment and we should set Reply-url for SPN to properly configure the Explorer. What would be the replacement for that?

**Comment by jiasli** [comment]
@farchide, that depends on your scenario to choose whether `--web-redirect-uris` or `--public-client-redirect-uris`. You may contact AAD support if you have questions about the service usage.

**Comment by savcic-milorad** [comment]
I have tried updating the web.redirectUris in two ways and both of them have failed when I pass multiple redirect URIs.

**Attempt 1**
```
az ad app update --id '<client-id>' --web-redirect-uris "https://hostname.com/callbackx https://hostname.com/callbacky"

One or more properties contains invalid values.
```

**Attempt 2**
This one fails regardless of number of redirectUris that are passed
```
az ad app update --id '<client-id>' --set "web.redirectUris=['https://hostname.com/callbackx', 'https://hostname.com/callbacky']"

Couldn't find 'web' in ''. Available options: []
```

<hr />

I have a scenario where my pipeline should update the app registration with an additional redirectUrl. 
I have managed to extract the current web.redirectUris with the following:

` existing_urls=$(az ad app show --id '<client-id>' --query "[web.redirectUris]" --output tsv)`

I would like to achieve something like this

```
existing_urls=$(az ad app show --id '<client-id>' --query "[web.redirectUris]" --output tsv)
az ad app update --id '<client-id>' --web-redirect-uris "$existing_urls https://hostname.com/newCallback"
```

**Comment by MoChilia** [comment]
Hi @savcic-milorad,
For **Attempt 1**, since `--web-redirect-uris` only supports **space-separated** values, the correct format should be
```
az ad app update --id '<client-id>' --web-redirect-uris "https://hostname.com/callbackx" "https://hostname.com/callbacky"
```
Spaces shouldn’t occur between double quotes, otherwise spaces will be parsed as literals. 

For **Attempt 2**, this is a [known issue](https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration#known-issues) that `--set` is only supported to use on the root level of a Graph object and using `--set` on sub-levels currently doesn't work.

For the same reason as Attempt 1, the command in the scenario you want to achieve should be
```
az ad app update --id '<client-id>' --web-redirect-uris $existing_urls "https://hostname.com/newCallback"
```
