### ISSUE TITLE
Offline VM image list

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-cli#23403]
**Related command**
az vm image list

**Describe the bug**
`az vm image list` returns an offline list of VM images across Linux and Windows as an alternative to `az vm image list --all` which is online. The offline list stored in the CLI source (see additional context). This file should be updated periodically to reflect the latest distro releases available on Azure. Some examples include:
- Ubuntu 18.04 -> 20.04
- Debian 10 -> 11
- Centos 7.5 -> 7.9

**To Reproduce**
 `az vm image list | jq -r .[].urn`

**Expected behavior**
The offline list should be periodically updated.

**Additional context**
The config is stored `src/azure-cli/azure/cli/command_modules/vm/_alias.py`.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@rguptar In fact, the offline configuration file used by CLI is [aliases.json](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/arm-compute/quickstart-templates/aliases.json
), and `src/azure-cli/azure/cli/command_modules/vm/_alias.py` is only a backup when the [aliases.json](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/arm-compute/quickstart-templates/aliases.json
) cannot access due to network problems.

Please note that because CLI team was unable to keep up with the latest information of these images, this file  [aliases.json](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/arm-compute/quickstart-templates/aliases.json
) was previously maintained by the service team. 
This is our workflow to update the image information in the [aliases.json](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/arm-compute/quickstart-templates/aliases.json
): if service team wants to update the image information in the configuration file, please submit a PR like https://github.com/Azure/azure-rest-api-specs/pull/16707, and then our team will assist in reviewing it.

**Comment by Sandido** [comment]
The CLI team [released ](https://github.com/Azure/azure-cli/pull/25930) the fix I put into the [source ](https://github.com/Azure/azure-rest-api-specs/pull/23261/files)of these images. 
The outdated image aliases are planned to be removed in the Oct 2023 breaking change release. 

And @rguptar has confirmed the issue is fixed. Thanks!
