### ISSUE TITLE
Command 'az network bastion rdp' does not work in admin powershell window

### ISSUE THREAD

**Issue by KevinKitts** [Azure/azure-cli#23515]
Running the following command in an admin powershell window results in the below error on multiple machines. It works just fine in a normal / non-admin window.
```
az network bastion rdp --subscription [MySubID] --target-resource-id [MyTargetResourceID] --resource-group [MyResourceGroup] --name [MyBastionName]
```

Error:
'Invalid connection file (C:\Windows\System32/conn.rdp) specified'

![image](https://user-images.githubusercontent.com/49320308/184251580-3db21f25-7b53-4511-b654-f191f2816c2d.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by dvicari-fedcap** [comment]
I just wanted to add that I was able to reproduce this issue.  The RDP connection fails with the above error when running Powershell as Admin.  The RDP connection is successful when running Powershell as a normal / non-admin session.

**Comment by PramodValavala-MSFT** [comment]
@KevinKitts The command creates the `conn.rdp` file in the current working directory which is `C:\Windows\System32` since you are running as admin. While I'm not sure why it fails to create the file (without actually failing 😕), you should be able to resolve this simply by changing into a different directory and running the command.

**Comment by dvicari-fedcap** [comment]
@PramodValavala-MSFT  I'm not the original commenter but I tested your work around and it does resolve the issue.  I changed the directory to just the C:/ and was able to run the command in an admin powershell window.  I appreciate your input!
