### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by Red1971** [Azure/azure-cli#23562]
Doc show workspace as optional..

az synapse managed-private-endpoints delete --pe-name
                                            [--ids]
                                            [--workspace-name]
                                            [--yes]

![image](https://user-images.githubusercontent.com/100938039/185209829-ebaf473b-9b16-4019-b324-77629a0468b8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f554620d-874d-97c5-fe88-2f8e6f529001
* Version Independent ID: ccc641f5-c2ac-7937-553d-f5190ad9d49c
* Content: [az synapse managed-private-endpoints](https://docs.microsoft.com/en-us/cli/azure/synapse/managed-private-endpoints?view=azure-cli-latest#az-synapse-managed-private-endpoints-create)
* Content Source: [latest/docs-ref-autogen/synapse/managed-private-endpoints.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/synapse/managed-private-endpoints.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Red1971 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The above PR has been filed and it is currently under review.

**Comment by navba-MSFT** [comment]
@Red1971 Thanks for reporting this issue. The above PR has been created to track this. Pasting the reply from the CLI Repo team as-is:

>We'll discuss if we should fix this issue inside CLI team.
Even if we need fix it, we should fix it in cli core, but not in specific modules as it's a shared design for all modules (i.e. if user provides --ids, like /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/synapse-cli000001/providers/Microsoft.Synapse/workspaces/clitest000003, then they don't need provide --workspace-name as --ids contains everything including --workspace-name.

You can track the progress in this PR https://github.com/Azure/azure-cli/pull/23620.
There is no ETA to fix this for now. We will update this thread once this issue is addressed.
