### ISSUE TITLE
Add priorityMixPolicy property to VMScaleSets 

### ISSUE THREAD

**Issue by aleclawlor** [Azure/azure-cli#23671]
This design review is based off of the issue created in the Powershell Design request: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1250. There, I have listed a more extensive list of use cases and requirements for being able to set the property. Since the property itself is a struct with 2 fields, it may be best to flatten that struct. I have also listed this on the Powershell design request linked above. 

Additionally, please note that the Swagger changes and SDK changes have not been merge to their respective feature branches, and the PowerShell features also have not been implemented by the PS team. 

**Resource Provider**
CRP (Microsoft.Compute)

**Description of Feature or Work Requester**
Add support in Azure CLI to be able to set priorityMixPolicy property of VMScaleSets in VMSS creations and updates

i.e.

az vmss create --name myScaleSet --resource-group myResourceGroup -priority-mix-policy
az vmss update --name myScaleSet --resource-group myResourceGroup -priority-mix-policy

**Minimum API Version Required**
2022-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/20079

**Target Date**
September, 2022

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@aleclawlor Please note that the code of this sprint will be frozen in a few days. Since the feature request is submitted late, it may not be able to catch up with the release in this sprint. 
Therefore, we plan to release it in the next sprint. The release time is **10-12**, may I ask does this date meet your expectations?

**Comment by aleclawlor** [comment]
> @aleclawlor Please note that the code of this sprint will be frozen in a few days. Since the feature request is submitted late, it may not be able to catch up with the release in this sprint. Therefore, we plan to release it in the next sprint. The release time is **10-12**, may I ask does this date meet your expectations?

Hi Zhoxing, we want to get the code in with this Sprint if at all possible. I'd be happy to make and test the changes myself, as it is not a major change to the code, but the feature itself will be very beneficial to have.

The only issue I see is that the Swagger and SDK changes are not yet published to their respective repositories. However, is it possible to run code generation locally, or manually make changes, so that I am still able to raise a PR to this repository? I know the CLI relies on the Python SDK, however, I also know the changes can be generated locally using autorest. This would let me bypass the whole "depends on" nature of the API/SDK/CLI/PS releases. 

To note, the Swagger release will not be merged to the master branch of the public API specs until 8/31, so if I could use local code generation, or just make manual changes, to have the code in without waiting on the whole release pipeline, that would be ideal.

**Comment by aleclawlor** [comment]
@zhoxing-ms ^^^

**Comment by zhoxing-ms** [comment]
@aleclawlor Yes, since CLI relies on Python SDK, if the Python SDK and Swagger are not ready, we cannot develop and release this feature in this sprint. 
However, we can first develop locally through a private Python SDK from Swagger PR, and then generate a private CLI package through edge build. We should be able to provide you with a private CLI package for testing this feature or for customers with urgent needs in September. Do you think this way is acceptable?

**Comment by zhoxing-ms** [comment]
@aleclawlor In addition, please note that the local build currently only supports generating private packages of pip. If you want to have the private packages with multiple installation methods *(such as MSI, docker..), you need to release the python SDK as soon as possible, so that we can generate the private package through the [edge build](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md) from PR CI pipeline.

**Comment by PARADISSEEKR** [comment]
`"priorityMixPolicy": {
          "baseRegularPriorityCount": 4,
          "regularPriorityPercentageAboveBase": 50
        }`

Hi @aleclawlor  when I test it returns error
`BadRequest: InvalidParameter, The value of parameter priorityMixPolicy is invalid.`

Do we need to register this feature to our test subscription to use it?
