### ISSUE TITLE
Add detail to docs about how `--only-show-errors` flag disables `az login --use-device-code` functionality

### ISSUE THREAD

**Issue by jidicula** [Azure/azure-cli#23773]
`az login` uses stderr for its prompts/info output. When using the `--use-device-code` flag together with the `--only-show-errors` flag, the prompt for user action (navigate to the auth URL and enter the code) is silenced with no stdout output, so the tool hangs quietly.

Or perhaps instead of documenting around this behaviour, it could be changed so the prompt for user action isn't written to stderr? When calling `az login --use-device-code` from Powershell <7.2, it requires some extra finagling to unset `ErrorActionPreference` from `'Stop'` if it's set, because the `'Stop'` behaviour in Powershell 7.1 and earlier halts execution if anything is written to stderr, not just for nonzero/nontruthy exits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login-optional-parameters)
* Content Source: [latest/docs-ref-autogen/reference-index.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/reference-index.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
In 2.40.0, `--only-show-errors` will no longer control the device code message:

- https://github.com/Azure/azure-cli/pull/23647

Device code message will now directly be printed to `stderr`, instead of through `WARNING`.

> it could be changed so the prompt for user action isn't written to stderr?

Unfortunately, `stderr` is the only place to print messages like this. Printing to `stdout` will be "catastrophic" as it breaks the output JSON. Any downstream program consuming the JSON output will break.
