### ISSUE TITLE
Issue with az vm create

### ISSUE THREAD

**Issue by cyberjoac** [Azure/azure-cli#2401]
Hi,
When I'm trying to create a VM with az vm create:
```
/home/ubuntu/bin/az vm create --name demo1\
>              --resource-group MyRG \
>              --image Canonical:UbuntuServer:16.04-LTS:latest \
>              --ssh-key-value ~/.ssh/mykey.pub \
>              --size Standard_DS3_v2 \
>              --admin-username ubuntu \
>              --nsg mysg\
>              --storage-sku Premium_LRS
```
I very often get the error message:
```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "AllocationFailed",
        "message": "Allocation failed. Please try reducing the VM size or number of VMs, retry later, or try deploying to a different Availability Set or different Azure location."
      }
    ]
  }
}  Correlation ID: 54480dba-4be8-42cb-b4d1-a88795ce8b57
```

I tried debugging the error messages from the Activity Log in the Azure portal but there is very little information of value.
Any recommendations to fix the issue ?

Please note I have largely enough quota

Thanks

**Comment by cyberjoac** [comment]
Actually it is also happening in the Azure Console

**Comment by derekbekoe** [comment]
@cyberjoac what location were you deploying to?

**Comment by cyberjoac** [comment]
West Europe

**Comment by tjprescott** [comment]
Hi @cyberjoac from the error message it seems you might try choosing a small SKU (DS1 or 2), but realistically, if it is intermittent and happens when you try to create through the portal, then your best bet would probably be to open a Support request.

On the portal if you open your resource group and scroll to the bottom of the blade you should see an option for a "New Support Request".  This sounds like a service issue, and that's the quickest way to get your issue to the service team.

**Comment by yugangw-msft** [comment]
Agreed with @tjprescott 
Closing as this is not a CLI issue

**Comment by cyberjoac** [comment]
Issue has been resolved.
Thanks for your help
