### ISSUE TITLE
`az acs create` fails on empty subscription due to QuotaExceeded

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2402]
When provisioning a Kubernetes cluster in westus in a newly created subscription (MSDN linked) via 
```
az acs create -g ${project_id} -n ${cluster_name} --orchestrator-type Kubernetes \
  --ssh-key-value ~/.ssh/kube_rsa.pub
```

The error is the following:
```json
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "QuotaExceeded",
        "message": "Provisioning of resource(s) for container service 'k8s-cluster' in resource group 'habitat-k8s' failed with 1 error(s): \\n Resource target: , code: QuotaExceeded, message: \\n Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 12.\r\n"
      }
    ]
  }
}
```

I would expect the default command to provision and not exceed the quota possibly with less resources (if possible). If not possible, we should provide guidance on using a different region or requesting a higher quota.

@brendandburns what would you want to happen in this situation?

**Comment by devigned** [comment]
@johanste have you thought about a cross-cutting way that we should handle quotas?

**Comment by brendandburns** [comment]
@devigned you can reduce the number of masters, or the size of the machines.

In this case, the default is 3 masters, 3 workers x 2 cores each == 12 cores.

Nonetheless we should probably catch this error and print a more intelligent suggestion about how to fix.

**Comment by devigned** [comment]
@brendandburns yep. That's what I ended up doing: https://github.com/devigned/azure-oss-devops-examples/blob/master/habitat-k8s/docker_scripts/deploy.sh.

**Comment by johanste** [comment]
@devigned, off the top of my head, no, I don't have any clever ideas as to how correctly handle quota errors (I'm not sure if the QuotaExceeded code is universal across all Azure Resource Providers).

**Comment by murphye** [comment]
This should be properly documented. I am a new Azure user and I was a bit flummoxed by this one due to the lack of docs. The initial error message told to file a Customer Support ticket to get my quota level raised; I was shocked.

I am on the Free Trial which maybe is giving me a limited quota. I finally ended up doing to get the k8s cluster to deploy:

az acs create --orchestrator-type kubernetes --resource-group sample --name sample-cluster --agent-vm-size Standard_DS1_v2 --agent-count 2

As a new Azure user, I had to research even what VM size to put. Please make it more clear for new Azure users how to deploy a basic k8s cluster given limited quota.

**Comment by devigned** [comment]
@JasonRShaver just wanted bring this one to your attention. It would be nice to have better feedback to empower customers to either increase quota via CLI or understand why the quota was exceeded during the failed operation. This is pretty much an echo of what @brendandburns said [above](https://github.com/Azure/azure-cli/issues/2402#issuecomment-284950484).

**Comment by murphye** [comment]
@devigned Thanks for reaching out. I am using edge CLI (due to recent defects) and running on Python 3 (as a workaround to a defect). To be honest, I have had an extremely rough experience so far using Azure CLI with the Container Services, such as this issue, and:

https://github.com/Azure/azure-cli/issues/4678
https://github.com/Azure/azure-cli/issues/4587
https://github.com/Azure/azure-cli/pull/4646

I ran into another quota issue today where I deleted my k8s cluster and tried to start a new one, but the fact that the cluster was deleted didn't register with the quota limit. I finally had to upgrade to Pay as You Go because I was blocked and couldn't do anything with Container Service. Now I am under the impression that I am being charged even though I had plenty of credits left on my Free Trial, which is unfortunate.

At the time I received the quota error, I did not have anything else running in Azure which could have been reducing my quota. I wish Azure just worked like the Google Cloud free trial where there are no quotas put in place (as far as I know) simply because I am on a trial account.  

I really hope you guys get things ironed out with the CLI and Container Service in Azure. It's promising but it seems like I have had Murphy's Law so far in using it. I even had to upgrade my Mac OS to High Sierra just to be able to build the edge CLI project due to Python dependency issues.

**Comment by mason-chase** [comment]
I have the same issue today and it appears the free trial is not enough to run a smallest possible of AKS just to test how it works, it is either a sales gimmick having your credit card in account or they really did not think this through after many years of service?
