### ISSUE TITLE
Az Cli 2.29 for Azure Stack Hub not available on RHEL8 repository

### ISSUE THREAD

**Issue by maxhunstar** [Azure/azure-cli#24033]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
sudo dnf list --showduplicates azure-cli

**Describe the bug**
Az CLI 2.29 is not available on microsoft's official repo for RHEL8. However. this is the latest version supported for AzureStack Hub, as mentionned by the documentation :

https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2206&tabs=ad-win

**To Reproduce**
sudo dnf list --showduplicates azure-cli

Earliest version is 2.35.0-1.el8

**Expected behavior**
Having a version available on the RHEL8 repo that works with AzureStack Hub.

**Environment summary**
Fresh install of RHEL8 + azure repo

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Az CLI 2.29.0 is no longer maintained. We don't backport old Azure CLI versions to RHEL 8 repo. You may try installing from `pip`: https://github.com/Azure/azure-cli/issues/20476#issuecomment-1007131837, but it is not guaranteed to work.

**Comment by domggarrity** [comment]
Hi @jiasli, is this issue resolved? If so, are we able to close it?

**Comment by TheOnlyWei** [comment]
Hi @maxhunstar, is this still an issue? Azure Stack Hub currently no longer supports using 2.29.0 due to a CVE vulnerability in versions previous to 2.40.0. Current recommendations are to use Azure CLI version 2.40.0 or higher. Note that there are some issues with some commands not being supported for Azure Stack Hub in the higher Azure CLI versions, and for those commands the work-arounds are documented here:

https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2306&tabs=ad-win#general-known-issues
