### ISSUE TITLE
az afd security-policy update fails with "(BadRequest) Domain 'customdomain' not attached to this AFDX profile."

### ISSUE THREAD

**Issue by Apholisha** [Azure/azure-cli#24116]
## Describe the bug

Cannot update the security policy associations with custom domains.
Used to work on 2.30.

If I pass just one ID - it works. Problem is when you try to pass multiple IDs.
I tested with passing it the ones that are already associated with it, just to make sure I'm not passing incorrect values and it fails with " Domain 'customdomain' not attached to this AFDX profile." which is not possible since that domain is already associated with the policy.

**Command Name**

` az afd security-policy update --profile-name "fd-core-fd-stg" --resource-group  "rg-core-fd-stg" --security-policy-name "default" --domains $policy.parameters.associations.domains.id `

**Errors:**
```
(BadRequest) Domain 'customdomain' not attached to this AFDX profile.
Code: BadRequest
Message: Domain 'customdomain' not attached to this AFDX profile.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run:
```
 $policy = az afd security-policy show --profile-name fd-core-fd-stg-01--resource-group  rg-core-fd-stg --security-policy-name default | ConvertFrom-Json   
 az afd security-policy update --profile-name "fd-core-fd-stg" --resource-group  "rg-core-fd-stg" --security-policy-name "default" --domains $policy.parameters.associations.domains.id 
```

## Expected Behavior
To update the list of custom domains accosted with the with the security policy. Even though it's the exact same two domains that are already there. 

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
account 0.2.1
azure-devops 0.18.0
front-door 1.0.16
managementpartner 0.1.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by t-bzhan** [comment]
Hi @Apholisha , as mentioned in this [issue](https://github.com/Azure/azure-cli/issues/23797#issuecomment-1238997338), Azure CLI is not designed to take a PowerShell array for space-separated values, it used to work by accident. You could use [splatting ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2)to pass list as multiple arguments like below:

> PS  > $policy = az afd security-policy show --profile-name fd101 --resource-group  bogroup --security-policy-name sp101 | ConvertFrom-Json
> PS > $policy.parameters.associations.domains.id
> /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/afdendpoints/ed101
> /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/customdomains/fd102-localdev-cdn-azure-cn

Instead of using:

> PS > az afd security-policy update --profile-name fd101 --resource-group  bogroup --security-policy-name sp101 --domains $policy.parameters.associations.domains.id --debug
> cli.knack.cli: Command arguments: ['afd', 'security-policy', 'update', '--profile-name', 'fd101', '--resource-group', 'bogroup', '--security-policy-name', 'sp101', '--domains', '/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/afdendpoints/ed101 /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/customdomains/fd102-localdev-cdn-azure-cn', '--debug']
> cli.knack.cli: __init__ debug log:
> Enable color in terminal.
> Enable VT mode.
> cli.knack.cli: Event: Cli.PreExecute []

That would cause the `'/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/afdendpoints/ed101 /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/customdomains/fd102-localdev-cdn-azure-cn'` be passed to CLI as a single value which will cause the BadRequest.

You could try below statement to using splatting to pass array as multiple arguments. Splatting seems not to work with nested property, you need to define a variable to refer to the domains first, the [split ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_split?view=powershell-7.2)function here is used to convert the string to array in case the `domains` property only contains one element, in that case, the type of `$policy.parameters.associations.domains.id` is string instead of array, if split is not used, splatting will pass every single character in the string as arguments to the CLI. There should be others approaches for that, I am not an expert for Powershell and get frustrated by its type system from time to time, :(, @jiasli might provide more input here.

> PS > $domains = $policy.parameters.associations.domains.id.split()
> PS > az afd security-policy update --profile-name fd101 --resource-group  bogroup --security-policy-name sp101 --domains @domains --debug
> cli.knack.cli: Command arguments: ['afd', 'security-policy', 'update', '--profile-name', 'fd101', '--resource-group', 'bogroup', '--security-policy-name', 'sp101', '--domains', '/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/afdendpoints/ed101', '/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/fd101/customdomains/fd102-localdev-cdn-azure-cn', '--debug']
> cli.knack.cli: __init__ debug log:
> Enable color in terminal.
> Enable VT mode.
