### ISSUE TITLE
az group lock list does not work without optional parameters

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#24452]
**Describe the bug**
`az group lock list` does not have required parameters.  The command should produce a list of all locks for all RGs in the subscription, correct?

**To Reproduce**
![image](https://user-images.githubusercontent.com/58762114/198290500-356d1e70-8d7d-4c96-b3ce-7d0e6078899e.png)

**Expected behavior**
Running the command without a parameter should result in all resource group locks being listed for the active subscription.  Instead, no locks are listed.  The only way to get locks to list is to supply `--resource-group` but this parameter shows as `optional`.

**Environment summary**
I am testing in Azure Cloud Shell

Here is the list of current `az group lock` issues: https://github.com/Azure/azure-cli/issues?q=is%3Aissue+is%3Aopen+group+lock+in%3Atitle%2Cbody

Here is a link to the autogen reference content: https://learn.microsoft.com/en-us/cli/azure/group/lock?view=azure-cli-latest#az-group-lock-list

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
In fact, there are three groups of commands corresponding to three levels of operations for lock
1. `az lock list`: List locks under subscription level
2. `az group lock list`: List locks under group level
3. `az resource lock list`: List locks for a specific resource

Therefore, `az group lock list` only queries the lock under a resource group, which is in line with expectations, but I will submit a PR to change the `--resource-group` parameter to required

**Comment by dbradish-microsoft** [comment]
@zhoxing-ms , so there is no way to get a list of all group-level locks in a subscription?  The customer has to loop through all their subscriptions passing one RG name at a time?

**Comment by zhoxing-ms** [comment]
@dbradish-microsoft At present, there is no way to directly query all group level locks in a subscription. 
Because the RSET [list-at-subscription-level](https://learn.microsoft.com/en-us/rest/api/resources/management-locks/list-at-subscription-level?tabs=HTTP) does not support filtering the lock level *(resource level or resource group level)*, and the returned data has no attribute to distinguish the lock level. Therefore, this feature needs to be supported by the REST service first
