### ISSUE TITLE
Delete a repository from Azure Container Registry

### ISSUE THREAD

**Issue by bddenhartog** [Azure/azure-cli#2445]
It is not currently possible to delete an image from a repository in Azure Container Registry, either through the UI or the CLI tool -- other than manually looking at all of the digests for all of the layers of a specific image, and deleting those through the blob filesystem (this is an unreasonable method of deletion, prone to human error).

The registry API supports deleting images (all image layers): https://docs.docker.com/registry/spec/api/#deleting-an-image

`az acr repository` should support deleting an image repository from a specific registry, perhaps in the format of:

```bash
az acr repository delete --name MyRegistry --repo someRepo/someImage
```

**Comment by yuwaMSFT2** [comment]
Currently ACR doesn't have the delete API enabled yet.

The current implementation of DELETE API may not be what customer expects. The blob delete only deletes the link to the real image blob (since the real blob can still be referenced by other images). Thus it won’t reduce the storage usage much, and it may leave some garbage around.

1)	Delete manifest (image). It will delete the specific version of the manifest of the image.
2)	Delete blob. It will delete the reference to the blob from the specified image, but not the blob data itself.

ACR was considering to turn it on, but didn't since not sure if it’s the desired behavior…Besides, we have been thinking of the alternative where we do garbage collection of unreferenced blob when delete. This is still under design…

Would like to hear more feedback before we act on it…

**Comment by SajayAntony** [comment]
Would recommend closing this and tracking the issue azure/acr#33 since this is a service implementation limitation and not a azure CLI issue.

**Comment by bddenhartog** [comment]
> Would recommend closing this and tracking the issue `Azure/acr#33` since this is a service implementation limitation and not a azure CLI issue.

Creating an issue for ACR is appreciated, but IMO that doesn't invalidate the need for the implementation in the CLI.

**Comment by SajayAntony** [comment]
@bddenhartog Yes that makes sense. Let's keep this open for the CLI side.

**Comment by prelution** [comment]
More feedback:  From my point of view the delete should be available for the user.  I know that the current implementation from the Docker API will only delete the reference and not the blob data (layers).  But it would be useful when the list of images becomes large and you would like to remove images tags that are no longer used or needed.

**Comment by bddenhartog** [comment]
quote @prelution:

> I know that the current implementation from the Docker API will only delete the reference and not the blob data

Yes, but Microsoft's implementation should account for this by using the reference to gather and delete all layers that aren't being used by other images. This can be accomplished by comparing the hashes of the layers from other images currently on the host.
