### ISSUE TITLE
Add an existing LB to an existing VMSS instance

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#24593]
**Related command**

This should fall under az vmss update command 

**Is your feature request related to a problem? Please describe.**

Currently, on portal users can attach an existing load balancer to an existing vmss instance. This feature doesn't exist for CLI

**Describe the solution you'd like**

A CLI command that allows users to attach an existing LB to an existing VMSS instance, similar to how the portal experience is. 

**Describe alternatives you've considered**

Portal, but the portal experience isn't scalable for customers

**Additional context**

The portal experience is shown in the screen shot attached. The CLI experience should accomplish the same task and reach parity with the portal experience. 

<img width="770" alt="Screenshot 2022-11-08 141406" src="https://user-images.githubusercontent.com/110857524/200687222-ba1a4915-faa0-46c1-8d5e-a3dd26da25b4.png">

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@mahipdeora Since this is an internal feature request rather than a bug and we need to know some necessary information *(such as REST service, Swagger link, command design...)* , could you please use this template [service_team_request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&template=Service_team_request.yaml) to help us create a feature request?
After you create the new feature request, we will evaluate it's priority and workload, and add it to our development plan for the subsequent sprints, thanks~

**Comment by zhoxing-ms** [comment]
@mahipdeora Could you please use the template  [service_team_request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&template=Service_team_request.yaml) to help us supplement the necessary information?

**Comment by mahipdeora** [comment]
Hi @zhoxing-ms, I found a workaround using CLI (will have a doc posted about this soon). I will do further testing tomorrow, and if it works, we can close this.

**Comment by mahipdeora** [comment]
Hi @zhoxing-ms, I just tested the CLI command I found, and it works. There is no need to create a new CLI command. I will create documentation on this use case. Thanks for your help.
