### ISSUE TITLE
az acr build failed with python setup.py bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by aksssdf** [Azure/azure-cli#24619]
【Issue】
az acr build command failed with below error：
Step 16/58 : RUN pip3 install greenlet==1.1.2 -i https://pypi.douban.com/simple/
 ---> Running in 5b0be7e2c12b
Looking in indexes: https://pypi.douban.com/simple/
Collecting greenlet==1.1.2
  Downloading https://pypi.doubanio.com/packages/0c/10/754e21b5bea89d0e73f99d60c83754df7cc64db74f47d98ab187669ce341/greenlet-1.1.2.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 13.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py): started
  Building wheel for greenlet (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [302 lines of output]
      running bdist_wheel
      running build
      running build_py
...【More output errors please refer to attachment "Dockerbuild.txt"】

【 az version】
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

【How to reproduce】
1. Please find dockerfile in attachment "Dockerfile"
2. Using command：az acr build --image sample/test000:v1  --registry testacr0  --file dockerfile . 
3. Issue will be reproduced

【Ask】
Please kindly help check why did build command fail？ And how to resolve it？Thanks

【Attachment】
[Attachment.zip](https://github.com/Azure/azure-cli/files/9986029/Attachment.zip)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@aksssdf Based on the logs, your build fails while trying to build the greenlet native module from source.

Looking up the first error leads to [this issue](https://github.com/python-greenlet/greenlet/issues/295) on the greenlet repo and based on the comment there, you might just have to update to a version of greenlet that works with the python version you are using.

Note that this is not really an Azure CLI issue and it would be best to check on the greenlet repo instead of more help regarding the package.

On a side note, you could just a different index in the `pip install -r requirements.txt` as shown [here](https://stackoverflow.com/a/57060441/10417839) instead of having so many lines to maintain in your dockerfile. 😄

**Comment by PramodValavala-MSFT** [comment]
@aksssdf Glad we could help! Closing.
