### ISSUE TITLE
create apim api from azure resource

### ISSUE THREAD

**Issue by tomabg** [Azure/azure-cli#24767]
Hi,

currently it is not possible via cli to "Create an API from azure resource" like Logic APP in API Management Service.

In Azure portal this functionality is available and would be great step for all IAC develpoers to have the same funstionality in azure cli.

..or maybe azure portal should provide a useable REST API so that this feature can be implemented in azurerm terraform provider.

for any questions please come back.
Thomas

**Comment by RakeshMohanMSFT** [comment]
@adrianhall FYI

**Comment by yonzhan** [comment]
route to CXP team

**Comment by adrianhall** [comment]
Thanks for the suggestion.  It is actually on our list, but I've done a +1 on the feature to record your interest.  

Since this is a feature request in the platform (and not specific to the CLI), and also not likely to be released for some time (due to competing priorities), I'll close this issue.  However, please note that we have recorded your interest.

#please-close
