### ISSUE TITLE
Add --no-wait parameter to operations related to Azure Relay Hybrid Connections and Azure Container Instances

### ISSUE THREAD

**Issue by tasdevani21** [Azure/azure-cli#24885]
**Related command**
- az container stop
- az relay hyco create 
- az relay hyco delete
- az relay hyco update
- az relay hyco authorization-rule create
- az relay hyco authorization-rule delete
- az relay hyco authorization-rule update

**Is your feature request related to a problem? Please describe.**
When using the Azure CLI commands to create, delete, and update Azure Relay hybrid connections along with stopping the created Azure Container Instances, the operations did not provide an option to add a `--no-wait` in order to not wait for the long running operations to finish which resulted in waiting for long periods of time for the commands to finish.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by tasdevani21** [comment]
> PramodValavala-MSFT

Thank you for sharing but if you could clarify a little more that would be helpful. 

`az container stop` does not have the --no-wait capability but `az container start`, `az container create`, `az container restart` does. I would like to get a better understanding on why some of the commands support the no wait capability. It seemed natural that if `az container start` supports it, then `az container stop` would also support it.

**Comment by PramodValavala-MSFT** [comment]
@tasdevani21 Apologies for the delay here! The commands here are essentially wrappers around the REST API and the `--no-wait` flag is applicable to endpoints that tend to return a `202 Accepted` response - which means that the actual work has been accepted and will be done asynchronously.

The `--no-wait` flag is simply a way to "fire and forget" these endpoints without any output (which is similar to what happens when running the command as I've shared in my last comment). The main request is still sent even with the flag (which is probably taking time depending on other circumstances) but the final response is not polled for.

The `az container stop` command returns once the request is successful but doesn't really wait for the container itself to stop, which is why the `--no-wait` parameter would not make a difference here in terms of execution time.
