### ISSUE TITLE
Update image builder template

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-cli#24893]
### Related command

az image builder update

### Resource Provider

Microsoft.VirtualMachineImages

### Description of Feature or Work Requested

PUT request on image template resource is still not yet supported.
But PATCH image template is now supported. There are no API changes in this request.
Two parts of data can be updated:
1. ARM resource tags (was previously supported on service side but not in az cli)
2. managed identity (new)
    - context: image builder only supports one user assigned identities
    - PATCH can now remove the identity by setting identity type to 'None'. However, this will essentially break the normal functionality.
    - PATCH can now add only one identity when the existing identity type is 'None'.
    - PATCH can swap existing identity for a new one.

### Minimum API Version Required

2022-02-14

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/imagebuilder/resource-manager/Microsoft.VirtualMachineImages/stable/2022-02-14/imagebuilder.json

### Request Example

1. PATCH request url: `https://management.azure.com/subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.VirtualMachineImages/imageTemplates/<image-template-name>?api-version=2022-02-14`
2. PATCH request body 1 (remove identity):
```{
    "identity": {
        "type": "None"
    }
}
```
3. PATCH request body 2 (add identity after previous one is removed):
```
{
    "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "<identity-resource-id>": {}
        }
    }
}
```
4. PATCH request body 3 (swap identities directly without removing first. note: the existing identity value is `null` while the new identity value is `{}`):
```
{
    "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "<existing-identity-resource-id>": null,
            "<new-identity-resource-id>": {}
        }
    }
}
```
5. PATCH request body 4 (setting tags): 
```
{
  "tags": {
    "key1": "value1",
    "key2": "value2"
  }
}
```
5. PATCH response: expect http code 202 (async) and empty response body for patching identities. expect http code 200 (sync) and updated resource json as response body for patching tags.

### Target Date

2023-01-03

### Additional context

since `az image builder update` was never supported, I cannot comment on the parameters required.

**Comment by yonzhan** [comment]
compute feature

**Comment by feiyushi** [comment]
When PUT update is supported, it may have different semantics so I'm not sure how the parameters will look like then.

**Comment by zhoxing-ms** [comment]
@feiyushi Since this feature request was submitted late, we plan to develop and release it in the next sprint. The release date is 2023-02-07, may I ask is this date can you meet your expectations?

**Comment by feiyushi** [comment]
> @feiyushi Since this feature request was submitted late, we plan to develop and release it in the next sprint. The release date is 2023-02-07, may I ask is this date can you meet your expectations?

Should be fine. Thanks! When it's being developed, could you help address my earlier comment regarding PATCH vs PUT potential parameters? thanks. I'd like to know what you plan to address it.

**Comment by yanzhudd** [comment]
Hello @feiyushi, could you please help to confirm these items?

- In order to support updating managed identity, we usually do not use `update` command. We have a unified specification. Please refer to the [managed_identity_command_guideline](https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md) for details. May I ask if the design in this guideline meets your expectations?

- The 4th request example described above:
> 4. PATCH request body 3 (swap identities directly without removing first. note: the existing identity value is null while the new identity value is {}):

we usually do not have `replace` operation in our CLI commands, instead of combining `assign` and `remove` commands to achieve the effect of `replace` operation. Thus, directly replacing existing identity with a new identity may not be supported in our side.

**Comment by feiyushi** [comment]
hi @yanzhudd ,
If we don't use `az image builder update` to update identity, then no need to add support to PATCH tags now.
I think we can go with the guidelines for identity. If I understand correctly, these 3 commands will be added:
1. `az image builder identity assign … --user-assigned <AzureResourceId1>` to assign identity. Corresponding to PATCH new identity.
2. `az image builder identity remove … --user-assigned` to remove identity. Corresponding to PATCH None type identity.
3. `az image builder identity show…` to GET identity.

Since we only support assigning one identity, the first two commands definitely will have its own limited use cases. But I think the command format looks fine. If you don't think so, please let me know. Thanks.

**Comment by yanzhudd** [comment]
Hi @feiyushi,
Great! But in order to keep consistent with implement of other commands related identity and be more convient to futher support assigning several identities, we recommend that CLI would not limit the input of users, i.e., following commands will be added:

1. **`az image builder identity assign … --user-assigned <AzureResourceId1> <AzureResourceId2>`** to assign identities. Corresponding to PATCH new identities.
2. `az image builder identity remove … --user-assigned` to **clear** identities. Corresponding to PATCH None type identity.
3. `az image builder identity show...`  to GET identity.
4.  **`az image builder identity remove … --user-assigned <AzureResourceId1> <AzureResourceId2>` to remove identities. Corresponding to PATCH identities setting userAssignedIdentities values of AzureResourceId1 and AzureResourceId2 to None. In fact, this scenario would not encountered currently, since only one identity is supported.** 

Could you please help to confirm this? If you have any comments, please let us know. Thanks.

**Comment by feiyushi** [comment]
that's fine. we restrict the usage of multiple identities at the service side.
