### ISSUE TITLE
'az functionapp plan create' fails when setting the '--is-linux' parameter to true

### ISSUE THREAD

**Issue by ilmarikyl** [Azure/azure-cli#24995]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az functionapp plan create

**Describe the bug**
I'm trying to create a new function app plan that has `EP1` as the value of the `--sku` parameter and with `--is-linux` se as `true`.  The plan creation runs without errors without the Linux parameter, but when it is present, I get:
 
 `Requested feature is not available in resource group <my_resource_group>. Please try using a different resource group or create a new one.`

I have found no explanation why hosting the app on Linux workers would not be possible for my resource group. I also tried spelling "true" different quotation marks and without them.
 
**To Reproduce**

Run the following command:
`az functionapp plan create --name $premiumPlanName --sku EP1 --resource-group $resourceGroup  --is-linux 'true'  --location 'West Europe'`

**Expected behavior**

A function app plan with Linux as host worker type and EP1 as service plan type should be created.

**Environment summary**

azure-cli 2.43.0
macOS 13.0.1 (22A400)
PowerShell 7.3.1

Installer: Homebrew

**Additional context**

**Comment by SaurabhSharma-MSFT** [comment]
@ilmarikyl We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ilmarikyl I am not able to reproduce this issue and the premium plan is getting created with `is-linux` parameter.
![image](https://user-images.githubusercontent.com/38112130/210038522-bdc775c2-196b-4f1a-8d5e-d3a15bb87c8d.png)
I believe you are creating a new App Service Plan within an existing same resource group that once already had a non-premiumV2 App Service Plan deployed in it, then this scale unit will not support PremiumV2 tier creation since it belongs to an older deployment. 
OR
You are creating both windows and linux apps together and it seems same OS's (Linux/Windows) App Service Plans (ASP) cannot be used in the same Resource Group with same Region.
Ref: 

- [The requested app service plan cannot be created in the current resource group because it is hosting Linux apps](https://stackoverflow.com/questions/54577245/the-requested-app-service-plan-cannot-be-created-in-the-current-resource-group-b)
- [[Premium] Pricing tier not allowed in existing resource group](https://github.com/Azure/Azure-Functions/issues/1194)
 If this is not the case, then I suggest you to please open a [Azure Support Ticket](https://aka.ms/azsupt) so that a Support engineer can check further on this issue.
