### ISSUE TITLE
Private AKS is not able to find the path of my local files to do a deployment through Helm

### ISSUE THREAD

**Issue by hvaandres** [Azure/azure-cli#25074]
Helm Version: 3
Kubernetes Version: 1.23.12

I'm currently trying to deploy my helm charts through my private aks cluster. However, I'm unable to do anything since it can't find the path of my local directory.

This is the command that I'm running:
```
az aks command invoke \
--resource-group aharo-aks-appgateway01 \
--name aharo-aks02 \
--command "helm install haro ./haro_files_helm_chart" 
```
This is the error message that I'm getting

```
command started at 2023-01-06 22:49:46+00:00, finished at 2023-01-06 22:49:46+00:00 with exitcode=1
Error: INSTALLATION FAILED: path "./haro_files_helm_chart" not found
```

Also, I will be getting the same issue if I use a file flag

```

az aks command invoke \
--resource-group aharo-aks-appgateway01 \
--name aharo-aks02 \
--command "helm install haro ./haro_files_helm_chart" 
--file deployment.yaml

```

OR

```
az aks command invoke \
  --resource-group aharo-aks-appgateway01  \
  --name  aharo-aks02 \
  --command "helm install aharo ./haro_files_helm_chart" \
  --file .

```

To prove that this type of command can work, I tried one from Microsoft Documentation. By running this command, I don't have any issues but I don't understand why my local files are not visible in the private AKS. 

```
az aks command invoke \   
--resource-group aharo-aks-appgateway01 \
--name aharo-aks02 \  
--command "helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update && helm install my-release bitnami/nginx"
```

What else can I do to find the path of my directory? Do you know if I could be missing any configuration on my cluster?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@hvaandres The `az aks command invoke` command spawns a container on AKS and runs the command there, which is why it doesn't find any local files.

You need to use the `--file` parameter to send local files and mount them on the spawned container in AKS for it to find them but looks like you already tried this.

Could you confirm you are running the `az` command from the right folder and run a simple command like `ls` to make sure the files got copied over correctly?
