### ISSUE TITLE
[Storage][Vm] bugs in paging

### ISSUE THREAD

**Issue by kairu-ms** [Azure/azure-cli#25088]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

https://github.com/Azure/azure-cli/blob/db539d485890e65da4ca5fbccd651526845535f5/src/azure-cli/azure/cli/command_modules/storage/track2_util.py#L82-L84

https://github.com/Azure/azure-cli/blob/38bd80bd72a7ee6bfee874f96e645c5c1ae5e7bc/src/azure-cli/azure/cli/command_modules/vm/custom.py#L5122-L5124

When `num_results` is not divisible by page number, the break will be ignored and it will get all items.

Should use `>=` here 
```
if num_results >= len(result): 
```

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
bugs in paging

**Comment by MoChilia** [comment]
Since `num_results` is a parameter just called as `result_per_page` in [azure-cli/blob.py/list_blobs](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/operations/blob.py#LL175-L186C66),  the situation 'num_results is not divisible by page number' will not happen in storage. The code in [azure-cli/track2_util.py L83](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/track2_util.py#LL82-L84C22) is good and does not need to be modified. For the code in [azure-cli/custom.py L5128](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/custom.py#LL5127-L5129C22), I raised the PR [#25400](https://github.com/Azure/azure-cli/pull/25400) which revised `==` to `<=` to meet the scenario mentioned in this issue.
