### ISSUE TITLE
I'm trying to create a AKS service, I received this error  **unrecognized arguments: --enable-rbac**, tried over debugging, but issue haven't resolved. Attached screenshots for your reference.

### ISSUE THREAD

**Issue by Varunr1995** [Azure/azure-cli#25275]
I'm trying to create a AKS service, I received this error  **unrecognized arguments: --enable-rbac**, tried over debugging, but issue haven't resolved. Attached screenshots for your reference.
![image](https://user-images.githubusercontent.com/59080666/214646654-ddacf8d5-bb9d-4488-83d0-cd6a762c86d7.jpg)
<img width="448" alt="Screenshot 2023-01-25 at 11 22 47 PM" src="https://user-images.githubusercontent.com/59080666/214646444-2f6a84f5-63bc-48c4-b061-f61997e28c5f.png">
<img width="986" alt="Screenshot 2023-01-25 at 11 22 16 PM" src="https://user-images.githubusercontent.com/59080666/214646454-89ec082f-e1fb-4f89-afbd-3ba096e2d6a8.png">

_Originally posted by @Varunr1995 in https://github.com/Azure/azure-cli/issues/16018#issuecomment-1404025467_

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Varunr1995 Thank you for reporting this, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@Varunr1995 can you please share `az version` details? We are able to use the flag without any issue see below screenshot
![image](https://user-images.githubusercontent.com/49954584/215421407-e93ece95-9a49-42d6-a8d2-3a16ad2d9510.png)

Also which document are you referring to, because the flag name is  **`--enable-azure-rbac`**. While using **`--enable-azure-rbac`** you should remember that we cannot specify "--enable-azure-rbac" if managed AAD is not enabled so you must use it like this `--enable-aad --enable-azure-rbac`
