### ISSUE TITLE
azure cli example for "Create a standard disk for uploading blobs" fails

### ISSUE THREAD

**Issue by demoray** [Azure/azure-cli#25308]
## Describe the bug

Running the example command directly as shown fails.  Note, this is the example command:

```
❯ az disk create --help | grep -B 1 -A 3 "Create a standard disk for uploading blobs"

    Create a standard disk for uploading blobs.
        az disk create -g MyResourceGroup -n MyDisk --size-gb 10 --upload-type Upload


❯
```

**Command Name**
`az disk create`

**Errors:**
```
(InvalidParameter) Required parameter 'creationData.uploadSizeBytes' is missing (null).
Code: InvalidParameter
Message: Required parameter 'creationData.uploadSizeBytes' is missing (null).
Target: creationData.uploadSizeBytes

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az disk create -g {} -n {} --size-gb {} --upload-type {}`

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1

Extensions:
azure-devops 0.26.0
resource-graph 2.1.0
application-insights 0.1.18

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by yanzhudd** [comment]
Hi @demoray, in `az disk create` command, `--upload-type Upload` should be used with `--upload-size-bytes` parameter instead of `--size-gb`, i.e., you could run this command to create a standard disk for uploading blobs:

`az disk create -g MyResourceGroup -n MyDisk --upload-size-bytes 20972032 --upload-type Upload`

We will fix the help message. Thanks.
