### ISSUE TITLE
Unable to extend the list of replyUrls / redirectUris with az app update

### ISSUE THREAD

**Issue by upr-kmd** [Azure/azure-cli#25413]
## Describe the bug
I was able to extend the replyUrls list in an application using az-cli up to version 2.36. 
Example:
az ad app update --id XXXXX --add replyUrls https://some/url/here

Now it's not possible using the new Graph API in az-cli 2.37 or later.
Example:
az ad app update --id XXXXX --add web.redirectUris "https://some/url/here"
Couldn't find 'web' in 'web'. Available options: []

**Command Name**
`az ad app update --id XXXXX --add web.redirectUris "https://some/url/here"`

**Errors:**
```
Couldn't find 'web' in 'web'. Available options: []
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create an app registration in Azure AD.
- Update the app's replyUrls / web.redirectUris using az-cli tool.

## Expected Behavior
az-cli should be able to extend the application property web.redirectUris using "az ad app update --add". Currently there is no way to do this in azure CLI v. 2.37 or later. There is a workaround possible to overwrite the whole list of URIs every time, but that's not feasible nor user-friendly when handling a long list or URIs.

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1 *
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
As explained in https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration#known-issues, `--add` currently doesn't work for Microsoft Graph related commands.

> There is a workaround possible to overwrite the whole list of URIs every time, but that's not feasible nor user-friendly when handling a long list or URIs.

Yes, this is currently the correct way to make changes on `redirectUris`. The reason is because Azure CLI tries to keep consistency with Microsoft Graph REST API. Since there is no "**Add Redirect URI**" API on the service side, Azure CLI can only update it with **Update application** API: https://learn.microsoft.com/en-us/graph/api/application-update

**Comment by upr-kmd** [comment]
@jiasli can you file a bug against Graph API to add the "Add Redirect URI" API?

**Comment by jiasli** [comment]
I believe this is the design of Graph API, instead of a bug.
