### ISSUE TITLE
cosmosdb sql database throughput migrate giving error message.

### ISSUE THREAD

**Issue by JainVirender** [Azure/azure-cli#25488]
Hi,

I am tring to validate throughput migration from manual to autoscale via cli but I am getting error message like "Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found
ActivityId: 3cf8bdc0-ae18-11ed-aefd-b63dd93e76bc, Microsoft.Azure.Documents.Common/2.14.0"
 
I am not able to find any gap in the command. I have validated that db already present so Entity found is not looking valid"
I had also tried similar commands on 3 month old cosmosdb but same result.

**Commands: - 3rd one failing**
az cosmosdb create --name cdb-virender --resource-group rg-bi --default-consistency-level Eventual --locations regionName="UK South" failoverPriority=0 isZoneRedundant=False --locations regionName="South Central US" failoverPriority=1 isZoneRedundant=False
az cosmosdb sql database create -a cdb-virender -g rg-bi -n cdb-virender-abc
**az cosmosdb sql database throughput migrate -a cdb-virender -g rg-bi -n cdb-virender-abc -t autoscale**

I added container manually and tried below command but same error:
az cosmosdb sql container throughput migrate -a cdb-virender -g rg-bi -d cdb-virender-abc -n container1 -t autoscale

If I remove/misspelle any aurgment/value then I am getting proper error for incorrect syntex.
but command with correct values throwing error "Entity with the specified id does not exist in the system"

Regards,
Virender

**Comment by yonzhan** [comment]
route to CXP team

**Comment by JainVirender** [comment]
I hope someone looking into the issue.

**Comment by SaurabhSharma-MSFT** [comment]
@JainVirender You are getting this error because you have not configured a database throughput while creating it.  Please note that if a database or container is initially created without throughput, it cannot then be changed to have throughput. You must create a new database or collection with throughput to later change it.
I have tested this with a new database using a CLI having `throughput` or `max-throughput` and later changed it to have a Manual throughput using `az cosmosdb sql database throughput migrate` and it worked as expected.
![image](https://user-images.githubusercontent.com/38112130/221049028-1eb0c567-3312-42a7-8a4a-93d99ed08a21.png)

Please let me know if you have any questions.  Thanks.

**Comment by JainVirender** [comment]
Thank You @SaurabhSharma-MSFT, Your solution seems working. 
I need to check it further by including it in main script which will take time because it depends on others. I will update on it till next weekend.

Thank you
Virender

**Comment by SaurabhSharma-MSFT** [comment]
@JainVirender Sure, thanks for the updates.
