### ISSUE TITLE
[Azure AD] Execute command on non-default tenant

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#2560]
Hey
I would like to use the ad commands, but with a different tenant. We have multiple tenants in our subscriptions, but it seems that this command only works with the default tenant. Using PowerShell I can do something like `Azure-LoginRmAccount -TenantId `. I tried to do something similar using `az login -t` but it failed: `No subscriptions found for this account`. When I tried to login without tenant it succeeds. Does this flow supported? 
Thanks,
Omer

**Comment by yugangw-msft** [comment]
@omerlh, not supported. 
`ad` commands in CLI was positioned as facility commands for RBAC scenarios which operate on resources under subscriptions.
I will keep this issue open. It is feasible for CLI to incorporate this new context if we have more user voices on this.

**Comment by omerlh** [comment]
Ok, good to  know. Will it help if I create a PR? I might have time for  that.

**Comment by yugangw-msft** [comment]
Contribution is welcome! Could you share your thoughts before you start the work?

**Comment by omerlh** [comment]
Sure. I hope I will have time to work on that in the future, and then I will share my thoughts...

**Comment by chaliy** [comment]
Hello, I want to double check if the issue is the same. So my scenario is:

1. I have additional tenant(I can see it and switch to it in Azure Portal)
2. I want `az ad group list` to list groups in AD in those tenant. There is no option to specify tenant, so I got nothing.
3. I tried `az login -t newtenantid`, however it seems that I still logged into default tenant
4. `az ad group list` returns the same results.

I this the same issue? Is there any workaround?

**Comment by yugangw-msft** [comment]
@chaliy, does your `newtenantid` has any subscriptions? I mean, if you run `az account list`, do you see any subscriptions associated with it? If not, which is likely, then there are no good workaround. 
I plan to fix this issue in the next few weeks.

**Comment by omerlh** [comment]
@yugangw-msft I am glad to hear that! looking forward to try it out...
