### ISSUE TITLE
az appservice plan update --name $PLAN_NAME --resource-group $RESOURCEGROUP --elastic-scale true An error has occurred.

### ISSUE THREAD

**Issue by JeroenMBooij** [Azure/azure-cli#25656]
When executing the command `az appservice plan update --name $PLAN_NAME --resource-group $RESOURCEGROUP --elastic-scale true`

you will receive an error saying `An error has occurred.`

I want to use Azure CLI to add custom autoscale to the app plan of my web app.

**Comment by gsethdev** [comment]
This may happen in case of app service Linux wherein this feature cannot be switched on. We have it documented here https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-app-service-automatic-scaling/bc-p/3015759#M561. It will help to execute the command with debug flag so that you get details of the error and share details. Also try to create a new resource group and app service plan with premium SKU and retry the command. If you still see the same error please rerun with debug flag and share details on this thread

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
Closing due to no response. Please re-open if this is still an issue.
