### ISSUE TITLE
az aks get-credential needs subscription access

### ISSUE THREAD

**Issue by uthsab** [Azure/azure-cli#25723]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

az aks get-credential does not work if we have access to the AKS resource / RG only and not the subscription. It shows this error. 

 az aks get-credentials --resource-group "rg" --name "aks" --subscription "xxx"
Subscription 'xxx' not recognized.
Subscription 'xxx' not found. Check the spelling and casing and try again.

Is this the expected behavior? If so, is it called out somewhere?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@uthsab Thanks for reaching out to us and reporting this issue. Please run the below command first to set the right subscription and then you can run the az aks command. That should help.

> az login
> az account set --subscription "XXXXXXX-XXXX-XXXX-XXXX-XXXXX"
> az aks get-credentials --name MyManagedCluster --resource-group MyResourceGroup

Hope this helps.

**Comment by uthsab** [comment]
Yes, it is working for me. 
I had tried that earlier but was seeing the same error. I was suspecting that is because I have access to the AKS cluster RG only. not the entire subscription. 

Apparently it was some cache issue. Az logout an az login again helped refresh the permissions. 

Thanks for the help.

**Comment by CaishenNefri** [comment]
Hi @navba-MSFT, @yonzhan 
it still happens. 

Reproduce:
- Create Service Principal
- Grant access inside Kubernetes RBAC - not in the Azure RBAC
- Login to via az cli `az login --service-principal --username "xxx" --password "xxx" --tenant "xxx" --allow-no-subscriptions`
- `az aks get-credentials --resource-group XXX --name XXX --subscription XXX`
- Error: `Subscription 'XXX not recognized.
Subscription 'XXX' not found. Check the spelling and casing and try again.`

I guess it happens because service principal doesn't have access to any subscription inside Azure.
