### ISSUE TITLE
Improve az iot edge deployment create help text

### ISSUE THREAD

**Issue by delarooster** [Azure/azure-cli#25752]
After extensive work attempting to utilize the `az iot edge deployment create` command recommend the following:
1. Include specifications for `deployment-id` limitations, like in Azure Portal. (i.e. Lowercase and the following special characters are allowed: [-+%_*!']).  This was quite difficult to debug as the cli error code is useless. 
`ERROR: {'Message': 'ErrorCode:ArgumentInvalid;BadRequest', 'ExceptionMessage': 'Tracking ID:75a881e527b64b00abb4f282a12ce560-G:0-TimeStamp:03/10/2023 12:36:02'}`
a. Further adding the cli error response messaging to include the above messaging would help future debugging.
2. The recommended format for custom-labels is straight up wrong.  From the documentation:
![image](https://user-images.githubusercontent.com/24897179/224394377-146519cb-db17-471f-a4a8-761ebbcfd761.png)
but what actually works:
![image](https://user-images.githubusercontent.com/24897179/224394409-70e92626-1f9b-4f8a-8b60-5c862897bdd3.png)
Creating "space separated" creates one tag and dumps all the others into the value section of said key, e.g. 
![image](https://user-images.githubusercontent.com/24897179/224394726-2fade583-893e-40b9-a299-b19c5e925f7d.png)
Instead of the desired:
![image](https://user-images.githubusercontent.com/24897179/224394856-dedd2689-cf39-42d7-9021-37755e502ac2.png)

3. Include an example of the format required by target-condition.  Only help I discovered was [in this article](https://www.koskila.net/azure-iot-edge-gotchas/) and an example of intended use is highly helpful if this parameter is expected to be utilized. 
![image](https://user-images.githubusercontent.com/24897179/224395303-93603fbf-2dfc-4c6a-bb3e-cd60b0c59766.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f635760-7886-3abb-0491-fcc728b4a90d
* Version Independent ID: eeb3b44f-acc7-6f7e-7604-392d16722a26
* Content: [az iot edge deployment](https://learn.microsoft.com/en-us/cli/azure/iot/edge/deployment?view=azure-cli-latest#az-iot-edge-deployment-create)
* Content Source: [latest/docs-ref-autogen/iot/edge/deployment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/edge/deployment.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Elsie4ever** [comment]
Hi @delarooster, would you mind sharing the whole command you ran? there is an example of using the command if you run `az iot edge deployment create --help`
![image](https://user-images.githubusercontent.com/22055990/225450438-ed842cac-82fb-45ac-9a1b-315c22903a00.png)
Please make sure you are using the parameter in format of key-value pair(`--custom-labels key0="value0" key1="value1"`) instead of an entire string(``--custom-labels "key0=value0 key1=value1"``), thanks!

**Comment by delarooster** [comment]
Thanks @Elsie4ever about the recommendation, that's the final understanding I came to after iterating over many different inputs.  Appreciate the update on that second issue.

Any updates about the first or third point?  Would be entirely helpful to update documentation so someone else doesn't tread down the same path I had to traverse.

**Comment by vilit1** [comment]
Regarding the first input, we will add the parameter help text about the specific naming for the deployment id.

Regarding the third input, the examples for target condition are already there
<img width="423" alt="image" src="https://user-images.githubusercontent.com/73560279/227067754-c035a0ad-a90a-416c-bcd1-c838026c6ea3.png">

However, since it is hard to see, we will update the help text for the parameter too.

**Comment by digimaun** [comment]
We've improved the command [documentation](https://learn.microsoft.com/en-us/cli/azure/iot/edge/deployment?view=azure-cli-latest#az-iot-edge-deployment-create) taking into account the points you listed in the issue. Thank you for the feedback.
