### ISSUE TITLE
az extension add frozen

### ISSUE THREAD

**Issue by vb3** [Azure/azure-cli#26076]
## Describe the bug
install hangs at " - Installing .." and doesnt make progress for hours.
I've tried restarting my computer, and reinstalling az cli

I'm able to install other extensions (e.g. "account") this seems specific to "az extension add --name azure-devops"

**Command Name**
`az extension add --name azure-devops`

**Errors:**
did not receive error message, just hangs at installing.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- fresh installation of "Microsoft.AzureCLI" from winget.
- `az extension add --name azure-devops`

## Expected Behavior
to install the extension

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nextstate** [comment]
Why was this issue closed? There is no resolution here for the `az extension add --name ...` command when there is an `index-url` in effect that requires `artifacts-keyring` installed to succeed.

A workaround is to open Task Manager to extract the command-line that is hung, and type that into the terminal with the modification of adding `--isolated` to the `pip install` command.

One solution would be to add a command-line parameter to `az extension add` so that the extension could be installed isolated. Such as, `az extension add --name azure-devops --isolated`.

Another solution would be to provide a command-line paramter to `az` to install `artifacts-keyring` so that future commands do not hang. For example: `az install-artifacts-keyring`.

**Comment by TheOnlyWei** [comment]
I just ran into this issue, @vb3 is there a fix? Otherwise, I will create a new issue.

**Comment by MsMatias** [comment]
> I just ran into this issue, [@vb3](https://github.com/vb3) is there a fix? Otherwise, I will create a new issue.

I have a reference to a private artifact registry in my ~/.config/pip/pip.conf and as  @CoromT and @nextstate mentioned, I've just commented the two lines and everything went well.
