### ISSUE TITLE
az lock create: "Readonly attribute name will be ignored in class ..."

### ISSUE THREAD

**Issue by pubrich-ingka** [Azure/azure-cli#26155]
## New warning received after upgrading from v2.46.0 to v2.47.0

**Command Name**
`az lock create`

**Description**
We were using the `az lock create` command with the commands listed in the "To Reproduce" section for a longer time.
Now we have updated from v2.46.0 to v.2.47.0 and are encountering the warning listed below.

**Errors:**
```
Readonly attribute name will be ignored in class <class 'azure.mgmt.resource.locks.v2016_09_01.models._models_py3.ManagementLockObject'>
```

## To Reproduce:

- `az lock create --name {} --resource-group {} --lock-type {} --resource-type {} --resource {}`

## Expected Behavior

Since the parameters seem to be valid based on the help section of the command, no such warning should be printed.
Or it should be rephrased to clearly communicate what is wrong.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0

Extensions:
azure-devops 0.26.0
log-analytics 0.2.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by pubrich-ingka** [comment]
@yonzhan @zhoxing-ms Did you perhaps have a chance to look into this?

**Comment by channeladam** [comment]
Encountered the same issue - causing my deployment pipeline to fail due to this unexpected stderr message

**Comment by bebound** [comment]
I think this behavior is by design.
In `ManagementLockObject`, it has `{"readonly": True}` in `_validation`.
https://github.com/Azure/azure-sdk-for-python/blob/d31433d347fbd2e0f4d45694818b1225812e5aa4/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/locks/v2016_09_01/models/_models_py3.py#L75-L80
It is a subclass of `_serialization.Model`. this warning is print during `__init__`.
https://github.com/Azure/azure-sdk-for-python/blob/ea94f14c4e6175c068e9e5a90335595b24ae0d71/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/locks/_serialization.py#L285-L286

**Comment by zhoxing-ms** [comment]
In fact, this issue was caused by improper use of the `ManagementLockObject` model in CLI legacy code. I submitted a PR #26347 to fix it

**Comment by DigiBanks99** [comment]
@zhoxing-ms 

> In fact, this issue was caused by improper use of the `ManagementLockObject` model in CLI legacy code. I submitted a PR #26347 to fix it

What is the planned release for this fix?

**Comment by zhoxing-ms** [comment]
> What is the planned release for this fix?

@DigiBanks99 It will be released on **05-23**
