### ISSUE TITLE
Transparently handle SAS key when working with blobs

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-cli#2620]
Having to manage multiple authentication levels with the CLI seems a little excessive.  Why not just translate the current user's credentials for them into whatever access is required to perform the operation?

**Comment by tjprescott** [comment]
This isn't always possible. For example, you could use the CLI storage (data plane) commands without having an Azure subscription if you had a valid SAS token.

What I typically do when I want to interact with storage specifically is store the connection string in the AZURE_STORAGE_CONNECTION_STRING environment variable. There is a mechanism whereby, if you have permission to retrieve the account keys, you can specify just the storage account name and the CLI will query the keys for you. However, I don't recommend doing this. It's easier just to issue the two calls to retrieve and then set your connection string.

**Comment by williexu** [comment]
@tjprescott I believe you are referencing the [OAuth](https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview#included-features) feature that is included with the storage-preview extension, which will use the user's credentials to authenticate given the `--auth-mode` parameter. 
Do know that this is different from using a SAS key and will require the additional granting of the right permissions for the user: [Manage access rights with RBAC](https://docs.microsoft.com/en-us/rest/api/storageservices/authenticate-with-azure-active-directory#manage-access-rights-with-rbac).

@atrauzzi SAS keys are used to give other users, who wouldn't otherwise have access, fine-tuned permissions. If you want to give someone full-blown control, give them the account key instead(make sure you really want them to have full write permissions). If this is for your own personal use and you have the privileges, as travis mentioned, you do not need to specify any further authentication arguments; we will query the account corresponding to the name specified, grab a account key, and use that in the operation.

**Comment by atrauzzi** [comment]
That's not my point.

My point is if you're signed in as a user already and want to run a command, the command should detect that I'm running with an authenticated session and do what it must to make the command work.

I don't care if it's a rubber duck race or an SAS key that goes on in the background.  I'm already authenticated, extra credentials are redundant at that point.

**Comment by williexu** [comment]
@atrauzzi referencing the end of my last comment:
"If this is for your own personal use and you have the privileges, as travis mentioned, you do not need to specify any further authentication arguments; we will query the account corresponding to the name specified, grab a account key, and use that in the operation."

i.e. you can run the following successfully:
```
az storage blob upload -n <name> -f <file> -c <container> --account-name <storage account>
```
No need for `--account-key`, `--sas-token`, etc.

**Comment by atrauzzi** [comment]
Granted, I made this ticket over a year ago, but that didn't seem to be the case.  Maybe things have changed since then...

**Comment by williexu** [comment]
@atrauzzi please try using the latest version of the CLI. I promise that this is the current behavior.
