### ISSUE TITLE
Sample command not works in Powershell

### ISSUE THREAD

**Issue by Bobilala** [Azure/azure-cli#26244]
when I use **az appconfig feature filter add -n appconfig --feature feature --filter-name Microsoft.TimeWindow --filter-parameters "Start"=\"2023-04-16T16:00:00Z\" "End"=\"2023-04-25T16:00:00Z\"**, it works perfectly in Bash, but in Powershell it will not work.

Changed escape "\" to "`" still failed. Could you help on this?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SwathiDhanwada-MSFT** [comment]
@Bobilala Thanks for your question. You can pass the parameters to filter-parameters property as shown below

az appconfig feature filter add -n appconfig --feature feature --filter-name Microsoft.TimeWindow --filter-parameters "Start=""2023-04-16T16:00:00Z""" "End=""2023-04-25T16:00:00Z"""

<img width="907" alt="image" src="https://user-images.githubusercontent.com/48976275/235886274-27af0c63-98b6-4103-8ee2-7a732b30f6c6.png">

**Comment by Bobilala** [comment]
@SwathiDhanwada-MSFT It doen't work in powershell with the exception "Filter parameter value must be a JSON escaped string. "2023-04-16T16:00:00Z" is not a valid JSON object.", I tried to add parameters using "az appconfig kv import -s file -n <storeName> --format json --path <filePath>"

**Comment by SwathiDhanwada-MSFT** [comment]
@Bobilala Have you tried to execute the command I have provided in my previous comment? Were you facing similar error?

I am bit confused about your last comment, are you trying to import from a file and then passing it to the command az appconfig feature filter add? If so, can you please let me know if you ae importing the keys and feature flags from JSON file ? If possible, kindly share code snippet that you are tweaking.

**Comment by SwathiDhanwada-MSFT** [comment]
@Bobilala I was wondering if you had a chance to review my comment. If you have any questions, please feel free to ask.

**Comment by LotteVoorhorst** [comment]
Hi, 

I've tried the solution you've provided above, but I'm getting the same error: 
az appconfig feature filter add -n <redacted> --feature '<redacted>' --filter-name Microsoft.TimeWindow --filter-parameters "Start=""2023-04-16T16:00:00Z""" "End=""2023-04-25T16:00:00Z"""

Filter parameter value must be a JSON escaped string. "2023-04-16T16:00:00Z" is not a valid JSON object.

Any idea on how to fix this?

**Comment by SwathiDhanwada-MSFT** [comment]
@LotteVoorhorst  Can you please share screen shot of the command and the result you have executed ?

**Comment by LotteVoorhorst** [comment]
@SwathiDhanwada-MSFT Here is the command and the result
![image](https://github.com/Azure/azure-cli/assets/77776940/3cdfe245-5740-4907-899b-c5500a0e2878)

**Comment by SwathiDhanwada-MSFT** [comment]
@LotteVoorhorst Thanks for the screenshot. It's weird to see same command working in my environment but not in your environment with similar configuration as yours. 

Can you please try passing the feature parameter in double quotes as shown in below image and also add --debug to the command so that we can check the log.

<img width="951" alt="image" src="https://github.com/Azure/azure-cli/assets/48976275/5dd73676-c6d1-4771-980d-12e5d2a01fbc">

**Comment by LotteVoorhorst** [comment]
@SwathiDhanwada-MSFT 
Here you go:
![image](https://github.com/Azure/azure-cli/assets/77776940/8cbfa4b9-88f0-4b07-a5ae-6bf94c04d349)

Again, am running the following versions:
![image](https://github.com/Azure/azure-cli/assets/77776940/c4f57a25-5e18-4d42-9df9-ce47a7959899)

Thanks!

**Comment by LotteVoorhorst** [comment]
@SwathiDhanwada-MSFT any update on this?

**Comment by SwathiDhanwada-MSFT** [comment]
@LotteVoorhorst  Apologies for late reply. Can you please try to execute the below command ?

`az appconfig feature filter add -n appconf--feature Feature --filter-name Microsoft.TimeWindow --filter-parameters "Start=\""2023-05-16T16:00:00Z\""" "End=\""2023-05-25T16:00:00Z\"""`

Due to a known issue in PowerShell, some extra escaping rules apply. For more information, refer [this document](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md).

**Comment by SwathiDhanwada-MSFT** [comment]
@LotteVoorhorst @Bobilala Hope the solution provided is helpful. As we haven't heard from you, we will close the issue for now. If there are further questions, please revert and we will be glad to assist you.

**Comment by LotteVoorhorst** [comment]
@SwathiDhanwada-MSFT Thanks for the solution! This works!
