### ISSUE TITLE
KeyVault group members takes a lot of time to update

### ISSUE THREAD

**Issue by sofialouisyax** [Azure/azure-cli#26448]
Hi!

When I add a member to a group that has permission to read keyvault secret, it takes a long time (>10 min) for the keyvault to accept being read by this member. If I check if the member is in the group, I can find it there, but keyvault will still deny access.

I would like to be able to force-update the permission, so that i can get access immediately, and if not, I would at least like a reliable way to check if it has access, instead of doring the show-secret call until no error occurs. It there something I have missed?

Best regards,
Sofia 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://learn.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-list)
* Content Source: [latest/docs-ref-autogen/keyvault/secret.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/keyvault/secret.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by sofialouisyaxis** [comment]
I have received following answer from microsoft:

Security groups takes up to several hours to propagate. Since Key Vault itself has multiple instances, you may call experience that one call is success and next one is not. Usually access to Key Vault should not change often for apps (usually never change, one app per vault), for users, which should not access it often, we recommend just-in-time with PIM and delay for assignment is expected.

**Comment by evelyn-ys** [comment]
Closed since customer has got the answer
