### ISSUE TITLE
`az account list` should return "enabled" subscriptions only, by default.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#2645]
We should add a flag (e.g., `--all`) that lists "disabled" accounts along with "enabled" accounts, but the default should only list "enabled" accounts.

**Comment by johanste** [comment]
Sounds like a good suggestion. I may lean towards being more explicit in the parameter name and say something like --include-disabled instead of --all. But since in the majority of times, you are going to use the list to switch to another enabled one, this is a good proposal.

**Comment by yugangw-msft** [comment]
Suggest we put a warning when we hide the non-enabled ones; otherwise users might get confused that the current account is not in the result from the `list`. The chance of running into this is low since we have made change to default to `enabled` one, but users would still run into it as the default subscription could become disabled after a `login` say he hasn't paid the bill

**Comment by twitchax** [comment]
I'd say that we could make an exception for the default.  That is, if the subscription is the default subscription, it gets displayed no matter what.

**Comment by yugangw-msft** [comment]
@twitchax, FYI what i suggested has a similar pattern in `az vm image list`. Also I much prefer to get the logic simple which will help users use the command 
1. we expose `--all` 
2. we output a warning to tell people so
   `You are viewing an offline list of images, use --all to retrieve an up-to-date list`

**Comment by mayurid** [comment]
I agree with @yugangw-msft. Also i would prefer --all instead of --include-disabled. The help can cllarify that --all means that it includes disabled as well
