### ISSUE TITLE
Incorrect alias definition for 'layered' parameter.

### ISSUE THREAD

**Issue by iainwhiteigs** [Azure/azure-cli#26502]
The description for the `--layered` parameter, says "This option is an alias for --no-validation." I don't think it is an alias for `--no-validation` - it seems to have a different operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f635760-7886-3abb-0491-fcc728b4a90d
* Version Independent ID: eeb3b44f-acc7-6f7e-7604-392d16722a26
* Content: [az iot edge deployment](https://learn.microsoft.com/en-us/cli/azure/iot/edge/deployment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/iot/edge/deployment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/edge/deployment.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@iainwhiteigs Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@iainwhiteigs The  current description for` --layered` parameter is accurate. In short, a layered deployment is determined based on an existing base deployment and the form of the users modulesContent, rather than a service toggle. The edge deployment create command description describes this more. There is history around this, we've talked about potential deprecation of the flag, however it currently remains where we may add some form of layered validation.
