### ISSUE TITLE
ERROR: The subscription of 'XXXX' doesn't exist in cloud 'AzureCloud'.

### ISSUE THREAD

**Issue by shishirdash24** [Azure/azure-cli#26561]
### Describe the bug

We have an Azure build pipeline in DevOps which uses "az extension add -n ml" to install azure ML V2.
This process was working properly till 2 weeks back. Suddenly it has started giving the below error:
ERROR: The subscription of 'XXXX' doesn't exist in cloud 'AzureCloud'.

Note: There has been no changes to the subscription id. I am able to see that on our resource group. A quick help in resolution will help here.

### Related command

az extension add -n ml
<img width="736" alt="Azure issue" src="https://github.com/Azure/azure-cli/assets/124028176/5df8d8f5-14ed-4fdd-bf89-64193fc5353c">
<img width="730" alt="Azure issue1" src="https://github.com/Azure/azure-cli/assets/124028176/09697529-ec15-426f-abcd-dcab459c7b89">
<img width="624" alt="worked fine previously" src="https://github.com/Azure/azure-cli/assets/124028176/e38e2a43-398d-42c2-b134-517e209282a5">

### Errors

ERROR: The subscription of 'XXXX' doesn't exist in cloud 'AzureCloud'.

### Issue script & Debug output

[logs.txt](https://github.com/Azure/azure-cli/files/11598119/logs.txt)

### Expected behavior

Installation of CLI V2 has to be successfull.

### Environment Summary

azure-cli                         2.48.1 *

core                              2.48.1 *
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

### Additional context

N/A

**Comment by shishirdash24** [comment]
Hi,

Did the same as suggested in a test deployment process, but this time too it failed with the same error.
***@***.***


Thanks & regards,
Shishir Kumar Dash
Principal Data Scientist
CleanHarbors, Pune
+91-8390650790
www.cleanharbors.com<http://www.cleanharbors.com/>
Safety Starts with Me: Live It 3-6-5
***@***.***
­­­­­­­­­­­­­­­­__________________________________
[New Image]

Upcoming planned leave: 9th & 29th June 2023

**Comment by MoChilia** [comment]
Hi @shishirdash24! I noticed that you used a service principal to login and the login message showed that you were using a tenant level account.
```
2023-05-30T08:54:46.9080191Z     "name": "N/A(tenant level account)",
```
That's why it failed in `az account set --subscription` and reported the error: `The subscription of 'XXXX' doesn't exist in cloud 'AzureCloud'`. 

To solve this issue, please make sure you have assigned the service principal with proper role and scope by using [`az role assignment`](https://learn.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest).

**Comment by shishirdash24** [comment]
Thank you. Let me check internally if some changes has been made to the account. It was working fine till 8th March.

**Comment by MoChilia** [comment]
@shishirdash24, this issue is not related to Azure CLI version, but the loss of RBAC permission. Besides, `az upgrade` currently doesn't work in Azure DevOps agent but will not fail with `ERROR: The subscription of 'XXXX' doesn't exist in cloud 'AzureCloud'.` This error is caused by `az account set`.

**Comment by fabianfoos** [comment]
Is there any new on this? I have the exact same issue. Which are the service principal's roles and scopes I need to configure?
Thank you!

**Comment by MoChilia** [comment]
Hi @fabianfoos,
Please follow [Assign Azure roles using Azure CLI](https://learn.microsoft.com/azure/role-based-access-control/role-assignments-cli) to select the appropriate role, identify the needed scope, and assign role for the service principal. For more information about role and scope, please refer to [Understand Azure role definitions](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-definitions) and [Understand scope for Azure RBAC](https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview). 
If you have any further question, you may open a new issue for better tracking.
