### ISSUE TITLE
Create authorization rule fails after creating an eventhub with log compaction

### ISSUE THREAD

**Issue by adejongh93** [Azure/azure-cli#26865]
### Describe the bug

We successfully create an eventhub with cleanup policy set as `Compact` and then we try to create an authorization rule for that eventhub, but the creation of the rule fails.

### Related command

First we run:
`az eventhubs eventhub create --subscription <subscription-value> --resource-group <resource-group-value> --namespace-name <namespace-value> --name <eventhub-name-value> --partition-count <partition-count-value> --cleanup-policy Compact`

The response of the above command is successful and it includes this:
```
"retentionDescription": {
    "cleanupPolicy": "Compact"
  }
```

Then we run:
`az eventhubs eventhub authorization-rule create --subscription <subscription-value> --resource-group <resource-group-value> --namespace-name <namespace-value> --eventhub-name <eventhub-name-value> --name <authorization-rule-name> --rights Send`

And it fails with the error below.

### Errors

`(MessagingGatewayBadRequest) SubCode=40000. CleanupPolicy changes are not allowed in update.`

### Issue script & Debug output

cli.azure.cli.core.azclierror: (MessagingGatewayBadRequest) SubCode=40000. CleanupPolicy changes are not allowed in update. TrackingId:a4e9bb9e-9d67-4d70-8ffe-efb3a970db6c_G52, SystemTracker:...development.servicebus.windows.net:eventhub-name, Timestamp:2023-07-11T14:45:19
Code: MessagingGatewayBadRequest
Message: SubCode=40000. CleanupPolicy changes are not allowed in update. TrackingId:a4e9bb9e-9d67-4d70-8ffe-efb3a970db6c_G52, SystemTracker:....servicebus.windows.net:eventhub-name, Timestamp:2023-07-11T14:45:19

### Expected behavior

The authorization rule should be created without any failure.

### Environment Summary

azure-cli 2.50.0

**Comment by navba-MSFT** [comment]
@adejongh93 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@adejongh93 I had a discussion on this issue internally with the Product Owners. We completed our investigation on the reported issue and recognized a bug in CLI that we have been working to fix. It should be fixed with this month end release. 

Until the issue is fixed the workaround would be to use [PowerShell to create rules](https://learn.microsoft.com/en-us/powershell/module/az.eventhub/new-azeventhubauthorizationrule?view=azps-10.1.0), that should work fine.

**Comment by damienmorgansmith** [comment]
Having the same problem; SubCode=40000. CleanupPolicy changes are not allowed in update.

**Comment by navba-MSFT** [comment]
@damienmorgansmith As mentioned above this is a bug within CLI. It should be fixed with this month end release.

Until the issue is fixed the workaround would be to use [PowerShell to create rules](https://learn.microsoft.com/en-us/powershell/module/az.eventhub/new-azeventhubauthorizationrule?view=azps-10.1.0), that should work fine.

**Comment by navba-MSFT** [comment]
@adejongh93 @damienmorgansmith This issue is fixed now. Please update your AzCLI to most recent version (2.51.0) and then test again.

**Comment by adejongh93** [comment]
> @adejongh93 @damienmorgansmith This issue is fixed now. Please update your AzCLI to most recent version (2.51.0) and then test again.

Yeah, we have done some tests and it looks good now, thanks!
