### ISSUE TITLE
AKS Scaling nodes fails

### ISSUE THREAD

**Issue by oriverhu** [Azure/azure-cli#26994]
### Describe the bug

Today I was triying to scale down a nodepool from 5 nodes to 1, so I used this command:

`az aks scale -n AKS-NAME -c 1 -g RG-NAME`

This command started to run, but suddenly an error came out in the console, and the cluster right now says:

"This cluster is in a failed state. If you didn't do an operation, AKS may resolve the provisioning status automatically if your cluster applications continue to run. Learn more"

So I'm trying to do what the documentation recomends that is running this command 

`az resource update --ids ...`

But I still have the problem in the AKS cluster 

What can I do to get the cluster in Ready state again?

### Related command

az aks scale

### Errors

This cluster is in a failed state

### Issue script & Debug output

I didn't run the command with the debug parameter

### Expected behavior

Scale down from 5 nodes to 1

### Environment Summary

azure-cli                         2.39.0 *

core                              2.39.0 *
telemetry                          1.0.6 *

Extensions:
aks-preview                      0.5.118
application-insights              0.1.18
azure-devops                      0.25.0
containerapp                      0.3.23

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\user\.azure\cliextensions'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@oriverhu Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@oriverhu Could you please open the AKS cluster in Azure Portal and go to Activity log and search for the operation there ? You should see the error for the failed start operation and some more information about the failure.

Also you can go to "Diagnose and solve problems" at AKS level and check if any issue is exposed there. More Info [here](https://learn.microsoft.com/en-us/azure/aks/aks-diagnostics).

Alternatively, if you go to the associated vmss nodepool, is it also in failed state ? If yes, if you click on the red ribbon which has link to failure, you can see more info about this error there.  

If these doesn't help, I would recommend you opening a Microsoft Support ticket, so that we can look at this issue more closely and assist you better.

**Comment by navba-MSFT** [comment]
@oriverhu I hope you had a chance to look at the [above ](https://github.com/Azure/azure-cli/issues/26994#issuecomment-1652943335)suggestion.  If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
