### ISSUE TITLE
{webpubsub} HTML tag isn't allowed in example syntax

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#27054]
### Describe the bug

The source code for webpubsub is using HTML tags for examples

Instance 1: https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webpubsub.yml#L198
`Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.'`

Instance 2: https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webpubsub.yml#L205
`Example: --set property1.property2=<value>.'`

Modify these instances to use some other character like a backtick or escape character.

**Contributor's Guide guideance:**
https://review.learn.microsoft.com/en-us/help/platform/validation-ref/disallowed-html-tag?branch=main

**Instance 1 YML syntax looks like this:**
 summary: 'Remove a property or an element from a list.  Example: --remove property.list \<indexToRemove> OR --remove propertyToRemove.'

**Instance 1 published content renders like this:**
![image](https://github.com/Azure/azure-cli/assets/58762114/e433ef3a-5829-4924-b6fd-1b45781c6fdf)

**Instance 1 example correction:**
![image](https://github.com/Azure/azure-cli/assets/58762114/7caf5c8a-83af-4c24-82f4-1e0578cc6116)

**This impacts 2017-03-08-profile, 2018-03-01-hybrid and latest**
- https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/2017-03-09-profile/docs-ref-autogen/webpubsub.yml
- https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/2018-03-01-hybrid/docs-ref-autogen/webpubsub.yml
- https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webpubsub.yml

### Related command

az webpubsub update --remove
az webpubsub update --set

### Errors

MicrosoftDocs/azure-docs-cli build warning:

![image](https://github.com/Azure/azure-cli/assets/58762114/694dc3d3-4610-485f-8142-500aa6eab2ba)

### Issue script & Debug output

See "Describe the bug" section above.

### Expected behavior

See "Describe the bug" section above.

### Environment Summary

See "Describe the bug" section above.

### Additional context

See "Describe the bug" section above.

**Comment by dbradish-microsoft** [comment]
@yonzhan, do you know if this issue made it to anyone's backlog to get fixed?

**Comment by yonzhan** [comment]
webpubsub related CLI commands are owned by service team.

**Comment by jiasli** [comment]
This is the first reported issue so I will use this one as the centralized tracker.

The `<indexToRemove>` string comes from the help message of generic update argument `--remove`:

https://github.com/Azure/azure-cli/blob/261c6d53a3ce205291ef08e85cf487ae1b97bcbb/src/azure-cli-core/azure/cli/core/commands/arm.py#L391

https://github.com/Azure/azure-cli/blob/5eddcd4ff7cfce21c0b42b89435cf28cc6e094cf/src/azure-cli-core/azure/cli/core/aaz/_arg.py#L644

`<indexToRemove>` is actually a placeholder, instead of an HTML tag.

This happens not only to `--remove`, but to `--set` as well: https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-update()

![image](https://github.com/Azure/azure-cli/assets/4003950/e45c5c8d-3a0c-4fd7-af0f-eb890ba175fa)

It should have been `--set property1.property2=<value>`.

https://github.com/Azure/azure-cli/blob/261c6d53a3ce205291ef08e85cf487ae1b97bcbb/src/azure-cli-core/azure/cli/core/commands/arm.py#L390

Possible solutions:

1. Mark it as code with `` ` ``: `` `--remove property.list <indexToRemove>` OR `--remove propertyToRemove` ``
1. Use curly brackets `{}`: `{indexToRemove}`
1. Escape `<>` with `\`: `\<indexToRemove\>`

**Comment by chenkennt** [comment]
@zackliu please help take a look

**Comment by zackliu** [comment]
@jiasli I think the docs is auto generated so what we need to fix is the source code in azure-cli? However, these issues come from common commands, cli team will fix it at large?

**Comment by jiasli** [comment]
I will fix this issue for `webpubsub` in #27752.

**Comment by jiasli** [comment]
The reference doc of `az webpubsub update` has now been fixed. `<>` placeholders in `--add` and `--remove`'s help messages are displayed correctly:

https://learn.microsoft.com/en-us/cli/azure/webpubsub?view=azure-cli-latest#az-webpubsub-update

![image](https://github.com/Azure/azure-cli/assets/4003950/b74d3c11-caa4-47e1-8121-da246459f495)

![image](https://github.com/Azure/azure-cli/assets/4003950/39e2cce5-e716-45b6-bcc6-cb73a456f267)
