### ISSUE TITLE
Region recommendation message style update

### ISSUE THREAD

**Issue by hyoshis** [Azure/azure-cli#27284]
![Screenshot 2023-08-29 at 3 26 23 PM](https://github.com/Azure/azure-cli/assets/13126058/7e044caa-2af4-4327-8753-26cdbe36fa61)

Update message style for post VM create to improve readability:
1. For the regional recommendation message, highlight the command with BrightBlue variable.
2. Separate each message with a new line.

Attached the proposed design solution.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@hyoshis I am so sorry, because we have been super busy with the top priority project Azure Copilot recently, and the end of September is the Mid-Autumn Festival holiday in China, I am afraid we do not have enough time and bandwidth to release this feature in September.
We would like to postpone it to the next sprint **(the relase date is 11-15)** for development and release, do you think this time is acceptable?
cc our CLI PM  @dcaro @Jacekey23
