### ISSUE TITLE
unrecognized arguments: –-enable-cost-analysis

### ISSUE THREAD

**Issue by vlad-333** [Azure/azure-cli#27974]
### Describe the bug

Hello everyone,

I am trying to follow this tutorial https://learn.microsoft.com/en-us/azure/aks/cost-analysis.
I followed all of the steps successfully and I meet all prerequisites but when I want to enable the cost-analysis on my cluster I get this:
az aks update -n my-cluster -g my-rg –-enable-cost-analysis
**unrecognized arguments: –-enable-cost-analysis**

### Related command

az aks update

### Errors

unrecognized arguments: –-enable-cost-analysis true

### Issue script & Debug output

cli.azure.cli.core.azclierror: unrecognized arguments: –-enable-cost-analysis
az_command_data_logger: unrecognized arguments: –-enable-cost-analysis

### Expected behavior

The command must enable the cost analysis on my aks.

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.173
connectedk8s                       1.5.4

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ramdaspotale** [comment]
I am also facing this problem, @yonzhan do we have any update on this?

**Comment by nkemakolam** [comment]
I am also getting this error unrecognized arguments: --enable-cost-analysis any update on the error

**Comment by ramdaspotale** [comment]
i was able to enable it after i followed all steps in the article i.e.
1. update az cli 
2. Register the ClusterCostAnalysis feature flag
3. refresh the registration of the Microsoft.ContainerService resource provider 

not sure if others are still facing after doing this.

**Comment by MS-mikeo** [comment]
There is no problem with the switch, it works fine.  The problem is with the learn documentation and copying of the command switches.  You can see the mismatch in size of the hyphens in instead of -- .  Type it manually or copy from a working switch and it will work fine.  I have helped multiple with this already.  As far as I can tell, the only command that is wrong in the docs is the typo on the –-disable-cost-analysis here.  https://learn.microsoft.com/en-us/azure/aks/cost-analysis#disable-cost-analysis . You can see the white vs blue for the right size hyphen.

**Comment by nkemakolam** [comment]
Finally figured it out and also have it working and documented it [https://techcommunity.microsoft.com/t5/apps-on-azure-blog/aks-cost-analysis-an-azure-native-cost-visibility-experience/ba-p/3973401 ](cost analysis)
