### ISSUE TITLE
netappfiles volume update --usage-threshold confuses GB and TB when sanitizing input

### ISSUE THREAD

**Issue by matt-chan** [Azure/azure-cli#29026]
### Describe the bug

The `netappfiles volume update --usage-threshold` parameter only accepts input from 100 to 2400. The REST API documentation shows that the input is from 100 *GB* to 2400 *TB*. The means azure CLI cannot resize a volume less than 100TB. 

<img width="719" alt="image" src="https://github.com/Azure/azure-cli/assets/1048117/f552f592-b8c7-48d2-a049-f554f550c38e">

Please fix this because our team needs to automate volume resizing less than 100TB.

### Related command

netappfiles volume update --usage-threshold

### Errors

N/A

### Issue script & Debug output

N/A

### Expected behavior

Should resize volumes between 100GB and 2400TB.

### Environment Summary

azure-cli 2.61.0

core 2.61.0
telemetry 1.1.0

Dependencies:
msal 1.28.0
azure-mgmt-resource 23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/hpcadmin/.azure/cliextensions'

Python (Linux) 3.11.8 (main, May 16 2024, 03:47:41) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by DogFace2234** [comment]
Tried a few newer version but tried 2.51.0 instead which is working. Parameter for subnet-id is different. It's -subnet instead of -subnet-id.... but it works. I conveyed the same to customer w/ link for download per documentation.

 

The linked github article is for resizing and mostly seems related to Large Volumes.  I think we need a unique bug for volume creation and regular volumes also.

**Comment by audunn** [comment]
This issue with `--usage-threshold` was fixed in https://github.com/Azure/azure-cli/pull/29389 

@DogFace2234 regarding the subnet the command acceppts `--subnet` and `--subnet-id`
