### ISSUE TITLE
Publish x64 MSI on GitHub release page

### ISSUE THREAD

**Issue by BronsonMagnan** [Azure/azure-cli#29024]
Currently the x64 msi installer is only available by this shortened URL: 
https://aka.ms/installazurecliwindowsx64
While the x32 msi installer is available from both the github release page, as well as this shortened URl:
https://aka.ms/installazurecliwindows

Adding the x64 msi installer to the release page, would allow us to better integrate build systems automation.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Thanks for the feedback.

32-bit MSI packages are distributed on https://github.com/Azure/azure-cli/releases since long time ago. However, Microsoft has a compliance requirement that all packages should be distributed from Microsoft-owned production storage account, i.e. https://azcliprod.blob.core.windows.net/.

I will consult related teams internally and get the approval for publishing 64-bit MSI, along with the 64-bit ZIP package.

**Comment by bebound** [comment]
Similar request: https://github.com/Azure/azure-cli/issues/28856

**Comment by bebound** [comment]
x64 MSI has been available since 2.63.0.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.63.0
