### ISSUE TITLE
Azure CLI Feature: az functionapp show should either differentiate from list or just use list

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli#2936]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3)

**OS Version:** What OS and version are you using?  
Answer here: macOS 10.12.3

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on macOS

---

### Description

When we run `az functionapp show ...` it outputs the same information as `az functionapp list`, except that it allows filtering by group or name, etc. Instead of introducing a new command for `show`, I propose we just use `list` and add the filters to it.

**Comment by tjprescott** [comment]
For consistency with the rest of the CLI, all resource types that support "get" and "list" in their SDK are exposed as "show" and "list" respectively. We would either make this change wholesale across the CLI or not at all, and as we already have GA modules using this pattern, we will continue to expose both commands.

**Comment by johnpapa** [comment]
OK, thanks for the explanation.

Please help me understand when we use list and when we use show? This is not clear to me.

**Comment by tjprescott** [comment]
Show if you want information on a specific thing. List if you want to know all the things in either the subscription or resource group (for those services that support both). List is handy because it requires fewer parameters. You could filter the list down and replicate the output of show, but that would require more effort than simply doing the show.

You could have a structure like:
```Python
def command(resource_group=None, name=None):
  if resource_group and name:
     return sdk.get(resource_group, name)
  elif resource_group:
     return sdk.list(resource_group)
  else:
     return list-all()
```

The issues with this are (a) the get returns an object, not a list and (b) there's no guarantee that the get returns the same structure as the list.  If the get returns Foo, it is generally the case that the list commands return [Foo]. However, this isn't guaranteed and services could return something like [FooSummary].

Get will always return as much or more than list, while list will return as much or less than get.
