### ISSUE TITLE
[Functions] Listing Azure Functions information - Keys

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-cli#2999]
Hi,

is there any possibility(or maybe ongoing work) to manage Azure Functions using Azure CLI? I'm talking mostly about adding/retrieving keys for a specific function or listing URLs in release/deploy scenarios.

**Comment by yugangw-msft** [comment]
@kamil-mrzyglod, we are waiting for service API available. If no ETA, I will submit a PR to support at least `adding/retrieving keys for a specific function`

**Comment by panchagnula** [comment]
@ahmelsayed is this supported using FUNC CLI if so can you share the details here?

**Comment by chriswue** [comment]
Seeing that this has been open for 2.5 years - is there any plan to get traction on this? The func core tools have some basic support for this (see https://github.com/Azure/azure-functions-core-tools/pull/190) but the output is insufficient since I require access to some of the details such as the contents of the function.json

**Comment by anthonychu** [comment]
Related #4041
