### ISSUE TITLE
az vm stop in the CLI stops the VM but Stop in the portal deallocates the resources. need parity between the two?

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#3026]
### Description
**Outline the issue here:**

az vm stop in the CLI stops the VM but does not deallocate the resources. The customer continues to get charged for the resources. Stop in the portal though deallocates the resources. I think we should have parity between the 2.

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:dev build

**OS Version:** What OS and version are you using?  
Answer here:MACOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:terminal

**Comment by rtyler** [comment]
I would like to register my support for this, since I just got bitten by this awkward distinction as well. Fortunately I didn't waste _that much_ money.

**Comment by jluk** [comment]
+1 good report, will bring to CLI team thanks Saurya

**Comment by Claire-dai** [comment]
I'd like to vote for this request. Azure portal, Powershell and CLI need follow the same design rule so that end users won't get lost.

**Comment by TecumsehSamp** [comment]
Also just gotten bitten by this after I saw my bill, "Stop" in the Portal and Powershell (by default) means deallocation and there should be parity between the methods of resource management. 

I think it's a valid assumption to make that someone using "az stop" intends to deallocate the virtual machine rather than just shutdown the guest operating system. Especially if they're used to Azure anyway (which you can also assume they are if they're using the Az CLI over the Portal). 

My suggestion is to either - rename "stop" to "Power-Off" in line with the Azure Compute Rest API [here](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines) and keep the behaviour of `az vm deallocate` so that it is clear that you are just powering off the guest OS and the VM is yet to be deallocated or change `az vm stop` to be similar with the Portal/Powershell and completely deallocate the machine, which might mean getting rid of `Az VM deallocate` altogether.

**Comment by darthkurak** [comment]
What about documentation? It needs update too.
