### ISSUE TITLE
ScenarioTest: needs a few improvements 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3027]
Under playback:
- [x]  Mock away "time.sleep"
- [ ]  ~Mock away~ `Skip` the `setUp` method of individual test

**Comment by troydai** [comment]
@yugangw-msft can you elaborate the item 2? Today you don't need to specify anything in 'setUp'

**Comment by yugangw-msft** [comment]
@troydai, i updated the item 2's description

**Comment by troydai** [comment]
There can be other cases where the `setUp` is needed in recording mode. Therefore from the perspective of a general test framework, it can't deterministically skip the setup process in either playback or recording mode, since it is a test author's decision to make.

The philosophy of the new test framework is to let the __preparer__ to prepare the test environment. The pattern serves fairly well for other command modules. So maybe we can take a look at your scenario and figure out what's the recording only steps you need for the tests and write a preparer for it.

**Comment by yugangw-msft** [comment]
Sounds good
