### ISSUE TITLE
az container not working in 2.0.5

### ISSUE THREAD

**Issue by christianhxc** [Azure/azure-cli#3231]
Why it was removed the container module in the latest version? What's the replacement now?

**Comment by tjprescott** [comment]
@mayurid can you comment on this one?

**Comment by tiagorosendo** [comment]
not work on 2.0.6 too

**Comment by johnsta** [comment]
Hi Christian,

The CI/CD pipeline creation commands in the Azure CLI and ACS portal blade have been deprecated. We experimented with the ‘az container release create’ functionality, but based on user feedback and product usage, it became clear that we needed to improve container experiences directly within the VS Team Services portal and client tools like Visual Studio IDE, as well as target a broader set of deployment environments.  At //build 2017, experience improvements were made available for Visual Studio and Team Services to support container CI/CD to App Services and Service Fabric, with Kubernetes coming soon. Note that any CI/CD pipelines that were originally created with the ‘az container release create’ command will continue to function properly, because it created VSTS build/release definitions and Azure resources like Azure Container Service and Azure Container Registry that are supported products.

More information:
[Continuous Delivery Tools for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VSIDEDevOpsMSFT.ContinuousDeliveryToolsforVisualStudio)

Regards,
John

**Comment by christianhxc** [comment]
Thanks @johnsta for the feedback 👍 I was able to create the registry and the integration manually, the problem I had then was that when creating the tunnel by running this command:

> az acs dcos browse -g myacs-rg -n myacs

That command was useful because I could easily access the DC/OS UI and access the containers in a private manner. Sure, I can create the tunnel using Putty but I couldn't access the containers because they're using a dynamic port. It seems that the above command is using the "az container" command too because it doesn't work in the latest version. Any other recommendation or alternative?

**Comment by johnsta** [comment]
The 'az acs dcos browse' command continues to be supported. Seems like there was a recent regression and how you need to also explicitly pass in the --ssh-key-file argument, which should include the full path to the SSH private key associated with your cluster. 

The command used to look up your default SSH path, and that behavior now seems to have regressed. I noticed you opened up a separate issue (thank you) and we should track that there, i.e. https://github.com/Azure/azure-cli/issues/3232

**Comment by christianhxc** [comment]
Ok, got it, I thought it was related, sorry 👍 

I'll continue in the other ticket then and for me that will be all for this one :)

**Comment by christianhxc** [comment]
@johnsta I see you even deleted the page I was using as reference :( https://docs.microsoft.com/en-us/azure/container-service/container-service-setup-ci-cd

**Comment by brendandburns** [comment]
the `az container` command is not owned by ACS, removing label.
