### ISSUE TITLE
Azurestack: Need per cloud or per profile default value for vm sizes

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3337]
### Description
CLI uses the default size as Standard_DS1_v2 all the time. however this size is not available in azurestack

**Comment by mayurid** [comment]
@yugangw-msft and @derekbekoe to close on plan here and other defaults that we have which will need adjustment for profiles (and sovereign clouds)

**Comment by yugangw-msft** [comment]
@derekbekoe, @tjprescott 
I suggest we do nothing at this point, rather stack should just support this size since it is available across all public regions, meaning it is a selected and useful one.
Or, stack should port the [/sku API](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2017-03-30/swagger/compute.json#L1100). This new API is available in '2017-03-30' and '2014-04-30preview'. It aims to help clients check whether the size is really applicable under current subscription, so that clients can emit out good errors. I plan to have CLI integrate this in create commands for VM, VMSS, and AV-set.

**Comment by bganapa** [comment]
I think its easy to add a profile specific default value for the VM size parameter,  I have to check whether the sku api will be supported in imminent future. In general, we want to take a stance whether we want to support profile specific default values

**Comment by yugangw-msft** [comment]
@bganapa, per our conversation with @johanste and @derekbekoe last week, please ensure azure stack to have this size available, which is available across all regions in public cloud.

**Comment by yugangw-msft** [comment]
Stack should make the service change to have the size available

**Comment by yugangw-msft** [comment]
We can live with it considering we have no user voices
