### ISSUE TITLE
az vm create: attach data disks at creation time

### ISSUE THREAD

**Issue by hensilva** [Azure/azure-cli#3366]
### Description
**Outline the issue here:**
It is not possible to create a VM from an existing set of disks using CLI. Using az vm create It is possible to attach an OS disk, but it is not possible to attach existing data disks. Only parameter supported is related to the creation of new data disks.

Using PowerShell (tested from steps provided here: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/create-vm-specialized

When recreating VMs with existing data disks, it may be necessary to fire the OS with all disks attached to ensure application + data consistency, so the option to add disks later is not the best.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.6

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 (Build 1703)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Ubuntu Bash on Windows 10

**Comment by yugangw-msft** [comment]
Comparing with POSH, CLI has a much flattered out command arg structures for easy-to-use, but front-loading too much support will make the `create` too complex to be usable.
So for this scenario, please use separate command of `az vm disk attach` to accomplish. Of course, if you can elaborate scenarios that the attaching will have to be done at provisioning time, that will help the triage.

**Comment by mayurid** [comment]
@hensilva : Thoughts on using 'az vm disk attach'?

**Comment by yugangw-msft** [comment]
@hensilva has chatted with me. The rational of asking to do it on VM create is the `os` disk to attach has the knowledge about the data disk so the initial booting might not go right, or at least a bit concerning. This [blog post](https://blogs.msdn.microsoft.com/linuxonazure/2016/07/21/cannot-ssh-to-linux-vm-after-adding-data-disk-to-etcfstab-and-rebooting/) mentioned a few cases. Of course, this only happens when people use the practices of snapshot both os and data disk, and then rebuild the VM later-on through disk-attaching. By default `vm create` creates fresh new os and data disks.
