### ISSUE TITLE
[KeyVault] KeyVault Mgmt 2016-10-01

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3423]
Update KeyVault mgmt SDK and support for the following:

- [x] Deleted vault operations (show, list, purge)
- [x] Add support for 'soft delete', 'create mode' and 'storage permissions
- [ ] Add support for Managed Storage Account Keys

See:
https://github.com/Azure/azure-sdk-for-python/pull/1186
https://github.com/Azure/azure-sdk-for-python/pull/1182

**Comment by tjprescott** [comment]
@schaabs, I believe the first two are completed. @troydai was your recent storage key PR related to issue 3?

**Comment by troydai** [comment]
My recent change to the storage creation command is to support manager service identity. Does this item mean that?

**Comment by tjprescott** [comment]
Hmm... no I don't think so.

**Comment by troydai** [comment]
then, no. Can I have the spec for this feature?

**Comment by mbsnl** [comment]
KeyVault Data Plane SDK 0.3.6 (since 0.3.4 in fact) that has been pulled into the CLI main branch supports "Managed Storage Account keys for managing storage credentials and provisioning SAS tokens".
Can someone look at this, so we can also test this from Linux and not stick to PowerShell/Windows-only?

**Comment by tjprescott** [comment]
@schaabs is this still outstanding?

**Comment by schaabs** [comment]
Full support for managed storage account keys has been added.  Closing the issue.
