### ISSUE TITLE
az webapp config appsettings set should not print out all settings

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3599]
### Description
The  `az webapp config appsettings set` command currently prints out all settings for the webapp, which is unexpected and has an unintended consequence of printing sensitive information to the console. For example, if you run:
`az webapp config container set --name somename --docker-custom-image-name ${DOCKER_REGISTRY}/someimage--docker-registry    -server-url https://${DOCKER_REGISTRY} --docker-registry-server-password ${DOCKER_PASSWORD} --docker-registry-server-user ${DOCKER_USER}`

Then the registry credentials are automatically set in appsettings. If someone later runs:
`az webapp config appsettings set --settings PORT=8080 --name somename`

Then the username and password for the registry get printed to the screen.

As a general rule, set commands shouldn't print out state information.

**Comment by tjprescott** [comment]
For all of our create and update commands, we output what the service responds with. `set` is just the verb we use when we don't have separate create and update commands (because it's a better command name than "create-or-update").  So outputting what the service returns is completely consistent with the rest of the CLI.

The issue is that app settings are pretty much just generic key-value pairs. We could:
1. have the command return nothing (this would be inconsistent with other set/update commands) 
2. suppress all displaying of appsettings for this command (necessitates a show call if you want to see the appsettings)
3. apply a heuristic to try and guess whether a setting is sensitive or not (easy for things to fall through the cracks)

If you used the show command, these values would be displayed as well.  If that is acceptable, then I don't see why we wouldn't just lease the behavior as-is.

**Comment by yugangw-msft** [comment]
//cc: @naziml, @ahmedelnably
The root cause is lack of service side protections. For credential related fields, the server should support write, but not read. App service does that for deployment credentials, and we should do the same at here.

**Comment by yugangw-msft** [comment]
@tjprescott, thanks for the suggestions. Per our discussion, I will hide this specific field from related appsettings/container command. This is the closest to the similar server behaviors.
