### ISSUE TITLE
CLI Component Story

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3619]
### Description

Native package manager installs (MSI, Docker image, apt-get, Homebrew) don't support the CLI 'az component update/add' story as:
- Self-updating packages are frowned upon with many of the above package managers.
- Similar story with downloading and installing new code from untrusted stores.

Suggestions:
(1) Remove 'az component update', 'az component remove' & 'az component list-available'.
    The remaining command will be 'az component list'.
    Rationale:
        * These commands aren't supported in most install methods any way (see above).
        * We include all modules from our repo in our default install anyway.

(2) Update docs.microsoft.com install page.
    Remove messages like 'this install does not support components'.
    Rationale:
        * If we're going to remove the above commands, we should remove doc references to it.

(3) What if I have a special use-case where I want extension or preview modules optionally installed?
    Separate instructions can be provided in these scenarios.
        - Create a Python virtual environment (`virtualenv myenv`)
        - Provide a `requirements.txt` file that instructs pip on the required packages. (This could point to your private GitHub repo, storage account or other location).
        - Install with pip `pip install -r <path_to_requirements.txt>`

(4) In the future, if we need the ability to hide/show commands we can look at that when it becomes an issue.

Affects: `pip` and `interactive script` installs mostly.

cc: @mayurid, @johanste, @JasonRShaver

**Comment by JasonRShaver** [comment]
Agree on all points.  I expect #3 to be a point-in-time workaround for some kind formalized component helper for private and preview, especially for those without a base python install (MSI)

**Comment by mayurid** [comment]
@derekbekoe: This looks good.
I agree with @JasonRShaver that we need to look deeper in scenario #3 to understand what customers would want to do and look into more seamless ways to help them acquire preview/extension modules.
We should prioritize #1 and #2 asap.

**Comment by troydai** [comment]
Agree upon item 1 and 2. And I have a different idea of item 3.

The prominent case of item 3 is the Azure Batch Extension Tools. We saw a few customers inquire about `az component` specifically for it. What customers really want to is to use the batch command, therefore CI shouldn't get in the way.

My solution is to make `azure-cli-core` powerful and portable enough to be consumed as a library by other teams. Batch team can simply build their own CLI on top it. They can ship their batch commands CLI as a standalone application. When their commands are mature enough, we can roll over their commands and added to our master repository. Because their commands at time are already depending on `azure-cli-core` the migration would be easy.

This can also become an extension story, just like git. For example, `az batch` command will be shell out to `az-batch` command, which is a standalone application but share the same command / parameters pattern.

**Comment by itowlson** [comment]
@troydai @derekbekoe We've had this flagged as an issue by Azure Batch program management.  We have a workaround where we can advise customers to use the MSI then run az's private copy of pip to install the extensions (`C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe -m pip install azure-cli-batch-extensions`).  This isn't very obvious to customers though, and doesn't give a clean uninstall experience (not sure about the upgrade experience), so we've been asked to raise this with the CLI leads.

Is there an ETA for 'nice' extension support?
