### ISSUE TITLE
Azure Batch durations reported in wrong format in JSON

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-cli#3633]
### Description

When you do a 'get' or 'list' of Azure Batch resources containing durations, the resulting JSON contains a textual description of the duration rather than the round-trippable, machine-processable representation used in the API.  E.g.

```
C:\temp>az batch job show --job-id cmd-line
{
  "constraints": {
    "maxTaskRetryCount": 0,
    "maxWallClockTime": "10675199 days, 2:48:05.477581"  // <------- not useful
  },
  "creationTime": "2016-10-26T02:29:14.820357+00:00",
  "displayName": null,
  "eTag": "0x8D3FD47E0FA3E0A",
...
```

This is particularly problematic for the value shown, which actually represents "no maximum wall clock time" using the implementation detail of .NET TimeSpan.MaxValue, and should therefore probably be omitted from the JSON.  But for non-default durations, or if we must present the default duration, it should be in PnnnTmmm format (ISO 8601).

---

### Environment summary

**Install Method:** pip

**CLI Version:** 

```
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
batch-extensions (1.0.0rc2)
billing (0.1.0)
(snip)
```

**OS Version:** Windows 10

**Shell Type:** Windows

**Comment by mayurid** [comment]
@annatisch and @xingwu1 to comment

**Comment by bgklein** [comment]
Assign  to me if necessary...  Going to need joint investigation how other teams handle durations/if we need to parse SDK responses or if this is an issue for base SDK.

**Comment by bgklein** [comment]
Python SDK stores durations as timedeltas, whose toString takes the specified form. We can clean up the output by creating custom commands but this seems to be the native python representation of timedeltas

**Comment by bgklein** [comment]
@mjconnection / @bsiegel  / @tjprescott this ticket has been passed down in the Batch SDK team over time and still remains, In fact it was filed by an internal Batch Service Team member.

Do you know if other teams create custom JSON formatters to override python datetimes default duration __str__ ? Overall seems like something to be done by the CLI core JSON serializer rather than us doing it ourselves, but ultimately will leave that decision up to the CLI team.

Don't know if this necessarily classifies as bug as it ultimately falls down to the Python SDK using Pythons timedelta to represent time deltas, which by default has this representation. Feel free to correct me or point me to any examples if you feel like we should be doing additional CLI level parsing here.

**Comment by bgklein** [comment]
Displaying it seems rationale since it is defaulted service side and obscuring an actual part of the response/property does not conform with other SDKs/REST spec.

With regard to the timedelta we are using the default CLI json timedelta(python) __str__ representation.  Resolving case.

**Comment by tjprescott** [comment]
@bgklein the other alternative would be to make those datetime arguments accept both formats and internally convert them to ISO 8601. There is a `get_datetime_type` helper in the CLI that could help with that.

**Comment by bgklein** [comment]
Ill create a new issue. The main thing with this one was the duration/print string. We have durations in multiple of our json formats and don't think we should create a different format there from the rest of the CLI. Accepting both in input would be fine tho
