### ISSUE TITLE
Autocompletion support in Windows command line

### ISSUE THREAD

**Issue by Parth6288** [Azure/azure-cli#3892]
Hi,
Is the auto completion for windows command line enabled yet? 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:  azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Windows 7 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd

**Comment by tjprescott** [comment]
Unfortunately, no, not from a native terminal.  For a tab completion experience on Windows, my best recommendation would be to try `az interactive`.

**Comment by JasonRShaver** [comment]
To the best of my knowledge, this is not possible in the Windows command shell (cmd).  Here is a random [SuperUser question on this](https://superuser.com/questions/114595/autocomplete-in-windows-cmd-prompt) with a few ideas.  

Otherwise, as mentioned by Travis, we do offer full auto-complete in `az interactive` mode.

**Comment by RSwarnkar** [comment]
You can install Git SCM and use the Git CLI as a Linux-like CLI on windows.
