### ISSUE TITLE
Inconsistent error thrown when naming a missing blob using a pattern

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#4012]
If I try to delete a blob with a pattern that doesn't match anything:

    az storage blob copy start-batch --destination-container="foo" --source-container "bar" \
                                     --pattern "foo/*"

or even

    az storage blob copy start-batch ... --pattern "foo*"

I get an expected empty list of copied paths.  However, if there is no
`*` in the pattern I get an error:

    az storage blob copy start-batch ... --pattern "foo"
    → Failed to copy blob foo to container deleted.

This is inconsistent: I expected this case to also produce an empty list.

It is particularly bad when viewing storage as a hierarchy of
directories and files: in such a case, to copy `foo`, I need to do two
copies:

    az storage blob copy start-batch ... --pattern "foo"
    az storage blob copy start-batch ... --pattern "foo/*"

because the union of both cannot be done in a single glob (and using
`foo*` will also remove, for example `foo1`, which is wrong).

**Comment by troydai** [comment]
The root cause is a performance optimization [here](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py#L28). When the pattern doesn't contain a wildcard, we use it as blob name directly to fetch the source so as to save the listing cost. Hence the inconsistency. This can be fixed.

However, I'd like to point out one thing. Blob container is not considered as a hierarchy of directories, which is file share. The blobs' names may look like a path, but it doesn't indicate a tree topology. In blob container, you cannot create an empty directory and you can move content from one directory to another. To mock a file system, you should consider Azure File Share.

And in your case, if `foo` is indeed representing a directory, then this command `az storage blob copy start-batch ... --pattern "foo"` shouldn't be necessary. Because there isn't a `foo` blob. When copy `foo/bar` blob to the destination container will essentially be established the `foo` because it is a segment contained in `foo/bar` name string. Now, because blob container is not a file system. Then `foo` can exist as a blob. However, then in this case, `foo*` matches `foo1` is a perfectly correct match.

I'll add this to sprint 19 for now.

**Comment by elibarzilay** [comment]
1. Yes, I am *extremely* aware that it's not a hierarchical directory
   tree...  (And I know about some of the alternatives.)

   (And BTW, see the note from the storage team
   [here](https://feedback.azure.com/forums/217298-storage/suggestions/6417741-static-website-hosting-in-azure-blob-storage).
   Also, the desire to make it look like a hierarchy obviously strong,
   as evident by how the storage explorer works --- or even
   `upload-batch`...)

2. In my case, the `copy` is actually part of two operations: copy a
   blob to a different container and then remove the original.

3. Also, I'm dealing with a `foo` that can sometime be a "directory"
   (ie, there are blobs that start with `foo/...`), sometime it can be a
   blob, and sometimes it can be both (to serve http, I have for each
   directory in the source a `foo` blob that redirects to a `foo/`, and
   `foo/` is a copy of `foo/index.html`).  Dealing with all of that is
   why I'm so aware that it's not a hierarchy...  This is of course
   unrelated to this inconsistency, just a possible explanation for why
   I'm running into so many edge cases.

----

(And only loosely related to all of this: I think that it can be
possible to fill in the gap in making it possible to get a more FS-like
behavior: things like making a `*` in a glob pattern not match `/`s.
Alternatively, it's probably not too hard to make a set of cli commands
that mimic common FS operations.)

**Comment by troydai** [comment]
Great. Glad we cleared it up. I will deal with the inconsistency.

Regarding the matching mechanism, the current match function is `fnmatch`, one step further we can use `glob`, and the ultimate case is `regex`. There are things we can do to make the matching more flexible. Thanks for the advice, we will look into it.

**Comment by elibarzilay** [comment]
Thanks!
