### ISSUE TITLE
Add SR-IOV in the azure-cli tools

### ISSUE THREAD

**Issue by chubin** [Azure/azure-cli#4115]
### Description

**It is not possible to create SR-IOV VMs at the moment. Could you please add support of this in the tools?**

**Comment by tjprescott** [comment]
Are you able to create such a VM in the Azure portal?

**Comment by chubin** [comment]
I'm not sure about the portal, I don't use it (but I think it should be possible),
but it is definitively possible with PowerShell

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking

**Comment by yugangw-msft** [comment]
Accelerated networking is still in preview for Linux. We have change staged but need to coordinate with network service team before merge the change

**Comment by chubin** [comment]
@yugangw-msft Great news! What do you think, how long could it take?

**Comment by szarkos** [comment]
Isn't this already supported via this PR: https://github.com/Azure/azure-cli/pull/3751 ?  The CLI tools available via cloud shell already supports this parameter (--accelerated-networking true).

Accelerated Networking is already GA for Windows, so it should be publicly documented.

**Comment by yugangw-msft** [comment]
Hi folks,
1. For vm,  since this is not a very common scenario, I suggest do like @szarkos mentioned by creating such  a NIC and attach it to the VM on creation, e.g.
```bash
az network public-ip create -g yugangw -n my-pip
az network vnet create -g yugangw -n my-vnet --subnet-name my-subnet1
az network nic create -g yugangw -n my-nic --subnet my-subnet1 --vnet-name my-vnet --public-ip-address my-pip --accelerated-networking true
az vm create -g yugangw -n yugangw-2 --image win2016datacenter --nics my-nic --size Standard_DS4_v2 --admin-password MyVerySecretPassword123
```
We have e2e tests running every day to guarantee we will support it for long run so you can count on this flow
2. For VMSS, it is impossible to scaffolding every single instance, so we have to update the create command. I will get that change in through #4026

Let me know if you have any questions

**Comment by yugangw-msft** [comment]
Closing this and will re-open if there are sizable voices that we need to have strong support from `vm create`
