### ISSUE TITLE
Azure Stack unsupported commands/features should be hidden from az --help

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#4192]
### Description
In 2017-03-09-profile, unsupported commands, modules or features should be hidden while az --help is run

For example, vm managed disk should be hidden when “az vm –help” is executed. 
Adding supported_api_version condition in commands.py file didn't help hiding the help content or block it from running the command.

**Comment by derekbekoe** [comment]
I have verified in the CLI that when I had the `if supported_api_version` constraint to commands I don't want to appear in the older API profile, they don't appear.

**Comment by tjprescott** [comment]
@derekbekoe the issue isn't with commands that leverage `supported_api_version`.  The issue exists for those command models where the SDK is NOT multi-versioned, supported in the CLI, but not supported in stack--for example, app service.

**Comment by tjprescott** [comment]
While #4284 is a short-term fix for Stack, we should consider a general solution that won't require each new service to add `if not supported_api_version(PROFILE_TYPE, max_api='2017-03-09-profile'):` to their commands.

Perhaps when we load the command modules, if the profile doesn't have an entry for a given module, it is not loaded. @derekbekoe thoughts?

**Comment by derekbekoe** [comment]
The logic in https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L61 is focussed around Resource Types rather than command modules.

But yes, currently we have a way of specifying which commands should load per profile (as in the linked PR) but not a way of doing this per command module. We can do this in the future.

Currently, as is, when a new command module is added, it will automatically appear in the older profile (FYI @viananth).
