### ISSUE TITLE
Inconsistency between cname and other record types for delete operations

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4275]
### Description

cname delete - doesn't have "--yes" option - and just deletes outright as compared to a record which has --yes for prompt

---

### Environment summary

**Install Method:** nightly
**CLI Version:** azure-cli (2.0.12+1.dev20170808)
**OS Version:** ubuntu 16.04 x64
**Shell Type:** bash

You should consider a 'az supportinfo' command to return the above in directly copy-pastable form.

**Comment by tjprescott** [comment]
This is intentional, because CNAME record-sets are unique in that they can only contain a single record. We only use the confirmation prompt when there's the potential to delete multiple records (which is why delete has `--yes` for the other record types). Thus, there's no `--yes` option for this type.
