### ISSUE TITLE
Unexpected behaviour : deleting last Azure web app in the Azure App Service plan deletes the plan

### ISSUE THREAD

**Issue by vykhand** [Azure/azure-cli#4497]
Reproduce plan:

1. create plan
2. create app
3. delete app
4. try to create it again and see that it is missing the plan

See the following log:
 
**PS C:\10.DEV_REPOS\powerbi-embed-v2> az appservice plan create --sku B1 --is-linux -l northeurope -n pbiembedplan -g PBIWebapp**
AppServicePlanName    GeoRegion     Kind    Location        MaximumNumberOfWorkers  Name          ProvisioningState    Reserved    ResourceGroup    Status
    Subscription
--------------------  ------------  ------  ------------  ------------------------  ------------  -------------------  ----------  ---------------  ------
--  ------------------------------------
pbiembedplan          North Europe  linux   North Europe                         3  pbiembedplan  Succeeded            True        PBIWebapp        Ready
    ....
**PS C:\10.DEV_REPOS\powerbi-embed-v2> az webapp create -n pbiembed001 -g PBIWebapp --plan pbiembedplan -i vykhand/pbiembed:latest**

.... Running  Normal

**PS C:\10.DEV_REPOS\powerbi-embed-v2> az webapp delete -n pbiembed001 -g PBIWebapp**
**PS C:\10.DEV_REPOS\powerbi-embed-v2> az webapp create -n pbiembed001 -g PBIWebapp --plan pbiembedplan -i vykhand/pbiembed:latest**

**Cannot find ServerFarm with name pbiembedplan.**

**Comment by tjprescott** [comment]
This is the design behavior. That is why there is a flag for `--keep-empty-plan`.

**Comment by snobu** [comment]
Shouldn't it be the other way around? Be explicit that you want to remove the plan vs. finding out after the fact that you had to pass in the extra parameter? If you didn't `tab tab` before the fact, here's what you've just lost:

- The inbound and outbound public IP addresses that you may already have a dependency on (since there's zero guarantee your next plan will spin up in the same scale unit)
- Autoscale rules
- VNET integration and Hybrid Connections

@davidebbo - If i call the raw ARM API, will it default to removing the plan if i remove the last app in the plan?

**Comment by davidebbo** [comment]
@snobu yes, that's the behavior today. Deleting the last app in a Plan (at raw API level) removes the Plan.

**Comment by snobu** [comment]
This is a bit surprising to learn but if the API does it i consider this case closed. Thanks for confirming it.

**Comment by davidebbo** [comment]
Issue is that without this behavior, users ended up getting billed for a bunch of plans that didn't even realize still existed because they had no apps they could see.

**Comment by vykhand** [comment]
Thanks for the explanation!
