### ISSUE TITLE
Command performance is different when it run under admin and user on the Windows

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4526]
Reference: https://github.com/Azure/azure-cli/issues/4477

**Comment by leidegre** [comment]
I outlined my initial findings [here](https://github.com/Azure/azure-cli/issues/4477#issuecomment-331510458) and you can see my timings in [this](https://docs.google.com/spreadsheets/d/1K-gdsBQ9fKKwYuzz39Kvc7INzY_RWsIJdF6o3hQE6M0/edit?usp=sharing) Google spreadsheet. There was a big difference after running the `az` command as an admin on windows, the difference persisted and sped up `az` commands outside of admin context which led me to conclude that it is related to caching of precompiled python files (I did see ACCESS DENIED errors related to this using `procmon`).

**Comment by troydai** [comment]
We're looking into installing the command tools under `<user profile>\AppData\` instead of traditional `Program Files` folder to allow a user privileged installation to avoid `Access Denied` issue.

**Comment by leidegre** [comment]
Bump.

This is still an issue, just tested this with version `2.0.26`. Time taken for any command is about 3 sec, after having run any command as admin, any command running as a normal user takes 1.5 sec.

This is the time it takes running a Samsung NVMe SSD 960 EVO. On average, the latency from Azure Resource Manger APIs is at most 500 ms, often half of that. With that in mind, the Azure CLI 2.0 tooling triples and quadruples request times.

We use Azure CLI 2.0 in our tooling during development and deployment. All these invocations happen as separate calls to `az`. This added start up latency adds up quite a bit and things which don't have to be slow are slow due to things like this.

Back in September, I took a closer look at the https://github.com/projectkudu/ARMClient project which leverages Azure CLI 2.0 to get an access token and then uses that to just make the Azure Resource Manger REST API calls. So, I did something similar.

Here's what I've found.

- it takes about 2-3 milliseconds to read the access token from `%USERPROFILE%\.azure\accessTokens.json` if such a valid token exists
- it takes anywhere from 250-1000 milliseconds for the Resource Manager REST API to respond
- consistently, my LINQPad script takes around 300 milliseconds to execute and return the result
- `az` takes about 2 seconds longer, every time. Yet the result is the same.

The command is was using was `az resource list -g <resource-group>` and the API is was calling was `https://management.azure.com/subscriptions/{subscriptionId}/resources?$filter=resourceGroup%20eq%20%27{resourceGroup}%27&api-version=2017-05-10`

**Comment by yonzhan** [comment]
issue triaged.

**Comment by fengzhou-msft** [comment]
I have ran some commands side by side with latest 2.1.0. And the performance difference is not that significant now.

**Comment by yungezz** [comment]
HI @troydai are you still seeing the big performance difference? Azure CLi is evolving a lot in past 2 years, I would like to close the issue for now. Feel free to create a new issue if found any performance issue.
