### ISSUE TITLE
Cannot create a batch pool with a custom image

### ISSUE THREAD

**Issue by xpillons** [Azure/azure-cli#4620]
### Description
to create a batch pool based on a custom image you need to specify an image ID in the pool.json file that you can specify on the CLI : az batch pool create --json-file pool.json
    "virtualMachineConfiguration": {
        "imageReference": {
          "virtualMachineImageId ": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/images/{imageName}"
        }
      },  

however this returns an error : Parameter 'ImageReference.publisher' can not be None.
when looking at the REST specs it says that virtualMachineImageId is "mutually exclusive with other ImageReference properties" https://docs.microsoft.com/en-us/rest/api/batchservice/pool/add#definitions_imagereference

So the validation test is wrong and should respect the REST specification.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Windows MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.18

**OS Version:** What OS and version are you using?  
Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
cmd.exe

**Comment by djm158** [comment]
This requires AAD integration correct? Are there any docs/examples on doing this from the azure cli?

**Comment by hoangpx** [comment]
how is this going ? I got the same error.  What is publisher for custom image ?

**Comment by xingwu1** [comment]
@xpillons could you send me full json if possible?

I try my json and it works as expected:

```
{
  "id": "pool2",
  "vmSize": "standard_a1",
  "virtualMachineConfiguration": {
      "imageReference": {
        "virtualMachineImageId": "/subscriptions/<subid>/resourceGroups/<resourcegroup>/providers/Microsoft.Compute/images/<image>"
      },
      "nodeAgentSkuId": "batch.node.ubuntu 16.04"
  },
  "resizeTimeout": "PT15M",
  "targetDedicatedNodes": 1,
  "targetLowPriorityNodes": 0,
  "maxTasksPerNode": 3,
  "taskSchedulingPolicy": {
    "nodeFillType": "spread"
  }
}
```

**Comment by annatisch** [comment]
@xingwu1 - This issue is quite old, from before the knack conversion - so quite possibly no longer an issue. From what I can see, the only client-side validation we do for pool settings is not applied if a json file is used, as opposed to individual parameters:
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py#L236

We simply pass the contents of the JSON file to the Python SDK to deserialize into the model:
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py#L481
and:
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py#L294

Perhaps this was a service-side and/or swagger bug at the time?

@xpillons - can you confirm if you are still having trouble with this command?

**Comment by bgklein** [comment]
This issue should be resolved.
