### ISSUE TITLE
webapp: Fix --web-server-logging param to accept storage option

### ISSUE THREAD

**Issue by LukaszStem** [Azure/azure-cli#4764]
Currently `az webapp log config --web-server-logging` has a 'storage' option but is not working.

The webapp team needs to decide the best strategy to go about implementing this.

**Comment by panchagnula** [comment]
this is not something we have plans to support on CLI since this this needs the customer to share some secrets in the Sass-URL -> this can be achieved using the portal for now. This was internal item that got filed during a PR by our team & not a request from customer. Please file a new issue if this is something that needs support from CLI. Thank you.

**Comment by panchagnula** [comment]
Also storage is not an option on this command anymore https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-config
