### ISSUE TITLE
KNACK SQL Module Conversion

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4919]

**Comment by yugangw-msft** [comment]
//cc @tjprescott 
Most done, except
1. `Argument Context.extra()` doesn't work
2. 4 tests failed due to the ArgumentContext issue above and dependencies on not yet converted command modules
   a. `test_sql_db_import_export_mgmt` (missing `az storage blob generate-sas`)
   b. `test_sql_db_operation_mgmt`  (service flakiness `Cannot cancel database management operation '30ef1785-2d63-45e0-99b1-e397b0ae144a' in the current state.`)
   c. `test_sql_tdebyok` (missing `az keyvault` command)
   d `test_sql_vnet_mgmt` (caused by 'ArgumentContext.extra' not working)
