### ISSUE TITLE
Information on user feedback is stored in config file

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#5017]
Based on `azclishell/configuration.py`, information on whether or not a user has provided feedback is in the user-maintained `.azure/config` file. This doesn't seem like an appropriate place to store this information since this file is meant to be editable and maintained by the user. See L113-115, `has_feedback()` method.

**Comment by sptramer** [comment]
It also looks like other CLI-managed values, such as `first_run`, are stored in the user config file as well. There may need to be a general audit.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
I can't find `has_feedback` in the project anymore. Also after running `az feedback`, `~/.azure/config` is not changed.

But the point is correct, for private config like 
```
[core]
first_run = yes
```
ideally it shouldn't appear in user-configurable `config` file. 

But since we already have a warning in the doc [CLI configuration values and environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables):

> You may see other values in your configuration file, but these are managed directly through CLI commands, including az configure. The ones listed in the table above are the only values you should change yourself.

Without further complaining from customers, I prefer not to change the current behavior.
