### ISSUE TITLE
acr says "Please verify if docker daemon is running properly." despite docker daemon running

### ISSUE THREAD

**Issue by p-** [Azure/azure-cli#5075]
**Problem**
After performing a login to the container registry: `az acr login --name <acrName>`
acr says "Please verify if docker daemon is running properly." despite docker daemon running.

**Suspected cause**
The root cause of this issue seems to be that [acr/custom.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py) tries to run `docker ps` which needs elevated rights on some systems. So the command returns a non-zero error and throws an exception.

So a solution for the cli might be to provide a better warning.

A **workaround/solution** for people encountering this issue is to run the command with `sudo`:
`sudo az acr login --name <acrName>`

---

### Environment summary

Install Method: apt-get
azure-cli (2.0.22)
acr (2.0.16)

**Comment by udelblue** [comment]
This may help [https://github.com/Azure/azure-cli/issues/4407](https://github.com/Azure/azure-cli/issues/4407)

**Comment by udelblue** [comment]
or user this 
docker login myregistry.azurecr.io -u xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -p myPassword 
will allow you to login from docker not using the az cli
more info here 
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli

**Comment by yugangw-msft** [comment]
@djyou, could you please comment?

**Comment by djyou** [comment]
The root cause here is that `docker` daemon always runs as the `root` user. The validation using `docker ps` is correct since `docker login` also needs elevated rights (so as `docker pull`, `docker push`, etc.).

I will fix the CLI warning to suggest users add a `sudo` in such cases.

Also if you don’t want to use `sudo`, here are the steps https://docs.docker.com/engine/installation/linux/linux-postinstall/

**Comment by gimler** [comment]
Please reopen. It seems that the docker image doesn't provide `docker`. Also it is based on alpine so no `sudo` available.

**Comment by gimler** [comment]
got it to work with
```
docker run --rm -it  -v /var/run/docker.sock:/var/run/docker.sock  microsoft/azure-cli:2.0.25
```

then
```
apk --no-cache add docker
```

now it works for me

**Comment by djyou** [comment]
@gimler It's by design that `docker` wasn't installed in the CLI container, please see https://github.com/Azure/azure-cli/pull/3747#pullrequestreview-44628171
What you've suggested are exactly the steps in [acr doc](https://github.com/Azure/acr/blob/master/docs/FAQ.md#how-to-log-into-my-registry-when-running-the-cli-in-a-container).
