### ISSUE TITLE
MSI: move msi commands to its own command module in knack style

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5105]
So far, I put the `az identity` command tree inside `azure-cli-vm` command module as i want to avoid the on-going knack conversion. But after the knack release, i will do the work for the new command module. The whole thing is transparent to end users

**Comment by yugangw-msft** [comment]
@tjprescott @williexu, is it worthwhile to do this for 5 tiny commands? I can go either way.

**Comment by tjprescott** [comment]
I suppose it should be done, but there's really no urgency around it.

**Comment by adewaleo** [comment]
@yugangw-msft @tjprescott, it is indeed 5 commands, do we want to move the commands into their own new module?

**Comment by tjprescott** [comment]
@adewaleo @yugangw-msft instead of putting them in their own module, would it make sense to put them in a module that already exists?  For example `azure-cli-role` has to do with authentication, which is what MSI is.  I'd prefer not to put them in a stand-alone module, but if there's a more logical place for them to live besides the VM module that sounds good to me.

**Comment by yugangw-msft** [comment]
yes, a new command module would be too heavy and expensive.  I agree we move them to `azure-cli-role`. MSI essentially is a service principal as a resource. So this makes sense.

**Comment by jiasli** [comment]
As now Azure CLI has command index to accelerate the module load time, moving `az identity` to a separate command module will actually make it faster.

Also, `az ad` has become more and more heavy with Microsoft Graph, including `az identity` in `role` command module also introduces difficulties for command coverage computation.
