### ISSUE TITLE
webapp:Support passing a JSON file for appsettings

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5228]
Ex. az webapp config appsettings set -n <appname> -g <rgname> --settings-file <path-json-file>

**Comment by tjprescott** [comment]
My recommendation would be to overload the `--settings` argument but this seems very reasonable.

**Comment by Ciantic** [comment]
Yes, this is nearly impossible to use right now besides simple cases.

I have a long list of settings provided by `az webapp config appsettings list` command, but no good way to set them back after modifying them.

Usually getters and setters should have symmetry so that value that comes out of getter (in this case `list`) is readily usable by the setter.

**Comment by yugangw-msft** [comment]
@panchagnula , i will take this one unless you are interested

**Comment by Scythen** [comment]
What is the state of this feature? Is it being worked on? Done?

**Comment by markheath** [comment]
would be extremely helpful to work around issues with invalid characters in settings values as mentioned in #7147
