### ISSUE TITLE
Windows 10 Enterprise: kubectl : The term 'kubectl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by lostllama** [Azure/azure-cli#5374]
Following the video here https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/ (see 4:00)

I've successfully run the az aks install-cli command, but running `kubectl get nodes` results in the following message:

kubectl : The term 'kubectl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Please can you either fix the documentation or make this work out of the box?

---

### Environment summary

Windows 10 Enterprise N (10.0.16299 Build 16299)

**Comment by lostllama** [comment]
@tjprescott Why do you think this is a question? This is pointing out Microsoft's failings to support Windows as an operating system. Ironic that the commands in the example would work fine on a Mac, isn't it?

**Comment by tjprescott** [comment]
Hi @lostllama the question label is something we assign to most new issues until the relevant person has a chance to look at it and better classify it.

@mboersma for comment. I have also experienced this on Windows 10 on the current CLI version.

**Comment by mboersma** [comment]
@lostllama yes, I'm well aware of this bug and intending to fix it for the next `az` release. (This behavior was inherited from `az acs kubernetes install-cli` BTW.)

Dropping a binary into the `%Path%` without requiring an Admin shell on Windows is tricky. Using [`chocolatey`](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-chocolatey-on-windows) is actually the recommended way, but we can't assume that's set up on every box. My ideas are:
1. Try to determine where `az` lives and put `kubectl` in the same directory
2. Force the user to specify a full path for where `kubectl.exe` should be saved
3. Keep the default of `C:\Program Files\kubectl.exe` and then use that full path in the `az aks browse` command
4. Keep the default of `C:\Program Files\kubectl.exe` but then admonish the user to move the binary somewhere in the `%Path`
5. Modify the actual `%Path%` environment variable to ensure the target directory is searched (probably impossible since I don't think `win32api` and other native packages are installed)

**Comment by jnoller** [comment]
Given PR #5511 and the issues loading binaries correctly on windows systems into the %PATH variable, closing this issue.
