### ISSUE TITLE
`storage file upload` unable to specify file name with no extension for destination

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#5416]
---
The `--path` argument determines whether the input is a file path or directory path(in which it keeps the filename of the source) by looking at the presence of an extension in the file name [here](https://github.com/Azure/azure-cli/blob/92af6b3cea52f99eee84df93f5d3e2003a273d04/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py#L458).
 
This makes the command unable to specify a filename with no extension to be put into the fileshare.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by limingu** [comment]
It has the work around. As the source file can be the file without extension, the path can just be the  destination path.

I tested with the local file name without extension. It can be successfully uploaded to the destination path.

**Comment by pobby69** [comment]
This problem still persists, it seems to think that a file without an extension is a folder/directory in the fileshare.

**Comment by abagonhishead** [comment]
Not sure why this has been closed. We're now 6 years on and I still can't upload a file with no file extension while specifying the absolute destination path. 

What @pobby69 says is correct -- because there is no file extension, Azure CLI appears to interpret the file as a directory, and makes the assumption that I want to upload the file to a subdirectory but with the same name. It shouldn't do this unless there is a trailing slash.

@limingu I'm not sure I understand what you mean by "the path can just be the destination path." Do you mean that omitting the path parameter is a workaround? Because if so, what if I need to be able to upload the file with a different filename? For example, using Powershell:
```pwsh
$file = New-Item -ItemType File "some_file"
az storage directory create --account-name "my_storage_account"`
--share-name "my_share_name"`
--name "some_directory"`
--account-key "my_account_key"
az storage file upload --account-name "my_storage_account"`
--share-name "my_share_name"`
--path "some_directory/some_file_with_another_name"`
--source "$($file.FullName)" `
--account-key "my_account_key"
```

The error:
```
The specified parent path does not exist.
RequestId:afd5cadc-b01a-00a5-6303-c08272000000
Time:2025-05-08T10:24:38.6574906Z
ErrorCode:ParentNotFound
Program "az.cmd" ended with non-zero exit code: 3.
```

The workarounds are that I either have to rename/copy the file locally before uploading just to accommodate Azure CLI, which isn't always possible, or I need to upload the file _with_ a file extension, copy it to a new file _without_ a file extension, and then delete the original.

This should be reopened as it's a pretty basic bug, and very unclear what the issue is when it pops up.
