### ISSUE TITLE
Is there a way to know which kubernetes versions are supported?

### ISSUE THREAD

**Issue by gmflau** [Azure/azure-cli#5461]
Is there a way to find out which Kubernetes versions are supported by using "az aks create" cli command?  In your documentation, you mentioned 1.7.7 as default and 1.8.2 as well.  Is there a way to find out supported Kubernetes versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* [Content](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: unspecified

**Comment by derekbekoe** [comment]
@mboersma can you comment on this?

**Comment by mboersma** [comment]
@gmflau there isn't currently a way to do so, but I have a change ready that renames `az aks get-versions` to `az aks get-upgrades` and has `az aks get-versions` return the versions available to create:

```console
$ az aks get-versions -l eastus -o table
KubernetesVersion    UpgradesAvailable
-------------------  --------------------------------------------------------
1.8.6                None available
1.8.2                1.8.6
1.8.1                1.8.2, 1.8.6
1.7.12               1.8.1, 1.8.2, 1.8.6
1.7.9                1.7.12, 1.8.1, 1.8.2, 1.8.6
1.7.7                1.7.9, 1.7.12, 1.8.1, 1.8.2, 1.8.6
$ az aks get-upgrades -g maboersm -n test177 -o table
Name     ResourceGroup    MasterVersion    NodePoolVersion    UpgradesAvailable
-------  ---------------  ---------------  -----------------  ----------------------------------
default  maboersm         1.7.7            1.7.7              1.7.9, 1.7.12, 1.8.1, 1.8.2, 1.8.6
```

I haven't submitted it yet because there is still some tidying up to do on the server side for this, but we will make every effort to get this functionality in the next `az` CLI release for mid-February.

cc: @dmitsh
