### ISSUE TITLE
webapp:zip deployment command : -src should be an optional parameter & support zip & option to enable build

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#5524]
- [ ] needs .kuduignore or .azureignore file to allow for excluding files beyond the command defaults.
- [ ] add .NET Core support and other languages

**Comment by anthonychu** [comment]
Would like to see these changes to `az webapp deployment source config-zip`:

* If `--src` is not specified, automatically zip up the current working directory for deployment
* Provide a way to ignore files (like `.gitignore`, perhaps even defaulting to `.gitignore` if a command-specific ignore file doesn't exist)
* (optional) add a flag to indicate whether Kudu should run a build (equivalent to setting SCM_DO_BUILD_DURING_DEPLOYMENT)

There are 2 things this will help with:

* It provides a new method of deploying a folder to App Service using the CLI (and optionally invoking a kudu build if SCM_DO_BUILD_DURING_DEPLOYMENT is true in app settings or .deployment). 
* This command can be leveraged by `az webapp new` command, instead of that command implementing is own logic for zipping and ignoring files

**Comment by panchagnula** [comment]
@btardif can you review this ask please?

**Comment by btardif** [comment]
Looking at this thread there seem to be a lot of duplicate functionality with `az webapp up` command.

We are currently working on adding per stack (node/python/.net/etc...) default ignore logic as well as having user define ignore paths. 

I think parsing the `.gitingonre` file if present is a brilliant idea @anthonychu 

I think all of this request are valid from an experience perspective and `az webapp up` delivers (or will deliver) on that soon.

I think `az webapp deployment source config-zip` is more of a single function command that folks would want to use when scripting for the single purpose of pushing a zip file that has already been crafted.

@spboyer if we add the functionality discussed to `az webapp up` that already does the ziping for you then your asks should be met no? or am I missing something?

**Comment by panchagnula** [comment]
@spboyer / @anthonychu any comments here?

**Comment by spboyer** [comment]
@panchagnula -` webapp up` does more than `zip` correct? `up` creates the application and group etc? If there can be shared code so we are only doing the work once, I think that makes sense.
