### ISSUE TITLE
`azdev test` gives usage error when given module and test

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#5626]
---
What is wrong with this???:
```
(env36) C:\Users\wilx\azure-cli>
azdev test --test test_storage_blob_batch_copy --modules storage --live

usage error: [--test TESTS [TESTS ...]] [--src-file FILENAME] | --modules MODULES [MODULES ...]
```
### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
You don't need `--module` since it automatically figures out that's in the storage module. Technically, what your command is saying is: "Hey, run all the storage tests, and this other storage test again."  There may be cases where you would want to do that, to say run all the network tests and then some specific non-network tests, but I was trying to avoid exactly the situation you posted.

**Comment by williexu** [comment]
Makes sense. However, it's still a problem that the error message gives no real indication that this is the case. In addition, this is change in the behavior in how we used to use `run_tests` and should be documented better.

**Comment by tjprescott** [comment]
This has been fixed as `--module` has been removed.
