### ISSUE TITLE
 Cannot read property 'ipConfigurations' in config file

### ISSUE THREAD

**Issue by Rocknpools** [Azure/azure-cli#566]
I'm trying to deploy a kubernetes cluster on azure following the official [guide](http://kubernetes.io/docs/getting-started-guides/azure/).
Now i need to expose the cluster to the external world to work in [LoadBalancer](http://kubernetes.io/docs/user-guide/load-balancer/) mode. Unfortunately the deployment tools used [(azkube)](https://github.com/colemickens/azkube) is not compatible with this mode and now i have to manually configuring a load balancer and altering the VMSS model to place the NICs into the LoadBalancer backend pool.
This will need to be done from the azure-splat-cli.

Running this command “azure vmss config load-balancer-backend-address-pools set” using this config file:
….
….
"networkProfile": {
      "networkInterfaceConfigurations": [
        {
          "name": "mre-staging-node-nic",
          "primary": true,
          "ipConfigurations": [
            {
              "name": "mre-staging-node-ip",
              "subnet": {
                "id": "/subscriptions/0db6e557-51f6-49d5-87f3-bccd7de8190c/resourceGroups/mre-staging/providers/Microsoft.Network/virtualNetworks/mre-staging-vnet/subnets/mre-staging-subnet"
              }
            }
          ]
        }
      ],
      "id": "/subscriptions/0db6e557-51f6-49d5-87f3-bccd7de8190c/resourceGroups/mre-staging/providers/Microsoft.Network/networkInterface/mre-staging-node-nic"
    }
  },
….
…. 

i got the following error:
parameter-file :  mre-staging-vmss-config.json
error:   Cannot read property 'ipConfigurations' of undefined
error:   Error information has been recorded to /home/ubuntu/.azure/azure.err
error:   vmss config load-balancer-backend-address-pools set command failed

Can someone help me???

**Comment by JasonRShaver** [comment]
Paolo,

You should open an Issue on the Xplat CLI:
https://github.com/Azure/azure-xplat-cli

If you have trouble finding the next step (or creating an issue in the xplat repo does not help you), let us know!

**Comment by sauryadas** [comment]
@Rocknpools 

To set the back end pool using the config command use this ->

azure vmss config load-balancer-backend-address-pools set --parameter-file virtualMachineScaleSetsCreateOrUpdate_createOrUpdate.json --index 0 --ip-configurations-index 0 --network-interface-configurations-index 0 --value "test"

The reason you have to provide indexes is because back end address pool is 3 level below in the ip configurations..

"networkInterfaceConfigurations": [
        {
          "name": "",
          "primary": null,
          "ipConfigurations": [
            {
              "name": "",
              "subnet": {
                "id": ""
              },
              "applicationGatewayBackendAddressPools": [
                {
                  "id": ""
                }
              ],
              "loadBalancerBackendAddressPools": [
                "test"
              ]

You will see the usage if you do the following.

azure vmss config load-balancer-backend-address-pools set "test" --parameter-file virtualMachineScaleSetsCreateOrUpdate_createOrUpdate.json -h

The actually tells you all the index you need to set.

![image](https://cloud.githubusercontent.com/assets/15387759/17383185/7984f582-5989-11e6-974f-6900c386e0a2.png)

**Comment by jpoon** [comment]
For reference, you can generate a config using: `azure vmss config create` or if you have an existing vmss: `azure vmss show --json`

Thanks @sauryadas.

**Comment by jpoon** [comment]
I am in the same boat as @Rocknpools, deployed a Kubernetes cluster using the [official guide](http://kubernetes.io/docs/getting-started-guides/azure/) and am trying to externally expose the VMSS in the cluster via adding manually adding a load balancer. 

Here's what I did:

1) Generate parameter file from existing VMSS: `azure vmss show --json -g <my_resource_group> -n <my_vmss_name> > config.json`
2) Updated parameter file adding backend pools: `azure vmss config load-balancer-backend-address-pools set --parameter-file config.json --index 0 --ip-configurations-index 0 --network-interface-configurations-index 0 --value "test"`
3) Update existing VMSS: `azure vmss create -p config.json -g <my_resource_group> -n <myvmss_name>`

But I get this error: 

```
verbose: SyntaxError: Unexpected token c
  <<< async stack >>>
    at Object.parse (native)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:760:34)
  <<< raw stack >>>
    at Object.parse (native)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:760:34)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:748:164)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:748:180)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:743:190)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:743:206)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
```

I get a similar parsing error when using an unmodified parameters file (e.g. skipped step 2) and an empty parameters file (e.g. `azure vmss config create`).

I'm clearly doing something wrong here -- just not sure what.

**Comment by jpoon** [comment]
Moving this issue over to https://github.com/Azure/azure-xplat-cli/issues/3092.

**Comment by xtophs** [comment]
the c in the unexpected token is the first letter of the parameter to -p. in your case, you passed in config.json ... which starts with a 'c'.

It's because -p expects:  A string of parameters in JSON format.
You need --parameter-file <parameter-file>      when passing the name of a text file that contains input parameter object in JSON format.

azure vmss create --parameter-file config.json -g <my_resource_group> -n <myvmss_name>

and everything is good to go.

**Comment by xtophs** [comment]
Instructions on adding a VMSS to an Azure Load Balancer now available here: https://github.com/xtophs/add-vmss-to-existing-load-balancer

**Comment by jpoon** [comment]
Oh, right. Also here: http://jasonpoon.ca/2016/08/24/adding-a-load-balancer-to-your-virtual-machine-scale-set/ :)
