### ISSUE TITLE
az bash script she-bang assumes /bin location.

### ISSUE THREAD

**Issue by idatum** [Azure/azure-cli#5673]
az script fails on FreeBSD, because bash is installed in a different location (i.e. /usr/local/bin).
FreeBSD is an example where bash is a package; hence generally ends up in /usr/local/bin/bash. It would be nice to configure this during setup (assuming bash is found).
Is /bin/sh good enough for this simple script?
---

### Environment summary
FreeBSD 11.1-RELEASE-p4 amd64
Install Method: python3 -m pip install azure.cli

**Comment by yugangw-msft** [comment]
Using Python Shebang should deal with it. This is sort of related with https://github.com/Azure/azure-cli/issues/7367 and https://github.com/Azure/azure-cli/issues/7726.
//CC @marstr @lmazuel 
If Python shebang turns out have side impact which is a no-go, I suggest we document the workaround which tells users how to tweak manually. Updating the our setup for this is a stretch to me.

**Comment by fengzhou-msft** [comment]
Fixed by #10516, will release on 11/26
