### ISSUE TITLE
Interactive Login Callback Speed

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#5779]
Is there any way to tell the CLI to speed up the check for valid interactive login? I'm demoing with interactive login and it usually takes a minute or so to get the CLI to refresh with login OK.

**Comment by tjprescott** [comment]
What platform are you demoing on?  When I do interactive login is usually updates right after I jump back to the terminal window.

**Comment by jonbgallant** [comment]
Windows is mainline, but also Ubuntu 16.04 VM on Azure.   I can demo for you if you'd like.

**Comment by yugangw-msft** [comment]
If you have accesses to multiple tenants, then it will take some time to dig out all subscriptions from each one of them.  Since June, CLI has emitted out a message to make the waiting less stressful `You have logged in. Now let us find all the subscriptions to which you have access...`. Will that be good enough?
I can make CLI hit tenants in parallel, but since you are the only one with such ask, I am not convinced that I should do it right now.

**Comment by jongio** [comment]
Yes, I have access to 11 tenants.  Have access to that many tenants is probably not normal, so feel free to close.
