### ISSUE TITLE
Argument name matching is dangerous/pointless?

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cli#580]
I realized it when I got an error like:

```
az vm create: error: ambiguous option: --subnet could match --subnet-ip-address-prefix, --subnet-name
```

Then I realized `--subnet-n` actually could be used for `--subnet-name`.

Why do you have this _hidden feature_? This sounds very unintuitive. Many CLI tools offer auto-correction in case of typos etc (which is kind of a better alternative). You already have shorthand forms for many arguments.

**Comment by BurtBiel** [comment]
yes, it's an argparse feature

**Comment by JasonRShaver** [comment]
This is a standard behavior for some CLIs (we use ArgParse as mentioned above).  We've had a number of discussions with champions on both sides, but this 'feature' has become quite common in practical use, for example, `az vm list --out tsv` instead of `az vm list --output tsv`

As we get more usage, we will be actively looking at the success rate of this pattern via telemetry and reinvestigate this if it is seems to not provide joy.

**Comment by ahmetalpbalkan** [comment]
> This is a standard behavior for some CLIs

like which ones?

**Comment by johanste** [comment]
Any program that uses getopt_long (which is more or less the de facto standard) or emulates the same behavior will allow for partial name matching. This includes the standard Python argument parser (argparse) which we are using, and thus got this for "free".

We had a lively discussion on the pros and cons of having this feature (it can be turned off in Python 3.5+ I believe - would have to look up the specific version that it was introduced) but there is no supported way of doing so in argparse in earlier versions.

Since both argparse and getopt_long have this behavior, and both are very widely used, the current assumption is that the existing behavior is not completely unexpected to users.

For what it's worth, Personally, I now frequently take advantage of this feature after having used the CLI for a while, and would be bummed out if it was removed :)

We are obviously open to suggestions to change this behavior, but I would suggest that we gather additional data before making an effort to change this.

Sent from my iPhone

On Aug 4, 2016, at 2:30 AM, Ahmet Alp Balkan <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a standard behavior for some CLIs

like which ones?

-

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
