### ISSUE TITLE
[Monitor] metrics list-defintions: bad error message

### ISSUE THREAD

**Issue by annisele** [Azure/azure-cli#5802]
when I run " az monitor metrics list-definitions --resource explorer-1"
I get a message that says "usage error: --resource_uri ID | --resource_uri NAME --resource-group NAME --resource_uri-type TYPE [--resource_uri-parent PARENT] [--resource_uri-namespace NAMESPACE]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c722777b-9914-5c57-b869-a92bb16e159e
* Version Independent ID: 19b7e250-35b0-6e41-6662-b86791cf4c78
* Content: [az monitor metrics | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Hi @annisele the reason you get that error is because you are providing a resource by name and thus you have to provide the other parameters, at a minimum `--resource-group` and `--resource-type`.  If you provide only `--resource` then you must supply a full resource ID, not just a name. That's what that usage statement is telling you.

There is a bug though, since it appears as "resource_uri-X" in the message instead of "resource-X". We will get that fixed in an upcoming release.
