### ISSUE TITLE
az login command fails

### ISSUE THREAD

**Issue by automagicallyio** [Azure/azure-cli#5841]
All of the sudden az cli command started failing on my laptop with the following error:
Please ensure you have network connection. Error detail: 
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443)
: Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by NewConnectionError('<urllib3.conne
ction.VerifiedHTTPSConnection object at 0x03F5A9D0>: Failed to establish a new connection: [WinError 10060] A connection
 attempt failed because the connected party did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond',))
```

I tried setting up environmental variables HTTP_PROXY, HTTPS_PROXY, AZURE_CLI_DISABLE_CONNECTION_VERIFICATION, and ADAL_PYTHON_SSL_NO_VERIFY, but no luck. Please advise.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
@automagicallyio, are you configuring a proxy?

**Comment by andreassisask** [comment]
I'm having exactly the same issue on my machine. Was working fine for an hour this morning and then suddenly started to fail.

**Comment by yugangw-msft** [comment]
Are you logging as a user or service principal?

**Comment by andreassisask** [comment]
@yugangw-msft I'm logging in as a user. Just opening a new shell corrected the issue, probably because the environment was reset.

**Comment by automagicallyio** [comment]
Strangely enough az cli scripts did not work last week, but this week they are working again. Nothing in the scripts was changed. So, either our networking team did something or Microsoft did something. Weird.

**Comment by tjprescott** [comment]
There may have been a temporary service issue on the auth side.  Please re-open if this issue recurs.

**Comment by JeetSharan** [comment]
I was facing the same issue when running az login in my cmd:

"_HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by NewConnectionError ('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F5A9D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))"

I ran the following commands in cmd:
set HTTP_PROXY=
set HTTPS_PROXY=

After running the above commands, az login command worked.

**Comment by yugangw-msft** [comment]
It is not about the credential, nor about that CLI having bugs which it doesn't. Cmd and WSL could have different network configuration system. You will need to configure the proxy setting with the credential in WLS correctly, otherwise, CLI (more accurately, the basic python requests package) would not work. There are a few blog posts covering this which I hope will help, say [this one]. (https://blog.jhnr.ch/2018/05/16/working-with-azure-cli-behind-ssl-intercepting-proxy-server/). To configure proxy with user name and password, check out [here](https://askubuntu.com/questions/82880/how-do-i-set-a-system-wide-proxy-with-a-username-and-password)

**Comment by varveti** [comment]
hi all,
I seeing the same issue irrespective of the CLI I use. I saw the below issue on "az network nic create"

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c4426c0b-036f-4bfb-b2d3-5c910c5389d6/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xf63d042c>: Failed to establish a new connection: [Errno -2] Name or service not known',))

This issue is not constant. Could anyone please tell me what is the reason that we are seeing this issue and solution for it?

**Comment by dantheman999301** [comment]
If anyone else runs into this, I had Fiddler open with it's self signed cert which was breaking things.

**Comment by ejdoh1** [comment]
Had the same problem but this fixed it:
```
set +H #if your password contains '!'
export http_proxy="<domain\username>:<password>@<proxy server URL>:<port>"
export https_proxy=“<proxy server URL>:<port>”
az login
```
[gist](https://gist.github.com/ejdoh1/3d1badd1fb20ea83ffa9415737b84584)

**Comment by thavlik** [comment]
> Had the same problem but this fixed it:
> 
> ```
> set +H #if your password contains '!'
> export http_proxy="<domain\username>:<password>@<proxy server URL>:<port>"
> export https_proxy=“<proxy server URL>:<port>”
> az login
> ```
> 
> [gist](https://gist.github.com/ejdoh1/3d1badd1fb20ea83ffa9415737b84584)

I can confirm this fixes the issue for me on WSL Debian 9.

**Comment by vermaaakansha** [comment]
> Had the same problem but this fixed it:
> 
> ```
> set +H #if your password contains '!'
> export http_proxy="<domain\username>:<password>@<proxy server URL>:<port>"
> export https_proxy=“<proxy server URL>:<port>”
> az login
> ```
> 
> [gist](https://gist.github.com/ejdoh1/3d1badd1fb20ea83ffa9415737b84584)

I'm having the same error. till yesterday my VS code was working fine , when i was working with azure. today when i did az login, its prompting me this error. 
**Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))**


I saw you fixed the issue. Can you please explain the steps you followed. highly appreciable. 
(Im having Windows10 laptop, proper connected to home wifi. havent done any changes in my laptop.)

**Comment by nectimaneesh** [comment]
az login issue happened .

Trying with the next one
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

It was working but sudden it stopped  login, 

I  am using user account credential for login, not service principle.

**Comment by techadmin1982** [comment]
Experiencing same issue while test deploying some ARM templates in Azure. Tested on Local Powershell ISE , Visual Studio Code but no joy.  Tested the same ARM templates using old Azure-RM modules from Visual Studio Deployment Project and it worked like charm. 
![error](https://user-images.githubusercontent.com/42249185/84645576-69f89580-af1e-11ea-92e4-f537365293ad.JPG)

This is not good at all. Imagine I was deploying something critical. I was lucky that I have kept AzureRM, new Az Modules and also Azure CLI on my system. But i need someone from MSFT to look into this and let us know. Also, I have checked there are no outages on the regions which could have caused this.

**Comment by esnell-midmark** [comment]
used the set HTTP_Proxy and HTTPS_Proxy commands and that didn't work, but checked settings and there was an "all_proxy" value as well ; 
used set all_proxy=
and that fixed the issue 
.... end result all "proxy" settings are blank

**Comment by jiasli** [comment]
Azure-RM is built on PowerShell which has different network logic as Azure CLI, which is built on Python. 

If you are still facing the same issue with Azure CLI, please check your proxy setting and set [`HTTP_PROXY`, `HTTPS_PROXY`](https://2.python-requests.org/en/master/user/advanced/#proxies) or [`ALL_PROXY`](https://2.python-requests.org/en/master/community/updates/#id37) correctly, especially when the proxy uses [Basic Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) .

**Comment by jiasli** [comment]
@esnell-midmark, [`HTTP_PROXY`, `HTTPS_PROXY`](https://2.python-requests.org/en/master/user/advanced/#proxies) and [`ALL_PROXY`](https://2.python-requests.org/en/master/community/updates/#id37) should have the same effect.

Could you try directly invoking `requests`?

```pwsh
# CMD
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"

# PowerShell
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

It will be great if you can create a new issue with detailed **error message** and **proxy configuration** provided. Thanks.

**Comment by jiasli** [comment]
BTW, I have created https://github.com/psf/requests/issues/5558 to [requests](https://github.com/psf/requests) to report the missing `ALL_PROXY` doc.

**Comment by esnell-midmark** [comment]
@jiasli  I created https://github.com/Azure/azure-cli/issues/14812 to track the bug with all_proxy setting

**Comment by mankuuuuu** [comment]
I removed auto generated values by WSL in /etc/resolv.conf and added google NS now it is able to resolve it.
```
# [network]
# generateResolvConf = false
nameserver 8.8.8.8
```

**Comment by sapna-dentsu** [comment]
> used the set HTTP_Proxy and HTTPS_Proxy commands and that didn't work, but checked settings and there was an "all_proxy" value as well ; used set all_proxy= and that fixed the issue .... end result all "proxy" settings are blank

Yes, works for me as well

**Comment by Sanjib-Chowdhury** [comment]
Hi,

Try this & share the outcome -

1. convert the Sever certificate (if not using proxy)/ proxy certificate (if using proxy) using OpenSSL/ Portecle or similar tools
2. Download run the script https://github.com/Sanjib-Chowdhury/407-proxy-authentication-required-CERTIFICATE_VERIFY_FAILED-from-AWS-Azure-Git-NPM-CLI

**Comment by jiasli** [comment]
@Sanjib-Chowdhury, thanks for the script. 

### ⚠️ For anyone else, please be aware this script is not provided by Microsoft. Please use it with caution!

**Comment by dlabout** [comment]
In my case I was having the issue above, but finally resolved the issue by using.
az login -u <username> -p <password> --verbose --debug 
That pointed me to...msal_extensions.persistence.PersistenceDecryptionError: [Errno -2146893813] Decryption failed: [WinError -2146893813] 
oft-authentication-extensions-for-python/wiki/PersistenceDecryptionError: 'C:\\Users\\dola\\.azure\\msal_token_cache.bin'

I renamed the msal_token_cache.bin file to "msal_token_cache.bin.old" and I'm back up and running.

**Comment by baneramu** [comment]
Simply run ipconfig /all from cmd 
then update your DNS server in vi /etc/resolv.conf
#nameserver 10.153.151.1
nameserver x.x.x.x

it will work

**Comment by munirnasir** [comment]
reinstalled az cli, worked fine
