### ISSUE TITLE
sub-resource IDs for scaleset nics aren't supported in az network nic commands

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#588]
az network nic update: error: argument --ids: invalid ResourceId value: '/subscriptions/--sub--/resourceGroups/myvms/providers/Microsoft.Compute/virtualMachineScaleSets/dcos-agent-public-18F03D8E-vmss0/virtualMachines/1/networkInterfaces/agentNodeNic'

**Comment by tjprescott** [comment]
@BurtBiel when I created a VM and called `vm show`, it gave me an ID for the NIC that worked just fine with the `nic update` command.

**Comment by BurtBiel** [comment]
This particular one is for a nic on a vm in a scaleset

**Comment by tjprescott** [comment]
@BurtBiel I'm not sure there's much we can do about this one because the SDK call only accepts the NIC name and and resource group. There's no way to specify a scale set in the call to create_or_update.

I think we would need to go through the compute SDK, but (a) we'd have one custom command tunneling through two completely separate SDKs and (b) it doesn't look like the scale sets operations of the compute SDK exposes anything that would allow us to accomplish this either.

**Comment by BurtBiel** [comment]
sounds reasonable to me
