### ISSUE TITLE
VMSS should support the same strongly typed extensions as `vm create`

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#619]
boot diagnostics
access extension

**Comment by yugangw-msft** [comment]
This should be at lower priority than other features such as data disks

**Comment by yugangw-msft** [comment]
We did for `diagnostic` because we know it is useful for scale-set . The `access`/`boot diagnostics` are mainly for people to manage an individual VM, rather a group of instances, so I don't think there is need.
I am working with scaleset team for the common extensions we should support better. When I have the data, I will open related issues
