### ISSUE TITLE
env vars don't autocomplete within commands

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#6371]
**Describe the bug**

Environment variables don't autocomplete within an `az ...` command.

**To Reproduce**

```bash
MY_VAR=test
echo $MY_V<tab>    # autocompletes
az vm start -n $MY_V<tab>   # does not autocomplete
```

**Expected behavior**

```bash
MY_VAR=test
az vm start -n $MY_V<tab>    # should autocomplete
```

**Environment summary**

Installed with apt on Ubuntu 17.04
az CLI version 2.0.32
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
Related to https://github.com/kislyuk/argcomplete/issues/67

For dev, as mentioned [here](https://github.com/Azure/azure-cli/blob/983399fcecf2368a2f3e35f4cddac908a6ecd457/doc/configuring_your_machine.md#preparing-your-machine), Azure CLI registers auto-complete using https://github.com/Azure/azure-cli/blob/983399fcecf2368a2f3e35f4cddac908a6ecd457/src/azure-cli/az.completion.sh#L11

For production, Azure CLI registers auto-complete using https://github.com/Azure/azure-cli/blob/983399fcecf2368a2f3e35f4cddac908a6ecd457/az.completion#L21

We can add `-o bashdefault` to `az.completion` for a quick fix. @fengzhou-msft, is it possible to replace `az.completion` with `az.completion.sh` so that they share the same logic? 

Meanwhile, `register-python-argcomplete` [doesn't include](https://github.com/kislyuk/argcomplete/blob/abfa18712ec795445857f4125ed5ff3b51107f2c/argcomplete/shell_integration.py#L77) `-o bashdefault` in the default `complete` call. Luckily, this can be overridden with [`--complete-arguments`](https://github.com/kislyuk/argcomplete/blob/b2a3192d6804986a4b51a0e355d5bb0cc1f7c6eb/scripts/register-python-argcomplete#L38-L41), and it later goes to the [`complete`](https://github.com/kislyuk/argcomplete/blob/abfa18712ec795445857f4125ed5ff3b51107f2c/argcomplete/shell_integration.py#L39) command. You may directly run this command to register auto-complete for `az`:

```sh
eval "$(register-python-argcomplete az  --complete-arguments -o nospace -o default -o bashdefault)"
```

The result is expected:

`$ az $` <kbd>Tab</kbd><kbd>Tab</kbd>
```
$BASH                      $DIRSTACK                  $LOGNAME                   $SHELL
$BASHOPTS                  $EUID                      $LS_COLORS                 $SHELLOPTS
$BASHPID                   $GROUPS                    $MACHTYPE                  $SHLVL
```
