### ISSUE TITLE
[Key Vault] table output for secrets isn't correct

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#6372]
**Describe the bug**

Table output for `az keyvault secret list` isn't correct.

**To Reproduce**

```bash
VAULT=my-vault
az keyvault secret list --vault-name $VAULT --output table
```

**Expected behavior**

output a table with ID and Content-Type properties (at least)

**Environment summary**

CLI 2.0.32
Ubuntu 18.04 w/ updates
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by gsacavdm** [comment]
This is related to this issue: [Empty results on query for table output](https://github.com/Azure/azure-docs-cli-python/issues/638), while there's a workaround, it's a pretty terrible one. As it stands, the `az keyvault secret list -o table` command is useless if you don't add adding this hack `--query "[].{i:id}"`.

Options:
* **IDEAL**: the Key Vault team adds a name property to the result set of the [Get Secrets API call](https://docs.microsoft.com/rest/api/keyvault/getsecrets/getsecrets#secretlistresult)
* CLI adds logic, "if the results don't include a name property, print out the ID." It'll probably have to more than name in this check as I'm assuming some other Rest API calls return the name in some other form, for example as databaseName instead of just name.

**Comment by gsacavdm** [comment]
@joshgav , can you include in the issue's **Describe the bug** the current output for the command, which is a table consisting only of the ContentType and Managed, both of which are empty for any non-cert secrets. Example:

|ContentType|Managed|
|---|---|
|application/x-pkcs12|True|
|*{empty}*|*{empty}*|
|*{empty}*|*{empty}*|

**Comment by brentmcconnell** [comment]
Is there a plan to fix this?

**Comment by mlushpenko** [comment]
Just ran into this as well, almost opened another issue.
