### ISSUE TITLE
Configuring the SSL certs file

### ISSUE THREAD

**Issue by edupo** [Azure/azure-cli#6451]
**Is your feature request related to a problem? Please describe.**
We must be able to specify the **ssl certificate file** to use in order to work with azure-cli inside our organization since our SSL connections are being inspected.

**Describe the solution you'd like**
I want to have the option in my configuration file to specify the certificates file used for SSL

**Describe alternatives you've considered**
- Setting that as a configuration in your configuration file.
- Making azure-cli to use the system certificates if available: 
  For Ubuntu those are `/etc/ssl/certs/ca-certicates.crt`

**Additional context**
Nothing is described in the documentations regarding this issue.
https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest

**Comment by tjprescott** [comment]
What command are you trying to use?

**Comment by edupo** [comment]
`az login`

**Comment by tjprescott** [comment]
@yugangw-msft

**Comment by Klaas-** [comment]
this is still an issue as of azure-cli-2.0.57-1.el7.x86_64 
path for rhel package is /usr/lib64/az/lib/python2.7/site-packages/certifi/cacert.pem
simplest way to fix it for me:
`cp /etc/pki/tls/certs/ca-bundle.crt /usr/lib64/az/lib/python2.7/site-packages/certifi/cacert.pem`

usecase: this is needed here because the sign on via our internal AD is being used. When connecting from our internal network the domain uses a certificate signed by our own internal ca.

**Comment by yugangw-msft** [comment]
I suggest use `REQUESTS_CA_BUNDLE`. Check out the [blog](https://blog.jhnr.ch/2018/05/16/working-with-azure-cli-behind-ssl-intercepting-proxy-server/) for more details.

**Comment by Klaas-** [comment]
@yugangw-msft maybe that blog post is worth mentioning in the cli docs? :) but yeah I'd say that solves this issue

**Comment by yugangw-msft** [comment]
@Klaas- i have also thought about this, and I will add a new section to #8351.

**Comment by yonzhan** [comment]
add to S165.

**Comment by qianwens** [comment]
Yugang's PR [ #8351](https://github.com/Azure/azure-cli/pull/8351) has documented the SSL cert configuration and this PR has been merged. I will close this issue since it is solved.
