### ISSUE TITLE
ImagePullBackoff error when creating a kubernetes cluster using yaml file

### ISSUE THREAD

**Issue by badarosama** [Azure/azure-cli#6620]
I am using the following tutorial but using my own project and not the example code used in the tutorial.
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster

I created a yaml file and replaced the image source to following image: listingssdfregistry.azurecr.io/listingsdevfrontend:v1

Ran the following command to see the image in my azure registry:
**az acr repository list --name ListingsSDFRegistry --output table**
and it returns:
Result:
listingsdevfrontend

The image is uploaded to ACR. I did the "Configure ACR authentication" step.
When I run **kubectl apply -f listingsfrontend.yaml**
it successfully creates a deployment and a service as i specified in yaml file.

when i run: kubectl get pods:
it shows the **ImagePullBackOff** Status.

**Environment summary**
Using Windows, Powershell, ACR, AKS.
I am using the following tutorial but using my own project and not the example code used in the tutorial.
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster

I created a yaml file and replaced the image source to following image: listingssdfregistry.azurecr.io/listingsdevfrontend:v1

Ran the following command to see the image in my azure registry:
**az acr repository list --name ListingsSDFRegistry --output table**
and it returns:
Result:
listingsdevfrontend

The image is uploaded to ACR. I did the "Configure ACR authentication" step.
When I run **kubectl apply -f listingsfrontend.yaml**
it successfully creates a deployment and a service as i specified in yaml file.

when i run: kubectl get pods:
it shows the **ImagePullBackOff** Status.

Also when i try:
 kubectl get service listingsfrontend-deployment --watch

i get external-ip as None.

**Environment summary**
Using Windows, Powershell, ACR, AKS.

**Comment by sajayantony** [comment]
Is this incorrectly tagged as ACR?

**Comment by tjprescott** [comment]
It's labeled ACR because the only CLI command involved are ACR commands. What do you feel it should be labeled?

**Comment by sajayantony** [comment]
The kubectl commands and ImagePullBackOff Issues seems like incorrectly configured Kubernetes secret and the docs are under AKS. So maybe route it to the AKS folks?

**Comment by tjprescott** [comment]
@jnoller if this is purely a kubectl issue, feel free to close, but there is a suggestion that it might be an AKS-specific issue.

**Comment by jnoller** [comment]
This issue may be related to the custom code and image settings. AKS Support can assist diagnosing and working through issues like this. 

For cluster  or use-case specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
