### ISSUE TITLE
resource-group mixup during az sql db copy

### ISSUE THREAD

**Issue by coldwell** [Azure/azure-cli#6664]
**Describe the bug**
When attempting to copy a sql database with the command `az sql db copy`, there appears to be confusion about which resource group is referenced. It may be noteworthy that I'm:
* copying within the same subscription
* copying to a difference resource group
* the source and destination use elastic pools

**To Reproduce**
This is the command and parameters I'm attempting to run:
```
az sql db copy \
   --dest-name newDatabaseName \
   --dest-resource-group newResourceGroup \
   --dest-server newSqlServerName  \
   --name originDatabaseName \
   --resource-group originResourceGroup \
   --server originServer \
   --elastic-pool newElasticPoolName
```
I get the error:

> The provided resource group name 'originResourceGroup' did not match the name in the Url 'newResourceGroup'.

**Expected behavior**
The database should copy without error. 

**Environment summary**
I'm using az cli version 2.0.38 on WSL/Ubuntu. azure-cli was installed (and recently updated) via apt-get.
I was previously on 2.0.31 and did not experience this issue on that version.

**Additional context**
n/a

**Comment by sfico** [comment]
Hello, I'have the same problem with version 2.0.37 and 2.0.38

**Comment by tjprescott** [comment]
cc/ @jaredmoo

**Comment by jaredmoo** [comment]
The problem is that the old version of the REST API expects the elastic pool name such as `pool1`, but the new version of the REST API expects full elastic pool resource id such as `/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/rg/providers/Microsoft.Sql/servers/myserver/elasticPools/pool1`. 

In order to maintain compatibility of SQL CLI commands, I implemented a helper function that converts pool name to pool id ( https://github.com/azure/azure-cli/blob/dev/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_validators.py#L87 ), however for `sql db copy` and `sql db replica create` commands this helper function uses the incorrect resource group and server name.

I am implementing a fix now. Until then it is possible to workaround which is to use the full resource id e.g. `/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/rg/providers/Microsoft.Sql/servers/myserver/elasticPools/pool1`.

Sorry about this bug, and thanks for reporting!
