### ISSUE TITLE
Interactive login experience breaks on text interface

### ISSUE THREAD

**Issue by gopitk** [Azure/azure-cli#6717]
**Describe the bug**
Updated to AZ CLI 2.0.40 and tried "az login" on Ubuntu text terminal.  Noticed that it is trying to open a text browser which does not have JS support.

**To Reproduce**
See above

**Expected behavior**
Fallback to --use-device-code option by default if default browser is a not JS capable or text based. 

**Environment summary**
Ubuntu 16.04 LTS, AZ CLI 2.0.40

**Comment by yugangw-msft** [comment]
@gopitk, i assume with `--use-device-code`, you would use a JS capable browser in another machine to finish up the authentication? Or you have other JS capable browsers in the same machine, but you happened to use CLI in the text terminal where the text browser is the default?
I am trying to understand your context before figure out the right option. More information will help.

**Comment by gopitk** [comment]
In this scenario, I have SSHed into a Linux VM on Azure using putty and need to run cli commands on the Linux VM. In general, I think opening a text browser that is incapable of supporting the Interactive Azure Auth is not the best UX.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by efratshabtai** [comment]
In general, having a breaking change to the az login API without changing a major version is not a good practice. There are several products that are taking a dependency on az cli, specifically the az login command. Every time there is a breaking change like this one breaks these products too.

It will be great if you can follow the semantic version of az cli to reflect breaking changes in the future, meaning, increasing patch version for a patch only change, increasing minor version for a functionality change that is backwards compatible and increasing major version whenever there is a breaking change. 

Thank you

**Comment by yugangw-msft** [comment]
Thanks for the feedback. CLI doesn't use semantic version, but we are considering.
For context, this change only impacts interactive logging, other flows(mainly for scripting) stay unchanged. We thought the transition would be fine with the warning emitted and the benefit coming with the new flow; but it didn't go perfect because of this bug and I would apologize for this as honestly I didn't know there are text based browser such things.
In hindsight, we should at least have done more broad announcement for such changes before make it into the release; and yes, semantic versioning would definitely help.

**Comment by gopitk** [comment]
Thanks @yugangw-msft . What are the next steps and ETA? Ideally, if you can recognize the browser you are trying to use to open the interactive login is a text browser and fallback to using device code that would be great and avoid this issue.

**Comment by yugangw-msft** [comment]
The fix will be released in 2 weeks.
The change would be to detect whether you have GUI available. As with GUI, the text browser will be skipped and the UI browser will be launched; otherwise, you will get device code flow which is your case
I am still cross checking the right detection mechanism for multiple distros, but the fix should be merged by the end of this week.

**Comment by yugangw-msft** [comment]
#6725 will fix this. I also put in the code to exclude the text browser.
