### ISSUE TITLE
What is package activate good for?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6749]
`package create` creates and activates a package. When would `package activate` be used? Also, why does it require a `--format` parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa179798-6ff5-80e0-4f78-adf2392649a3
* Version Independent ID: 230d4bc3-5f84-e972-33af-4a48cd096e58
* Content: [az batch application package](https://docs.microsoft.com/en-us/cli/azure/batch/application/package?view=azure-cli-latest#az-batch-application-package-create)
* Content Source: [src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bgklein** [comment]
Assign ownership to me if necessary. Will contact one of our team members who specialized in the AppPackage feature to see if there is a reason for this behavior, or if it would make sense to either delete activate or create a deactivate option.

**Comment by bgklein** [comment]
Package activate does not serve a purpose in a pure CLI workflow as the create is handling the activate for the user, as we handle uploading to storage for convenience.   In a pure REST implementation the workflow would be create => upload to storage => activate => AppPackage ready for use, whereas the CLI is create=> ready to use.  Because of this we can likely remove activate from the CLI

**Comment by tjprescott** [comment]
You would probably want to keep it in case someone started the process via the rest API and wanted to finish it via the CLI.  You can add text to help to clarify this if you want. In either case, the question has been answered so I'll close this issue.
