### ISSUE TITLE
Docker setup suggestions

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#678]
Here's an easier way to run it inside a container

```
$ docker pull azuresdk/azure-cli-python
$ alias az='docker run --rm -v ~/.azure2:/root/.azure azuresdk/azure-cli-python az'
$ az account login
...
```

this way 
1) you don't have to create a new container everytime 
2) you don't have to stay in the container's shell 
3) you don't have to login over and over again

I suggest documenting it like this.

**Comment by mayurid** [comment]
Adding @derekbekoe to take a look

**Comment by derekbekoe** [comment]
I wouldn't remove the old documentation as that's a perfectly valid scenario.
With the current method (`docker run -it azuresdk/azure-cli-python:latest`), you can still achieve everything described:
- you don't have to create a new container everytime as the one initially created will still be running
- you don't have to stay in the container's shell as you can do `docker exec <container> az vm list` for example
- you don't have to login over and over as the container holds the credentials
+ You also get isolation of the persisted login info as it's in the container rather than mapped to a host directory.

I think this suggestion is neat though so we can still add documentation to use the container in this way as an alternative method. I'll work on a PR for this.

**Comment by ahmetalpbalkan** [comment]
> you don't have to create a new container everytime as the one initially created will still be running

not if you reboot your computer, or accidentally hit ctrl+c in container's shell. The old container will still be around and will be stopped `docker run` creates a new container every time

> you don't have to stay in the container's shell as you can do docker exec <container> az vm list for example

you can't `docker exec` once you exit the container (when it's stopped), you have to do `docker start --a`.

> you don't have to login over and over as the container holds the credentials

Nope, as I said `docker run` creates a brand new container every time. Try doing `docker run` and    then `az login` then exit the container by typing `exit`, then run the same `docker run`, you won't have your `~/.azure` == it's a new container.
