### ISSUE TITLE
ACR Credential Helper for Docker and Maven Settings

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-cli#6795]
**Is your feature request related to a problem? Please describe.**
An ACR credential helper for Docker and Maven Settings file will ease the pain for developers

**Describe the solution you'd like**
This should be modeled after [`az aks get-credentials`](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials)

Credentials should be set for Docker CLI and Maven Settings file. Here is an example of how to put them in Maven settings file.
Example settings.xml:

```
<settings>
  ...
  <servers>
    ...
    <server>
      <id>MY_REGISTRY</id>
      <username>MY_USERNAME</username>
      <password>{MY_SECRET}</password>
    </server>
  </servers>
</settings>
```
The id field should be an identifier for a registry server these credentials are for.

**Describe alternatives you've considered**
Manual construction - painful and error prone.

**Comment by selvasingh** [comment]
server credentials in Maven can be [encrypted](https://maven.apache.org/guides/mini/guide-encryption.html)

**Comment by yugangw-msft** [comment]
I would suggest Java SDK team just documents that users can invoke `az acr credential show -n <ACR>` and then propagate the output to the maven xml file. Yes, this requires admin user enabled, but otherwise CLI can only provide 1 hour long token which is not meaningful to be persisted either.
Kubectl has much tighter relationship with AKS in a sense that you can't manage AKS w/o kubectl, hence it makes sense for `az aks get-credentials` to do that; but I don't think this is a right model to ACR to follow.

CC: @djyou
