### ISSUE TITLE
Cannot define Batch start task user identity (admin/non-admin)

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6816]
In the Azure Portal you can define whether the start task should run as admin or not. The `az batch pool create` command doesn't seem to support that. It makes certain scenarios impossible.

**Comment by bgklein** [comment]
This will  likely require discussion within the team.  Part of the problem with exposing the complex property of user identity is that it is complex.   This forces either us to specify every parameter of a user identity or specifying this as a 'won't fix ' forcing users into using SDK's/REST for these advanced behaviors. If you are looking for an answer on an implementation decision for the CLI I shall have one by end of week 8/12-8/19

**Comment by bgklein** [comment]
After discussing with the team, we don't plan on adding this parameter.  The pool is one of the more complex objects in Batch and we need to avoid expanding every one of its sub-properties and their sub-sub-properties to maintain ease of use for the cli.  If you need this behavior, the json-file option allows you to specify the full pool body

**Comment by bgklein** [comment]
The team has designated this as a wont fix.  Due to the complexity of the pool object we cannot list out all  parameters and keep the cli a friendly user experience. Seeing as this property  If you need the specified behavior the suggested route is to use the json-file option to specify the full REST API backed object
