### ISSUE TITLE
After update to cli 2.0.42 command az group show --name changed behavior

### ISSUE THREAD

**Issue by nakonczy** [Azure/azure-cli#6866]
**Describe the bug**
The output of "az group show --name" when the group does not exist changed after updating from version 2.0.41 to 2.0.42.
This breaks all shell scripts depending on this output.

**To Reproduce**
With version 2.0.41 and earlier:
az group show --name test
Prints nothing, exit status is 0 when 'test' does not exist.
With version 2.0.42 prints 'Resource group 'test' could not be found.' and exit status is 3.

**Expected behavior**
I expect to have same behavior as before updating - no output and exit status 0.

**Environment summary**
CLI 2.0.42
Ubuntu 16.04 LTS

**Additional context**
Similar problem was noticed also for "az disk show" in earlier update.

**Comment by tjprescott** [comment]
@williexu

**Comment by tjprescott** [comment]
This was intentional.  
https://github.com/Azure/azure-cli/issues/6612
https://github.com/Azure/azure-cli/pull/6740

**Comment by williexu** [comment]
@nakonczy we made this change to address the mounting inconsistency arising in our CLI with show commands. All `show` commands should now fail with an exit status with encountering a 404 (missing resource). Please take a look at https://github.com/Azure/azure-cli/issues/6612 for a full description of the change and the reasoning for it.

**Comment by nakonczy** [comment]
@williexu Thanks for explaining. However, this is a breaking change which will force me to review all my shell scripts and I'd like to ask additional questions:
- Are all related changes released with one cli version? (2.0.42 ?)
- Are there any other commands in addition to 'show' affected?

**Comment by mkozioro** [comment]
Hi @williexu 
Will you plan to make such changes easier to spot in future, for example by changing minor part of version, like switch from versioning from 2.0.41 to  2.1.0? What is current meaning of versioning schema?

**Comment by williexu** [comment]
Yes, that's a good point.
Currently, we reserve a minor version bump of the CLI for large breaking changes, as individual commands often change in behavior due to the number of services the CLI covers. We do not want to do this too often.

Unfortunately, this makes the versioning decisions subjective at times. We will use your feedback for future occasions and try to make changes such as this more apparent to users.

**Comment by doubleyewdee** [comment]
I just want to bump this because it bit me in another cool way. Using AzCli.invoke() from azure.cli.core in wrapper python now ALSO makes scripts just... exit. It's wildly unintuitive. I'm poking at the code to see what makes sense but my gut feel is that AzCli.invoke needs to know about this magic behavior and do... something … to make peoples' scripts not just implode
