### ISSUE TITLE
AADSTS90100: flowtoken parameter is empty or not valid.

### ISSUE THREAD

**Issue by riramar** [Azure/azure-cli#6913]
Here is not the best place to post this issue but I don't know where to post.
I'm trying to log in azure Android client with my corporate account but I'm getting this error:

AADSTS90100: flowtoken parameter is empty or not valid.

Could you please help to address this issue?

**Comment by vairamsvsjdo** [comment]
You might use corporate support ticket for this, app login is working fine

**Comment by riramar** [comment]
Thanks!

**Comment by yugangw-msft** [comment]
Not a Azure CLI thing

**Comment by AjayKce** [comment]
You are using saml federated authentication , In which your organization create a saml assertion and this assertion is encoded and post via https://login.onmicrosoft.com . After the assertion is verified and create a trust relation between your organisation where it process the flow token to kmsi endpoint.

May be your issue is solved by connecting azure aad from your organization to azure portal
