### ISSUE TITLE
Tracking: 'resource policy show' is broken on built-in ones

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#692]
If you create a custom one, you can show it, but not for built-in ones
Confirmed with ARM team, that it is a known server bug
Will close after the fix is deployed

**Comment by mayurid** [comment]
@yugangw-msft : Is there a timeframe for this on Service side? We can fix the right milestone once we know their status

**Comment by yugangw-msft** [comment]
@ravbhatnagar for ETA
No change is needed at cli side. Once service change is deployed, command should just work.

**Comment by gandhiniraj** [comment]
ACK from ARM team, we are investigating this and will provide ETA by 11/28

**Comment by brendandburns** [comment]
@gandhiniraj any updates on this?

**Comment by ravbhatnagar** [comment]
@yugangw-msft - This has been fixed. Please let us know if you still see this.

**Comment by brendandburns** [comment]
Closing, please re-open if the issue re-occurs.

**Comment by andy26nash** [comment]
Still don't seem to be able to 'show' a built-in policy

Was trying to assign one of the built-in polices “Allowed resource types” using the CLI in the Azure console.

I can list the available policies ‘az policy definition list’ which includes the policy I want to use.

When I try to show that specific policy I get nothing back, no error 

az policy definition show --name a08ec900-254a-4555-9bf5-e42af04b5c5c (with or without single or double quotes)
or
az policy definition show --name "/providers/Microsoft.Authorization/policyDefinitions/a08ec900-254a-4555-9bf5-e42af04b5c5c" (again with or without all variant of quotes)

Same happens when I try to assign it: The policy definition 'a08ec900-254a-4555-9bf5-e42af04b5c5c' could not be found.

**Comment by tjprescott** [comment]
As reported in #4374, this is still a problem.

**Comment by troydai** [comment]
Wasn't this supposed to be fixed in the service? Is there a service issue tracking?

**Comment by tjprescott** [comment]
Closing again. Hopefully we won't need to re-open again.

**Comment by sipazzo** [comment]
I don't know what was fixed because I can't get the policy definition to show whether it is a built in definition or not. It works in Powershell but not cli:
``
Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq "blah" }

Name               : 66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceId         : /subscriptions/b4eebb81-65ae-4a23-a46e-beae9f953e8a/providers/Microsoft.Authorization/policyDefini
                     tions/66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceName       : 66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceType       : Microsoft.Authorization/policyDefinitions
SubscriptionId     : b4eebb81-65ae-4a23-a46e-beae9f953e8a
Properties         : @{displayName=blah; policyType=Custom; mode=All; description=Adds or replaces the specified tag
                     and value when any resource group is created or updated. Existing resource groups can be
                     remediated by triggering a remediation task.; metadata=; parameters=; policyRule=}
PolicyDefinitionId : /subscriptions/b4eebb81-65ae-4a23-a46e-beae9f953e8a/providers/Microsoft.Authorization/policyDefini
                     tions/66288472-91a0-447a-8bfd-a9daf1cb5571


PS C:\Users\myuser> az policy definition show --name "blah"
The policy definition 'blah' could not be found.

az --version
azure-cli                                           2.0.81
command-modules-nspkg              2.0.3
core                                                 2.0.81
nspkg                                              3.0.4
telemetry                                        1.0.4


``
Am I misunderstanding something?

**Comment by sipazzo** [comment]
I don't know what was fixed because I can't get the policy definition to show whether it is a built in definition or not. It works in Powershell but not cli:
``
Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq "blah" }

Name : 66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceId : /subscriptions/xxxxxx-xxxx-xxxx/providers/Microsoft.Authorization/policyDefini
tions/66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceName : 66288472-91a0-447a-8bfd-a9daf1cb5571
ResourceType : Microsoft.Authorization/policyDefinitions
SubscriptionId : xxxxxx-xxxx-xxxx
Properties : @{displayName=blah; policyType=Custom; mode=All; description=Adds or replaces the specified tag
and value when any resource group is created or updated. Existing resource groups can be
remediated by triggering a remediation task.; metadata=; parameters=; policyRule=}
PolicyDefinitionId : /subscriptions/xxxxxx-xxxx-xxxx/providers/Microsoft.Authorization/policyDefini
tions/66288472-91a0-447a-8bfd-a9daf1cb5571

PS C:\Users\myuser> az policy definition show --name "blah"
The policy definition 'blah' could not be found.

az --version
azure-cli 2.0.81
command-modules-nspkg 2.0.3
core 2.0.81
nspkg 3.0.4
telemetry 1.0.4

``
Am I misunderstanding something?

**Comment by muralidharvr** [comment]
I am also facing same issue. 
This works:
Get-AzPolicyDefinition | where-object {$_.Properties.metadata.category -eq "General" -and $_.Properties.displayName -eq 'Allowed resource types'}

This fails:
az policy definition show --name 'Allowed resource types'

**Comment by BintangPradana** [comment]
Hi, I am also facing the same issue when I tried to edit the policy definition

**Comment by zhoxing-ms** [comment]
This is still a service related issue.
For the command `az policy definition show -n` to query build-in policy, the request flow of CLI is:

1. Query the custom policy through [Policy Definitions - Get](https://docs.microsoft.com/en-us/rest/api/resources/policydefinitions/get)


2. If it is not found, it will continue to call [Policy Definitions - Get Built In
](https://docs.microsoft.com/en-us/rest/api/resources/policydefinitions/getbuiltin
) to query the build in policy

Returned data from service:
> {"error":{"code":"PolicyDefinitionNotFound","message":"The policy definition 'xxx' could not be found."}}

So the failure to find it this time is not in line with expectations, we need service team to help to have a look~

**Comment by the-rennegade** [comment]
This still appears to be an issue.......

**Comment by jleonelion** [comment]
Please reopen.  This issue remains - cannot query details of a built-in policy using latest az cli version
```
azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.28.0
ssh                                2.0.4

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1
```
