### ISSUE TITLE
List-* naming inconsistencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#694]
`azure account list-location` <- singular
`azure vm list-ip-addresses` <- plural

**Comment by mayurid** [comment]
@BurtBiel and @yugangw-msft : Do you see any concerns with making it consistent as "list_ip_address"? if I am not wrong this is a custom command.
Also, we should look through and see if there are more such inconsistencies. (I will take a pass)

**Comment by BurtBiel** [comment]
@mayurid @yugangw-msft 
I think list ip addresses (plural) is more correct since lists return arrays.  That also fits with the English command "list <plural>", e.g. "list the tasks".  

To best fit our patterns we would say "ip-address list", but for single commands I think bunching up into "list-<plural noun>" is fine.

**Comment by yugangw-msft** [comment]
@BurtBiel , I agree. I will fix the account list command name then

**Comment by yugangw-msft** [comment]
I found 2 other places and updated them as well
