### ISSUE TITLE
Do not print stack traces unless --verbose or --debug?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#701]
See stack trace at #700. 

You already print an `ERROR: ` and then print the `Exception`. No need to print the stack trace unless somebody is debugging?

**Comment by tjprescott** [comment]
@derekbekoe similar to, but not the same as #611.

**Comment by derekbekoe** [comment]
The exception raised in #700 is a bug in the code that should be fixed (an unexpected exception). In this case, I think it's correct to show the stack trace.

In #611, the exception is 'expected' and not due to a bug in the code so there we should not print the stack trace.

To answer the question "Do not print stack traces unless --verbose or --debug?", yes we shouldn't print stack traces for expected exceptions but **should** print stack traces for unexpected exceptions (due to a possible bug in the code).

**Comment by mayurid** [comment]
@tjprescott : is this addressed as part of #759?

**Comment by tjprescott** [comment]
@mayurid not really. #759 suppresses the stack trace for CloudErrors only. This is a suggestion that we not print any stack trace unless the user has opted-in with --verbose or --debug. That's open for discussion but our current policy is what Derek points out (that we print stack traces for unexpected errors regardless of --verbose/--debug).

**Comment by derekbekoe** [comment]
IMO this can be closed. @tjprescott agree?

**Comment by yugangw-msft** [comment]
I will fix #700. 
I agree this issue can be closed
