### ISSUE TITLE
unable to set property groupMembershipClaims

### ISSUE THREAD

**Issue by jimsander** [Azure/azure-cli#7128]
$ az ad app update --id 1e9d0695-9a30-a9dd-b2e0-ecf5e201ab0c --set groupMembershipClaims=SecurityGroup

Property 'groupMembershipClaims' not found on root. Send it as an additional property .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@yugangw-msft

**Comment by nphmuller** [comment]
Just also ran into this. For me the property is actually set though, despite the warning.

**Comment by yugangw-msft** [comment]
This is by design. In nutshell, the Python SDK is not in sync with the service payload, so CLI's generic updater ends up finding the relevant field in the property bag not recognized by the SDK. 
But, like @nphmuller mentioned, this property will still be set correctly. 
If more people get confused, i can consider to downgrading to an info, but let us leave it as is for now

**Comment by timja** [comment]
I got confused by this too and there's also this issue raised:
https://github.com/Azure/azure-cli/issues/7283
Wasted more time than I liked looking into this...
