### ISSUE TITLE
differences between Windows & Ubuntu: type, kind, sku-name parameters

### ISSUE THREAD

**Issue by oedenfield** [Azure/azure-cli#713]
Hello Everyone,

Yesterday I was using Azure CLI on Windows and had to use this command to create a storage account:

**azure storage account create -g <RESOURCEGROUPNAME> --type RAGRS -l <LOCATION> <STORAGEACCOUNTNAME>**

and I had to use this command on Ubuntu to create a storage account:

**azure storage account create -g <RESOURCEGROUPNAME> --kind Storage --sku-name RAGRS -l <LOCATION> <STORAGEACCOUNTNAME>**

I believe the same command should work across platforms, correct?

**Comment by tjprescott** [comment]
If your command starts with 'azure' instead of 'az' then your issue would actually go here: https://github.com/Azure/azure-xplat-cli.

However, it looks like you might have different versions of the CLI on your Windows and Ubuntu machines. The storage SDKs were updated recently with changes that would make your second command the most current. Specifying `--type` is the "old way". There's nothing (at least in this CLI, but probably not in Xplat either) that changes the parameters based on the OS.

**Comment by oedenfield** [comment]
ok, I'll try updating azurecli on my Windows box and try again.  Thank you for your help.

**Comment by tjprescott** [comment]
@oedenfield Did that resolve your issue? You can use `azure --version` in Xplat or `az --version` in the new CLI to check.

**Comment by oedenfield** [comment]
I do have an older version of azurecli on Windows but I have not had a chance to get it updated.  Will try tonight or tomorrow and let you know.

**Comment by oedenfield** [comment]
After updating Azure CLI on Windows to 0.10.3 I'm now able to use the same command (using --kind) on both Windows & Ubuntu.  Thank you.
