### ISSUE TITLE
az acr create not idempotent

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-cli#7159]
after executing az acr create for the second time with the same parameters the exit code is 1. Which is an error. First time exit code is 0. 

Other az cli * create commands are idempotent (like webapp, postgres). 
Please make this one idempotent also by having the same behavior and result no matter how many times the command is executed.

**Comment by tjprescott** [comment]
Thank you for the report @pascalnaber. Indeed, per our command guidelines, all create commands should be idempotent:

https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types

**Comment by djyou** [comment]
We intentionally blocked this behavior because Classic registry has a dependency on a user storage account. The semantic of the following command is to (1) create a new storage account; and (2) create a registry.

```
az acr create -n Registry -g ResourceGroup --sku Classic
```

When you run the command the second time, it creates another storage account and `updates` your registry with the new storage account.

It can truly be idempotent if `--storage-account-name` is provided:

```
az acr create -n Registry -g ResourceGroup --sku Classic --storage-account-name mystorage
```

@tjprescott We could internally do a GET first to mock the idempotent behavior, then if the second command provides different parameters, I assume we should just update the resource?

@pascalnaber What's you use scenario where you need to run create multiple times?

`az webapp create` doesn't have a dependent resource and they make a PUT request regardless, which is idempotent.

**Comment by pascalnaber** [comment]
We have a CI/CD pipeline running that deploys whenever we want it to run. Now it runs fine the first time only. After that the release fails because of the Error response of az acr create.
We are not using a classic registry.
`az acr create --resource-group $(RESOURCEGROUP_NAME)  --name $(CONTAINERREGISTRYNAME) --sku Premium
