### ISSUE TITLE
[Best Practices] Tests should be self-contained ResourceGroupVCRTests

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#741]
Today many (most?) of the VCR tests rely on manually created assets in order to run.  This makes re-recording those tests much more difficult and makes a bulk re-recording of the test bed very time consuming.  We should convert the tests that inherit directly from VCRTestBase to inherit from ResourceGroupVCRTestBase and make them create all the resources they need to run so re-recording is simple.

**Comment by tjprescott** [comment]
The reason we have not done this across the board is because certain tests take a painfully long time to rerecord. I've added this guidance to the test authoring guide. Additionally, I'll add logic to each test that still needs to be converted so that the test to will fail during re-recording and prompt the developer to update the test structure to ResourceGroupVCRTestBase.
