### ISSUE TITLE
apt-transport-https required to run apt-get update

### ISSUE THREAD

**Issue by robkinyon-roivant** [Azure/azure-cli#7481]
**Describe the bug**

In your [documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt), you say to:

- Add the repository to sources.list.d
- Add the signing key
- Run apt-get update
- Install apt-transport-https and azure-cli

If apt-transport-https isn't already installed, this will fail. Instead, you have to install apt-transport-https *prior* to running apt-get update.

**To Reproduce**

Run the commands in documentation and see them fail.

**Expected behavior**

The commands in documentation will succeed.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
Looking at the latest version of this doc, it does indeed say that the first step is to install `apt-transport-https`. 

![image](https://user-images.githubusercontent.com/5723682/49031109-f20d2380-f15d-11e8-99f7-18e2d601ea1f.png)

Since the issue seems to be resolved, I will close this. If you believe I did so mistakenly, please open an issue [here](https://github.com/Azure/azure-docs-cli-python), as the CLI team does not generate the documentation you are referring to.
