### ISSUE TITLE
az configure: input validation for defaults

### ISSUE THREAD

**Issue by mhausenblas** [Azure/azure-cli#7510]
**Is your feature request related to a problem? Please describe.**
Yes, a feature request for adding input validation. As pointed out in https://github.com/Azure/azure-docs-cli-python/issues/1061,  currently the input values are not validated. For example, you can execute `az configure --defaults location=blah` without any immediate issues, but that doesn't make sense and will potentially cause troubles, down the line.

**Describe the solution you'd like**
Check input against known, valid values and report invalid values back to user.

**Describe alternatives you've considered**
The current status is an, albeit non-desirable, alternative. A low-hanging fruit would be to just warn the user that the input values are not validated.

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
`location` varies depending on Resource Providers. Some services may not be available in all locations. 

Moreover, if CLI limits the location in `az configure`, once a new data center becomes available or a service becomes available in some data centers, users can't use them immediately and need to wait for CLI to be updated accordingly. 

That's why we decided not to implement this check but leave the check to individual commands instead. Thanks for understanding.
