### ISSUE TITLE
`az webapp config set` does not allow setting `--startup-file` to empty string

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-cli#7565]
**Describe the bug**
In Web Apps for Containers, we can use `az webapp config set --startup-file="some_cmd"` to set the command to run in the docker image.

The problem is, once we set startup-file to a non-empty vallue, it looks impossible to clear this out (set to empty).

**To Reproduce**

0. Get current settings:

```
az webapp config show
```

```
{
  "alwaysOn": true,
  "apiDefinition": null,
  "appCommandLine": "",
  "appSettings": null,
  ...
}
```

1. Set startup file to non-empty value.

```
az webapp config set --startup-file='/bin/nginx'
```

```
{
  "alwaysOn": true,
  "apiDefinition": null,
  "appCommandLine": "/bin/nginx",
  "appSettings": null,
  ...
}
```

2. Try setting to empty value using these variants:

```
az webapp config set --startup-file=
az webapp config set --startup-file=''
az webapp config set --startup-file=""
```

The settings remain unchanged:

{
  "alwaysOn": true,
  "apiDefinition": null,
  "appCommandLine": "/bin/nginx",
  "appSettings": null,
  ...
}
```


**Expected behavior**

The value of `appCommandLine` should be set to empty string.


**Environment summary**

OS X / Linux:

`azure-cli (2.0.43)`

**Comment by panchagnula** [comment]
@ppanyukov can you try using the --generic-configurations "{"appCommandLine": ""}"with az webapp config set to clear the setting?
https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az-webapp-config-set & see if that helps?

**Comment by panchagnula** [comment]
Closing this with the suggestion provided & since we haven't heard anything on this yet.

**Comment by metanomi** [comment]
just ran into this same issue, and while the --generic-configurations workaround does work I'm not sure why that should close this issue, since --startup-file is very much broken for empty strings

az webapp config set --name <name> --resource-group <resource-group> --startup-file=""

throws no errors but is effectively a no-op

you have to be attentive to the fact that the output didn't change to realize it didn't work, and if automating this it wouldn't script fail, like:

az webapp config set --name <name> --resource-group <resource-group> --startup-file="" 2>&1 1>/dev/null
echo $?
or similar with "echo %ERRORLEVEL%" in Win cmd cli

gives back 0
