### ISSUE TITLE
Group export -> Max retries exceeded with url

### ISSUE THREAD

**Issue by emnbdx** [Azure/azure-cli#7604]
**Describe the bug**
I can't export my resource group, I always get error on cli:
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: ....  (Caused by ResponseError('too many 500 error responses',))

**To Reproduce**
Just tap: az group export

**Expected behavior**
A json output version of my resource group

**Environment summary**
install with chocolatey
On windows 10
> az --version
azure-cli (2.0.47)

**Comment by tjprescott** [comment]
Are you able to export via the portal?  What kinds of resources are in your resource group?

**Comment by emnbdx** [comment]
not working in portal too

**Comment by tjprescott** [comment]
When I run this on a resource group with an app-service plan and webapp I get the following:
```
Export template operation completed with errors. Some resources were not exported. Please see details for more information.
Could not get resources of the type 'Microsoft.Web/sites/premieraddons'. Resources of this type will not be exported.
Could not get resources of the type 'Microsoft.Web/sites/sourcecontrols'. Resources of this type will not be exported.
```
A partial arm template is returned. Since this seems to be a problem with the web app resource itself, you will likely get a better response by opening a support ticket on the portal. There isn't anything we can do within the CLI to fix this, so I will close this ticket.
