### ISSUE TITLE
Change parameter name --elastic-pool to --dest-elastic-pool on az db copy

### ISSUE THREAD

**Issue by edernucci** [Azure/azure-cli#7678]
**Describe the bug**
The parameter --elastic-pool refer to destination pool, not source.

**To Reproduce**
az sql db copy --dest-name feature-cep --name feature-cep --resource-group desenvolvimento --dest-resource-group production --dest-server feature-production --server feature-develop --elastic-pool feature-production

**Expected behavior**
az sql db copy --dest-name feature-cep --name feature-cep --resource-group desenvolvimento --dest-resource-group production --dest-server feature-production --server feature-develop --dest-elastic-pool feature-production

**Environment summary**
Linux greenpass 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Not applicable.

**Comment by jaredmoo** [comment]
Thank you for the suggestion! This was an intentional design decision. A database is uniquely identified by resource group name, server name, and database name. Therefore, these parameters are the ones that are needed for both source & dest. All other arguments specified for `az sql db copy` are pertaining to the destination.
