### ISSUE TITLE
Daylight savings issue?

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-cli#7751]
I can't login

PS C:\Kubernetes\tools\arch> az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
The access token expiry UTC time '11/4/2018 7:00:28 AM' is earlier than current UTC time '11/4/2018 7:13:02 AM'.
PS C:\Kubernetes\tools\arch>

**Comment by marstr** [comment]
Did some quick digging on this, it seems like it's likely to relate to [this line](https://github.com/Azure/msrestazure-for-python/blob/35dc0e13240541e8991b796f164e248489cbb144/msrestazure/azure_active_directory.py#L172): 
``` Python
token["expiresOn"] = token['expiresIn'] + time.time()
```

I'm going to see what I can do to ensure that Timezone information is getting handled correctly.

**Comment by marstr** [comment]
I've verified that time.time() returns a value that is essentially GMT. Which means that the line I linked above is correct.

**Comment by marstr** [comment]
For anybody else who runs into this in the future, these sorts of issues can often be worked around by using `az account clear`.

**Comment by marstr** [comment]
Because we haven't been able to repro this, I'm going to close it out as stale. However, if anyone experiences this again in November, please open it back up! 

In the meantime, [Microsoft HQ may stop having Daylights Savings time](https://www.seattletimes.com/seattle-news/politics/permanent-daylight-saving-time-in-washington-gets-closer-with-senate-approval/). I'd be pretty pumped if this took off here and spread around the world.
