### ISSUE TITLE
Cli nukes existing SSH id_rsa key when creating AKS cluster

### ISSUE THREAD

**Issue by andig** [Azure/azure-cli#7926]
**Describe the bug**
Creating an AKS cluster with

    az aks create ... --generate-ssh-keys

will silenty overwrite an existing key in `.ssh/id_rsa`. Just nuked mine and I lost ssh access to my remote hosts.

**To Reproduce**

    az aks create ... --generate-ssh-keys

**Expected behavior**
Raise an error message if key file already exists

**Environment summary**
OSX howebrew

**Comment by tjprescott** [comment]
@adewaleo didn't you recently introduce changes to avoid this scenario?

**Comment by adewaleo** [comment]
@tjprescott, Yes I did in #7105. What version of the CLI are you using @andig?

**Comment by andig** [comment]
@adewaleo this is my cli:

    ❯ az -v
	azure-cli (2.0.51)

	acr (2.1.9)
	acs (2.3.11)
	advisor (2.0.0)
	ams (0.3.0)
	appservice (0.2.7)
	backup (1.2.1)
	batch (3.4.1)
	batchai (0.4.4)
	billing (0.2.0)
	botservice (0.1.1)
	cdn (0.2.0)
	cloud (2.1.0)
	cognitiveservices (0.2.4)
	command-modules-nspkg (2.0.2)
	configure (2.0.19)
	consumption (0.4.0)
	container (0.3.9)
	core (2.0.51)
	cosmosdb (0.2.5)
	dla (0.2.3)
	dls (0.1.5)
	dms (0.1.1)
	eventgrid (0.2.0)
	eventhubs (0.3.1)
	extension (0.2.3)
	feedback (2.1.4)
	find (0.2.12)
	hdinsight (0.1.0)
	interactive (0.4.0)
	iot (0.3.4)
	iotcentral (0.1.4)
	keyvault (2.2.7)
	lab (0.1.3)
	maps (0.3.2)
	monitor (0.2.7)
	network (2.2.9)
	nspkg (3.0.3)
	policyinsights (0.1.0)
	profile (2.1.2)
	rdbms (0.3.5)
	redis (0.3.2)
	relay (0.1.2)
	reservations (0.4.1)
	resource (2.1.6)
	role (2.1.10)
	search (0.1.1)
	servicebus (0.3.2)
	servicefabric (0.1.8)
	signalr (1.0.0)
	sql (2.1.5)
	storage (2.2.5)
	telemetry (1.0.0)
	vm (2.2.8)

	Python location '/usr/local/opt/python/bin/python3.7'
	Extensions directory '/Users/andig/.azure/cliextensions'

	Python (Darwin) 3.7.1 (default, Nov 27 2018, 16:34:55)
	[Clang 10.0.0 (clang-1000.11.45.5)]

	Legal docs and information: aka.ms/AzureCliLegal

brew does not offer any upgrade

**Comment by adewaleo** [comment]
@andig, I apologize for the late reply, I was on a vacation.

I just tested the command and it didn't delete or overwrite my ssh keys. I tried running the command with and without `--generate-ssh-keys` (it turns out this parameter actually does nothing) and I also tried using both `--ssh-key-value` and `--generate-ssh-keys`. None of these attempts reproduced the issue.

As a result, I have two requests:
1. Do you mind sharing with us the exact command you ran?
2. Also do you mind sharing with us the names of the ssh key pairs that were nuked. E.g. id_rsa and id_rsa.pub or id_rsa.private and id_rsa? Please examine your ~/.ssh folder to see if anything is strange.

**Comment by andig** [comment]
@adewaleo I've just retried and must admit that I cannot reproduce either. At this point I'm no longer sure if I haven't done a `brew upgrade` in between for whatever reason. I'm closing this issue and will reopen if positive that I can reproduce. Thank you for your kind support and patience!
