### ISSUE TITLE
Cannot set keyvault policy

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#8126]
**Describe the bug**
I tried to use the following command to set keyvault access policy:
```
az keyvault set-policy --name <redacted> --object-id <redacted> --key-permissions get list create encrypt decrypt
```
The command failed with the following, not a descriptive error:
```
An invalid value was provided for 'accessPolicies'.
```
**To Reproduce**
Run this command.

**Expected behavior**
Access policy created for the given key vault.
**Environment summary**
Install Method: brew
CLI version: `azure-cli (2.0.49)`, `keyvault (2.2.5)`
OS version: MacOS high sierra 10.13.6
Shell Type: bash

**Additional context**

**Comment by schaabs** [comment]
@omerlh Thanks for reporting this issue.  Unfortunately I was unable to reproduce the issue with using the version of the CLI you mentioned.  Could you possibly PM me with the output of the command that's failing also specifying the --debug flag?

**Comment by schaabs** [comment]
@omerlh I haven't heard back with anymore details on this issue.  I'm going to close it.  If you're still experiencing the issue please reopen the issue and add the --debug output detail so I can investigate further.

**Comment by omerlh** [comment]
Hey, sorry I somehow missed the notification. Did you check how this behaves when there is an existing policy? I think this is why I had a bug

**Comment by cchchoi1986** [comment]
I ran into this issue as well when I tried to script the azure cli key vault tutorial at the set-policy step:
`
principalidvar="$(az webapp identity assign \
  --resource-group $resourcegroupvar \
  --name $appvar \
  --query principalId
)"

az keyvault set-policy \
  --secret-permissions get list \
  --name $vvar \
  --object-id $principalidvar
`

After a long debug session I realized it happened because $principalidvar was actually "\"<myprincipalid>\"" instead of "myprincipalid"

changing principalvar to fixed my issue
`
principalidvar="$(az webapp identity assign \
  --resource-group $resourcegroupvar \
  --name $appvar \
  --query principalId \
  --out tsv \
)"
`
