### ISSUE TITLE
support -s for az group commands

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8227]
**Is your feature request related to a problem? Please describe.**
az account set accepts --subscription or -s shorthand.  az group accepts --subscription and not the -s shorthand.

**Describe the solution you'd like**
consistently support -s shorthand when --subscription is allowed.

**Describe alternatives you've considered**
n/a

**Additional context**
christian@entropy:~$ az group list -h

Command
    az group list : List resource groups.

Arguments
    --tag          : A single tag in 'key[=value]' format. Use '' to clear existing tags.

Global Arguments
    --debug        : Increase logging verbosity to show all debug logs.
    --help -h      : Show this help message and exit.
    --output -o    : Output format.  Allowed values: json, jsonc, table, tsv, yaml.  Default: json.
    --query        : JMESPath query string. See http://jmespath.org/ for more information and
                     examples.
    **_--subscription : Name or ID of subscription._** You can configure the default subscription using
                     `az account set -s NAME_OR_ID`.
    --verbose      : Increase logging verbosity. Use --debug for full debug logs.

Examples
    List all resource groups located in the West US region.
        az group list --query "[?location=='westus']"

**Comment by tjprescott** [comment]
We cannot do this because other commands use `-s` in other ways that predate the creation of the global `--subscription` and thus it would be a breaking change. Commands that have it do so because they already had a non-global `--subscription` prior to the introduction of the global argument.

At the time we added the global argument, we had much internal discussion and ultimately deemed that `--subscription` would be used infrequently, and thus is didn't merit a short option in the general case.

**Comment by christiankuhtz** [comment]
thanks. that's very unfortunate since i bounce between subs all the time.  is there another shorthand other than command line completion?

**Comment by tjprescott** [comment]
The way argparse parses arguments, any shorthand of subscription will work if "subscription" is the only logical completion (--s, --su, --sub, etc). The downside is that the minimal shorthand will differ from command to command.

**Comment by christiankuhtz** [comment]
ok, thank you. ;-) i'll close this.
