### ISSUE TITLE
Misleading message when the specified resource group does not exist.

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-cli#8262]
**Describe the bug**
Misleading message when the specified resource group does not exist.

**To Reproduce**
```
19:35 $ az aks get-credentials --resource-group resource-group-name --name cluster-name --overwrite-existing
The client 'XXX@YYY' with object id '**********' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/listClusterUserCredential/action' over scope '/subscriptions/**********/resourceGroups/resource-group-name/providers/Microsoft.ContainerService/managedClusters/dev02-cluster'.
```
**Expected behavior**
I would expect the message to report that the resource group does not exist.

**Environment summary**
Installed using brew on mac OSX, version 2.0.54 .

**Comment by zqingqing1** [comment]
I suspect your resource group does exist, Can you please run `az group show -g <resource group name>` to see if this is there?

**Comment by tjprescott** [comment]
@zqingqing1 the title clearly calls out that the resource group doesn't exist.

**Comment by andreacassioli** [comment]
The group does not exists in the subscription I am working on (if I am not mistaken that is the resource group name scope as for https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions).

Btw: even running `az group show -g resource-group-name` results in a similar error message about me having no privileges.

**Comment by zqingqing1** [comment]
If so, then it shouldn't be AKS issue. Probably, the error means your SP doesn't have permission on some resource(Maybe your subscription)

You can try this: <client-id> is the one showed in the error msg.
`az sp ad show --id <client-id> `
And get Service Principal Id from "ServicePrincipalNames" block, Pick the one looks like GUID, and then from portal, finding where the subscription is, and click the IAM and search if you have the service principal ID there. If not, then you can add it.

**Comment by andreacassioli** [comment]
I am not sure I understand. Here is what I get

```
21:45 $ az sp ad show --id ********************************
az: 'sp' is not in the 'az' command group. See 'az --help'.
```

Anyway, if I run `az group show -g xxx` on a resource group that exists, I see all details. What has the SP to do with that? What about just a badly handled exception?

**Comment by andreacassioli** [comment]
@tjprescott I get full information if the resource group exists.

**Comment by zqingqing1** [comment]
@andreacassioli, the right command should be `az ad sp`,  I mis-located the order. Can you try again?

**Comment by andreacassioli** [comment]
@tjprescott here it is:

```
21:40 $ az group show -g fakerg
The client 'XXX@YYY' with object id '********************' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/**************/resourcegroups/fakerg'.
```

**Comment by tjprescott** [comment]
@andreacassioli thank you very much for that. @zqingqing1 this is a CLI issue, not AKS. @yugangw-msft is there a way we can improve this error message when the user is logged in as a service principal?

**Comment by yugangw-msft** [comment]
it is hard to polish the error message just based on logged in as a service principal because a service principal can be as powerful as a admin while a user can have less permission than a service principal. 
Let us live with it since we only have one user with such confusion, and the error itself is not that bad.

**Comment by andreacassioli** [comment]
@yugangw-msft I am quite surprise by your message. Proper error messaging in key for a good CLI and basically ignoring user feedback is quite annoying. Maybe you do not care that much at MS.

**Comment by darryncurranHP** [comment]
@yugangw-msft I've just stumbled on this error today as well.

Unlike @andreacassioli I was deploying management-groups in the CLI but the issue was the same. I can create and show/list management-groups AFTER they have been created, but if I try and show/list for a management-group that doesn't exist I get the error below:

Code: AuthorizationFailed
Message: The client '<identifier>' with object id '<identifier>' does not have authorization to perform action Microsoft.Management/managementGroups/read over scope '/providers/Microsoft.Management/managementGroups/testManagementGroupName'

**Comment by yugangw-msft** [comment]
PAS team should take a look and emit out a better error such as the `resource doesn't exist`

**Comment by yugangw-msft** [comment]
//CC @skwan

**Comment by jiasli** [comment]
We have worked with ARM team to improve the error message. Now it shows 

> The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/xxx/resourcegroups/xxx' or **the scope is invalid**. If access was recently granted, please refresh your credentials.

Please let us know if this suits the need. Thanks.

**Comment by andreacassioli** [comment]
Sorry to insist, but the message will not help that much. It might be a matter of wording, but to me invalid scope does not necessary mean that a resource does not exist!

**Comment by jiasli** [comment]
If the signed-in user doesn't have permission to list resources, it is against security to report whether a resource exists or not. So user needs to check whether the scope is valid (matches the assigned scope).

**Comment by cole-brown** [comment]
Is it against security to have clear error messages?

For example:

- "You do not have enough permissions for that action."
- "You /do/ have enough permission for that action and that resource does not exist; **check your spelling**."
- "You /do/ have enough permission for that action and the scope is invalid."
- etc

You're encouraging me to escalate my security permissions until I notice I misspelled a resource name, currently. Like, this just happened and I'm not dropping my permissions back down because this has happened before for other reasons and maybe the new permissions will fix it? :shrug:

**Comment by jiasli** [comment]
@cole-brown, the error message is sent by ARM service, instead of Azure CLI. You may submit your feedback at https://feedback.azure.com/
