### ISSUE TITLE
Compute and Network services return resource IDs with different casing

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-cli#8283]
**Describe the bug**
When running `az network nic list --query "[?virtualMachine.id=='<ID>']"` the CLI processes case-sensitive. 

**To Reproduce**
You'd need to look up Private IP Address by VM ID 

```
vmList=$(az vm list --query "[?location=='westus']".id -o tsv)
for vmId in $vmList; do
   echo "$vmId"
   az network nic list --query "[?virtualMachine.id=='$vmId']".ipConfigurations[].privateIpAddress
done
```

**Expected behavior**
It should not handle case-sensitive.

**Environment summary**
Azure CLI version 2.0.43

**Comment by tjprescott** [comment]
If I understand correctly, the issue you are experiencing is that the VM IDs that comes back from VM list and the VM IDs that are associated with the NICs have different casing. Is that right?

The global `--query` argument uses the JMESPath query language. The fact that it is case sensitive is a property of the query language and not under our specific control.

**Comment by thuansoldier** [comment]
@tjprescott 

I tested by getting VM info using az vm list and NIC by az network nic list. The fact is that the resource ID gives case-sensitive differently

Below is from az vm list:
`id": "/subscriptions/XXXXXXXX/resourceGroups/**FOO-RG**/providers/Microsoft.Compute/virtualMachines/vm",`

and below is from az network nic list 

```
    "virtualMachine": {
      "id": "/subscriptions/XXXXXXXX/resourceGroups/foo-bar/providers/Microsoft.Compute/virtualMachines/vm",
```

Look at the resource group name. With this issue, when looking up NIC using VM ID it returns null.

**Comment by thuansoldier** [comment]
A workaround (perharp specific to my case to query private IP address) is to go with NIC resource ID and networkProfile property as follows:

```
vmNicId=$(az vm list --query "[?location=='westus']".networkProfile.networkInterfaces[].id -o tsv)
for nicId in $vmNicId; do
   echo "$nicId"
   az network nic list --query "[?id=='$nicId']".ipConfigurations[].privateIpAddress
done
```

**Comment by tjprescott** [comment]
Thanks @thuansoldier. I'll keep this issue open as the services should ideally be returning consistent casing for resource IDs.

**Comment by Drewm3** [comment]
The name of the resource groups returned through a VM List operation will always be upper-cased. This is the currently designed and expected behavior for VM List when no resource group is provided. When a resource group is provided then the response will use the casing of the resource group that was provided in the API.

The Resource URIs are not case sensitive. So when comparing any two resource URIs to determine if they are the same resource, then we recommend using a to_upper() or to_lower() function to get consistent casing of the URIs before the compare. Azure does not support two URIs that are exactly the same except for casing.
