### ISSUE TITLE
Azure CLI on Featured Server Snaps for Ubuntu

### ISSUE THREAD

**Issue by YoDaMa** [Azure/azure-cli#8421]
**Is your feature request related to a problem? Please describe.**

On the installation page for Ubuntu 18.04 Server Install there is a list of popular snaps to be quickly installed in server environments: 

![image](https://user-images.githubusercontent.com/8214060/52223922-98129380-285b-11e9-9377-02661c99dacf.png)

I noticed there is the aws-cli and google cloud sdk but nothing for azure. 

**Describe the solution you'd like**

Have azure-cli included on the list of snaps for quick installation when setting up a Ubuntu Server ISO.

**Comment by marstr** [comment]
Thanks for this feedback, @YoDaMa. This is something we've talked about internally, and even have a snap package [published](https://snapcraft.io/azure-cli) and [checked into our repository](https://github.com/Azure/azure-cli/blob/4b11d73a39822936033a137cf23f64452415f932/.snapcraft.yaml). Admittedly, this was driven by a developer who has since moved on (hence it being 1 year out of date.)

As a Fedora user myself, I would love to have our CLI available through Flatpak, Snap, and Appimage. However, for the moment, I think we'd like to use our resources to better support existing release channels. Issues like https://github.com/Azure/azure-cli/issues/7523 demonstrate some pretty real blind-spots for us.

I'm going to close this issue for now, because we don't currently have the intent to fix it. However, it's a great data-point for interest in the next generation of package-management. If people think it's important, and this gets a lot enough attention, we'll definitely re-open and re-evaluate.
