### ISSUE TITLE
Error color makes text unreadable

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-cli#8483]
**Describe the bug**
I cant read errors using the default console colors for windows 10. 
![image](https://user-images.githubusercontent.com/15381181/52522245-94fb1700-2c50-11e9-86fc-6af2867b3c93.png)

I expect to be able to read the error messages when displayed using the defaults for windows 10 console without having to resort to using screenshots and MS Paint's paintbucket to read them (like this) 
![image](https://user-images.githubusercontent.com/15381181/52522273-0c30ab00-2c51-11e9-8b19-000e2badef13.png)

**Environment summary**
Windows 10, usual updates. 

**Additional context**
Its also caused everything else typed into this prompt to now be unreadable, but I see that is a different bug reported here already.

**Comment by tjprescott** [comment]
On the Windows console, you can reset the color if it doesn't revert by typing `color 7`.

**Comment by StingyJack** [comment]
@tjprescott  - is the DarkRed color that is being displayed (that is _not_ in my console's settings for errors) coming from this utility or from Python?

**Comment by tjprescott** [comment]
Well, the colors are set from within the Knack library's logging methods. The implementation there uses the colorama library. There may be some platform differences there in how each color is interpreted (for example, the color for errors is designated as RED, not dark red). However, raw errors might be set by Python itself or otherwise be a property of the shell.

We could explore making the colors customizable in the config file. In the meantime, my suggestion would be to tweak your shell's background color to something that shows better contrast.

**Comment by StingyJack** [comment]
@tjprescott - found the Knack lib and piggybacked the [issue](https://github.com/Microsoft/knack/issues/71).

**Comment by tjprescott** [comment]
Yes, we also maintain knack, so thank you for opening the issue there. I'm not certain that that fix alone will address everything, but it should be a step in the right direction.

**Comment by adewaleo** [comment]
Conceptually, maybe we can add an option to `az configure` to update logging error / warning colors.

**Comment by jiasli** [comment]
Duplicate of #6080

**Comment by jiasli** [comment]
This issue has been fixed. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.
