### ISSUE TITLE
Missing PyPI packages for v2.0.58

### ISSUE THREAD

**Issue by dbaio** [Azure/azure-cli#8537]
Hi.

There aren't available PyPI packages for version 2.0.58.

I packaged azure-cli for FreeBSD and I noticed that our track system ([portscout](https://portscout.freebsd.org/dbaio@freebsd.org.html)) didn't find this new version.

We fetch packages from PyPI like this way:

https://files.pythonhosted.org/packages/source/a/azure-cli/azure-cli-2.0.57.tar.gz

And that's the way we track for upstream updates (guessing new versions).

Thank you for your time.

Regards.

**Comment by tjprescott** [comment]
When I run `pip install azure-cli` I get version 2.0.58 with all the appropriate modules. All of the packages do appear at PyPI.org.

**Comment by tjprescott** [comment]
@marstr did we change anything about what we publish with twine?

**Comment by dbaio** [comment]
Well, there is something strange, in the download page there aren't a .tar.gz file.

See this:

https://pypi.org/project/azure-cli-core/2.0.57/#files

https://pypi.org/project/azure-cli-core/2.0.58/#files

**Comment by marstr** [comment]
Hmmm, I handled the PyPI release process for both 2.0.57 and 2.0.58. I don't believe that there was any difference in procedure. Let me investigate.

**Comment by marstr** [comment]
I've mitigated this issue by downloading the PyPI artifacts from the [2.0.58 build](https://dev.azure.com/azure-public/azcli/_build/results?buildId=3173) and using twine to upload all non-existing assets from my local machine.

I verified that the previous build [2.0.57 Build](https://dev.azure.com/azure-public/azcli/_build/results?buildId=3084) seems like it has the same artifact structure.

I did check the [most recent PyPI release logs](https://dev.azure.com/azure-public/azcli/_releaseProgress?_a=release-environment-logs&releaseId=12&environmentId=62). Like with 2.0.57, there were some gremlins in our new release system that had meant I had to execute this step manually from my machine. My guess is that when I executed twine I used a wildcard like `*.whl` instead of just `*` when I executed locally.

However, the gremlins from the release were tracked in issue #8507, and we should not have to resort to manual execution next time.
