### ISSUE TITLE
azure-cli-core update tabulate dependency pin

### ISSUE THREAD

**Issue by kapilt** [Azure/azure-cli#8567]
tabulate seems to be one of the only dependency pins in azure-cli-core
https://github.com/Azure/azure-cli/blame/dev/src/azure-cli-core/setup.py#L74

there's a newer upstream release with mostly bug fixes, based on historical updates, its unclear why there is a version pin <=  for this dependency since all of the others are gte style pins.

This causes problems for downstream users that are using this as a library and are trying to keep up to date on their dependencies. ie the same reasoning in https://github.com/Azure/azure-cli/pull/5985

**Comment by tjprescott** [comment]
Anyone who directly pip installs the CLI is recommended to do so only within a virtual environment, so the differences in dependencies would be a non-issue (that isn't why we recommend it, but it has that nice side effect). We can take a look at why the dependency is pinned and possibly update it.

**Comment by kapilt** [comment]
thanks, in this case the azure-core-cli is being used as a library and is a dependency for another package, to enable another cloud management cli to source credentials/config per the azure cli defaults as noted in #5985

**Comment by glaubitz** [comment]
@tjprescott I'm packaging the Python Azure SDK as well as the Azure CLI utilities for openSUSE and SUSE Linux Enterprise.

In order to be able to provide Public Cloud customers with professional support, we need to be able to package upstream software as RPM packages and hence it would be nice if this particular version constraint could be relaxed if necessary.
