### ISSUE TITLE
Release new version on snap store

### ISSUE THREAD

**Issue by guilhem** [Azure/azure-cli#8631]
**Is your feature request related to a problem? Please describe.**

Current snaps are pretty old:
```
channels:
  stable:    –                            
  candidate: 2.0.25 2018-01-19   (7) 16MB -
  beta:      2.0.30 2018-03-30  (35) 23MB classic
  edge:      2.0.38 2018-07-06 (399) 25MB classic
```

**Describe the solution you'd like**

Integration with https://snapcraft.io/build to auto-build new versions.

**Describe alternatives you've considered**

A process in CI to publish packages.

**Additional context**

If there is a problem with ownership, please ask on https://forum.snapcraft.io/c/store

**Comment by tjprescott** [comment]
Hi @guilhem thanks for the report. We are working with the relevant folks to get this release channel properly maintained.

**Comment by marstr** [comment]
I'm going to unassign myself and @achandmsft from this, because the time line for this work is unclear.

**Comment by yonzhan** [comment]
add to S164.

**Comment by nzbart** [comment]
Is there any reason that there isn't a stable version published via snap? Are the current published versions safe to use for production code?

**Comment by deephack1982** [comment]
Hello Azure team! I would much prefer to use the snap package for the Azure CLI and I have time to maintain this package if you would like a hand?

**Comment by rcj4747** [comment]
I see that the newest snap in the edge channel is 2.0.38 from July 2018.  Any progress on making snap releases part of your process?

The [install docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) tell me not to use the version in Ubuntu because 2.0.81 is too old, making the snap ancient.  And I don't care for the instruction to run `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` as it seems just piping a script from the internet to bash as root is an abhorrent security anti-pattern.  Alternatively I can add your key and trust your entire deb repo, which is also more than I'd like; a user should be directed to add an apt preferences file to pin the repo so only azure-cli is installed from that repo.

**Comment by gaui** [comment]
Any update on this?

**Comment by jiasli** [comment]
Snap is not supported anymore and we don't have a plan to release on snap again. Thanks for your understanding.

**Comment by jiasli** [comment]
Hi @rcj4747,

> And I don't care for the instruction to run `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` as it seems just piping a script from the internet to bash as root is an abhorrent security anti-pattern.

I fully understand your concern. We will discuss internally for how to deal with it.

> a user should be directed to add an apt preferences file to pin the repo so only azure-cli is installed from that repo.

Could you share the detailed steps or the preferences file you want us to use? We can definitely consider including that in our doc.

**Comment by gaui** [comment]
> Snap is not supported anymore and we don't have a plan to release on snap again. Thanks for your understanding. 

Then why not close this ticket?
