### ISSUE TITLE
Create CLI commands for Azure Functions Premium plan scale out

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-cli#8659]
As part of the Azure Functions premium plan, I'd like to provide support for a few management commands when managing your plan.

## Operations on the app

`az functionapp` ideally would have a `config` or similar option that would let me set how many "pre warmed instances" the app has.  This is a setting that enables you to keep your app always warm on a certain number of instances.  

You can do this today via `az resource` like below:

```bash
az resource update --resource-type Microsoft.Web/sites -g <resource_group> -n <function_app_name>/config/web --set properties.reservedInstanceCount=<desired_prewarmed_count>
```
though note that the property is being renamed to `preWarmedInstanceCount` instead of `reservedInstanceCount`

## Operations on the plan

`az functionapp plan` would have the ability to control the scale.  There are 2 settings specifically

1. Minimum instances - this is the plan size, the minimum number of instances you always have reserved.  Can be a value between 1-20
1. Maxiumum burst instances - this is set currently by modifying the `maximumElasticWorkerCount`.  This is how many instances your app can scale up too.  Today the limit is 1-20, but plan is to make it 1-100 in coming weeks.    Can currently do today with `az resource` like below:

```bash
az resource update --resource-type Microsoft.Web/serverfarms -g <resource_group> -n <premium_plan_name> --set properties.maximumElasticWorkerCount=<desired_max_scale_out>

```

**Comment by ahmedelnably** [comment]
@jeffhollan for the Plan operations, I am assuming that at creation time there will be 3 values (exact names TBD)
`--number-of-workers`  <-- already there
`--min-worker-count`
`--max-worker-count`

Do we also need an update command? `az functionapp plan update` to update the min/max-worker-count

**Comment by ankitkumarr** [comment]
Would you know what site property refers to `--min-worker-count`? For an app service plan, I see a `maximum_number_of_workers`, `number_of_sites` and `target_worker_count`. 

Or if you already know a way to change min worker count, I can look at that too.

**Comment by jeffhollan** [comment]
Plan only has 2 properties.  Min instance count (which is really just number of workers.. in the UX for premium we just call it minimum instances), and the maximum instances.  This maps to the plan property `properties.maximumElasticWorkerCount`

**Comment by ankitkumarr** [comment]
Thanks @jeffhollan for the clarification.

From what I got, these are the commands and restrictions I am creating-

New Commands:
1. `az functionapp config --reserved-instance-count`
2. `az functionapp plan create --number-of-workers/--min-elastic-worker-count --max-worker-count`
3. `az functionapp plan update --number-of-workers/--min-elastic-worker-count --max-worker-count`
4. `az functionapp plan list` and `az functionapp plan delete` because those seem to be missing.

Restrictions:
1. `--max-worker-count` on create and update only if `--sku` Premium (or Elastic Premium?)
2. `--max-worker-count` and `--min-worker-count` need to be between 1 and 20.
3. [question] Any restriction on `--reserved-instance-count`? Or do we allow modifying this setting on any function app?

@ahmedelnably / @jeffhollan / @alexkarcher-msft , I would love it if you could have a quick look and verify or add on any additional commands/flags needed.

**Comment by jeffhollan** [comment]
Correct.  A few notes:

- Should be `--prewarmed-instance-count` instead of `--reserved-instance-count`
- Restriction is accurate - sku I believe is `ElasticPremium` and sizes are `EP1` `EP2` and `EP3`
- prewarmed instance count must be <= 20

**Comment by ankitkumarr** [comment]
Thanks Jeff, wasn't sure if we wanted to start with `--prewarmed-instance-count`. Makes sense.

**Comment by ankitkumarr** [comment]
Discussed offline with @alexkarcher-msft and @ahmedelnably , calling the params `--max-burst` and `--min-instances` consistent with the portal.

Also, adding a check for `--pre-warmed-instances` <= `plan.properties.maximumElasticWorkerCount`

**Comment by vigneshshankar1904** [comment]
@jeffhollan 

Hi Jeff.. Do we have any updates on the max prewarmed instance count?? I see from your earlier comment that there was a plan to make it 1-100. But when I tried setting the --max-burst to more than 20 through Azure CLI, I get this error:

`Usage error: --max-burst is expected to be between 0 and 20`

Any help would be appreciated. Thanks!
