### ISSUE TITLE
Enabling network rule on storage account using az cli disables encryption on storage 

### ISSUE THREAD

**Issue by sajithvasu** [Azure/azure-cli#8715]
Hello,
az cli removes existing encryption on storage account when network firewall rules are added.  This is a consistent behavior with mostly all the version of az cli.  I have tested on windows and linux. 

Steps to reproduce the behavior.
a) Create Storage account
b) Enable encryption on storage by using encryption key created on keyvault.
c) run storage account network command.
az storage account update --resource-group <rg_name> --name <storageaccountname> --default-action Deny
az storage account network-rule add --resource-group <rg_name> --account-name <storageaccountname> --ip-address x.x.x.x/x

**Comment by williexu** [comment]
@sajithvasu the issue is actually with the `storage account update` command, not actually the adding of network rules. 
The update command had some very faulty logic that was ignoring encryption parameters in various scenarios and replacing them with null values with a `Microsoft.Storage` key source. https://github.com/Azure/azure-cli/pull/8740 fixes this problem.
