### ISSUE TITLE
webapp: az webapp up - Add better error messages to report the failure cause & re-try instructions

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#8833]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by raahmed** [comment]
**Describe the bug**
Currently, when re-deploying an existing app using `az webapp up -n <app_name>`, an error message appears that says that 'The app <app_name> already exists'. There are no details in the error message on what must be done to re-deploy the app.

**To Reproduce**

1) Create an Azure Web App and deploy using `az webapp up -n <app_name>`
2) Make some changes to the app.
3) Attempt to redeploy, again using `az webapp up -n <app_name>`.
4) Notice the following error message:

![image](https://user-images.githubusercontent.com/25991359/54946973-78602900-4ef6-11e9-9b51-43bf8177b97c.png)

**Expected behavior**
1) Instead of the error message above, the app should either re-deploy or should explicitly inform the user on what changes must be made to the cli command in order to re-deploy.

**Environment summary**
VS Code 1.32.3
Mac OS Sierra v 10.12.6
Using VS Code's built-in Terminal
Azure CLI v. 2.0.60 installed using brew.

**Comment by yugangw-msft** [comment]
#9125 fixes it
