### ISSUE TITLE
az aks install-cli fails in WSL on Windows 10

### ISSUE THREAD

**Issue by tanmoycuat** [Azure/azure-cli#8867]
Error

Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl"
Connection error while attempting to download client ([Errno 1] Operation not permitted: '/usr/local/bin/kubectl')

**Comment by tanmoycuat** [comment]
Error as below

Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl"
Connection error while attempting to download client ([Errno 1] Operation not permitted: '/usr/local/bin/kubectl')

**Comment by adewaleo** [comment]
@tanmoycuat, can you give more context? Like the command you ran. It's good to give as much relevant info as possible. Please also add what version of the CLI you are on.

**Comment by tjprescott** [comment]
Please provide all of the information requested in the issue template:

======

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by Serenya** [comment]
I've faced with similar error. On my Win10 under WSL based on Ubuntu 18.04, azure cli version 2.0.62.
When I run **sudo az aks install-cli**, I get:

```
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
```

**Comment by Serenya** [comment]
Actually message `Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.` is just an information. Kubectl command works!

**Comment by joetortorelli** [comment]
> Actually message `Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.` is just an information. Kubectl command works!

I am a derp. Thank you for this. I had assumed this message was an error.

**Comment by seanmck** [comment]
As mentioned, this is a permissions issue. Running with sudo should work. We will update the docs to call that out, but closing this as there's no action on CLI.
