### ISSUE TITLE
Description for --use-cert-sn-issuer doesn't make sense

### ISSUE THREAD

**Issue by dsparkplug** [Azure/azure-cli#8875]
Can somebody explain what "Used with a service principal configured with Subject Name and Issuer Authentication in order to support automatic certificate rolls." means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@yugangw-msft @marstr can you clarify this?

**Comment by yugangw-msft** [comment]
This is a bit complex, so let me explain here 
1. The AAD Tenant the service principal comes from only accepts certain issuers (AME) which have strict association of subject name and requester.
2. Once the organization as the requester register the domain like `contoso.com` with AME CA, no one else can get it
3. This the foundation of SN/Issuer trust. Rather than trusting the thumbprint, you’re trusting that the CA vouches for me as the only one who can generate certs for that subject name.
4. W/o thumbprint involved, certificate auto-rolls becomes simpler because you don't need to update the service principal with new thumbprint from time to time.

Hope this clarifies. Please let me know if you have any further questions.

**Comment by xkszltl** [comment]
This is very helpful, but can it be documented in the help msg?
