### ISSUE TITLE
Allow Function Apps to change plan

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-cli#8913]
This command would allow you to change a Function App from a consumption to a premium plan.

The command would be something akin to:

Parameters:
-	SourceApp (the details for a function app already deployed)
-	DestinationPlan (the details for a plan you want to move it to - this likely needs to be in the same resource group so we don’t get into stamp incompatibility issues - or just make sure we have a warning if it fails because that plan is incompatible)

Steps:
1.	Get the resource ID of the destination plan /Microsoft.Web/serverfarm
2.	Update the Microsoft.Web/sites resource for the function app plan.
a.	Properties.serverFarmId should be set to the resource ID from step 1

Ideally the command should validate that the sourceapp plan is consumption / premium (via the SKU of the plan), and that the destination plan is consumption / premium.  Moving between ASP and consumption / premium may work but you need tom ake sure the WEBSITE_CONTENT_CONNECTIONSTRING / CONTENTSHARE settings are set before you do (by default dedicated won’t have these, you need them for consumption / premium

**Comment by alexkarcher-msft** [comment]
Looks like I don't have any permissions to add an assignee to this repo :(
Tagging @ankitkumarr @ahmedelnably @jeffhollan who are all in some way responsible for this 😃

**Comment by ankitkumarr** [comment]
> Moving between ASP and consumption / premium may work but you need tom ake sure the WEBSITE_CONTENT_CONNECTIONSTRING / CONTENTSHARE settings are set before you do (by default dedicated won’t have these, you need them for consumption / premium

If it's not an important feature/ask to move between ASP and consumption / premium, I would suggest we don't do that. Because in the flow, I would have to update WEBSITE_CONTENT_CONNECTIONSTRING / CONTENTSHARE settings before switching the plan. After updating the settings, if plan switching failed due to other reasons, we may leave the app in a broken state. 

That said, if we do need this, I can add a check to see if it failed and remove the added app settings appropriately. Unless necessary, I wouldn't want to do that.

**Comment by jeffhollan** [comment]
More than ok with use moving the ASP - > consumption / premium out of scope
