### ISSUE TITLE
`az aks-get credentials` and generated name of the context in kube config

### ISSUE THREAD

**Issue by wlodekb** [Azure/azure-cli#8934]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have clusters with the same name in various RGs and do `az aks get-credentials -g <rg-name> -n <cluster-name>`
In the current solution, context name is generated only from `cluster name`, so you need to edit context names in kube config manually every time

**Describe the solution you'd like**
An Ideal aproach could be:
`az aks get-credentials -g <rg-name1> -n <cluster-name>` --> context_name : `cluster_name-rg-name1`
`az aks get-credentials -g <rg-name1> -n <cluster-name>` --> context_name : `cluster_name-rg-name2`

**Describe alternatives you've considered**
Or there can be additional param in `az aks get-credentials` command for set `context` name in kube-config. Like `--context-name`?

**Comment by guanwening** [comment]
[guanwening](url)

**Comment by fredgate** [comment]
Yes it is very frustrating. I have sevreal resource groups each containing a k8s cluster with the same name. So I can not have several kubernetes contexts, because they will have the same name. A simple option could be to add an optional paramater to `az aks get-credentials` that specifies the name of the context to create (if the parameter is not specified, the actual behaviour can be preserved.
So we could register cluster as it :
```
az aks get-credentials -n k8s -g kube1 --context az1
az aks get-credentials -n k8s -g kube2 --context az2
```
It would be nice :-)

**Comment by worldspawn** [comment]
What exactly happened here?? running 2.2.0
```
az aks get-credentials -n xxname -g xxgroup --context sectest
A different object named clusterUser_xxgroup_xxname already exists in your kubeconfig file.
Overwrite? (y/n):
```

`--context` appears to do absolutely nothing.

**Comment by worldspawn** [comment]
Ah its works after I remove the original context that i didn't specify the name of.
