### ISSUE TITLE
Parameter accepts different values within the same module

### ISSUE THREAD

**Issue by glGarg** [Azure/azure-cli#8943]
**Describe the bug**
For command 'storage queue generate-sas', the parameter '--https-only' is a stored parameter (doesn't accept any values). In the same module, 'command storage account create' has a parameter '--https-only' which is a three state flag. In order to stay consistent to all commands in this module this parameter should either be stored or three state flag.

**To Reproduce**
Steps to reproduce the behavior.
No steps needed.

**Expected behavior**
No a runtime issue.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
No install required.

**Additional context**
https://github.com/Azure/azure-cli/blob/d1c0c406d3ec42e496770fc3f81f53de06e4b18c/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py#L49

**Comment by limingu** [comment]
@glGarg this is a very good point. I have checked our code base. '--https-only' is mostly used as three state flag in the storage module. Only for sas generation, '--https-only' is used as a stored parameter. That is the code above to use as 'protocol' argument. That is because the sdk function generate_shared_access_signature needs this parameter. It is related to '--https-only' but not exactly same. We are using the same name and caused some confusion.

If more customers want to change that, we can do that. But that will be a break change as we have to use a new parameter name such as '--protocol' to differentiate from the '--https-only'.

For now, we will still keep this way. Thanks.
