### ISSUE TITLE
webapp:moreSettings.json undocumented and GitHub comments are wrong.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-cli#8985]
The correct format for 'moreSettings.json' is a JSON array in this format:

```json
[
  {
    "name": "MY_APPSETTING_ONE",
    "value": "SomeValue",
    "slotSetting": false
  },
  {
    "name": "MY_APPSETTING_TWO",
    "value": "AnotherImportantValue",
    "slotSetting": false
  }
]
```
This was discovered using the new bulk edit option in the new Configuration Blade in the Portal. Please document to save others time!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by a9261** [comment]
does anyone can help me .  how to use --settings @moreSettings.json ? . i use  this on powershell . always show the error

**Comment by pratap-dotnet** [comment]
It does work with powershell, the syntax is --settings "@moreSettings.json"

**Comment by panchagnula** [comment]
This  {
    "name": "MY_APPSETTING_TWO",
    "value": "AnotherImportantValue",
    "slotSetting": false
  } i.e "slotSettings" is a portal concept & not a platform or API level format so don't use this for CLI. For CLI just use a name value pair. Thanks!

**Comment by joaopgrassi** [comment]
How come this is not documented? I just spent almost ah hour bashing my head because:

- I don't know the JSON format expected for `@settings.json`
- Calling `az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings mySetting=value @moreSettings.json` in Azure CLI (poweshell) throws an error. The exact command which is in the docs

I had to come to this ticket to:

- Know that the format of the JSON file can just be:

```
{
  "mySetting": "some-value",
  "mySetting2": "some-value",
  "mySetting3": "some-value",
}
```
instead of (see @panchagnula comment above)

```
{
    "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
    "value": "1.0.0",
    "slotSetting": true
  }
```
- That it's not `@settings.json` like it's in the docs, but "@settings.json". 

Can someone please fix this in the docs, and also in the helpers for `az webapp config appsettings set --help`?

**Comment by Cre8ivE-OnE** [comment]
Documentation seriously needs to be update to reflect @joaopgrassi 's comment.
