### ISSUE TITLE
powershell --query error

### ISSUE THREAD

**Issue by ArgTang** [Azure/azure-cli#9047]
**Describe the bug**
When not putting space in --query clause, cli will not work. If ignoring powershell formatting with --% same command works

**To Reproduce**

Using powershell 5.1
```powershell
$value = "searchingforsomevalue"

# dontwok
az keyvault secret list --vault-name "myvault" --query "[?contains(id,'$value')].{id:id}
# > ].{id:id} was unexpected at this time.  

# works
az keyvault secret list --vault-name "myvault" --query "[?contains(id,'$value')].{ id: id }

az keyvault secret list --vault-name "myvault" --query --% "[?contains(id,'searchingforsomevalue')].{id:id}

```

**Expected behavior**
While invoking the command it should return values from keyvault. Or give better errormessage

**Environment summary**
win10   
powershell 5.1  
az cli version 2.0.60

**Comment by tjprescott** [comment]
```
Azure:/
PS Azure:\> az group list --query "[?contains(name, '$value')].{id:id}"
[
  {
    "id": "/subscriptions/c9cbd920-c00c-427c-852b-8aaf38badaeb/resourceGroups/tjp-rg"
  }
]
Azure:/
PS Azure:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      0
```

You might try using PS 6.2, but since this is a shell issue, it occurs before the input ever reaches the CLI and thus there is nothing in the CLI we can do to mitigate this.

**Comment by RobertoBorges** [comment]
Confirmed the problem is on the Powershell :

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1         18362    628

**Comment by ChristopherEquinor** [comment]
I get this error due to OS differences, not PowerShell versions.

I can recreate a similar issue with identical PowerShell versions.

####  PSVersion 7.0.3 on Windows 10

 I run `az ad app list  --query "[?contains(displayName,'$value')].objectId"`, and get the error `].objectId was unexpected at this time.`

#### PSVersion 7.0.3 on Linux 4.15.0-1095-azure (Azure Cloud Shell)
 I run `az ad app list  --query "[?contains(displayName,'$value')].objectId"`, and it works.

**Comment by jiasli** [comment]
I able to repro it in PowerShell 7:

```powershell
> az ad app list --query "[?contains(displayName,'$value')].objectId"
].objectId was unexpected at this time.
```

This is a [known issue of PowerShell terminal](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md) to strip double quotes when calling native executable files (`C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd` in this case), and comma (`,`) is parsed as a [delimiter](https://ss64.com/nt/syntax-esc.html) by CMD. 

To workaround it, you may either add another pair of double quotes to feed into CMD:

```powershell
az ad app list --query "`"[?contains(displayName,'$value')].objectId`""
                        ^^                                          ^^
```

Or simply add a whitespace to force PowerShell to pass double quotes to CMD:

```powershell
az ad app list --query "[?contains(displayName,'$value')].objectId "
                                                                  ^
```

**Comment by jamcguire** [comment]
Hi there, I had this same issue myself and it took me a while to understand where I had gone wrong, just to point out the reason it's happening is because in your contains clause there is no space after the comma, your original statement:

az keyvault secret list --vault-name "myvault" --query "[?contains(id,'$value')].{id:id}

Should instead be formatted with an extra space after "?contains(id," , as such:

az keyvault secret list --vault-name "myvault" --query "[?contains(id, '$value')].{id:id}

And it will most likely work now.
