### ISSUE TITLE
Automate  Azure Bot registration channel with Azure CLI 

### ISSUE THREAD

**Issue by prathiparaj** [Azure/azure-cli#9184]
Below are the Azure CLI commands which am using to create bot channel registration.

az ad app create --display-name "TestBot" --homepage "https://testbot" --identifier-uris "https://testbot" --password "123adfaesdf" --end-date 2100-12-12

az bot create --resource-group "BotTest-RG" --kind "registration" --description "description-of-my-bot" --name "BotTest" -e https://pratbotreg.com --appid 2b6581ac-f****-4***-9**d-3124b8442420 --password KzxDnTnM3vsK2DyHSZ3WA4mo53ToB/DtYwc7MSkivH0=

az bot directline create -n testbotprat -g BotTest-RG --disablev1

Here am manually entering the values for all the parameters like --display-name, --password, --appid. Instead I need to get the values in the variable and use the variable instead of actual values(which we can use the variable in PowerShell).

**Comment by adewaleo** [comment]
@prathiparaj, what exactly is the problem, issue or question?

**Comment by tjprescott** [comment]
If you looking for general advice on how to work with Powershell variables, this is not the appropriate forum, but you will find plenty of tutorials on the web. If you are looking to work with Powershell objects explicitly, you should should consider using the Azure Powershell cmdlets at https://github.com/Azure/azure-powershell.

**Comment by sproloy** [comment]
how to store values in variable in Azure CLI?

Something like below we use in powershell:
$name =”myname”

**Comment by sproloy** [comment]
I posted a query? why is this thread closed?!  can I have a reason?

**Comment by adewaleo** [comment]
I believe @tjprescott closed this thread because of this:
> If you looking for general advice on how to work with Powershell variables, this is not the appropriate forum, but you will find plenty of tutorials on the web. If you are looking to work with Powershell objects explicitly, you should should consider using the Azure Powershell cmdlets at https://github.com/Azure/azure-powershell.

We generally address Azure CLI specific issues not shell-specific issues.

Regarding your question. The CLI is platform independent and accepts only string parameters. Because linux commands don't have the concept of objects as in powershell.

In linux shells you can store strings in variables as so and reference them, like so:
```
tosin$ my_rg="ova-test"
tosin$ az group show -n $my_rg
```

I am not as familiar with variables in cmd.exe, but you can search online. Here is a [guide](http://steve-jansen.github.io/guides/windows-batch-scripting/part-2-variables.html) I found on using cmd variables.
