### ISSUE TITLE
az network public-ip create --public-ip-prefix should default to standard sku

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#9227]
**Is your feature request related to a problem? Please describe.**
az network public-ip create \
 --resource-group rg \
 --name pip \
 _**--public-ip-prefix prefix**_

results in

PublicIPAddress SKU Name: Basic cannot be different from referenced PublicIpPrefix SKU Name: Standard for PublicIpAddress /subscriptions/foo/resourceGroups/rg/providers/Microsoft.Network/publicIPAddresses/pip.

**Describe the solution you'd like**
this should always default to Standard SKU since there are no plans to support prefix for Basic SKU public ip.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by tjprescott** [comment]
@christiankuhtz is there any reason the service doesn't simply default the SKU to Standard instead of throwing an error?  I removed the code in the CLI that was explicitly setting a default of "Basic" but I get the same error, implying the service is choosing Basic as the default.
```
msrest.http_logger : Request body:
msrest.http_logger : {"location": "westus", "properties": {"publicIPAllocationMethod": "Dynamic", "publicIPAddressVersion": "IPv4", "publicIPPrefix": {"id": "/subscriptions/xxxx/resourceGroups/tjp-rg/providers/Microsoft.Network/publicIPPrefixes/prefix1"}, "idleTimeoutInMinutes": 4}}

...

PublicIPAddress SKU Name: Basic cannot be different from referenced PublicIpPrefix SKU Name: Standard for PublicIpAddress /subscriptions/c9cbd920-c00c-427c-852b-8aaf38badaeb/resourceGroups/tjp-rg/providers/Microsoft.Network/publicIPAddresses/pip.
```

I could do this in the CLI, but we prefer to allow the service to control defaulting behavior so that if it changes we aren't overriding it.  Thoughts?

**Comment by MyronFanQiu** [comment]
@christiankuhtz Hello. Any update? Does this feature request still need to be implemented?
