### ISSUE TITLE
Docker image missing dependencies needed for Azure Artifacts

### ISSUE THREAD

**Issue by zarenner** [Azure/azure-cli#9276]
The azure-cli docker image is missing two dependencies required for Azure Artifacts "az artifacts" commands which use .NET Core based tooling.

Specifically, the (.NET Core) dependencies `libintl` and `icu-libs` are required. 
Currently, a user wanting to use the Azure Artifacts commands has to run:
```
apk update
apk add libintl icu-libs
``` 

Would it be acceptable to add these dependencies? If so, I'll send out a PR.

See https://github.com/Azure/azure-devops-cli-extension/issues/217 for additional context

**Comment by marstr** [comment]
@zarenner, thanks for asking. We would absolutely accept this PR.

In general I would like to move our alpine image slimmer rather than adding new dependencies. However for the moment, we are still aiming to fully support this CLI in this image. There may be a day where we split our container story in two, with a 'big' (based on Ubuntu) and 'small' (based on Alpine) package with slightly different audiences in mind. This is likely one more vote for that to happen.

**Comment by marstr** [comment]
Fixed by #9683.
