### ISSUE TITLE
I had a question about the az login, is that just OAuth2 Authorization Code flow?

### ISSUE THREAD

**Issue by VictorioBerra** [Azure/azure-cli#9303]
I noticed the CLI starts a web server, and listens for the browser to reply with the code before it can turn around and get a token using the code.

Is that just regular Authorization Code Flow? If so, do you guys just register that range of locahost and ports as valid redirect urls? I figured the redirect uri was an important part of the OAuth2 spec so im not sure how the user agent would redirect.

Device code flow would be my next guess, but that involves polling the server until it replies with a token (once the user confirms the code).

And my last guess is a custom grant type in which case im not sure the process at all.

I ask as an IdentityServer4 user looking to implement something similar for my users. I dont want to use Auth Code Flow since they explicitly advise against it in the docs, I dont want to use Resource Owner grant since that is also explicitly advise against, my next best bet seems to be Device Code Flow using the `verificationUrlComplete` to fire a process that opens the browser and lets the magic work.

Thanks

**Comment by yugangw-msft** [comment]
Yes, it is just `OAuth2 Authorization Code flow` 

    If so, do you guys just register that range of locahost and ports as valid redirect urls?
AAD supports `any ports`, so with the same host name, any ports will be valid; hence a range is not required.

I can understand `Resource Owner Grant` is not recommended because your users are passing credentials to your app, so they have to fully trust your app is not a malware. Rule of thumb is your credentials should only be circulated between you and your identity provider (like AAD, Facebook, Twitter, etc) 

`Auth Code Flow` is the most popular authentication flow and almost every web applications are using it if an oauth identity provider is involved.

Hope this helps. I am closing this since I have answered your questions, and there are no CLI issues involved here...
