### ISSUE TITLE
What does --properties do?

### ISSUE THREAD

**Issue by v-kydela** [Azure/azure-cli#9307]
And how do we use it?

I'm trying to get `az bot update` to work, but even following the example `az bot update -n botName -g MyResourceGroup --set properties.description="some description"` (with my own bot name and resource group) I can't get the command to work. It returns the bot's info so I know I'm logged in and it's finding the bot resource. It's just that the bot resource never changes. I can't even update its description.

Whenever I try `--properties` it throws an error and tells me to file a bug report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55111b1f-ca0d-0eb9-7457-3cdee47a6804
* Version Independent ID: 9442f477-20be-a67b-a38a-1846dc3cfbc4
* Content: [az bot](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-update)
* Content Source: [src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py)
* Service: **bot-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@stevengum for comment

**Comment by stevengum** [comment]
This is no longer relevant as in the May 6, 2019 (version _2.0.64_) release of Azure CLI we updated the command to specifically target properties instead of giving the ability to seemingly modify/add any property (which is not actually possible, some properties are readonly).

Now to [update](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-update) the description of a bot, you would use `az bot update -n botName -g MyResourceGroup --description "some description"`

The available properties of the bot that you can configure can be seen through the link provided or through typing `az bot update -h`
