### ISSUE TITLE
az bot create fails with site_name referenced before assignment

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli#9309]
## Describe the bug
Ran az bot create command at Azure CLI 2.0.63. Command failed.

**Command Name**
`az bot create`

**Errors:**
```
local variable 'site_name' referenced before assignment
Traceback (most recent call last):
Temp\pip-install-68v0_w99\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 523, in execute
azure\cli\core\commands\__init__.py, ln 581, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 574, in _run_job
Local\Temp\pip-install-68v0_w99\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 551, in _run_job
azure\cli\core\commands\__init__.py, ln 289, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 453, in default_command_handler
azure\cli\command_modules\botservice\custom.py, ln 136, in create
azure\cli\command_modules\botservice\bot_template_deployer.py, ln 153, in create_app
UnboundLocalError: local variable 'site_name' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bot create -n {} -l {} -g {} -k {} --appid {} -p {} -v {} -s {} --lang {} --verbose`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63

Extensions:
interactive 0.4.1

```

**Comment by stevengum** [comment]
@plzm, this bug was fixed in azure-cli 2.0.64. Please upgrade and try to run the command again.

**Please note** that there are a number of breaking changes in the `0.2.0` release of `az bot`. One of which being, that `--storage` is no longer used when creating v4 bots, and that for v4 bots, you must provide the `--echo` flag if you wish to have the old v4 echo bot provisioned when calling `az bot create -v v4`.

To see a full list of the breaking changes, please see the [`HISTORY.rst`](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-botservice/HISTORY.rst).
