### ISSUE TITLE
Trying to start vm with invalid resource group name should return helpful error message

### ISSUE THREAD

**Issue by codedevote** [Azure/azure-cli#9310]
Several times, I was calling 'az create vm' command and providing an invalid resource group name (i had a dash too much in the name). Instead of telling me, that the resource group has not been found/is invalid, I get an error message leading me into the wrong direction (permission related problem):
ERROR: The client 'SOME_GUID_HERE' with object id 'SOME_GUID_HERE' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/start/action' over scope '/subscriptions/SOME_GUID_HERE/resourceGroups/NAME_OF_RESOURCE_GROUP_HERE/providers/Microsoft.Compute/virtualMachines/NAME_OF_VM_HERE'.

**Describe the solution you'd like**
An error message telling me, that the resource group I provided does not exist (due to typo).

**Comment by yugangw-msft** [comment]
@codedevote, I can't reproduce this. `VM create` has a few pre-validations which include checking the resource group does exist. Can you please provide more details such as using `--debug` for the full trace?

**Comment by adewaleo** [comment]
To add, following this template as much as possible would be helpful for you and us in solving this problem:

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by codedevote** [comment]
Sorry for not providing all required details. I was now trying to collect the missing pieces and tried to reproduce it again. I was actually working in Azure CloudShell here. I tried minutes ago and I now get the expected error message 'Resource group XYZ could not be found'. Not sure what caused the error last time, I am currently not able to reproduce it as well. I will close this one and file a new issue should I stumble across this again.

**Comment by adewaleo** [comment]
That's strange. It could very well have been a service side issue, but I guess we might never know. I am happy you aren't having the issue anymore.
