### ISSUE TITLE
Allow creating a service plan as part of web app creation

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-cli#9315]
**Is your feature request related to a problem? Please describe.**
App Service is frequently used as a deployment target for apps in quickstarts, tutorials and learning content. Often, the act of creating a web app and deploying to it is not the focus of the content, and so any technique that minimizes the time and effort required to do so really helps keep the content focused. When web app creation is done from the CLI, the need to first run a separate command to create an App Service plan is distracting.

**Describe the solution you'd like**
Allow `az webapp create` to automatically create a new App Service Plan, similar to the way `az webapp up` does.

**Describe alternatives you've considered**
None.

**Additional context**
This is essentially a dupe of #1369 (which I [commented on](https://github.com/Azure/azure-cli/issues/1369#issuecomment-483499731) in an attempt to resurrect), which is over two years old. It actually resulted in an implementation that was [backed out](https://github.com/Azure/azure-cli/pull/2671) shortly after it was introduced. A lot has changed since then, including the introduction of `az webapp up`, which seems to have found an acceptably ergonomic way to implement this functionality, although it comes in a different shape and provides functionality that is out of scope relative to what I'm looking for here.

**Comment by tjprescott** [comment]
@yugangw-msft @panchagnula who have more context on this.

That change was backed out because the VP of Azure did not want CLI commands hiding the necessary infrastructure that backs webapps. It is the same reason we do not allow create commands to create the specified resource group if it does not already exist, or to auto-create a resource group if not specified.

The fact that `webapp up` creates a plan is not a precedent to point to for allowing `webapp create` to do the same thing. The `up` commands are convenience command for getting people up and running quickly. The management plane CRUD commands are intended for mainline script and devops scenarios, and it is expected that these individuals know and understand the infrastructure they are building (and being billed for).

**Comment by panchagnula** [comment]
@nickwalkmsft please try the command az webapp up this will Create RG, ASP & App plus use Zip Deployment to deploy code to you app. https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up

**Comment by nickwalkmsft** [comment]
Thanks for the context @tjprescott, that makes perfect sense. I will close this out.

@panchagnula `az webapp up` is a really close fit for my scenarios, but the inability to target an existing resource group makes it unusable in the target environment (Microsoft Learn sandbox, where the user has permissions to only one pre-created RG). I will play with it a little more and may open a feature request related to that.

**Comment by panchagnula** [comment]
@nickwalkmsft we did add the ability to support existing RG & Plans, looks like the online documentation isn't completely updated please do a az webapp up -h & you will find the --plan argument & the -g arguments supported with the most recent release version of azure-cli

**Comment by nickwalkmsft** [comment]
@panchagnula That's perfect! `--resource-group` is exactly what I needed. Thanks!
