### ISSUE TITLE
Create Web App Bot using dependent resources - storage, application insights, app service, and app service plan

### ISSUE THREAD

**Issue by PrajithB** [Azure/azure-cli#9378]
I'm trying to create a web app bot using CLI. The 'az bot create' command gives options to specify the app ID, password and storage account name. The 'az bot update' command gives option  --ai-api-key --app-insights-api-key to bind the application insights. I tried figuring out a way to configure an app service and its app service plan. Let me know please if there's a method in CLI and in AZ powershell as well.

**Comment by stevengum** [comment]
@PrajithB and @KevinBrooke if you want to update the App Service and its App Service Plan, these are configurable using the following command modules:

 - `az webapp`: https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest
 - `az appservice`: https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest

Since these are distinct resources on Azure, `az bot` doesn't support _updating_ them, it only provisions the resources on `az bot create`.

**Comment by stevengum** [comment]
Closing this issue as the answer was provided in this [comment](https://github.com/Azure/azure-cli/issues/9378#issuecomment-497395690). To upgrade/update the settings on the App Service or App Service Plan via the CLI, use `az webapp` or `az appservice`.
