### ISSUE TITLE
storage container create permission issue

### ISSUE THREAD

**Issue by awysza** [Azure/azure-cli#9396]
## Describe the bug
Running CLI command to create container name results in an error implying the permissions is missing.
`az storage container create -n {} --sas-token {} --account-name {}`

However I am Owner on the Subscription and as such have full rights, including data plane. In addition, I have added explicitly myself to a RBCA role "Storage Blob Data Contributor (Preview)" (in addition to being an Owner on a subscription). This resulted in the same error.
repro steps below.

**Command Name**
`az storage container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v1m4qsu_\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v1m4qsu_\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v1m4qsu_\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create -n {} --sas-token {} --account-name {}`

az storage container create -n ala --sas-token "https://rname.blob.core.windows.net/rbcdatalake?se=2019-05-30T23%3A59Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=blah" --account-name somename1

## Expected Behavior
container "ala" is created

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

Extensions:
dev-spaces-preview 0.1.6
resource-graph 0.1.8
storage-preview 0.2.5
subscription 0.1.1

```

**Comment by teplyuska** [comment]
I am also getting this after upgrading from 2.0.62 to 2.0.64

**Comment by limingu** [comment]
@awysza, as you are Owner on the Subscription. You should login as your account with command 'az login'. Then you can just use command as 'az storage container create -n ala --account-name somename1' to create "ala" container.

You don't need to pass the --sas-token as CLI will get the token for you with your login credential. If you do want to pass the --sas-token, you should pass it just token key not the url like "https://rname.blob.core.windows.net/rbcdatalake?se=2019-05-30T23%3A59Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=blah"

Let me know if that works for you.

**Comment by mswidde** [comment]
I think I might be running into the same problem. When I run the command 'az storage container create --name myblobname --accountname mystorageaccountname' it produces the above error message. So, no SAS tokens used and providing the key (with --account-key) does not help. Shouldn't be necessary because I am owner on the resource.

Note: as I am running this via cloud-shell I am already logged on. Creating the same container via the portal works fine.

**Comment by teplyuska** [comment]
I got this error recently after adding "--default-action Deny" to "storage account create"

In addition i had also added network-rule "storage account network-rule add" only allowing access from an on prem server. It seems the public ip of the machine from where you are running azure-cli also needs access.

**Comment by brandtr** [comment]
I also get the exact same error. Please fix.

**Comment by limingu** [comment]
Please post the details of the command and the error output. If you can rerun the command with --debug, send the details to limgu@microsoft.com. That will help the repro and debug. Thanks.

**Comment by CPeacockSoltec** [comment]
@limingu Same issue. Windows 10, Azure Cli v 2.0.65 (latest version downloaded today 3rd June 2019)

Error running command 'az storage blob upload -f <FILENAME> -c resources -n <FILENAME> --auth-mode key --account-name <SAName>--account-key <SAKey>': exit status 1. Output: ERROR:
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

**Comment by limingu** [comment]
@CPeacockSoltec, can you send me the details of the command with --debug? Please also verify that your account-key has the permission to upload the blob.

**Comment by CPeacockSoltec** [comment]
@limingu 

az storage blob upload -f FILE.txt -c resources -n FILE.txt --auth-mode key --account-name SANAME--account-key KEY --debug
Command arguments: ['storage', 'blob', 'upload', '-f', 'FILE.txt', '-c', 'resources', '-n', 'FILE.txt', '--auth-mode', 'key', '--account-name', 'SANAME', '--account-key', 'KEY', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03C422B8>, <function OutputProducer.on_global_arguments at 0x03D00078>, <function CLIQuery.on_global_arguments at 0x03D1CC90>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.013 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.008 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.010 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.005 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.004 seconds.
Loaded module 'container' in 0.005 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.005 seconds.
Loaded module 'dms' in 0.004 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.003 seconds.
Loaded module 'feedback' in 0.002 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'kusto' in 0.006 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.009 seconds.
Loaded module 'network' in 0.026 seconds.
Loaded module 'policyinsights' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'relay' in 0.006 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.006 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.005 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.008 seconds.
Loaded module 'sqlvm' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.032 seconds.
Loaded module 'vm' in 0.013 seconds.
Loaded all modules in 0.288 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\USERNAME\.azure\cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03CBEC00>, <function register_ids_argument.<locals>.add_ids_arguments at 0x03CDEF60>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04C97588>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03D000C0>, <function CLIQuery.handle_query_parameter at 0x03D1CCD8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03CDEFA8>, <function handler at 0x04D2EAE0>]
Getting data service client service_type=BlockBlobService
azure.multiapi.storage.v2018_03_28.common._auth : String_to_sign=PUT


848








x-ms-blob-content-type:text/plain
x-ms-blob-type:BlockBlob
x-ms-client-request-id:ID
x-ms-date:Tue, 04 Jun 2019 08:30:13 GMT
x-ms-version:2018-03-28
/SANAME/resources/FILE.txt
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=ID Outgoing request: Method=PUT, Path=/resources/FILE.txt, Query={'timeout': None}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-blob-cache-control': None, 'x-ms-blob-content-type': 'text/plain', 'x-ms-blob-content-disposition': None, 'x-ms-blob-content-md5': None, 'x-ms-blob-content-encoding': None, 'x-ms-blob-content-language': None, 'Content-Length': '848', 'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.3.0-1.3.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.59', 'x-ms-client-request-id': 'ID', 'x-ms-date': 'Tue, 04 Jun 2019 08:30:13 GMT', 'Authorization': 'SharedKey SANAME:KEY'}.
urllib3.connectionpool : Starting new HTTPS connection (1): SANAME.blob.core.windows.net:443
urllib3.connectionpool : https://SANAME.blob.core.windows.net:443 "PUT /resources/FILE.txt HTTP/1.1" 403 246
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=ID Receiving Response: Server-Timestamp=Tue, 04 Jun 2019 08:30:10 GMT, Server-Request-ID=ID, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'ID', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Tue, 04 Jun 2019 08:30:10 GMT'}.
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=ID Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Tue, 04 Jun 2019 08:30:10 GMT, Server-Request-ID=ID, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:IDTime:2019-06-04T08:30:11.4070873Z</Message></Error>.
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=ID Retry policy did not allow for a retry: Server-Timestamp=Tue, 04 Jun 2019 08:30:10 GMT, Server-Request-ID=ID, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:IDTime:2019-06-04T08:30:11.4070873Z</Message></Error>.

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

Event: CommandInvoker.OnFilterResult []
'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\knack\knack\output.py", line 132, in out
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bsrj0zf4\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable
telemetry.save : Save telemetry record of length 2499 in cache
telemetry.check : Negative: The C:\Users\USER\.azure\telemetry.txt was modified at 2019-06-04 09:23:42.075288, which in less than 600.000000 s

**Comment by MikaJustas** [comment]
Any update on the topic? Which is the previous version that does not contain this bug?

**Comment by CPeacockSoltec** [comment]
I think there was an update in feb 2019. That worked fine. Still waiting for feedback from @limingu

**Comment by limingu** [comment]
@CPeacockSoltec for the log:
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=ID Receiving Response: Server-Timestamp=Tue, 04 Jun 2019 08:30:10 GMT, Server-Request-ID=ID, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'ID', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Tue, 04 Jun 2019 08:30:10 GMT'}.

The authorization failed. It seems that the account key may be not correct. Can you try the following command:
az login
az storage blob upload -f FILE.txt -c resources -n FILE.txt --account-name SANAME --debug

**Comment by bitcloud** [comment]
is it possible that you configured a firewall that restricts the source ip of your request?

**Comment by jpluscplusm** [comment]
This is definitely related to the storage account's `--default-action` setting.

As subscription Owner with a freshly created account with `--default-action deny`, I get the error message as per the bug report. When I change it to `allow`, container creation works.

This seems to be regardless of the container creation `--auth-mode` setting - key or login.

**Comment by bitcloud** [comment]
Every request has to obey the firewall settings independent from its role and permissions as far as I know. The default-action you @jpluscplusm described just supports that.

**Comment by TryTryAgain** [comment]
I'm coming across this same issue, using sas. And the blob storage account has the defaultAction set to allow already, still not working.

**Comment by Juliehzl** [comment]
Hi @awysza Have your problem solved by setting firewall?

**Comment by robgarrett** [comment]
Can we re-open this issue? - it's still a problem.

**Comment by flytzen** [comment]
@Juliehzl 
This issue is definitely still there in azure cli 2.0.76.
To reproduce: Create a new storage account using the CLI and set `default-action Deny` then try to create a storage container. 
If you repeat the steps above but set `default-action Allow` then it all works.
