### ISSUE TITLE
[Bulk Commands] should be an option to run --ids in parallel

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#943]

**Comment by tjprescott** [comment]
Is there any reason that you would ever want --ids to run in series?

**Comment by BurtBiel** [comment]
I can't think of any practical reason, but one side effect of running in parallel is that the output is unreadable (the lines are interspersed because they all print at once)

**Comment by tjprescott** [comment]
I would think we could add the results to a dictionary (with operation id as a key) and then print that when all are finished. That way even if the multiple threads are streaming output (which isn't often the case), they would all end up in the right order and their own "buckets".

Recorded tests might be a problem though, but we rarely test with --ids anyways.

**Comment by johanste** [comment]
The results are already added to a list. In the order that they are executed. Which is the same order as the ids were specified on the command line. 

The only reason I didn't add support for executing the each invocation in a separate thread initially was because I hadn't done the full analysis w. regards to thread-safety. And I couldn't decide if it was enough to just rely on the async behavior of most (all?) long-running operations and bake in support for not expanding/paging/getting the final result into the command execution pipeline (there is no way today to indicate that you just want the initial response and you don't need to wait for the long running part to complete).

If we do the "don't wait for the long-running operation to complete" feature, I'd like to expose it all the way to the command line with a --no-wait flag since that would be useful for long running operations in general - not just for long running operations on multiple resources...

**Comment by djsly** [comment]
I was looking for this over the weekend... I ran a deallocate command with 85 VM Ids and this took way too long. 

It is currently faster to log on the portal and click ~300 times to shutdown all of the VMs... 

Any update on a `--no-wait` feature ? That would be really awesome.

**Comment by tjprescott** [comment]
VM deallocate already has --no-wait support.

**Comment by djsly** [comment]
thanks @tjprescott , I updated the azure-cli from 0.6 to 20.7 and I now see the flag ;) Life quality increase right there! :)

**Comment by JasonRShaver** [comment]
While we like the idea, we would want to have a customer in mind before changes like this.
