### ISSUE TITLE
No support for MARS (backup management type) in az backup container/item list

### ISSUE THREAD

**Issue by Wand3rvogel** [Azure/azure-cli#9437]
## Describe the bug
Result is empty. 

**Command Name**
`az backup container list`

**Errors:**

## To Reproduce:
- `az backup container list -g {} -v {} --debug`
msrest.http_logger : Request URL: 'https://management.azure.com/Subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vaults/xxx/backupProtectionContainers?api-version=2016-12-01&$filter=**backupManagementType%20eq%20%27AzureIaasVM**%27%20and%20status%20eq%20%27Registered%27'

## Expected Behavior
Two containers as result

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

```

**Comment by pvrk** [comment]
Currently, CLI for Azure Backup is only supported for Azure VMs. We are focussing on adding support for other Azure workloads like Azure File Share, SQL in Azure VM backups. Support for on-premise agents like MARS is currently not in THIS semester's roadmap i.e., until CY, 2019 end. Given that we have the support in PS, is this a blocker? If valid business justification is provided, I will see if we adjust the priority.

**Comment by Wand3rvogel** [comment]
I've found [another way with REST API](https://github.com/Azure/azure-powershell/issues/9533).
In PS this also [doesn't work](https://github.com/Azure/azure-powershell/issues/9638).

**Comment by TAdityaAnirudh** [comment]
That's correct @Wand3rvogel PS is not supported either because Central management for MARS is not a GA product. (i.e. syncing Backup items, jobs, alerts, etc. to Azure portal) We will add support for MARS Central management in CLI and PS when these features get to GA. Until then, can you please work around this using REST API?

**Comment by Wand3rvogel** [comment]
@TAdityaAnirudh I do it already.

**Comment by pvrk** [comment]
@Wand3rvogel: Thanks for the update. You cannot get backup items for MARS in PS but you can get containers for MARS. We do not have plans to onboard MARS to CLI in the current CY. I will re-visit this next year and since you are unblocked using REST API, I will close this issue.

Added to backlog and closing this since this is not taken up in this CY, 2019
