### ISSUE TITLE
Windows MSI installer: old version <2.0.64 are unavailable 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#9535]
We will recover them and will close once it is done.

**Comment by yugangw-msft** [comment]
//CC: @marstr

**Comment by marstr** [comment]
In order to correctly prioritize, if you are currently reading this and are impacted by this: Please tell us how far back you need. We are still deciding how far back to scope our recovery efforts.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
As time goes by, the necessity of fixing this issue is significantly decreased. We do receieved one request for old MSI as referenced above since the time the issue was created. It was solved by using a newer version.

Closing this issue now. Let us know if you need to install an MSI older than 2.0.64.
