### ISSUE TITLE
az eventgrid event-subscription create does not work  az cli but via portal.azure.com it does

### ISSUE THREAD

**Issue by dwhanger** [Azure/azure-cli#9547]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Using the az eventgrid event-subscription create should work like it does via the UI.

**To Reproduce**
using the following command:

az eventgrid event-subscription create  --name EndPointCheckerAlertSite --endpoint "https://xxxxxxx-app.azurewebsites.net/runtime/webhooks/EventGrid?functionName=EndPointTypeAlertSite" --endpoint-type webhook --subject-begins-with AlertSite --subject-case-sensitive false --event-delivery-schema eventgridschema --labels functions-endpointtypealertsite --source-resource-id "/subscriptions/yyyyyyyyyyyyyy/resourceGroups/xxxxxxxxxxxxx/providers/Microsoft.EventGrid/Topics/zzzzzzzzzzzzzzzzzzz-topic"

....it comes back with the following:

The attempt to validate the provided endpoint https://nirv-webp-ndsh-devintus-app.azurewebsites.net/runtime/webhooks/EventGrid failed. For more details, visit https://aka.ms/esvalidation.

**Expected behavior**
That the command would create the new eventgrid subscription like it does when executed via the portal.azure.com UI.

**Environment summary**
az --version is 2.0.65

**Additional context**

**Comment by ahamad-MS** [comment]
@dwhanger 

Thanks for reporting this issue. The EventSubscription validation is enforced on latest eventgrid CLI module and extension. The same behavior applies to both local machine and shell.portal.com. Details of the EventSubscription Handshake validation for webhook is found here (as shown in the error message)  http://aka.ms/esvalidation

Please check if you are using any old eventgrid extension in shell.portal.com and update it in order to use the latest version or remove the extension to let the latest CLI module kicks in:

here is the expected output from shell.portal.com as of 6/15:

~$ az extension list
[
{
"extensionType": "whl",
"name": "eventgrid",
"version": "0.4.2"
}
]
:~$ az eventgrid event-subscription create --name --source-resource-id "/subscriptions//resourceGroups//providers/Microsoft.EventGrid/domains/" --advanced-filter data.awe StringIn data.routeTo StringIn finsei all error. --endpoint "<URL>"
he behavior of this command has been altered by the following extension: eventgrid
If the provided endpoint doesn't support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order tocomplete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation

**Comment by ahamad-MS** [comment]
Information provided to customer. Closing this issue. Please reach out to us if the issue still persists

**Comment by dwhanger** [comment]
I upgraded the eventgrid extension for the az cli...still the same message.

Here is what I am using (what am I missing):

az eventgrid event-subscription create 
	--name EndPointCheckerXXXX 
	--endpoint 'https://<url from configured from url for a sister function eventgrid setup from within the portal>.azurewebsites.net/runtime/webhooks/EventGrid?functionName=<function name>' 
	--endpoint-type webhook 
	--subject-begins-with XXXX 
	--subject-case-sensitive false 
	--event-delivery-schema eventgridschema 
	--labels functions-endpointtypexxxx 
	--source-resource-id '/subscriptions/<subscription id>/resourceGroups/<resource group name>/providers/Microsoft.EventGrid/topics/<topic name>' 
	--subscription <subscription id>

**Comment by stevendarby** [comment]
@ahamad-MS @haroldrandom 
I'm having a similar issue. Can this issue be opened again as it doesn't look like it was resolved?

The webhook validation handshake is coming back as Unauthorized using `az eventgrid event-subscription create`. But I can create the subscription using exactly the same URL via the portal. Also, if I issue an OPTION request to exactly the same URL in something like postman (simulating the validation call?), I get a 200.

I saw a [comment](https://github.com/MicrosoftDocs/azure-docs/issues/107285#issuecomment-1559207889) elsewhere which may or may not be relevant/accurate - that `&` in the URL can cause issues, which my URL has.
