### ISSUE TITLE
azure-cli-2.0.66-1.el7.x86_64.rpm has an unknown GPG key

### ISSUE THREAD

**Issue by liko9** [Azure/azure-cli#9568]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.66

**Describe the bug**
The package azure-cli-2.0.66-1.el7.x86_64.rpm is signed with a different GPG key than the one provided at https://packages.microsoft.com/keys/microsoft.asc

**To Reproduce**
Using any RPM-based Linux OS (here, Fedora 29):
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
sudo yum install azure-cli

**Expected behavior**
RPM is upgraded or installed with the current version

**Environment summary**
Fedora 29, fully updated

**Additional context**
Actual received output:
warning: /var/cache/dnf/azure-cli-da5926ebd44c506b/packages/azure-cli-2.0.66-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 513b22cc: NOKEY
Azure CLI                                       1.5 kB/s | 983  B     00:00    
Importing GPG key 0xBE1229CF:
 Userid     : "Microsoft (Release signing) <gpgsecurity@microsoft.com>"
 Fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
 From       : https://packages.microsoft.com/keys/microsoft.asc
Is this ok [y/N]: y
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for azure-cli-2.0.66-1.el7.x86_64.rpm is not installed. Failing package is: azure-cli-2.0.66-1.el7.x86_64
 GPG Keys are configured as: https://packages.microsoft.com/keys/microsoft.asc
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

**Comment by jalberto** [comment]
This is at least 3rd time it happens, this process needs to be improved as it blocks other system updates.

**Comment by tjprescott** [comment]
We had updated our release pipeline to specifically check for this and block if things were unsigned. I believe we tried a new process this time where the signing was supposed to have occurred automatically in the pipeline. Not sure if the verification steps were altered. cc/ @marstr @yugangw-msft.

**Comment by S3v3nL34fKl0v3r** [comment]
Until this is fixed to the root, folks that are affected can work around it by setting gpgcheck=0

**Comment by jalberto** [comment]
@S3v3nL34fKl0v3r careful there, that can open the door to a big security hole, as we are talking a very sensible package :)

**Comment by S3v3nL34fKl0v3r** [comment]
It's true! My docker images currently aren't used in production, but I still need `az` to work... So i'm just going to hang out on this ticket until i can change it back. ;)

**Comment by marstr** [comment]
Howdy folks,

Sorry for the inconvenience. As a team, we've been focused on automating our release pipeline. This was the first release where we had introduced an automated job to sign the RPM package. Despite our best efforts to make sure everything was working, clearly something didn't go quite right and we're still getting to the bottom of it. Once we understand the root cause, we'll update this issue with an understanding.

In the short-term we're falling back to the old release process for RPM, and will have signed bits out before end of business today. In the meantime, to avoid security concerns regarding using unsigned bits, please use your package manager to downgrade to 2.0.65. If it is helpful, here is some Red Hat guidance on this practice: https://access.redhat.com/solutions/29617

**Comment by marstr** [comment]
UPDATE:

I have a copy of the 2.0.66 RPM in hand, which I have confirmed is signed with the following key: `be1229cf`. Furthermore, I have submitted it to the official Microsoft repository at https://packages.microsoft.com. Once their ingestion process is complete, the signed bits will be what is available to your package manager.

RCA:
This looks to have been a pretty simple problem: In our release pipeline, we signed with the incorrect key, a testing key, which didn't get updated when we moved to the production copy of the pipeline. The script that we use checks to make sure that there is a signature, but not that it's the production key. In order to ensure that this doesn't happen again, we'll be updating our release pipeline to check that that the _correct_ key was used.

**Comment by marstr** [comment]
UPDATE 2:

Replacing the existing RPM with a signed one is causing `dnf` and `yum` to complain about mismatching checksums. Even running the suggested metadata cleans will not solve the problem. An attempt to fix this by renaming the RPM to `azure-cli-2.0.66-2.el7.x86_64.rpm` and resubmitting did not solve the problem

To fix this, I'm building a new RPM with the release tag `3.el7` from the azure-cli.spec file iteself, and will get that copy signed and uploaded.

**Comment by marstr** [comment]
Just to reiterate the work around, I've confirmed that the following commands are working:

Enterprise Linux 7:
``` bash
yum install azure-cli-2.0.65
```

Fedora:
``` bash
dnf install azure-cli-2.0.65
```

**Comment by marstr** [comment]
UPDATE 3:

`azure-cli-2.0.66-3.el7.x86_64.rpm` was succesffuly built and extracted from a container on my Fedora 29 machine. The build was taken from commit d536d7d69c41815d4fe8449d79de55d039167014. It has been submitted to be signed.

**Comment by marstr** [comment]
UPDATE 4:

Incident resolved. I'm now able to successfully run `sudo dnf upgrade azure-cli` from my machine which previously had 2.0.65 installed, and in container environments running Centos 7 and Fedora 30, I'm able to run `dnf install azure-cli`, and have it pulled down and install the correct signed RPM.

**Comment by S3v3nL34fKl0v3r** [comment]
@marstr THANKS!!!!
