### ISSUE TITLE
Username / password authentication no longer works

### ISSUE THREAD

**Issue by wvxvw** [Azure/azure-cli#9581]
`az login -u user -p password` is no longer a feasible way to authenticate to Azure: it requires extra steps from user (opening some garbage webpage, which requires JavaScript and other nonsense).

I mean, Azure login was always a piece of shit.  But, this finally did it in.

On the other hand, there's no reason for you to support this API anymore.  So, you can remove it.  Will make it a little less of a clusterfuck, for those who stick with Azure service.

**Comment by tjprescott** [comment]
The login flow you described does work. You may have policies in place requiring 2FA, in which case you can't always use it. These parameters are also used to log in as a service principal, so we would not remove them.

Additionally, supplying `--password` from the command line directly is not encouraged for security reasons because the operating system may keep a log of all commands executed.

**Comment by wvxvw** [comment]
No. No two-factor authentication was ever configured for my account. But,
like I said, Azure login is a piece of shit. It fails randomly, often with
incorrect error messages, suggesting wrong treatments etc. Azure support is
incompetent and has no idea of how to manage their own system. But, that's
really not your fault. The functionality you describe as eorking, however,
does not work (things that work don't just randomly don't work for one user
and work for another). So, I don't see why closing my ticket. If you insist
on doing this, I will open another, and so until it is removed. I am
responsible to show this to a customer, who believes this piece of shit to
work, while it doesn't, and I don't want to take responsibility for it.
