### ISSUE TITLE
az sig image-definition list should take ids

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-cli#9682]
**Is your feature request related to a problem? Please describe.**
You can get the information of a subscription via:

az sig show --ids {}

But to get a list of image definitions, you have provide each of the details that are part of the same ID as above as individual params.

az sig image-definition list --subscription {} -r {} -g {}

**Describe the solution you'd like**
az sig image-definition list --ids {}

**Comment by tjprescott** [comment]
It is a CLI standard that list commands do not expose `--ids`. The reason is because the ID should be the ID of the main "thing". For `az sig show` that would be a SIG ID. For `sig image-definition list` it would be the image definition. Since the list command does not target image definitions but rather galleries, the ID parameter is not exposed.
