### ISSUE TITLE
az disk create --source BUG when disk and resource group in different regions. 

### ISSUE THREAD

**Issue by swbae31** [Azure/azure-cli#9732]
## Describe the bug

Disk copy via the 'az disk create --source' command fails when the source disk’s region is different from its resource group region.

**Command Name**
`az disk create -g <rg in region A> -n <new disk name> --source <disk in region B>`

**Errors:**
```
Resource <disk in region B> is not found.
```

## To Reproduce:

1) Create a resource group in region A (ex: westus 2)
2) Create a disk within that resource group in a region that is NOT A (ex: eastus 2)
3) Run ‘az disk create -g <created rg> -n <new-disk-name> --source <created disk>’ to copy the created disk 

## Expected Behavior
Disk copy success.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.7.2
Shell: python.exe

azure-cli 2.0.67

Extensions:
vm-repair 0.1.0 (dev) C:\Users\subae\Desktop\azure-cli-extensions\src\vm-repair

```
## Additional Context

More detailed info on the issue through the debug logs:

The copy REST call's request body is populated with the resource group region not the disk region.

1. GET call to gather meta data for source disk.
https://management.azure.com:443 "GET /subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourceGroups/AzureBootCamp744025493/providers/Microsoft.Compute/disks/VHD_OsDisk_1_83236fecedb04f57a193df3d6e889919?api-version=2018-09-30 HTTP/1.1" 200 None

Response:
{
  "managedBy": "/subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourceGroups/AzureBootCamp744025493/providers/Microsoft.Compute/virtualMachines/VHD",
….
"location": "eastus2",,
…
}
 
2. GET call for resource group
https://management.azure.com:443 "GET /subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourcegroups/AzureBootCamp744025493?api-version=2018-05-01 HTTP/1.1" 200 275

Response:
{"id":"/subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourceGroups/AzureBootCamp744025493","name":"AzureBootCamp744025493","location":"southcentralus","properties":{"provisioningState":"Succeeded"}}
 
3. The disk copy PUT request with body:
{"location": "southcentralus", "tags": {}, "sku": {"name": "Premium_LRS"}, "properties": {"hyperVGeneration": "V1", "creationData": {"createOption": "Copy", "sourceResourceId": "/subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourceGroups/AzureBootCamp744025493/providers/Microsoft.Compute/disks/VHD_OsDisk_1_83236fecedb04f57a193df3d6e889919"}}}

https://management.azure.com:443 "PUT /subscriptions/f8e584fb-ceeb-42c1-94a1-d10bbe83a82c/resourceGroups/AzureBootCamp744025493/providers/Microsoft.Compute/disks/VHD-DiskCopy-20190617233619?api-version=2018-09-30 HTTP/1.1" 404 135
 
Response:
{
  "error": {
    "code": "NotFound",
    "message": "Resource VHD_OsDisk_1_83236fecedb04f57a193df3d6e889919 is not found."
  }
}

**Comment by adewaleo** [comment]
This issue is not a CLI issue but a service side issue. Some compute services tend to be region specific / dependent. You cannot create a disk from another disk in a different region.

If you try this scenario with the --debug option, you will see that the error comes from the service even though the valid disk Resource ID is passed:

$ az disk create -g ova-test -n disk_copy_westus -g ova-test --source "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/disks/disk2_eastus" --debug

...

msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/disks/disk_copy_westus?api-version=2018-09-30'

...

msrest.http_logger : Request body:
msrest.http_logger : {"location": "westus", "tags": {}, "sku": {"name": "Premium_LRS"}, "properties": {"hyperVGeneration": "V1", "creationData": {"createOption": "Copy", "sourceResourceId": "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/disks/disk2_eastus"}}}

... 

msrest.http_logger : Response content:
msrest.http_logger : {
  "error": {
    "code": "NotFound",
    "message": "Resource disk2_eastus is not found."
  }
}
msrest.exceptions : Resource disk2_eastus is not found.
cli.azure.cli.core.util : Resource disk2_eastus is not found.
Resource disk2_eastus is not found.

A way around this issue is to copy the managed disk to a blob and then create the disk from the blob. I attempted this and it worked for me.
Steps:
- Generate a sas token for the managed disk and allow it to be copied to a blob: `az disk grant-access`
- copy the managed disk into a blob with `az blob copy start`
- create the disk in the desired region with `az disk create`

As you mentioned via email. You can use -l to specified the location of the source to create the disk in that location instead. Do this if the disk does not need to be created in a different location.

**Comment by mikiekelly** [comment]
A fix for this is to add the --location parameter of the source disk. As @adewaleo mentioned copying disks across regions is not currently possible using this approach.

`az disk create -g <rg in region A> -n <new disk name> --source <disk in region B> --location <source disk region (B)>`
