### ISSUE TITLE
Yum package manager fails to install azure-cli 2.0.67

### ISSUE THREAD

**Issue by michal-podskoczy** [Azure/azure-cli#9791]
Installation according to [instruction](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest) fails due to python2-virtualenv

After successful installation of previous version when trying to upgrade using `yum update` fails due to error:

```--> Finished Dependency Resolution
Error: Package: azure-cli-2.0.67-1.el7.x86_64 (azure-cli)
           Requires: python2-virtualenv
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest```

Environment:
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by marstr** [comment]
Howdy @michal-podskoczy, I'm afraid I don't have much experience with this distribution. I may be about to ask some naive questions.

- What happens if you run `yum install python2-virtualenv` first?
- What repositories does this Linux env provide? It says it's like RHEL and Fedora, but I imagine it's different. Do they work to conform to provide the same name as EL7, similar to CentOS?
- If all else fails, do you have the ability to create a virtualenv and install python on your own?

**Comment by vikramaditya234** [comment]
I am facing the same problem, answering your questions:

- What happens if you run `yum install python2-virtualenv` first?
    There is no such package, available packages are python26-virtualenv, python27-virtualenv, python34-virtualenv, python35-virtualenv, python36-virtualenv
- What repositories does this Linux env provide? It says it's like RHEL and Fedora, but I imagine it's different. Do they work to conform to provide the same package names as EL7, similar to CentOS?
    Here are the repos available amzn-main-Base, amzn-updates-Base, Azure CLI, Extra Packages for Enterprise Linux 7 - x86_64. I enabled EPEL repo as mentioned here https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/
- If all else fails, do you have the ability to install python and create a virtualenv on your own? If so, it may be easiest to get started by just running pip install azure-cli inside that virtualenv.
   This worked, but now cli opens only inside the virtualenv, I have never used virtualenv before, I am trying to figure out the solution for it

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
Please try with latest 2.0.77. The dependency of `python-virtualenv` is removed and it only depends on `python3` now.
