### ISSUE TITLE
Create man pages for the Debian package

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#983]
With our Debian package, we can provide man pages for commands.

Creating this issue to discuss this.

**Comment by irl** [comment]
My plan was to go for az.1 and az-$(subcommand).1 man pages.

I intend to split the official Debian package to build independent binary packages for each of the command modules, as I'm replacing the component subsystem to work using dpkg instead of apt for the official Debian package (as per Debian policy). This means it would be convenient for me if the man pages are split across command modules.

**Comment by tjprescott** [comment]
No movement on this in two years. Closing.
