### ISSUE TITLE
"az vmss create" completes before vmss nic list has been updated. 

### ISSUE THREAD

**Issue by srajtiwari** [Azure/azure-cli#9871]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
With vmss over-provisioning enabled, "az vmss create" completes before vmss nic list has been updated. 
E.g. Immediately after provisioning a 2 instance VMSS, querying “ az vmss list-instances” returns the correct number of instances(2), but “ az vmss nic list” returns an incorrect number of nics (returns 4 instead of 2). 
After waiting for 60 seconds and running the “az vmss nic list” again returns the correct number of nics (2). 

**To Reproduce**
az vmss create -n clstr2 -g accumulo-rg --instance-count 2 --image CentOS --output table
az vmss list-instances -g accumulo-rg -n clstr2 --output table
az vmss nic list -g accumulo-rg --vmss-name clstr2 --output table
sleep 60
az vmss nic list -g accumulo-rg --vmss-name clstr2 --output table

**Expected behavior**
"az vmss create" should not finish until the vmss nic list has been updated.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
Installed using yum on CentOS

**Additional context**
For my use case, I am creating a list of private IP addresses for the VMSS instances. Querying "az vmss nic list" immediately after creating the vmss returns "extra" ip addresses from the over-provisioned VMs which causes problems.

**Comment by yonzhan** [comment]
We will take a look after Ignite.

**Comment by qwordy** [comment]
I think vmss create is a synchronous command, although there are some asynchronous commands, like disk encryption. So I agree with your opinion.
@shpa-microsoft Do you know any details in server side?

Related doc:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning

**Comment by shpa-microsoft** [comment]
I am assuming this Is unrelated to the new feature we have been talking about? Given that and lack of other context, VMSS create sync path can return before this. What is the ask?

**Comment by qwordy** [comment]
@shpa-microsoft It's unrelated with the feature which we talked about.

**Comment by arrownj** [comment]
yes, I also tried with above steps and reproduce this issue. It seems that there are some asynchronous tasks to do the clean up work in service side.

I also tried to create a new vmss from portal and Az PowerShell, then use the command above to list the instance count and nic count. This problem still exists in portal and Az PowerShell creation scenarios.

@shpa-microsoft Could you please help with issue ?

**Comment by Drewm3** [comment]
The current behavior is a side-effect of the current implementation of VMSS. The NIC operations are serviced by the network resource provider while the determination of which instances will remain after over-provisioning is complete is handled by the compute resource provider. In an effort to optimize for create deployment time speed we complete the create API call as soon as we have the appropriate number of instances instead of delaying until the NIC delete operations complete. So the current behavior is effectively by design as part of a trade-off in deployment speed compared to NIC cleanup.

We are planning to make improvements to the overall over-provisioning experience later in 2020. We will incorporate this feedback into the designs for the over-provisioning experience improvements. 

For now, I am going to resolve this issue as "By Design".
