### ISSUE TITLE
How to provide cloud_roleName when retrieving metrics

### ISSUE THREAD

**Issue by bulkware** [Azure/azure-cli#9934]
Hello,

I am trying to set the cloud_roleName while retrieving metrics using the Azure CLI. I have tried several ways and here is an example:

```
az monitor metrics list --resource "/subscriptions/***/resourceGroups/***/providers/microsoft.insights/components/***" --metric "performanceCounters/memoryAvailableBytes" --aggregation "Total" --start-time "2019-07-14 09:00:00" --end-time "2019-07-14 09:01:00" --filter "cloud/roleName eq '***'"
```

The result is "Metric: performanceCounters/memoryAvailableBytes does not support requested dimension combination: cloud/rolename, supported ones are: cloud/roleInstance".

Is this even possible to set using the Azure CLI?

Thanks in advance =)

**Comment by MyronFanQiu** [comment]
@bulkware Hello. From Azure CLI perspective, we do not validate the value of the `filter`. Based on my understanding, the dimension key should be part of the metrics. Here is a doc. https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#dimension-keys. So, maybe we cannot do this filter. Anyway, let's wait for the response from the service team.

**Comment by vgorbenko** [comment]
You are seeing a limited set of dimensions because the underlying metrics API only works with standard pre-aggregated metrics. These metrics implement fewer dimensions comparing to log-based metrics. The https://docs.microsoft.com/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics explains the difference between log-based and pre-aggregated standard AppInsights metrics. Use https://dev.applicationinsights.io/apiexplorer/metrics to programmatically retrieve the log-based equivalent of your metric. The https://docs.microsoft.com/azure/azure-monitor/platform/app-insights-metrics lists queries for each log-based metric.

**Comment by KevinBlasko** [comment]
Closing the issue per @vgorbenko last response.
