### ISSUE TITLE
az ad app permission admin-consent for sovereign cloud

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-cli#9942]
**Is your feature request related to a problem? Please describe.**
https://github.com/Azure/azure-cli/blob/98007ca07ce625990ad79a9941c99221ba454e1f/src/azure-cli/azure/cli/command_modules/role/custom.py#L875

**Describe the solution you'd like**
Support `az ad app permission admin-consent` in sovereign cloud

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@jiasli new feature request, plan later.

**Comment by udayansarma** [comment]
I see that the all the az CLI command is doing is a post to the endpoint below. If that end point or equivalent exists in the sovereign cloud I don't see that this is a huge amount of work. Also, if that endpoint is available then we should be able to leverage that in the interim without having to go through the portal.  
On another though if we are able to consent using the Azure portal then there must be an API available to accomplish it. 
Any thoughts?
https://main.iam.ad.ext.azure.com/api/RegisteredApplications/{}/Consent?onBehalfOfAll=true'.format(
        application.app_id)

**Comment by jiasli** [comment]
`az ad app permission admin-consent` will be deprecated soon in the future, because as @udayansarma said, it is calling an AAD internal API: https://github.com/Azure/azure-cli/blob/4c28536a6db8c8e43b7182d0aaf202ac2b4ab777/src/azure-cli/azure/cli/command_modules/role/custom.py#L905-L907

For the new way of granting admin permissions, please check https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 for a temporary solution with `az rest` and Microsoft Graph.
