### ISSUE TITLE
Publish Edge Python Packages

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#9949]
Today we have edge builds published by this [ADO release pipeline](https://dev.azure.com/azure-sdk/internal/_release?view=all&definitionId=56). Note, it builds and uploads a Windows Installer (*.msi), and a homebrew manifest.

We should extend this to include publishing a tarball and wheels to a simple PEP 503 repository. We have done this in the past, but migrating this process to ADO was not a priority. Regardless, using [the same repo](https://azurecliprod.blob.core.windows.net/edge/index.html) would be advisable.

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look.

**Comment by fengzhou-msft** [comment]
Moved to Edge ADO. 

Change version to `post1` instead of `devXXX` because dev version is lower than a stable version, it will not be  picked by pip install with current version upgrade policy. We only upgrade the version when release, so edge builds for features of 2.0.77 are named 2.0.76.devXXX. It never gets installed as there's 2.0.76 on PyPI. This `post1` naming strategy will only keep one edge build for a version.
